/* speedrun.com 原始抓取数据 — Disruption Missions / Kappa / Solo */
/* level_id=9m5pe45d | 共 12 条 */
var disruption_missions_kappa_soloRecords = [
  {
    playerId:   "NamelessDeity",
    clearTime:  "1:10.333",
    uploadTime: "2025-08-27",
    videoUrls:  ["https://www.youtube.com/watch?v=aPjYCpetAuo"],
    src:        "srdc",
    srId:       "y4nvpqqm",
  },
  {
    playerId:   "sealmp4",
    clearTime:  "1:23.000",
    uploadTime: "2025-03-22",
    videoUrls:  ["https://youtu.be/xNgUe6_1LRM&t=322"],
    src:        "srdc",
    srId:       "yww5jo2y",
  },
  {
    playerId:   "_BaJIMaTbE_",
    clearTime:  "1:36.000",
    uploadTime: "2026-06-13",
    videoUrls:  ["https://www.youtube.com/watch?v=k6sdh-8yYi0"],
    src:        "srdc",
    srId:       "z5nq5vjz",
  },
  {
    playerId:   "Salat",
    clearTime:  "1:48.000",
    uploadTime: "2024-03-05",
    videoUrls:  ["https://www.youtube.com/watch?v=F3F0WrET6E8"],
    src:        "srdc",
    srId:       "meng700m",
  },
  {
    playerId:   "uhLenna",
    clearTime:  "1:53.000",
    uploadTime: "2025-07-08",
    videoUrls:  ["https://youtu.be/9nEr-DhmUKs?si=DaAfMoF2_deGcr-B"],
    src:        "srdc",
    srId:       "zqpejkrm",
  },
  {
    playerId:   "StasisPrime",
    clearTime:  "2:33.000",
    uploadTime: "2025-01-29",
    videoUrls:  ["https://youtu.be/fgN-1J1apes"],
    src:        "srdc",
    srId:       "y2npv29y",
  },
  {
    playerId:   "NamelessDeity",
    clearTime:  "53:43.000",
    uploadTime: "2025-11-24",
    videoUrls:  ["https://www.youtube.com/watch?v=1Bc6lQefhEY"],
    src:        "srdc",
    srId:       "zx5l31qm",
  },
  {
    playerId:   "sakvayumika",
    clearTime:  "55:49.000",
    uploadTime: "2025-09-28",
    videoUrls:  ["https://www.youtube.com/watch?v=5NQzaqJrC5c"],
    src:        "srdc",
    srId:       "zn58o1vz",
  },
  {
    playerId:   "oTonJleHue",
    clearTime:  "58:58.000",
    uploadTime: "2026-06-07",
    videoUrls:  ["https://youtu.be/kReZI7DHIwE"],
    src:        "srdc",
    srId:       "z5nnleez",
  },
  {
    playerId:   "Endryx_Ow",
    clearTime:  "59:14.000",
    uploadTime: "2026-04-22",
    videoUrls:  ["https://youtu.be/m1_Tfe7CRtM?si=NsCm7VaEjfw_MERs"],
    src:        "srdc",
    srId:       "z02nd88m",
  },
  {
    playerId:   "Elenjeager",
    clearTime:  "68:57.000",
    uploadTime: "2025-10-06",
    videoUrls:  ["https://b23.tv/KzUJGji"],
    src:        "srdc",
    srId:       "mr5xl22y",
  },
  {
    playerId:   "Clarn",
    clearTime:  "71:17.000",
    uploadTime: "2026-04-20",
    videoUrls:  ["https://youtu.be/d8HcTw0YjqU"],
    src:        "srdc",
    srId:       "m38lg8dy",
  },
];