/* speedrun.com 原始抓取数据 — Disruption Missions / Kappa / Co-op */
/* level_id=9m5pe45d | 共 20 条 */
var disruption_missions_kappa_coopRecords = [
  {
    playerId:   "hoshifcku / insxght",
    clearTime:  "1:07.000",
    uploadTime: "2026-05-14",
    videoUrls:  ["https://youtu.be/fKI9HMt-DIk"],
    src:        "srdc",
    srId:       "z10n81rm",
  },
  {
    playerId:   "sealmp4 / Rouxka",
    clearTime:  "1:28.000",
    uploadTime: "2025-03-19",
    videoUrls:  ["https://youtu.be/uqMg7dj6ujg"],
    src:        "srdc",
    srId:       "zxj01q8y",
  },
  {
    playerId:   "StasisPrime / coerulea",
    clearTime:  "2:28.000",
    uploadTime: "2025-01-26",
    videoUrls:  ["https://www.youtube.com/watch?v=owHk9TI3sdY"],
    src:        "srdc",
    srId:       "yjexr2om",
  },
  {
    playerId:   "NamelessDeity / Yamarashi / oTonJleHue / L1ndell",
    clearTime:  "35:06.000",
    uploadTime: "2026-05-09",
    videoUrls:  ["https://www.youtube.com/watch?v=t3Mlmqae_Ow"],
    src:        "srdc",
    srId:       "y8lwxp1m",
  },
  {
    playerId:   "Endryx_Ow / sealmp4 / Gamer123169 / joanardo",
    clearTime:  "35:38.000",
    uploadTime: "2026-01-17",
    videoUrls:  ["https://youtu.be/21h4oSgmDtE", "https://youtu.be/SnFhw74zhmk", "https://youtu.be/X4Y3pYiIFg0"],
    src:        "srdc",
    srId:       "z56wr0gy",
  },
  {
    playerId:   "qlll123 / LastShao / Kuva_Prime / Takagi1218",
    clearTime:  "37:37.000",
    uploadTime: "2025-07-21",
    videoUrls:  ["https://www.youtube.com/watch?v=6Feq9lDbIcw&t=2s"],
    src:        "srdc",
    srId:       "z16k739m",
  },
  {
    playerId:   "sealmp4 / Rouxka / Endryx_Ow / Gamer123169",
    clearTime:  "38:06.000",
    uploadTime: "2025-03-16",
    videoUrls:  ["https://youtu.be/oRxoJHWJ6v8"],
    src:        "srdc",
    srId:       "y4jnr2dy",
  },
  {
    playerId:   "sealmp4 / Rouxka / FlashSucks / max_1248",
    clearTime:  "38:27.000",
    uploadTime: "2025-01-16",
    videoUrls:  ["https://youtu.be/jveW9pzhn38"],
    src:        "srdc",
    srId:       "mr0r0v7m",
  },
  {
    playerId:   "NamelessDeity / Yamarashi",
    clearTime:  "38:28.000",
    uploadTime: "2026-04-19",
    videoUrls:  ["https://www.youtube.com/watch?v=sut_zO3QhKI"],
    src:        "srdc",
    srId:       "yl2n1xkz",
  },
  {
    playerId:   "LastShao / Kuva_Prime",
    clearTime:  "38:39.000",
    uploadTime: "2026-03-22",
    videoUrls:  ["https://www.youtube.com/watch?v=MwQoMn1TJwo"],
    src:        "srdc",
    srId:       "ydp9lejy",
  },
  {
    playerId:   "LastShao / Y_7BAB / Kuva_Prime / Takagi1218",
    clearTime:  "38:45.000",
    uploadTime: "2025-02-04",
    videoUrls:  ["https://www.youtube.com/watch?v=ueZ1zdcC6h0"],
    src:        "srdc",
    srId:       "yjed8qgm",
  },
  {
    playerId:   "NamelessDeity / Yamarashi / Quhuvi / Renemeded_Fufa",
    clearTime:  "38:51.000",
    uploadTime: "2024-12-05",
    videoUrls:  ["https://www.youtube.com/watch?v=ET1dkwammdQ"],
    src:        "srdc",
    srId:       "y6g7rqjm",
  },
  {
    playerId:   "Endryx_Ow / Gamer123169",
    clearTime:  "39:03.000",
    uploadTime: "2026-01-22",
    videoUrls:  ["https://youtu.be/5S4gQwVw5aE?si=XPXHaZ4i672GcS_b", "https://youtu.be/cNCEdvB_sDY?si=7D8IX4pscSy9W2Z8"],
    src:        "srdc",
    srId:       "yw550v3y",
  },
  {
    playerId:   "NamelessDeity / namenBARS / Quhuvi / \"Sappi_Bear\"",
    clearTime:  "39:56.000",
    uploadTime: "2024-05-15",
    videoUrls:  ["https://youtu.be/m0wrupTQvR4?si=GSMKEefwUjGge8JH"],
    src:        "srdc",
    srId:       "y4l4q5nz",
  },
  {
    playerId:   "Endryx_Ow / Txdo / _Dopa / HL_BAN",
    clearTime:  "40:54.000",
    uploadTime: "2025-02-10",
    videoUrls:  ["https://www.youtube.com/watch?v=yRPxHuvjrVQ", "https://youtu.be/jK8y-bKdNsc?si=wIONSxI0NIocMKcw"],
    src:        "srdc",
    srId:       "mr0onldm",
  },
  {
    playerId:   "Leaf_Riya / LastShao / Kuva_Prime / Y_7BAB",
    clearTime:  "40:57.000",
    uploadTime: "2024-08-09",
    videoUrls:  ["https://www.bilibili.com/video/BV1FcYteXETj/"],
    src:        "srdc",
    srId:       "y2w4jk5y",
  },
  {
    playerId:   "NamelessDeity / Yamarashi",
    clearTime:  "41:18.000",
    uploadTime: "2025-08-02",
    videoUrls:  ["https://www.youtube.com/watch?v=vaChoHOAjIg"],
    src:        "srdc",
    srId:       "zg6o9wjm",
  },
  {
    playerId:   "sakvayumika / RoniPrime",
    clearTime:  "43:53.000",
    uploadTime: "2025-10-19",
    videoUrls:  ["https://www.youtube.com/watch?v=rAuDuRBZ7oM"],
    src:        "srdc",
    srId:       "zx5260qm",
  },
  {
    playerId:   "qlll123 / YareliPrime11 / LHH030312 / 222zzz",
    clearTime:  "44:18.000",
    uploadTime: "2025-02-01",
    videoUrls:  ["https://www.bilibili.com/video/BV1T3FeeeEP6"],
    src:        "srdc",
    srId:       "zgjp0kdz",
  },
  {
    playerId:   "QianYuan / ranrangongzhu",
    clearTime:  "61:06.000",
    uploadTime: "2024-12-07",
    videoUrls:  ["https://www.bilibili.com/video/BV1r2qLY7EeB/?share_source=copy_web"],
    src:        "srdc",
    srId:       "z5lo2gdy",
  },
];