/* speedrun.com 原始抓取数据 — Limited Events / Razorback / Solo */
/* level_id=5wk8j12w | 共 17 条 */
var limited_events_razorback_soloRecords = [
  {
    playerId:   "--Q--DankNinja",
    clearTime:  "0:35.000",
    uploadTime: "2019-07-26",
    videoUrls:  ["https://www.youtube.com/watch?v=VMKurcNUwYM"],
    src:        "srdc",
    srId:       "zqr4el1y",
  },
  {
    playerId:   "_Gabriel",
    clearTime:  "0:54.000",
    uploadTime: "2022-10-27",
    videoUrls:  ["https://www.youtube.com/watch?v=gIAbzbhlNJY"],
    src:        "srdc",
    srId:       "z0lkok8z",
  },
  {
    playerId:   "PrimedDarkeN",
    clearTime:  "0:57.000",
    uploadTime: "2021-01-20",
    videoUrls:  ["https://www.youtube.com/watch?v=OrEvKAs5TRo"],
    src:        "srdc",
    srId:       "z181r1jy",
  },
  {
    playerId:   "V-_-iniciu-_-s",
    clearTime:  "0:59.000",
    uploadTime: "2019-05-19",
    videoUrls:  ["https://youtu.be/RJW-jjIZwPs"],
    src:        "srdc",
    srId:       "m7q1dgwz",
  },
  {
    playerId:   "LuisGuerra",
    clearTime:  "1:00.000",
    uploadTime: "2022-10-26",
    videoUrls:  ["https://www.youtube.com/watch?v=DfJGpfy2yW4"],
    src:        "srdc",
    srId:       "mkdr703y",
  },
  {
    playerId:   "Boll",
    clearTime:  "1:02.000",
    uploadTime: "2022-01-22",
    videoUrls:  ["https://www.youtube.com/watch?v=U4KadeBwHg4"],
    src:        "srdc",
    srId:       "ywj3269z",
  },
  {
    playerId:   "Wasamii",
    clearTime:  "1:03.000",
    uploadTime: "2022-01-21",
    videoUrls:  ["https://youtu.be/zae7LFeFyIY"],
    src:        "srdc",
    srId:       "zxl7w4gz",
  },
  {
    playerId:   "_Q_JS",
    clearTime:  "1:12.000",
    uploadTime: "2022-01-22",
    videoUrls:  ["https://www.youtube.com/watch?v=ILXQqkmsl44"],
    src:        "srdc",
    srId:       "y20pwg6m",
  },
  {
    playerId:   "striker350z",
    clearTime:  "1:14.000",
    uploadTime: "2021-03-27",
    videoUrls:  ["https://youtu.be/hNDk0Ncpi5Y"],
    src:        "srdc",
    srId:       "yo98x47y",
  },
  {
    playerId:   "_Q_BlackMaster",
    clearTime:  "1:16.000",
    uploadTime: "2022-01-20",
    videoUrls:  ["https://www.youtube.com/watch?v=RLNfFiNFKJE&ab_channel=Kirill"],
    src:        "srdc",
    srId:       "y20p7lwm",
  },
  {
    playerId:   "Nest20",
    clearTime:  "1:17.000",
    uploadTime: "2021-01-20",
    videoUrls:  ["https://youtu.be/24bkGZfL5O8"],
    src:        "srdc",
    srId:       "yw0pqe2m",
  },
  {
    playerId:   "Dark_Lugia",
    clearTime:  "1:19.000",
    uploadTime: "2021-01-20",
    videoUrls:  ["https://www.youtube.com/watch?v=8VC3Llvp1xw"],
    src:        "srdc",
    srId:       "ylo050ny",
  },
  {
    playerId:   "FaidZ",
    clearTime:  "1:19.000",
    uploadTime: "2022-01-20",
    videoUrls:  ["https://youtu.be/h6oja52HLtw"],
    src:        "srdc",
    srId:       "m363n26m",
  },
  {
    playerId:   "Hollowknuthollowknut",
    clearTime:  "1:33.000",
    uploadTime: "2023-01-06",
    videoUrls:  ["https://www.youtube.com/watch?v=bi7ygTJkQnA"],
    src:        "srdc",
    srId:       "mr23x92y",
  },
  {
    playerId:   "Salat",
    clearTime:  "2:07.000",
    uploadTime: "2020-07-31",
    videoUrls:  ["https://www.twitch.tv/videos/696524580"],
    src:        "srdc",
    srId:       "mk3wv6vz",
  },
  {
    playerId:   "LucianPlaysAllDay",
    clearTime:  "2:17.000",
    uploadTime: "2020-11-13",
    videoUrls:  ["https://www.twitch.tv/videos/802591628"],
    src:        "srdc",
    srId:       "y2dp897z",
  },
  {
    playerId:   "TheLegacy___",
    clearTime:  "2:26.000",
    uploadTime: "2020-07-29",
    videoUrls:  ["https://youtu.be/21wjBdWUbac"],
    src:        "srdc",
    srId:       "meo29k2z",
  },
];