/* speedrun.com 原始抓取数据 — Spy Missions / Amalthea / Solo */
/* level_id=r9g4qkk9 | 共 26 条 */
var spy_missions_amalthea_soloRecords = [
  {
    playerId:   "Salat",
    clearTime:  "0:45.000",
    uploadTime: "2026-03-12",
    videoUrls:  ["https://youtu.be/LqO2KCy5w98"],
    src:        "srdc",
    srId:       "ywo8nnnm",
  },
  {
    playerId:   "Aminee",
    clearTime:  "0:51.000",
    uploadTime: "2025-11-16",
    videoUrls:  ["https://www.youtube.com/watch?v=m_iaEe9YzXM"],
    src:        "srdc",
    srId:       "z0k7l99m",
  },
  {
    playerId:   "Salat",
    clearTime:  "0:57.000",
    uploadTime: "2026-03-11",
    videoUrls:  ["https://youtu.be/7vAsUCcXBIg"],
    src:        "srdc",
    srId:       "mrwk724y",
  },
  {
    playerId:   "_Gabriel",
    clearTime:  "1:02.000",
    uploadTime: "2023-08-25",
    videoUrls:  ["https://www.youtube.com/watch?v=JQcelU0pqUM"],
    src:        "srdc",
    srId:       "mk0n6nxz",
  },
  {
    playerId:   "L1ndell",
    clearTime:  "1:03.000",
    uploadTime: "2022-01-18",
    videoUrls:  ["https://youtu.be/5wYo2D0vv34?list=PL478Ancwsna9F8wy5mWKpC2ScFOQQR9Hb"],
    src:        "srdc",
    srId:       "ydwwkkjm",
  },
  {
    playerId:   "Nusmag",
    clearTime:  "1:04.097",
    uploadTime: "2018-07-25",
    videoUrls:  ["https://youtu.be/5_RYCRVN5RI"],
    src:        "srdc",
    srId:       "me8o910m",
  },
  {
    playerId:   "PrimedDarkeN",
    clearTime:  "1:06.000",
    uploadTime: "2021-03-05",
    videoUrls:  ["https://www.youtube.com/watch?v=oCjWL7KMTuM"],
    src:        "srdc",
    srId:       "zx6w01kz",
  },
  {
    playerId:   "Mortar",
    clearTime:  "1:07.000",
    uploadTime: "2020-08-07",
    videoUrls:  ["https://www.youtube.com/watch?v=WK9UWCUWjwA"],
    src:        "srdc",
    srId:       "mrk5o27y",
  },
  {
    playerId:   "Mortar",
    clearTime:  "1:07.000",
    uploadTime: "2020-08-07",
    videoUrls:  ["https://www.youtube.com/watch?v=WK9UWCUWjwA"],
    src:        "srdc",
    srId:       "zx25nw8m",
  },
  {
    playerId:   "Nusmag",
    clearTime:  "1:10.237",
    uploadTime: "2018-07-11",
    videoUrls:  ["https://youtu.be/kh0Wq_py-Gk"],
    src:        "srdc",
    srId:       "yj431woy",
  },
  {
    playerId:   "-Rekken-",
    clearTime:  "1:12.200",
    uploadTime: "2019-01-19",
    videoUrls:  ["https://youtu.be/CXu80dfYsN0"],
    src:        "srdc",
    srId:       "zp06v7nm",
  },
  {
    playerId:   "Nonqui",
    clearTime:  "1:14.000",
    uploadTime: "2019-01-23",
    videoUrls:  ["https://www.youtube.com/watch?v=S9h1lIIOcJA&feature=youtu.be"],
    src:        "srdc",
    srId:       "mk913w1z",
  },
  {
    playerId:   "holleufer98",
    clearTime:  "1:14.541",
    uploadTime: "2018-07-03",
    videoUrls:  ["https://youtu.be/6TnMlMhA1Q0"],
    src:        "srdc",
    srId:       "y433lgnz",
  },
  {
    playerId:   "NightWorrer",
    clearTime:  "1:14.970",
    uploadTime: "2018-07-25",
    videoUrls:  ["https://youtu.be/ZGk8lsQGn2I"],
    src:        "srdc",
    srId:       "y920nvez",
  },
  {
    playerId:   "ThatBlue",
    clearTime:  "1:22.415",
    uploadTime: "2018-06-25",
    videoUrls:  ["https://www.youtube.com/watch?v=40DWjqUNf4M&feature=youtu.be"],
    src:        "srdc",
    srId:       "zp004xnm",
  },
  {
    playerId:   "Boll",
    clearTime:  "1:23.000",
    uploadTime: "2021-02-10",
    videoUrls:  ["https://www.youtube.com/watch?v=QXYyPmw8Kdg&ab_channel=MuraTradebanned"],
    src:        "srdc",
    srId:       "yj15pody",
  },
  {
    playerId:   "zukerben",
    clearTime:  "1:25.000",
    uploadTime: "2020-05-25",
    videoUrls:  ["https://www.youtube.com/watch?v=QWTrP-VPKGI"],
    src:        "srdc",
    srId:       "zx2o36qm",
  },
  {
    playerId:   "holleufer98",
    clearTime:  "1:25.430",
    uploadTime: "2018-01-20",
    videoUrls:  ["https://www.twitch.tv/videos/220633236"],
    src:        "srdc",
    srId:       "m3d0jewz",
  },
  {
    playerId:   "-Vergilius-",
    clearTime:  "1:27.000",
    uploadTime: "2020-05-25",
    videoUrls:  ["https://youtu.be/ep11Rpr8w0s"],
    src:        "srdc",
    srId:       "y82ex5wy",
  },
  {
    playerId:   "-Arcturus.",
    clearTime:  "1:30.972",
    uploadTime: "2018-07-16",
    videoUrls:  ["https://youtu.be/kFdytN6pte0"],
    src:        "srdc",
    srId:       "zn4re1lm",
  },
  {
    playerId:   "-Arcturus.",
    clearTime:  "1:30.972",
    uploadTime: "2018-07-17",
    videoUrls:  ["https://www.youtube.com/watch?v=kFdytN6pte0"],
    src:        "srdc",
    srId:       "yd36lr0z",
  },
  {
    playerId:   "LeChat930",
    clearTime:  "1:55.000",
    uploadTime: "2023-07-08",
    videoUrls:  ["https://www.youtube.com/watch?v=lM4n2tva0rY"],
    src:        "srdc",
    srId:       "znvjv57m",
  },
  {
    playerId:   "6sceseos",
    clearTime:  "2:08.000",
    uploadTime: "2019-05-27",
    videoUrls:  ["https://www.youtube.com/watch?v=ewCFlHsgew4"],
    src:        "srdc",
    srId:       "yj3jqd7z",
  },
  {
    playerId:   "Nexdor",
    clearTime:  "2:11.000",
    uploadTime: "2018-05-09",
    videoUrls:  ["https://www.youtube.com/watch?v=f_xnmN7FPxk&feature=youtu.be"],
    src:        "srdc",
    srId:       "y8q5v1ny",
  },
  {
    playerId:   "Zlemoc",
    clearTime:  "2:33.410",
    uploadTime: "2018-02-22",
    videoUrls:  ["https://www.youtube.com/watch?v=zQqIDWwWUHY&feature=youtu.be"],
    src:        "srdc",
    srId:       "m3dvrn6z",
  },
  {
    playerId:   "Loki",
    clearTime:  "2:51.000",
    uploadTime: "2018-02-16",
    videoUrls:  ["https://youtu.be/Kc5gan_BoFo"],
    src:        "srdc",
    srId:       "yw1w5g2z",
  },
];