/* speedrun.com 原始抓取数据 — Spy Missions / Amalthea / Co-op */
/* level_id=r9g4qkk9 | 共 12 条 */
var spy_missions_amalthea_coopRecords = [
  {
    playerId:   "Endryx_Ow / Salat / L1ndell",
    clearTime:  "0:38.000",
    uploadTime: "2026-02-09",
    videoUrls:  ["https://youtu.be/kF56j-CBssQ"],
    src:        "srdc",
    srId:       "mkr6o33z",
  },
  {
    playerId:   "Febi / Kuremento / PrimedDarkeN",
    clearTime:  "0:41.000",
    uploadTime: "2021-04-07",
    videoUrls:  ["https://www.youtube.com/watch?v=WOJaKTdCyY4", "https://www.youtube.com/watch?v=63kzD8c8KgM", "https://youtu.be/JbCBJQWM6bk"],
    src:        "srdc",
    srId:       "z06vl6jz",
  },
  {
    playerId:   "L1ndell / zxcMolniya / Xo4yYMePetb",
    clearTime:  "0:41.000",
    uploadTime: "2022-01-28",
    videoUrls:  ["https://youtu.be/RVmMmK-EAR0"],
    src:        "srdc",
    srId:       "ylenokrz",
  },
  {
    playerId:   "holleufer98 / Nusmag",
    clearTime:  "0:44.311",
    uploadTime: "2018-07-04",
    videoUrls:  ["https://youtu.be/33U-XzUn42s"],
    src:        "srdc",
    srId:       "yd33v4jz",
  },
  {
    playerId:   "PrimedDarkeN / Menadion / Boll",
    clearTime:  "0:46.000",
    uploadTime: "2021-01-25",
    videoUrls:  ["https://youtu.be/G5U-6U1w5X4"],
    src:        "srdc",
    srId:       "z18j6lry",
  },
  {
    playerId:   "ThatBlue / QuasarWF / -Rekken-",
    clearTime:  "0:48.666",
    uploadTime: "2018-06-24",
    videoUrls:  ["https://youtu.be/nre5XuPJdGs"],
    src:        "srdc",
    srId:       "ywppp3nz",
  },
  {
    playerId:   "lucasengenho / Mortar",
    clearTime:  "0:56.000",
    uploadTime: "2019-10-15",
    videoUrls:  ["https://www.youtube.com/watch?v=15lFAIftNZo", "https://www.youtube.com/watch?v=Ee-f9doEwzQ"],
    src:        "srdc",
    srId:       "m31x57gz",
  },
  {
    playerId:   "PrimedDarkeN / Boll",
    clearTime:  "1:00.000",
    uploadTime: "2020-12-19",
    videoUrls:  ["https://youtu.be/uh8HKjq6HKs"],
    src:        "srdc",
    srId:       "yd0vkpxz",
  },
  {
    playerId:   "lucasengenho / Mortar",
    clearTime:  "1:09.000",
    uploadTime: "2019-10-15",
    videoUrls:  ["https://www.youtube.com/watch?v=O8-c5moy2eI", "https://www.youtube.com/watch?v=vKGfweLV8Y8"],
    src:        "srdc",
    srId:       "y81x2exz",
  },
  {
    playerId:   "Wambo / CreepingChamp",
    clearTime:  "1:18.000",
    uploadTime: "2020-12-06",
    videoUrls:  ["https://www.youtube.com/watch?v=LIDPiBihnmE"],
    src:        "srdc",
    srId:       "y4e6rxqm",
  },
  {
    playerId:   "Wambo / CreepingChamp",
    clearTime:  "1:18.000",
    uploadTime: "2020-12-06",
    videoUrls:  ["https://www.youtube.com/watch?v=LIDPiBihnmE"],
    src:        "srdc",
    srId:       "zq48199m",
  },
  {
    playerId:   "LucianPlaysAllDay / HelpMeDie09 / Gammer--2007 / Only_01-left",
    clearTime:  "1:47.000",
    uploadTime: "2020-11-15",
    videoUrls:  ["https://www.twitch.tv/videos/812734603"],
    src:        "srdc",
    srId:       "zgv2lgvz",
  },
];