/* speedrun.com 原始抓取数据 — Spy Missions / Arval / Co-op */
/* level_id=o9x7rm1d | 共 9 条 */
var spy_missions_arval_coopRecords = [
  {
    playerId:   "Endryx_Ow / Salat / L1ndell",
    clearTime:  "0:29.000",
    uploadTime: "2026-02-09",
    videoUrls:  ["https://youtu.be/uUfN5ZF9z2U"],
    src:        "srdc",
    srId:       "z56qljdy",
  },
  {
    playerId:   "Febi / Kuremento / PrimedDarkeN",
    clearTime:  "0:30.000",
    uploadTime: "2021-04-07",
    videoUrls:  ["https://www.youtube.com/watch?v=baNXcKy2Leg", "https://www.youtube.com/watch?v=S9krFzqbP5g", "https://youtu.be/jrrqpnAiiI0"],
    src:        "srdc",
    srId:       "zqgx9g1m",
  },
  {
    playerId:   "PrimedDarkeN / Menadion / Boll",
    clearTime:  "0:33.000",
    uploadTime: "2021-01-25",
    videoUrls:  ["https://youtu.be/8l4Pts8OjTQ"],
    src:        "srdc",
    srId:       "y66ljoqy",
  },
  {
    playerId:   "PrimedDarkeN / Boll",
    clearTime:  "0:44.000",
    uploadTime: "2020-12-19",
    videoUrls:  ["https://www.youtube.com/watch?v=ySWVa93uWKg&feature=youtu.be"],
    src:        "srdc",
    srId:       "zq42xo1m",
  },
  {
    playerId:   "-Rekken- / QuasarWF / ThatBlue",
    clearTime:  "0:44.678",
    uploadTime: "2018-06-20",
    videoUrls:  ["https://www.youtube.com/watch?v=wFDdPoBrxxg&feature=youtu.be"],
    src:        "srdc",
    srId:       "y2q3655y",
  },
  {
    playerId:   "Nusmag / IRojaz / Akemi",
    clearTime:  "0:49.150",
    uploadTime: "2017-12-31",
    videoUrls:  ["https://youtu.be/FyZ_LPzwn0k"],
    src:        "srdc",
    srId:       "zq6d4kry",
  },
  {
    playerId:   "Wambo / CreepingChamp",
    clearTime:  "1:16.000",
    uploadTime: "2020-12-06",
    videoUrls:  ["https://www.youtube.com/watch?v=PTxo5czXMRU"],
    src:        "srdc",
    srId:       "y2d2xejz",
  },
  {
    playerId:   "Wambo / CreepingChamp",
    clearTime:  "1:16.000",
    uploadTime: "2020-12-06",
    videoUrls:  ["https://www.youtube.com/watch?v=PTxo5czXMRU"],
    src:        "srdc",
    srId:       "z09drljz",
  },
  {
    playerId:   "LucianPlaysAllDay / HelpMeDie09 / Gammer--2007 / Only_01-left",
    clearTime:  "1:34.000",
    uploadTime: "2020-11-15",
    videoUrls:  ["https://www.twitch.tv/videos/812745785"],
    src:        "srdc",
    srId:       "zq4e8vxm",
  },
];