/* speedrun.com 原始抓取数据 — Spy Missions / Arval / Solo */
/* level_id=o9x7rm1d | 共 26 条 */
var spy_missions_arval_soloRecords = [
  {
    playerId:   "Salat",
    clearTime:  "0:33.183",
    uploadTime: "2026-01-16",
    videoUrls:  ["https://youtu.be/4AFQSX5u9U0"],
    src:        "srdc",
    srId:       "yw524k3y",
  },
  {
    playerId:   "L1ndell",
    clearTime:  "0:39.000",
    uploadTime: "2026-01-06",
    videoUrls:  ["https://youtu.be/M13ymDAfIbA"],
    src:        "srdc",
    srId:       "mr5x7o2y",
  },
  {
    playerId:   "_Gabriel",
    clearTime:  "0:43.000",
    uploadTime: "2023-09-08",
    videoUrls:  ["https://youtu.be/FrZqz4OYtFg"],
    src:        "srdc",
    srId:       "z5k5vkdz",
  },
  {
    playerId:   "PrimedDarkeN",
    clearTime:  "0:44.000",
    uploadTime: "2021-07-20",
    videoUrls:  ["https://www.youtube.com/watch?v=f2b3I70CpvU"],
    src:        "srdc",
    srId:       "m3re61gm",
  },
  {
    playerId:   "NoorbbY",
    clearTime:  "0:45.000",
    uploadTime: "2025-03-07",
    videoUrls:  ["https://youtu.be/j9MZMp0XR_0"],
    src:        "srdc",
    srId:       "m7eov75z",
  },
  {
    playerId:   "Febi",
    clearTime:  "0:48.000",
    uploadTime: "2021-07-22",
    videoUrls:  ["https://www.youtube.com/watch?v=5sn_AehX-FQ"],
    src:        "srdc",
    srId:       "m7dr3ewm",
  },
  {
    playerId:   "FXCloud",
    clearTime:  "0:51.000",
    uploadTime: "2026-01-02",
    videoUrls:  ["https://youtu.be/EpZEoVwh3kI"],
    src:        "srdc",
    srId:       "zn52el3z",
  },
  {
    playerId:   "Wasamii",
    clearTime:  "0:53.000",
    uploadTime: "2021-07-23",
    videoUrls:  ["https://youtu.be/rVVFDor1Iac"],
    src:        "srdc",
    srId:       "zxgep5gy",
  },
  {
    playerId:   "RoniPrime",
    clearTime:  "0:54.933",
    uploadTime: "2026-01-09",
    videoUrls:  ["https://youtu.be/0YwWW1H20Aw"],
    src:        "srdc",
    srId:       "m32jvrgy",
  },
  {
    playerId:   "Kuremento",
    clearTime:  "0:55.000",
    uploadTime: "2021-03-19",
    videoUrls:  ["https://youtu.be/kvZb81ks3Z0"],
    src:        "srdc",
    srId:       "zp3o8dnm",
  },
  {
    playerId:   "Menadion",
    clearTime:  "0:57.000",
    uploadTime: "2020-11-16",
    videoUrls:  ["https://www.youtube.com/watch?v=d3MsdCm6H5Y"],
    src:        "srdc",
    srId:       "y2ded8wz",
  },
  {
    playerId:   "Boll",
    clearTime:  "0:57.000",
    uploadTime: "2021-02-10",
    videoUrls:  ["https://youtu.be/Y2rgM6j_VwY"],
    src:        "srdc",
    srId:       "m787xpwz",
  },
  {
    playerId:   "Yangoo",
    clearTime:  "0:57.000",
    uploadTime: "2023-04-19",
    videoUrls:  ["https://youtu.be/s6Qmcw0GS9U"],
    src:        "srdc",
    srId:       "yol1r65y",
  },
  {
    playerId:   "nek5",
    clearTime:  "0:57.000",
    uploadTime: "2025-05-04",
    videoUrls:  ["https://www.youtube.com/watch?v=Mj03fefb5MA"],
    src:        "srdc",
    srId:       "mkw9vexm",
  },
  {
    playerId:   "Salat",
    clearTime:  "0:57.879",
    uploadTime: "2019-08-21",
    videoUrls:  ["https://www.youtube.com/watch?v=gZ6Pwhzc6N8"],
    src:        "srdc",
    srId:       "yv31vp6z",
  },
  {
    playerId:   "holleufer98",
    clearTime:  "1:00.344",
    uploadTime: "2017-12-06",
    videoUrls:  ["https://youtu.be/KqT7sYVBGSY"],
    src:        "srdc",
    srId:       "z5oe6k5y",
  },
  {
    playerId:   "Nusmag",
    clearTime:  "1:00.944",
    uploadTime: "2017-09-25",
    videoUrls:  ["https://youtu.be/3vjCsNVQ0qw"],
    src:        "srdc",
    srId:       "ydqw3eqm",
  },
  {
    playerId:   "zukerben",
    clearTime:  "1:03.000",
    uploadTime: "2020-02-15",
    videoUrls:  ["https://www.youtube.com/watch?v=hBmZfM_KXH0"],
    src:        "srdc",
    srId:       "y6lwx1py",
  },
  {
    playerId:   "Nusmag",
    clearTime:  "1:06.600",
    uploadTime: "2018-07-10",
    videoUrls:  ["https://youtu.be/OfLg86ysCew"],
    src:        "srdc",
    srId:       "mk922exz",
  },
  {
    playerId:   "Nonqui",
    clearTime:  "1:11.000",
    uploadTime: "2019-02-28",
    videoUrls:  ["https://www.youtube.com/watch?v=Rpku-emY1AI&feature=youtu.be"],
    src:        "srdc",
    srId:       "zg7612jz",
  },
  {
    playerId:   "holleufer98",
    clearTime:  "1:11.555",
    uploadTime: "2017-12-05",
    videoUrls:  ["https://youtu.be/SeJIxUMShKI"],
    src:        "srdc",
    srId:       "zn8j959z",
  },
  {
    playerId:   "ThatBlue",
    clearTime:  "1:13.423",
    uploadTime: "2018-06-26",
    videoUrls:  ["https://www.youtube.com/watch?v=uwA3pxDBdZo&feature=youtu.be"],
    src:        "srdc",
    srId:       "y433wpkz",
  },
  {
    playerId:   "Akemi",
    clearTime:  "1:17.050",
    uploadTime: "2017-09-20",
    videoUrls:  ["https://youtu.be/GP8WD3tH1s8"],
    src:        "srdc",
    srId:       "z0e74eom",
  },
  {
    playerId:   "OverusedMemes",
    clearTime:  "1:17.461",
    uploadTime: "2017-09-01",
    videoUrls:  ["https://www.youtube.com/watch?v=BhN9o9zSOeU"],
    src:        "srdc",
    srId:       "yl9qg3xy",
  },
  {
    playerId:   "LeChat930",
    clearTime:  "1:35.000",
    uploadTime: "2023-07-08",
    videoUrls:  ["https://www.youtube.com/watch?v=FxhzBeggWhc"],
    src:        "srdc",
    srId:       "y62ognjz",
  },
  {
    playerId:   "zopney",
    clearTime:  "1:39.068",
    uploadTime: "2017-08-26",
    videoUrls:  ["https://www.youtube.com/watch?v=_mtcVe7G4jo"],
    src:        "srdc",
    srId:       "zgng09ey",
  },
];