/* speedrun.com 原始抓取数据 — Spy Missions / Bode / Solo */
/* level_id=kwjz0gr9 | 共 20 条 */
var spy_missions_bode_soloRecords = [
  {
    playerId:   "Salat",
    clearTime:  "0:32.850",
    uploadTime: "2026-01-21",
    videoUrls:  ["https://youtu.be/Rorx4ZFNejA"],
    src:        "srdc",
    srId:       "yj77343y",
  },
  {
    playerId:   "L1ndell",
    clearTime:  "0:33.167",
    uploadTime: "2026-01-10",
    videoUrls:  ["https://youtu.be/BHHA_3yNIFk"],
    src:        "srdc",
    srId:       "ydov870z",
  },
  {
    playerId:   "Mortar",
    clearTime:  "0:37.000",
    uploadTime: "2024-03-17",
    videoUrls:  ["https://www.youtube.com/watch?v=86KTQS_3Htg"],
    src:        "srdc",
    srId:       "y22dnv9y",
  },
  {
    playerId:   "Mortar",
    clearTime:  "0:37.000",
    uploadTime: "2024-03-17",
    videoUrls:  ["https://www.youtube.com/watch?v=86KTQS_3Htg"],
    src:        "srdc",
    srId:       "y6vrg6pm",
  },
  {
    playerId:   "PrimedDarkeN",
    clearTime:  "0:40.000",
    uploadTime: "2022-06-08",
    videoUrls:  ["https://www.youtube.com/watch?v=o21FSBQuHS4"],
    src:        "srdc",
    srId:       "y9v630vm",
  },
  {
    playerId:   "Endryx_Ow",
    clearTime:  "0:40.000",
    uploadTime: "2025-06-24",
    videoUrls:  ["https://youtu.be/gfiTXEPMshI?si=nd-nLhtMVv3rcSnn"],
    src:        "srdc",
    srId:       "z16pjv7m",
  },
  {
    playerId:   "Theotim",
    clearTime:  "0:43.000",
    uploadTime: "2024-05-07",
    videoUrls:  ["https://youtu.be/l4nRBAbRBPo"],
    src:        "srdc",
    srId:       "m7n3q5ez",
  },
  {
    playerId:   "Febi",
    clearTime:  "0:47.000",
    uploadTime: "2021-07-26",
    videoUrls:  ["https://www.youtube.com/watch?v=SfEcnXlkuzY"],
    src:        "srdc",
    srId:       "mrnjvkgy",
  },
  {
    playerId:   "Boll",
    clearTime:  "0:55.000",
    uploadTime: "2021-02-07",
    videoUrls:  ["https://www.youtube.com/watch?v=ilONYiXw54w&feature=youtu.be&ab_channel=MuraTradebanned"],
    src:        "srdc",
    srId:       "y2vxed6z",
  },
  {
    playerId:   "Menadion",
    clearTime:  "0:56.000",
    uploadTime: "2020-09-17",
    videoUrls:  ["https://www.youtube.com/watch?v=c76XNdcoRHc"],
    src:        "srdc",
    srId:       "ylv98krm",
  },
  {
    playerId:   "Salat",
    clearTime:  "0:57.883",
    uploadTime: "2019-08-26",
    videoUrls:  ["https://www.youtube.com/watch?v=vCGpypd1cVo"],
    src:        "srdc",
    srId:       "yd6rkxjz",
  },
  {
    playerId:   "Wasamii",
    clearTime:  "0:58.000",
    uploadTime: "2021-07-24",
    videoUrls:  ["https://youtu.be/ffco01M5Zvg"],
    src:        "srdc",
    srId:       "z1xd36wm",
  },
  {
    playerId:   "holleufer98",
    clearTime:  "0:58.500",
    uploadTime: "2018-07-03",
    videoUrls:  ["https://www.youtube.com/watch?v=ZakAEfLQQtU"],
    src:        "srdc",
    srId:       "z033d29z",
  },
  {
    playerId:   "zukerben",
    clearTime:  "1:03.000",
    uploadTime: "2020-02-09",
    videoUrls:  ["https://www.youtube.com/watch?v=NMCqT8O83QM"],
    src:        "srdc",
    srId:       "m312evgz",
  },
  {
    playerId:   "holleufer98",
    clearTime:  "1:05.282",
    uploadTime: "2018-07-10",
    videoUrls:  ["https://www.youtube.com/watch?v=Pk_odhaVfWQ&feature=youtu.be"],
    src:        "srdc",
    srId:       "yd365x0z",
  },
  {
    playerId:   "Nusmag",
    clearTime:  "1:06.967",
    uploadTime: "2018-07-05",
    videoUrls:  ["https://youtu.be/E2aaJ5Vu9oY"],
    src:        "srdc",
    srId:       "y922g5rz",
  },
  {
    playerId:   "NightWorrer",
    clearTime:  "1:08.802",
    uploadTime: "2018-07-23",
    videoUrls:  ["https://youtu.be/tWEjtpJHBmk"],
    src:        "srdc",
    srId:       "z0353r9z",
  },
  {
    playerId:   "Fr3zzco",
    clearTime:  "1:10.000",
    uploadTime: "2024-02-28",
    videoUrls:  ["https://youtu.be/-i5aJ6G9800"],
    src:        "srdc",
    srId:       "yvlj5r6z",
  },
  {
    playerId:   "ThatBlue",
    clearTime:  "1:10.453",
    uploadTime: "2018-07-03",
    videoUrls:  ["https://www.youtube.com/watch?v=KTATyEEBpWg&feature=youtu.be"],
    src:        "srdc",
    srId:       "z511gpgm",
  },
  {
    playerId:   "LeChat930",
    clearTime:  "1:33.000",
    uploadTime: "2023-07-09",
    videoUrls:  ["https://www.youtube.com/watch?v=_iosaMEbQbg"],
    src:        "srdc",
    srId:       "y986exnz",
  },
];