/* speedrun.com 原始抓取数据 — Spy Missions / Cambria / Solo */
/* level_id=xd12zzqw | 共 41 条 */
var spy_missions_cambria_soloRecords = [
  {
    playerId:   "Salat",
    clearTime:  "0:47.433",
    uploadTime: "2026-05-03",
    videoUrls:  ["https://youtu.be/mHErshqhclU"],
    src:        "srdc",
    srId:       "zpvp9vxz",
  },
  {
    playerId:   "Mortar",
    clearTime:  "0:49.000",
    uploadTime: "2024-03-18",
    videoUrls:  ["https://www.youtube.com/watch?v=vgvY0H3SkVE"],
    src:        "srdc",
    srId:       "y46e49kz",
  },
  {
    playerId:   "Mortar",
    clearTime:  "0:49.000",
    uploadTime: "2024-03-18",
    videoUrls:  ["https://www.youtube.com/watch?v=vgvY0H3SkVE"],
    src:        "srdc",
    srId:       "zq84ok8z",
  },
  {
    playerId:   "Endryx_Ow",
    clearTime:  "0:49.000",
    uploadTime: "2024-11-02",
    videoUrls:  ["https://youtu.be/Wlq-156G0Bg?si=-vQ8IVIYt3Ok3TYs"],
    src:        "srdc",
    srId:       "zgo1rpem",
  },
  {
    playerId:   "Salat",
    clearTime:  "0:49.000",
    uploadTime: "2026-03-12",
    videoUrls:  ["https://youtu.be/BQ7iv2zDgto"],
    src:        "srdc",
    srId:       "zxp2wxky",
  },
  {
    playerId:   "PrimedDarkeN",
    clearTime:  "0:50.000",
    uploadTime: "2023-08-30",
    videoUrls:  ["https://www.youtube.com/watch?v=IzmJE3DYtG0"],
    src:        "srdc",
    srId:       "znvn618m",
  },
  {
    playerId:   "Akula",
    clearTime:  "0:55.000",
    uploadTime: "2023-02-27",
    videoUrls:  ["https://www.youtube.com/watch?v=xaM8KCG8Ihc&ab_channel=someone"],
    src:        "srdc",
    srId:       "z0nd3k4m",
  },
  {
    playerId:   "OgvDams",
    clearTime:  "0:55.000",
    uploadTime: "2024-03-17",
    videoUrls:  ["https://www.youtube.com/watch?v=p5iCWOrQ3mk"],
    src:        "srdc",
    srId:       "mew6gx3m",
  },
  {
    playerId:   "L1ndell",
    clearTime:  "0:56.000",
    uploadTime: "2023-01-26",
    videoUrls:  ["https://youtu.be/M4U6cUdqB-s"],
    src:        "srdc",
    srId:       "y4g8xeqy",
  },
  {
    playerId:   "Wasamii",
    clearTime:  "0:58.000",
    uploadTime: "2023-02-01",
    videoUrls:  ["https://youtu.be/X-rJjjUIKh4"],
    src:        "srdc",
    srId:       "ywv366pz",
  },
  {
    playerId:   "PrimedDarkeN",
    clearTime:  "0:59.000",
    uploadTime: "2021-04-04",
    videoUrls:  ["https://www.youtube.com/watch?v=1_xejd8ncsM"],
    src:        "srdc",
    srId:       "y9nrjpnz",
  },
  {
    playerId:   "TheLostJoshua",
    clearTime:  "1:00.000",
    uploadTime: "2022-11-26",
    videoUrls:  ["https://www.youtube.com/watch?v=R5bultc-o_Y"],
    src:        "srdc",
    srId:       "mroje88m",
  },
  {
    playerId:   "Mortar",
    clearTime:  "1:01.000",
    uploadTime: "2020-12-24",
    videoUrls:  ["https://www.youtube.com/watch?v=FFNJKszM-n4"],
    src:        "srdc",
    srId:       "ywd2l60z",
  },
  {
    playerId:   "Mortar",
    clearTime:  "1:01.000",
    uploadTime: "2020-12-24",
    videoUrls:  ["https://www.youtube.com/watch?v=FFNJKszM-n4"],
    src:        "srdc",
    srId:       "yj6qndgz",
  },
  {
    playerId:   "Febi",
    clearTime:  "1:01.000",
    uploadTime: "2021-06-18",
    videoUrls:  ["https://www.youtube.com/watch?v=O_EoFt8P12s"],
    src:        "srdc",
    srId:       "me7gkx2y",
  },
  {
    playerId:   "ChungFu",
    clearTime:  "1:01.000",
    uploadTime: "2024-03-01",
    videoUrls:  ["https://www.youtube.com/watch?v=y1X9PEwuJtM"],
    src:        "srdc",
    srId:       "zq8r6jxz",
  },
  {
    playerId:   "Seiso",
    clearTime:  "1:06.000",
    uploadTime: "2023-09-08",
    videoUrls:  ["https://www.youtube.com/watch?v=pRmg68bi2VM"],
    src:        "srdc",
    srId:       "zxw9njgm",
  },
  {
    playerId:   "Kuremento",
    clearTime:  "1:07.000",
    uploadTime: "2021-04-03",
    videoUrls:  ["https://www.youtube.com/watch?v=tmLuTgra_4Q"],
    src:        "srdc",
    srId:       "yj109eny",
  },
  {
    playerId:   "Theotim",
    clearTime:  "1:12.000",
    uploadTime: "2023-04-29",
    videoUrls:  ["https://www.youtube.com/watch?v=Vi4Y_ZyotMk"],
    src:        "srdc",
    srId:       "yl632g2y",
  },
  {
    playerId:   "ChungFu",
    clearTime:  "1:15.000",
    uploadTime: "2022-02-18",
    videoUrls:  ["https://youtu.be/j0EvcM5wRgs"],
    src:        "srdc",
    srId:       "m36jnndm",
  },
  {
    playerId:   "Maktoob",
    clearTime:  "1:15.000",
    uploadTime: "2023-08-14",
    videoUrls:  ["https://www.youtube.com/watch?v=PJDycDRJDHg"],
    src:        "srdc",
    srId:       "m70jqowy",
  },
  {
    playerId:   "zukerben",
    clearTime:  "1:18.000",
    uploadTime: "2020-02-10",
    videoUrls:  ["https://www.youtube.com/watch?v=Txcuoh077rM"],
    src:        "srdc",
    srId:       "yl024k3y",
  },
  {
    playerId:   "Nonqui",
    clearTime:  "1:23.000",
    uploadTime: "2019-02-27",
    videoUrls:  ["https://www.youtube.com/watch?v=8eG2icS_cFY&t"],
    src:        "srdc",
    srId:       "ywp22x2z",
  },
  {
    playerId:   "holleufer98",
    clearTime:  "1:23.317",
    uploadTime: "2018-02-22",
    videoUrls:  ["https://youtu.be/fl5EfLBGb6w"],
    src:        "srdc",
    srId:       "z5owrdey",
  },
  {
    playerId:   "holleufer98",
    clearTime:  "1:23.317",
    uploadTime: "2018-02-22",
    videoUrls:  ["https://youtu.be/fl5EfLBGb6w"],
    src:        "srdc",
    srId:       "zq6p1v8y",
  },
  {
    playerId:   "NightWorrer",
    clearTime:  "1:25.251",
    uploadTime: "2018-02-18",
    videoUrls:  ["https://youtu.be/7et_Z4tvv88"],
    src:        "srdc",
    srId:       "mrq0334y",
  },
  {
    playerId:   "Akemi",
    clearTime:  "1:25.549",
    uploadTime: "2017-12-14",
    videoUrls:  ["https://youtu.be/5Z1QBjiVH2k"],
    src:        "srdc",
    srId:       "yw1rd8nz",
  },
  {
    playerId:   "Akemi",
    clearTime:  "1:25.549",
    uploadTime: "2017-12-14",
    videoUrls:  ["https://youtu.be/5Z1QBjiVH2k"],
    src:        "srdc",
    srId:       "yjk26lom",
  },
  {
    playerId:   "Seiso",
    clearTime:  "1:27.000",
    uploadTime: "2022-11-06",
    videoUrls:  ["https://www.youtube.com/watch?v=5T4FcrnSXTw"],
    src:        "srdc",
    srId:       "yd1podjy",
  },
  {
    playerId:   "Chansey",
    clearTime:  "1:27.500",
    uploadTime: "2019-02-02",
    videoUrls:  ["https://www.youtube.com/watch?v=i873myi76S0"],
    src:        "srdc",
    srId:       "z51gqdnm",
  },
  {
    playerId:   "LeChat930",
    clearTime:  "1:33.000",
    uploadTime: "2023-08-20",
    videoUrls:  ["https://www.youtube.com/watch?v=u4zr0S4x3ic"],
    src:        "srdc",
    srId:       "znvl88vm",
  },
  {
    playerId:   "ErrorFileSystem",
    clearTime:  "1:35.000",
    uploadTime: "2020-03-19",
    videoUrls:  ["https://www.youtube.com/watch?v=UybH9dsr6rs"],
    src:        "srdc",
    srId:       "y6lkvxjy",
  },
  {
    playerId:   "ThatBlue",
    clearTime:  "1:35.361",
    uploadTime: "2018-12-05",
    videoUrls:  ["https://youtu.be/U79vVKUIS3A"],
    src:        "srdc",
    srId:       "zg7e3xnz",
  },
  {
    playerId:   "-Rekken-",
    clearTime:  "1:35.512",
    uploadTime: "2018-05-11",
    videoUrls:  ["https://youtu.be/VHb22-13Y8o"],
    src:        "srdc",
    srId:       "mrq3nrdy",
  },
  {
    playerId:   "-Rekken-",
    clearTime:  "1:35.512",
    uploadTime: "2018-05-11",
    videoUrls:  ["https://youtu.be/VHb22-13Y8o"],
    src:        "srdc",
    srId:       "zxveo85y",
  },
  {
    playerId:   "Vici",
    clearTime:  "1:46.000",
    uploadTime: "2018-09-30",
    videoUrls:  ["https://youtu.be/VjcbXoO0IPA"],
    src:        "srdc",
    srId:       "y2q7o97y",
  },
  {
    playerId:   "Nusmag",
    clearTime:  "1:52.546",
    uploadTime: "2017-09-21",
    videoUrls:  ["https://youtu.be/woXCWAfY3k4"],
    src:        "srdc",
    srId:       "y6794k0m",
  },
  {
    playerId:   "Nusmag",
    clearTime:  "1:52.546",
    uploadTime: "2017-09-21",
    videoUrls:  ["https://youtu.be/woXCWAfY3k4"],
    src:        "srdc",
    srId:       "yvgokw8y",
  },
  {
    playerId:   "jonocolwell",
    clearTime:  "1:59.000",
    uploadTime: "2020-05-21",
    videoUrls:  ["https://www.youtube.com/watch?v=8xwsebFkT2Q"],
    src:        "srdc",
    srId:       "meoe0k8z",
  },
  {
    playerId:   "-Piglington-",
    clearTime:  "2:08.000",
    uploadTime: "2018-11-04",
    videoUrls:  ["https://www.youtube.com/watch?v=gr4P1Wfbzpw&feature=youtu.be"],
    src:        "srdc",
    srId:       "yvj0gl4y",
  },
  {
    playerId:   "iFlaxo",
    clearTime:  "2:23.000",
    uploadTime: "2019-09-15",
    videoUrls:  ["https://www.youtube.com/watch?v=cBiEumUgALQ&feature=youtu.be"],
    src:        "srdc",
    srId:       "m7qw8r0z",
  },
];