/* speedrun.com 原始抓取数据 — Spy Missions / Dione / Solo */
/* level_id=rdnzmyqd | 共 16 条 */
var spy_missions_dione_soloRecords = [
  {
    playerId:   "Salat",
    clearTime:  "0:36.883",
    uploadTime: "2026-01-04",
    videoUrls:  ["https://youtu.be/c7V68RCviFI"],
    src:        "srdc",
    srId:       "yl5x9p2z",
  },
  {
    playerId:   "L1ndell",
    clearTime:  "0:42.000",
    uploadTime: "2022-12-30",
    videoUrls:  ["https://youtu.be/tFVHLWjN1Vs"],
    src:        "srdc",
    srId:       "ydg572xy",
  },
  {
    playerId:   "PrimedDarkeN",
    clearTime:  "0:43.000",
    uploadTime: "2021-06-11",
    videoUrls:  ["https://www.youtube.com/watch?v=zG2dziz5ICw"],
    src:        "srdc",
    srId:       "y4rol2nz",
  },
  {
    playerId:   "Febi",
    clearTime:  "0:48.000",
    uploadTime: "2021-12-09",
    videoUrls:  ["https://www.youtube.com/watch?v=LhDhaikc7Oc"],
    src:        "srdc",
    srId:       "y6n7v56z",
  },
  {
    playerId:   "Salat",
    clearTime:  "0:56.666",
    uploadTime: "2019-08-18",
    videoUrls:  ["https://www.youtube.com/watch?v=JByfjrZj8F4"],
    src:        "srdc",
    srId:       "y9593g2z",
  },
  {
    playerId:   "zukerben",
    clearTime:  "0:58.133",
    uploadTime: "2020-05-06",
    videoUrls:  ["https://www.youtube.com/watch?v=g4VzRQn_YRQ"],
    src:        "srdc",
    srId:       "zx2d0n8m",
  },
  {
    playerId:   "holleufer98",
    clearTime:  "0:58.476",
    uploadTime: "2018-07-20",
    videoUrls:  ["https://www.youtube.com/watch?v=RM-kaJLVVTg&feature=youtu.be"],
    src:        "srdc",
    srId:       "yvj3epey",
  },
  {
    playerId:   "Nusmag",
    clearTime:  "0:58.809",
    uploadTime: "2018-07-06",
    videoUrls:  ["https://youtu.be/x0sNw-qspjI"],
    src:        "srdc",
    srId:       "zn44lvlm",
  },
  {
    playerId:   "Wasamii",
    clearTime:  "1:00.000",
    uploadTime: "2021-07-24",
    videoUrls:  ["https://youtu.be/DxT9OKuxVkA"],
    src:        "srdc",
    srId:       "y693p91y",
  },
  {
    playerId:   "-Rekken-",
    clearTime:  "1:02.333",
    uploadTime: "2018-06-21",
    videoUrls:  ["https://youtu.be/o16-QPh_L0g"],
    src:        "srdc",
    srId:       "yj4kv1oy",
  },
  {
    playerId:   "felix_rs",
    clearTime:  "1:07.984",
    uploadTime: "2019-07-30",
    videoUrls:  ["https://www.youtube.com/watch?v=xQTkFipjzro&t"],
    src:        "srdc",
    srId:       "yw4d7q2z",
  },
  {
    playerId:   "holleufer98",
    clearTime:  "1:10.287",
    uploadTime: "2018-07-20",
    videoUrls:  ["https://youtu.be/Vo0LaJ5wUHM"],
    src:        "srdc",
    srId:       "zn4r6vlm",
  },
  {
    playerId:   "Nusmag",
    clearTime:  "1:10.754",
    uploadTime: "2018-07-06",
    videoUrls:  ["https://youtu.be/x0sNw-qspjI"],
    src:        "srdc",
    srId:       "ywpp7r9z",
  },
  {
    playerId:   "ThatBlue",
    clearTime:  "1:13.539",
    uploadTime: "2018-05-18",
    videoUrls:  ["https://www.youtube.com/watch?v=O6mVlPB2D5k&feature=youtu.be"],
    src:        "srdc",
    srId:       "yvgw5goy",
  },
  {
    playerId:   "-Rekken-",
    clearTime:  "1:13.799",
    uploadTime: "2018-06-01",
    videoUrls:  ["https://youtu.be/9OIWx7Q2l8U"],
    src:        "srdc",
    srId:       "mk9lqqvz",
  },
  {
    playerId:   "LeChat930",
    clearTime:  "1:36.000",
    uploadTime: "2023-07-10",
    videoUrls:  ["https://www.youtube.com/watch?v=xQF7oSQE7yE"],
    src:        "srdc",
    srId:       "y2gjl2wz",
  },
];