/* speedrun.com 原始抓取数据 — Spy Missions / Kelpie / Co-op */
/* level_id=ldygr6jd | 共 11 条 */
var spy_missions_kelpie_coopRecords = [
  {
    playerId:   "Endryx_Ow / Salat / L1ndell",
    clearTime:  "0:32.000",
    uploadTime: "2026-02-09",
    videoUrls:  ["https://youtu.be/vRf9jBjmE6Q"],
    src:        "srdc",
    srId:       "yw59w82y",
  },
  {
    playerId:   "Salat / L1ndell",
    clearTime:  "0:35.767",
    uploadTime: "2026-01-03",
    videoUrls:  ["https://www.youtube.com/watch?v=d1ngFnyPsDA", "https://youtu.be/UyGNUSGIY9g"],
    src:        "srdc",
    srId:       "z0kqw6em",
  },
  {
    playerId:   "PrimedDarkeN / Kuremento / Febi",
    clearTime:  "0:39.000",
    uploadTime: "2021-04-16",
    videoUrls:  ["https://www.youtube.com/watch?v=8mauyEf2AHo"],
    src:        "srdc",
    srId:       "y997weny",
  },
  {
    playerId:   "PrimedDarkeN / Boll / Menadion",
    clearTime:  "0:44.000",
    uploadTime: "2020-12-22",
    videoUrls:  ["https://www.youtube.com/watch?v=DUSDiFhdWJQ&feature=youtu.be"],
    src:        "srdc",
    srId:       "ylvjlkrm",
  },
  {
    playerId:   "silverdk / lucasengenho / Mortar",
    clearTime:  "0:49.100",
    uploadTime: "2019-08-23",
    videoUrls:  ["https://www.youtube.com/watch?v=nu0W-0BvpOc"],
    src:        "srdc",
    srId:       "yj3g03oz",
  },
  {
    playerId:   "holleufer98 / Nusmag",
    clearTime:  "0:50.384",
    uploadTime: "2018-07-08",
    videoUrls:  ["https://youtu.be/9dOkQmHw9lE"],
    src:        "srdc",
    srId:       "zq3rk6xy",
  },
  {
    playerId:   "PrimedDarkeN / Boll",
    clearTime:  "0:54.000",
    uploadTime: "2020-12-19",
    videoUrls:  ["https://youtu.be/Rw7C2bYOn3I"],
    src:        "srdc",
    srId:       "zxdjerky",
  },
  {
    playerId:   "-Rekken- / QuasarWF / ThatBlue",
    clearTime:  "1:01.439",
    uploadTime: "2018-05-16",
    videoUrls:  ["https://www.youtube.com/watch?v=K0BajJ-TGhA&feature=youtu.be"],
    src:        "srdc",
    srId:       "zn8dx19z",
  },
  {
    playerId:   "Wambo / CreepingChamp",
    clearTime:  "1:05.000",
    uploadTime: "2020-12-06",
    videoUrls:  ["https://www.youtube.com/watch?v=72GNfYJ6mDs"],
    src:        "srdc",
    srId:       "yj6ogd7z",
  },
  {
    playerId:   "Wambo / CreepingChamp",
    clearTime:  "1:05.000",
    uploadTime: "2020-12-06",
    videoUrls:  ["https://www.youtube.com/watch?v=72GNfYJ6mDs"],
    src:        "srdc",
    srId:       "zgvlgq0z",
  },
  {
    playerId:   "Panzof / LucianPlaysAllDay / Gammer--2007 / Malakiahdark",
    clearTime:  "2:13.000",
    uploadTime: "2020-11-25",
    videoUrls:  ["https://www.twitch.tv/videos/816173713"],
    src:        "srdc",
    srId:       "zxd3glky",
  },
];