/* speedrun.com 原始抓取数据 — Spy Missions / Kelpie / Solo */
/* level_id=ldygr6jd | 共 21 条 */
var spy_missions_kelpie_soloRecords = [
  {
    playerId:   "Salat",
    clearTime:  "0:39.750",
    uploadTime: "2026-01-06",
    videoUrls:  ["https://youtu.be/z-RZ_hgJI-8"],
    src:        "srdc",
    srId:       "mkr1kdvz",
  },
  {
    playerId:   "L1ndell",
    clearTime:  "0:40.000",
    uploadTime: "2026-01-07",
    videoUrls:  ["https://youtu.be/YQsiUoCKHus"],
    src:        "srdc",
    srId:       "y8npxw1y",
  },
  {
    playerId:   "Salat",
    clearTime:  "0:42.967",
    uploadTime: "2026-01-06",
    videoUrls:  ["https://youtu.be/6uijMJMs7cU"],
    src:        "srdc",
    srId:       "z0kqpp4m",
  },
  {
    playerId:   "PrimedDarkeN",
    clearTime:  "0:51.000",
    uploadTime: "2022-06-08",
    videoUrls:  ["https://www.youtube.com/watch?v=vj_AsZn2qaw"],
    src:        "srdc",
    srId:       "mr7onk2z",
  },
  {
    playerId:   "Febi",
    clearTime:  "0:55.000",
    uploadTime: "2021-07-22",
    videoUrls:  ["https://www.youtube.com/watch?v=bnq1pU8lD40"],
    src:        "srdc",
    srId:       "y8d5w11z",
  },
  {
    playerId:   "holleufer98",
    clearTime:  "1:03.213",
    uploadTime: "2017-11-27",
    videoUrls:  ["https://www.youtube.com/watch?v=lTjYv3Am1OI"],
    src:        "srdc",
    srId:       "y67o9j1m",
  },
  {
    playerId:   "Kuremento",
    clearTime:  "1:05.000",
    uploadTime: "2021-04-09",
    videoUrls:  ["https://youtu.be/p9gxiw43qPk"],
    src:        "srdc",
    srId:       "y66kk0py",
  },
  {
    playerId:   "Wasamii",
    clearTime:  "1:09.000",
    uploadTime: "2022-04-22",
    videoUrls:  ["https://youtu.be/qeTgtR9lvos"],
    src:        "srdc",
    srId:       "z527dlnz",
  },
  {
    playerId:   "zukerben",
    clearTime:  "1:12.000",
    uploadTime: "2020-02-09",
    videoUrls:  ["https://www.youtube.com/watch?v=kUThjTs5Gcc"],
    src:        "srdc",
    srId:       "zqr5x21y",
  },
  {
    playerId:   "TheLostJoshua",
    clearTime:  "1:12.000",
    uploadTime: "2022-11-16",
    videoUrls:  ["https://youtu.be/BFivoKXqILg"],
    src:        "srdc",
    srId:       "zgq5drjy",
  },
  {
    playerId:   "holleufer98",
    clearTime:  "1:14.057",
    uploadTime: "2018-07-11",
    videoUrls:  ["https://youtu.be/OHwqkOLOt6I"],
    src:        "srdc",
    srId:       "me8x902m",
  },
  {
    playerId:   "Nusmag",
    clearTime:  "1:19.096",
    uploadTime: "2018-07-11",
    videoUrls:  ["https://www.youtube.com/watch?v=ZLuZx9RR1Qw"],
    src:        "srdc",
    srId:       "yd369dvz",
  },
  {
    playerId:   "felix_rs",
    clearTime:  "1:32.292",
    uploadTime: "2019-07-21",
    videoUrls:  ["https://www.youtube.com/watch?v=m_quiiip9ks"],
    src:        "srdc",
    srId:       "zp4l478z",
  },
  {
    playerId:   "-Arcturus.",
    clearTime:  "1:39.298",
    uploadTime: "2018-07-14",
    videoUrls:  ["https://youtu.be/jvy4bNFF-NQ"],
    src:        "srdc",
    srId:       "z031ld9z",
  },
  {
    playerId:   "LeChat930",
    clearTime:  "1:47.000",
    uploadTime: "2023-07-11",
    videoUrls:  ["https://www.youtube.com/watch?v=Eh8zIPVpKTs"],
    src:        "srdc",
    srId:       "ydjj51vy",
  },
  {
    playerId:   "zzzzzhou",
    clearTime:  "1:51.000",
    uploadTime: "2020-04-13",
    videoUrls:  ["https://youtu.be/vmWik7BNUxY"],
    src:        "srdc",
    srId:       "yok25q7z",
  },
  {
    playerId:   "MagsPrime",
    clearTime:  "1:51.000",
    uploadTime: "2022-01-19",
    videoUrls:  ["https://youtu.be/8KD6D_TfCD8"],
    src:        "srdc",
    srId:       "yjxpllgz",
  },
  {
    playerId:   "zopney",
    clearTime:  "1:59.000",
    uploadTime: "2018-05-13",
    videoUrls:  ["https://www.youtube.com/watch?v=2D2C4f-LKcA"],
    src:        "srdc",
    srId:       "y23lk45m",
  },
  {
    playerId:   "V-_-iniciu-_-s",
    clearTime:  "2:11.000",
    uploadTime: "2019-07-20",
    videoUrls:  ["https://youtu.be/FNZutvzGLQ0"],
    src:        "srdc",
    srId:       "z57311nm",
  },
  {
    playerId:   "Scoinc",
    clearTime:  "2:19.000",
    uploadTime: "2018-07-16",
    videoUrls:  ["https://youtu.be/aJ5zclbaBiM"],
    src:        "srdc",
    srId:       "mr8el72y",
  },
  {
    playerId:   "SpeSOWN",
    clearTime:  "3:15.961",
    uploadTime: "2016-11-14",
    videoUrls:  ["https://www.youtube.com/watch?v=EhVvI-8z3rw"],
    src:        "srdc",
    srId:       "y23ok35m",
  },
];