/* speedrun.com 原始抓取数据 — Spy Missions / Nereid / Solo */
/* level_id=29v78q39 | 共 16 条 */
var spy_missions_nereid_soloRecords = [
  {
    playerId:   "Salat",
    clearTime:  "0:49.000",
    uploadTime: "2026-03-10",
    videoUrls:  ["https://youtu.be/aK4BXpR4haQ"],
    src:        "srdc",
    srId:       "yo8k30jz",
  },
  {
    playerId:   "Salat",
    clearTime:  "0:50.216",
    uploadTime: "2025-11-30",
    videoUrls:  ["https://youtu.be/3IpRhygc3xs"],
    src:        "srdc",
    srId:       "zg9pl7dm",
  },
  {
    playerId:   "PrimedDarkeN",
    clearTime:  "0:54.040",
    uploadTime: "2021-07-06",
    videoUrls:  ["https://www.youtube.com/watch?v=WtQOMqF9QnM"],
    src:        "srdc",
    srId:       "ydrp52wz",
  },
  {
    playerId:   "Wasamii",
    clearTime:  "1:10.833",
    uploadTime: "2022-03-27",
    videoUrls:  ["https://youtu.be/HgzdSMDk_6A"],
    src:        "srdc",
    srId:       "y9lrr3vy",
  },
  {
    playerId:   "-Rekken-",
    clearTime:  "1:14.541",
    uploadTime: "2018-06-27",
    videoUrls:  ["https://youtu.be/VlGyHeBwgw0"],
    src:        "srdc",
    srId:       "ywpp022z",
  },
  {
    playerId:   "-Rekken-",
    clearTime:  "1:15.666",
    uploadTime: "2018-08-11",
    videoUrls:  ["https://youtu.be/FU8xUB7895M"],
    src:        "srdc",
    srId:       "m3ogxgwm",
  },
  {
    playerId:   "Azynoth",
    clearTime:  "1:17.633",
    uploadTime: "2018-08-10",
    videoUrls:  ["https://youtu.be/6jR9aSzY-5M"],
    src:        "srdc",
    srId:       "y89r89nm",
  },
  {
    playerId:   "holleufer98",
    clearTime:  "1:18.078",
    uploadTime: "2018-01-08",
    videoUrls:  ["https://youtu.be/K-O_AcvxQro"],
    src:        "srdc",
    srId:       "y67q8x6m",
  },
  {
    playerId:   "Seiso",
    clearTime:  "1:29.000",
    uploadTime: "2023-09-14",
    videoUrls:  ["https://www.youtube.com/watch?v=3iRTZ-PH_Wo"],
    src:        "srdc",
    srId:       "y9k7v7kz",
  },
  {
    playerId:   "holleufer98",
    clearTime:  "1:31.592",
    uploadTime: "2018-01-08",
    videoUrls:  ["https://youtu.be/JppTeUge3pQ"],
    src:        "srdc",
    srId:       "y23kre5m",
  },
  {
    playerId:   "LeChat930",
    clearTime:  "1:52.000",
    uploadTime: "2023-09-15",
    videoUrls:  ["https://www.youtube.com/watch?v=mjj-5UxUeTw"],
    src:        "srdc",
    srId:       "y8kq6gny",
  },
  {
    playerId:   "MagsPrime",
    clearTime:  "1:57.000",
    uploadTime: "2022-01-19",
    videoUrls:  ["https://youtu.be/Y645lJaBFqQ"],
    src:        "srdc",
    srId:       "yorpk9dy",
  },
  {
    playerId:   "SpartansFury103",
    clearTime:  "2:18.000",
    uploadTime: "2020-12-30",
    videoUrls:  ["https://youtu.be/fduhdrJx0xQ"],
    src:        "srdc",
    srId:       "mk8xvnvm",
  },
  {
    playerId:   "Hennerz204",
    clearTime:  "2:37.000",
    uploadTime: "2021-07-18",
    videoUrls:  ["https://youtu.be/EZOK0l-WhKs"],
    src:        "srdc",
    srId:       "y8d74e1z",
  },
  {
    playerId:   "Zera",
    clearTime:  "2:49.000",
    uploadTime: "2019-09-08",
    videoUrls:  ["https://www.youtube.com/watch?v=eVFpCi5Oosw"],
    src:        "srdc",
    srId:       "z0174r8y",
  },
  {
    playerId:   "ShatteredEssence",
    clearTime:  "4:26.233",
    uploadTime: "2018-01-08",
    videoUrls:  ["https://www.youtube.com/watch?v=-mfLvNJnI0Q"],
    src:        "srdc",
    srId:       "zp00o4vm",
  },
];