/* speedrun.com 原始抓取数据 — Spy Missions / Oceanum / Co-op */
/* level_id=xd425l2w | 共 20 条 */
var spy_missions_oceanum_coopRecords = [
  {
    playerId:   "Endryx_Ow / Salat / L1ndell",
    clearTime:  "0:35.000",
    uploadTime: "2026-02-09",
    videoUrls:  ["https://youtu.be/qAw1HGy9wfw"],
    src:        "srdc",
    srId:       "yo5wqk1z",
  },
  {
    playerId:   "-Rekken- / QuasarWF / ThatBlue",
    clearTime:  "0:35.518",
    uploadTime: "2018-08-27",
    videoUrls:  ["https://youtu.be/vWWmTYgHcuo"],
    src:        "srdc",
    srId:       "zx463gqy",
  },
  {
    playerId:   "Febi / Boll / PrimedDarkeN",
    clearTime:  "0:39.000",
    uploadTime: "2021-04-11",
    videoUrls:  ["https://www.youtube.com/watch?v=Hq_lBOHIMAs&ab_channel=Mura"],
    src:        "srdc",
    srId:       "z0rwxojz",
  },
  {
    playerId:   "zxcMolniya / L1ndell",
    clearTime:  "0:39.000",
    uploadTime: "2021-11-15",
    videoUrls:  ["https://youtu.be/OmNItPvy-ms"],
    src:        "srdc",
    srId:       "y8e48q1y",
  },
  {
    playerId:   "Azynoth / ThatBlue / -Rekken-",
    clearTime:  "0:39.216",
    uploadTime: "2018-07-18",
    videoUrls:  ["https://youtu.be/bmn5oD532hc"],
    src:        "srdc",
    srId:       "z0318kez",
  },
  {
    playerId:   "Ceejay / -Arcturus. / QuasarWF",
    clearTime:  "0:41.233",
    uploadTime: "2018-07-18",
    videoUrls:  ["https://youtu.be/BXKAZQWFLH0"],
    src:        "srdc",
    srId:       "zg7kjx0z",
  },
  {
    playerId:   "--Q--EValueAction / .cat / namenBARS",
    clearTime:  "0:42.600",
    uploadTime: "2018-12-16",
    videoUrls:  ["https://youtu.be/SlSbyQskCYY"],
    src:        "srdc",
    srId:       "z11ll0rz",
  },
  {
    playerId:   "Febi / Akula / PrimedDarkeN",
    clearTime:  "0:45.000",
    uploadTime: "2021-03-31",
    videoUrls:  ["https://www.youtube.com/watch?v=_smUea6kjdg"],
    src:        "srdc",
    srId:       "znolv47y",
  },
  {
    playerId:   "PrimedDarkeN / Boll / Menadion",
    clearTime:  "0:48.000",
    uploadTime: "2020-12-22",
    videoUrls:  ["https://www.youtube.com/watch?v=bFvU-CNln0c&feature=youtu.be"],
    src:        "srdc",
    srId:       "yj6qwlgz",
  },
  {
    playerId:   "ThatBlue / -Rekken-",
    clearTime:  "0:48.532",
    uploadTime: "2018-07-17",
    videoUrls:  ["https://youtu.be/0uy_rryD8So"],
    src:        "srdc",
    srId:       "y925d4rz",
  },
  {
    playerId:   "-Arcturus. / QuasarWF / Ceejay",
    clearTime:  "0:50.716",
    uploadTime: "2018-07-17",
    videoUrls:  ["https://www.youtube.com/watch?v=zy_yqQcDL5c&feature=youtu.be"],
    src:        "srdc",
    srId:       "ywp4xnpz",
  },
  {
    playerId:   "Ceejay / ThatBlue",
    clearTime:  "0:51.985",
    uploadTime: "2018-11-30",
    videoUrls:  ["https://youtu.be/FZm0Bg52oWA"],
    src:        "srdc",
    srId:       "z03nq34z",
  },
  {
    playerId:   "holleufer98 / Nusmag",
    clearTime:  "0:52.252",
    uploadTime: "2018-07-08",
    videoUrls:  ["https://youtu.be/cRakpc_kNYE"],
    src:        "srdc",
    srId:       "mr8ejqdy",
  },
  {
    playerId:   "-Rekken- / ThatBlue",
    clearTime:  "0:54.721",
    uploadTime: "2018-06-20",
    videoUrls:  ["https://www.youtube.com/watch?v=XyuQbWiWsvM&feature=youtu.be"],
    src:        "srdc",
    srId:       "y2q36d7y",
  },
  {
    playerId:   "PrimedDarkeN / Boll",
    clearTime:  "0:55.000",
    uploadTime: "2020-12-19",
    videoUrls:  ["https://youtu.be/FHzyU8WimMU"],
    src:        "srdc",
    srId:       "yo3q1w5y",
  },
  {
    playerId:   "Koto / Divlyn",
    clearTime:  "1:00.000",
    uploadTime: "2018-04-08",
    videoUrls:  ["https://www.youtube.com/watch?v=FjEAiz6ZCJw"],
    src:        "srdc",
    srId:       "zxvrldgy",
  },
  {
    playerId:   "Wambo / CreepingChamp",
    clearTime:  "1:09.000",
    uploadTime: "2020-12-06",
    videoUrls:  ["https://www.youtube.com/watch?v=555l3IlP9vo"],
    src:        "srdc",
    srId:       "yo307d1y",
  },
  {
    playerId:   "Wambo / CreepingChamp",
    clearTime:  "1:09.000",
    uploadTime: "2020-12-06",
    videoUrls:  ["https://www.youtube.com/watch?v=555l3IlP9vo"],
    src:        "srdc",
    srId:       "zpl61gnm",
  },
  {
    playerId:   "deathcurzo / Gaqlaxy",
    clearTime:  "1:34.000",
    uploadTime: "2018-11-25",
    videoUrls:  ["https://www.youtube.com/watch?v=XZrD6bqa7yM&lc=z23lwjgxppyfuzwzo04t1aokgwu11jcuu0ngilkekb5ark0h00410"],
    src:        "srdc",
    srId:       "y43g8lkz",
  },
  {
    playerId:   "Panzof / LucianPlaysAllDay / Gammer--2007 / Only_01-left",
    clearTime:  "1:57.000",
    uploadTime: "2020-11-26",
    videoUrls:  ["https://www.twitch.tv/videos/816182602"],
    src:        "srdc",
    srId:       "zgvegpjz",
  },
];