/* speedrun.com 原始抓取数据 — Spy Missions / Oceanum / Solo */
/* level_id=xd425l2w | 共 34 条 */
var spy_missions_oceanum_soloRecords = [
  {
    playerId:   "Salat",
    clearTime:  "0:38.883",
    uploadTime: "2026-03-12",
    videoUrls:  ["https://youtu.be/aFWX7_Q-BsM"],
    src:        "srdc",
    srId:       "zpvrp6vz",
  },
  {
    playerId:   "Salat",
    clearTime:  "0:45.600",
    uploadTime: "2026-03-12",
    videoUrls:  ["https://youtu.be/bXgjQmUq6oY"],
    src:        "srdc",
    srId:       "y6w5qv0z",
  },
  {
    playerId:   "L1ndell",
    clearTime:  "0:46.100",
    uploadTime: "2026-02-08",
    videoUrls:  ["https://youtu.be/PNZiZqQfSeM"],
    src:        "srdc",
    srId:       "y8n7d35y",
  },
  {
    playerId:   "PrimedDarkeN",
    clearTime:  "0:50.000",
    uploadTime: "2022-06-08",
    videoUrls:  ["https://www.youtube.com/watch?v=AUDNMeTjKok"],
    src:        "srdc",
    srId:       "zx7no2qy",
  },
  {
    playerId:   "_Gabriel",
    clearTime:  "0:50.000",
    uploadTime: "2023-02-12",
    videoUrls:  ["https://www.youtube.com/watch?v=yWxZ7cpk62Q"],
    src:        "srdc",
    srId:       "m7220k9z",
  },
  {
    playerId:   "Salat",
    clearTime:  "0:52.717",
    uploadTime: "2019-09-21",
    videoUrls:  ["https://www.youtube.com/watch?v=ZUxGhiheHMc"],
    src:        "srdc",
    srId:       "znr793ly",
  },
  {
    playerId:   "holleufer98",
    clearTime:  "0:56.857",
    uploadTime: "2017-11-09",
    videoUrls:  ["https://www.youtube.com/watch?v=39seUf1N8hI&feature=youtu.be"],
    src:        "srdc",
    srId:       "m79xdl0y",
  },
  {
    playerId:   "Salat",
    clearTime:  "0:57.183",
    uploadTime: "2019-09-21",
    videoUrls:  ["https://www.youtube.com/watch?v=d9ewxvy9EIo"],
    src:        "srdc",
    srId:       "yv3qn9ez",
  },
  {
    playerId:   "Febi",
    clearTime:  "0:58.000",
    uploadTime: "2021-07-25",
    videoUrls:  ["https://www.youtube.com/watch?v=ZopMDvClQWo"],
    src:        "srdc",
    srId:       "z5d5vlnm",
  },
  {
    playerId:   "Nusmag",
    clearTime:  "0:59.409",
    uploadTime: "2017-09-21",
    videoUrls:  ["https://youtu.be/McORSzTz5T0"],
    src:        "srdc",
    srId:       "zpq8evxy",
  },
  {
    playerId:   "Nonqui",
    clearTime:  "1:02.495",
    uploadTime: "2019-06-30",
    videoUrls:  ["https://www.youtube.com/watch?v=5XZg7rkLnN4&feature=youtu.be"],
    src:        "srdc",
    srId:       "znrrqp8y",
  },
  {
    playerId:   "-Rekken-",
    clearTime:  "1:05.333",
    uploadTime: "2018-08-10",
    videoUrls:  ["https://youtu.be/oXeasiPgBAc"],
    src:        "srdc",
    srId:       "y89rjpxm",
  },
  {
    playerId:   "holleufer98",
    clearTime:  "1:06.950",
    uploadTime: "2017-11-13",
    videoUrls:  ["https://youtu.be/XCecivFHzK4"],
    src:        "srdc",
    srId:       "z13gqvjm",
  },
  {
    playerId:   "Nusmag",
    clearTime:  "1:07.517",
    uploadTime: "2017-09-24",
    videoUrls:  ["https://youtu.be/SpQo-j0pEKM"],
    src:        "srdc",
    srId:       "zn878plz",
  },
  {
    playerId:   "Rhystic",
    clearTime:  "1:07.650",
    uploadTime: "2022-03-13",
    videoUrls:  ["https://youtu.be/nTYvxqjJMLE"],
    src:        "srdc",
    srId:       "y8jlk7nz",
  },
  {
    playerId:   "Mortar",
    clearTime:  "1:08.000",
    uploadTime: "2020-12-24",
    videoUrls:  ["https://www.youtube.com/watch?v=IwqeMQpSmeY"],
    src:        "srdc",
    srId:       "y91e48km",
  },
  {
    playerId:   "Mortar",
    clearTime:  "1:08.000",
    uploadTime: "2020-12-24",
    videoUrls:  ["https://www.youtube.com/watch?v=IwqeMQpSmeY"],
    src:        "srdc",
    srId:       "m75lr0ez",
  },
  {
    playerId:   "TheLostJoshua",
    clearTime:  "1:12.000",
    uploadTime: "2022-11-15",
    videoUrls:  ["https://youtu.be/Ibbb2qTvSSg"],
    src:        "srdc",
    srId:       "m3xpg66m",
  },
  {
    playerId:   "ThatBlue",
    clearTime:  "1:12.605",
    uploadTime: "2018-08-26",
    videoUrls:  ["https://youtu.be/bOXy9tDNrm4"],
    src:        "srdc",
    srId:       "yvj2016y",
  },
  {
    playerId:   "Wasamii",
    clearTime:  "1:13.000",
    uploadTime: "2021-09-29",
    videoUrls:  ["https://youtu.be/oLsYiFOPGyA"],
    src:        "srdc",
    srId:       "y27gk25z",
  },
  {
    playerId:   "Chansey",
    clearTime:  "1:15.083",
    uploadTime: "2018-09-16",
    videoUrls:  ["https://www.youtube.com/watch?v=dKAh2bYjhV8"],
    src:        "srdc",
    srId:       "ywpq750z",
  },
  {
    playerId:   ".cat",
    clearTime:  "1:16.000",
    uploadTime: "2019-03-06",
    videoUrls:  ["https://www.youtube.com/watch?v=h1LC13ZzGa0&feature=youtu.be"],
    src:        "srdc",
    srId:       "m3o2nrqm",
  },
  {
    playerId:   "Ceejay",
    clearTime:  "1:16.776",
    uploadTime: "2018-08-15",
    videoUrls:  ["https://youtu.be/7H1LKukFAI8"],
    src:        "srdc",
    srId:       "zg7v6gnz",
  },
  {
    playerId:   "FXCloud",
    clearTime:  "1:21.613",
    uploadTime: "2019-09-15",
    videoUrls:  ["https://youtu.be/dqDQsylvwfg"],
    src:        "srdc",
    srId:       "yj3xg03z",
  },
  {
    playerId:   "Omnimble",
    clearTime:  "1:31.000",
    uploadTime: "2018-11-08",
    videoUrls:  ["https://youtu.be/dmTYvVoBqc0"],
    src:        "srdc",
    srId:       "yo2d787z",
  },
  {
    playerId:   "-Arcturus.",
    clearTime:  "1:31.227",
    uploadTime: "2018-07-15",
    videoUrls:  ["https://youtu.be/p3r2ImOS_c4"],
    src:        "srdc",
    srId:       "me8x1d2m",
  },
  {
    playerId:   "Megami_infini",
    clearTime:  "1:32.000",
    uploadTime: "2020-06-12",
    videoUrls:  ["https://www.youtube.com/watch?v=oWzTUpjdeOM"],
    src:        "srdc",
    srId:       "z15g7l9y",
  },
  {
    playerId:   "X479",
    clearTime:  "1:34.550",
    uploadTime: "2017-03-20",
    videoUrls:  ["https://www.youtube.com/watch?v=aK87MoCzMM8"],
    src:        "srdc",
    srId:       "ydq6l90m",
  },
  {
    playerId:   "--Liang.Pi--",
    clearTime:  "1:51.000",
    uploadTime: "2018-07-27",
    videoUrls:  ["https://www.youtube.com/watch?v=nlzgs1HFNxU"],
    src:        "srdc",
    srId:       "z035od9z",
  },
  {
    playerId:   "LeChat930",
    clearTime:  "1:51.000",
    uploadTime: "2023-07-12",
    videoUrls:  ["https://www.youtube.com/watch?v=17AG1Mn0BYU"],
    src:        "srdc",
    srId:       "z1llqjjm",
  },
  {
    playerId:   "MagsPrime",
    clearTime:  "1:54.000",
    uploadTime: "2022-01-19",
    videoUrls:  ["https://youtu.be/R4Jg71ITp_U"],
    src:        "srdc",
    srId:       "m7w6g5ez",
  },
  {
    playerId:   "Posous",
    clearTime:  "2:04.000",
    uploadTime: "2019-02-02",
    videoUrls:  ["https://www.youtube.com/watch?v=I7ktqJuHYZg"],
    src:        "srdc",
    srId:       "m7pok04m",
  },
  {
    playerId:   "-CCC-buttofu",
    clearTime:  "2:30.000",
    uploadTime: "2018-06-15",
    videoUrls:  ["https://youtu.be/m4M1RZvNNx4"],
    src:        "srdc",
    srId:       "zq367exy",
  },
  {
    playerId:   "Dexxterious",
    clearTime:  "2:54.000",
    uploadTime: "2018-10-31",
    videoUrls:  ["https://www.youtube.com/watch?v=G-4z78MIujE"],
    src:        "srdc",
    srId:       "y6px6n0m",
  },
];