/* speedrun.com 原始抓取数据 — Spy Missions / Pago / Co-op */
/* level_id=xd0qe8x9 | 共 10 条 */
var spy_missions_pago_coopRecords = [
  {
    playerId:   "Endryx_Ow / Salat / L1ndell",
    clearTime:  "0:34.000",
    uploadTime: "2026-02-09",
    videoUrls:  ["https://youtu.be/Yc-PBpfgn5U"],
    src:        "srdc",
    srId:       "zx51jdgm",
  },
  {
    playerId:   "PrimedDarkeN / Kuremento / Mortar",
    clearTime:  "0:39.000",
    uploadTime: "2021-04-04",
    videoUrls:  ["https://www.youtube.com/watch?v=5koUm8AU0bY", "https://youtu.be/DV6eGVpsPlA", "https://www.youtube.com/watch?v=iTPtkfD9LFE"],
    src:        "srdc",
    srId:       "mk76vlxy",
  },
  {
    playerId:   "L1ndell / Xo4yYMePetb / zxcMolniya",
    clearTime:  "0:39.000",
    uploadTime: "2022-05-08",
    videoUrls:  ["https://youtu.be/Cft-bTPjz3g"],
    src:        "srdc",
    srId:       "me39oj3z",
  },
  {
    playerId:   "PrimedDarkeN / Menadion / Boll",
    clearTime:  "0:47.000",
    uploadTime: "2020-09-22",
    videoUrls:  ["https://www.youtube.com/watch?v=TBcIX8A-bBs&t=1s"],
    src:        "srdc",
    srId:       "y8r96dnm",
  },
  {
    playerId:   "Wambo / Ceejay / PrimedDarkeN / Mortar",
    clearTime:  "0:55.000",
    uploadTime: "2020-08-24",
    videoUrls:  ["https://www.youtube.com/watch?v=UGBRfIxSwuU"],
    src:        "srdc",
    srId:       "mk363jlz",
  },
  {
    playerId:   "Wambo / Ceejay / PrimedDarkeN / Mortar",
    clearTime:  "0:55.000",
    uploadTime: "2020-08-24",
    videoUrls:  ["https://www.youtube.com/watch?v=UGBRfIxSwuU"],
    src:        "srdc",
    srId:       "zx21d9gm",
  },
  {
    playerId:   "Ceejay / silverdk / lucasengenho / Mortar",
    clearTime:  "0:59.000",
    uploadTime: "2019-08-23",
    videoUrls:  ["https://www.youtube.com/watch?v=csq7jzJfazQ", "https://www.youtube.com/watch?v=Alery3DM7Fw"],
    src:        "srdc",
    srId:       "yj3gro3z",
  },
  {
    playerId:   "Mortar / silverdk / lucasengenho / Ceejay",
    clearTime:  "1:03.966",
    uploadTime: "2019-08-23",
    videoUrls:  ["https://www.youtube.com/watch?v=IuzhBbsPsxs", "https://youtu.be/0eYgOHKGXZA"],
    src:        "srdc",
    srId:       "y21xnn5z",
  },
  {
    playerId:   "Nusmag / holleufer98 / Senguash",
    clearTime:  "1:35.000",
    uploadTime: "2017-03-19",
    videoUrls:  ["https://youtu.be/lS6-rFyRKQc"],
    src:        "srdc",
    srId:       "yo46g80m",
  },
  {
    playerId:   "Shul / zopney",
    clearTime:  "2:55.000",
    uploadTime: "2017-05-15",
    videoUrls:  ["https://www.youtube.com/watch?v=U7imgT5ugRo"],
    src:        "srdc",
    srId:       "m3don9qz",
  },
];