/* speedrun.com 原始抓取数据 — Spy Missions / Pago / Solo */
/* level_id=xd0qe8x9 | 共 56 条 */
var spy_missions_pago_soloRecords = [
  {
    playerId:   "L1ndell",
    clearTime:  "0:46.533",
    uploadTime: "2026-06-01",
    videoUrls:  ["https://youtu.be/BDDeN9A2Uco"],
    src:        "srdc",
    srId:       "zxp5jogy",
  },
  {
    playerId:   "Salat",
    clearTime:  "0:47.533",
    uploadTime: "2026-05-12",
    videoUrls:  ["https://youtu.be/IyjwNdvyEWA"],
    src:        "srdc",
    srId:       "z02d4djm",
  },
  {
    playerId:   "Txdo",
    clearTime:  "0:50.750",
    uploadTime: "2025-04-30",
    videoUrls:  ["https://www.youtube.com/watch?v=q0r6N3Kdi0U&ab_channel=Txdo"],
    src:        "srdc",
    srId:       "yjqkrx3m",
  },
  {
    playerId:   "PrimedDarkeN",
    clearTime:  "0:50.933",
    uploadTime: "2024-10-07",
    videoUrls:  ["https://www.youtube.com/watch?v=FAwYm2izNaQ"],
    src:        "srdc",
    srId:       "mrxx2k4m",
  },
  {
    playerId:   "Endryx_Ow",
    clearTime:  "0:57.000",
    uploadTime: "2024-11-06",
    videoUrls:  ["https://youtu.be/f8o03xAonnA"],
    src:        "srdc",
    srId:       "ydlxqdqz",
  },
  {
    playerId:   "Yangoo",
    clearTime:  "0:59.000",
    uploadTime: "2024-04-07",
    videoUrls:  ["https://www.youtube.com/watch?v=1vhzpAVxDnw"],
    src:        "srdc",
    srId:       "ylxl3x2y",
  },
  {
    playerId:   "4MIR",
    clearTime:  "0:59.000",
    uploadTime: "2026-07-03",
    videoUrls:  ["https://youtu.be/zsGZ69dQidM?si=-HOUDDg79YwrVfX5"],
    src:        "srdc",
    srId:       "me5kn39m",
  },
  {
    playerId:   "Kuremento",
    clearTime:  "1:00.000",
    uploadTime: "2021-12-17",
    videoUrls:  ["https://www.youtube.com/watch?v=UOvw5bzdMjc"],
    src:        "srdc",
    srId:       "z5v0d5dm",
  },
  {
    playerId:   "Mortar",
    clearTime:  "1:03.000",
    uploadTime: "2020-09-27",
    videoUrls:  ["https://www.youtube.com/watch?v=BAFv5mBnuj0"],
    src:        "srdc",
    srId:       "zpl40gvm",
  },
  {
    playerId:   "Mortar",
    clearTime:  "1:03.000",
    uploadTime: "2020-09-27",
    videoUrls:  ["https://www.youtube.com/watch?v=BAFv5mBnuj0"],
    src:        "srdc",
    srId:       "yd063gxz",
  },
  {
    playerId:   "Febi",
    clearTime:  "1:03.000",
    uploadTime: "2021-12-12",
    videoUrls:  ["https://www.youtube.com/watch?v=crEsh9xLLkg"],
    src:        "srdc",
    srId:       "yv8oxqxm",
  },
  {
    playerId:   "Xo4yYMePetb",
    clearTime:  "1:04.000",
    uploadTime: "2023-04-26",
    videoUrls:  ["https://youtu.be/eOsr-W17C_k"],
    src:        "srdc",
    srId:       "y623x8jz",
  },
  {
    playerId:   "Titoxx",
    clearTime:  "1:04.500",
    uploadTime: "2024-07-21",
    videoUrls:  ["https://www.youtube.com/watch?v=c4gTjkPAfEM"],
    src:        "srdc",
    srId:       "ywx41o3m",
  },
  {
    playerId:   "FXCloud",
    clearTime:  "1:08.000",
    uploadTime: "2026-01-02",
    videoUrls:  ["https://youtu.be/RyoIxo9ByAU"],
    src:        "srdc",
    srId:       "y68vqq1z",
  },
  {
    playerId:   "Wasamii",
    clearTime:  "1:09.000",
    uploadTime: "2023-01-17",
    videoUrls:  ["https://youtu.be/2BsgZdZCRQA"],
    src:        "srdc",
    srId:       "zxngewkm",
  },
  {
    playerId:   "OgvDams",
    clearTime:  "1:10.000",
    uploadTime: "2023-01-20",
    videoUrls:  ["https://www.youtube.com/watch?v=tKfdItc81l8&ab_channel=MrDams"],
    src:        "srdc",
    srId:       "y4g7x92y",
  },
  {
    playerId:   "Theotim",
    clearTime:  "1:10.000",
    uploadTime: "2024-05-07",
    videoUrls:  ["https://youtu.be/-AnZKVf--5A"],
    src:        "srdc",
    srId:       "zq8dr4xz",
  },
  {
    playerId:   "HL_Unknown",
    clearTime:  "1:10.000",
    uploadTime: "2024-07-13",
    videoUrls:  ["https://youtu.be/cHwVWbK0Upg?feature=shared"],
    src:        "srdc",
    srId:       "mk14er5y",
  },
  {
    playerId:   "TheLostJoshua",
    clearTime:  "1:15.000",
    uploadTime: "2021-03-12",
    videoUrls:  ["https://youtu.be/FwNUgRFM9nE"],
    src:        "srdc",
    srId:       "yj19dgdy",
  },
  {
    playerId:   "Boll",
    clearTime:  "1:16.000",
    uploadTime: "2021-02-19",
    videoUrls:  ["https://www.youtube.com/watch?v=TQPdCM4efOI&feature=youtu.be&ab_channel=Mura"],
    src:        "srdc",
    srId:       "m786kq9z",
  },
  {
    playerId:   "ChungFu",
    clearTime:  "1:18.000",
    uploadTime: "2021-12-14",
    videoUrls:  ["https://youtu.be/HtTRR0ufvVA"],
    src:        "srdc",
    srId:       "m36ox84m",
  },
  {
    playerId:   "Menadion",
    clearTime:  "1:20.000",
    uploadTime: "2020-10-03",
    videoUrls:  ["https://www.youtube.com/watch?v=15YjA9urBro"],
    src:        "srdc",
    srId:       "ylv05r2m",
  },
  {
    playerId:   "Laufeyson",
    clearTime:  "1:23.000",
    uploadTime: "2023-04-23",
    videoUrls:  ["https://youtu.be/4F5qs_q-kPg"],
    src:        "srdc",
    srId:       "mrljq72m",
  },
  {
    playerId:   "RoniPrime",
    clearTime:  "1:26.000",
    uploadTime: "2026-02-12",
    videoUrls:  ["https://youtu.be/GeCP-6ARN5A"],
    src:        "srdc",
    srId:       "m32e5j6y",
  },
  {
    playerId:   "SA_Demmodor",
    clearTime:  "1:30.000",
    uploadTime: "2022-08-02",
    videoUrls:  ["https://www.youtube.com/watch?v=vRGvRkDYt2Q"],
    src:        "srdc",
    srId:       "y4x58ddz",
  },
  {
    playerId:   "zukerben",
    clearTime:  "1:35.000",
    uploadTime: "2020-02-13",
    videoUrls:  ["https://www.youtube.com/watch?v=4J0Wroesx_I"],
    src:        "srdc",
    srId:       "y6lw96qy",
  },
  {
    playerId:   "CreepingChamp",
    clearTime:  "1:35.000",
    uploadTime: "2020-12-02",
    videoUrls:  ["https://youtu.be/GXfX4zgw-PA"],
    src:        "srdc",
    srId:       "yo3o027y",
  },
  {
    playerId:   "CreepingChamp",
    clearTime:  "1:35.000",
    uploadTime: "2020-12-02",
    videoUrls:  ["https://youtu.be/GXfX4zgw-PA"],
    src:        "srdc",
    srId:       "z1ok91gm",
  },
  {
    playerId:   "LiAXiM",
    clearTime:  "1:35.000",
    uploadTime: "2021-12-22",
    videoUrls:  ["https://youtu.be/Vtfva9uXbHE"],
    src:        "srdc",
    srId:       "zq0rxwxy",
  },
  {
    playerId:   "Fr3zzco",
    clearTime:  "1:38.000",
    uploadTime: "2024-02-28",
    videoUrls:  ["https://youtu.be/AfpkCgV4rog"],
    src:        "srdc",
    srId:       "zn245p3z",
  },
  {
    playerId:   "Desky",
    clearTime:  "1:42.000",
    uploadTime: "2020-06-10",
    videoUrls:  ["https://www.youtube.com/watch?v=Tsymb_sbVPI"],
    src:        "srdc",
    srId:       "yv6r5p6z",
  },
  {
    playerId:   "holleufer98",
    clearTime:  "1:43.687",
    uploadTime: "2018-01-30",
    videoUrls:  ["https://youtu.be/SeiEROxzXUM"],
    src:        "srdc",
    srId:       "zq6q909y",
  },
  {
    playerId:   "holleufer98",
    clearTime:  "1:43.687",
    uploadTime: "2018-07-03",
    videoUrls:  ["https://www.youtube.com/watch?v=SeiEROxzXUM"],
    src:        "srdc",
    srId:       "m3oojlwm",
  },
  {
    playerId:   "felix_rs",
    clearTime:  "1:44.368",
    uploadTime: "2020-05-26",
    videoUrls:  ["https://www.youtube.com/watch?v=1fP4qzWu8Zo"],
    src:        "srdc",
    srId:       "yd5ejkqm",
  },
  {
    playerId:   "OverusedMemes",
    clearTime:  "1:45.572",
    uploadTime: "2018-01-31",
    videoUrls:  ["https://www.youtube.com/watch?v=Pk5oXfavAqU"],
    src:        "srdc",
    srId:       "yw1xv7pz",
  },
  {
    playerId:   "OverusedMemes",
    clearTime:  "1:45.572",
    uploadTime: "2018-01-31",
    videoUrls:  ["https://www.youtube.com/watch?v=Pk5oXfavAqU"],
    src:        "srdc",
    srId:       "mrq5opdy",
  },
  {
    playerId:   "MagsPrime",
    clearTime:  "1:47.000",
    uploadTime: "2022-01-25",
    videoUrls:  ["https://youtu.be/abKVq5QYHMU"],
    src:        "srdc",
    srId:       "yle1xwnz",
  },
  {
    playerId:   "Hamudi",
    clearTime:  "1:48.000",
    uploadTime: "2024-01-01",
    videoUrls:  ["https://youtu.be/tiyC0WtZcoA?si=CDvAOFUTep9XSwHe"],
    src:        "srdc",
    srId:       "y22v0gwy",
  },
  {
    playerId:   "Nusmag",
    clearTime:  "1:53.463",
    uploadTime: "2017-09-21",
    videoUrls:  ["https://youtu.be/AO0_nPrrr_c"],
    src:        "srdc",
    srId:       "y8qe4gdy",
  },
  {
    playerId:   "LeChat930",
    clearTime:  "2:03.000",
    uploadTime: "2023-07-19",
    videoUrls:  ["https://www.youtube.com/watch?v=O7QSFJxmUug"],
    src:        "srdc",
    srId:       "znved87m",
  },
  {
    playerId:   "Helbrecht",
    clearTime:  "2:04.000",
    uploadTime: "2019-09-22",
    videoUrls:  ["https://www.youtube.com/watch?v=h4iOVUj7q6M&feature=youtu.be"],
    src:        "srdc",
    srId:       "y6lnjljy",
  },
  {
    playerId:   "Thornax",
    clearTime:  "2:05.000",
    uploadTime: "2020-04-20",
    videoUrls:  ["https://youtu.be/IvWMnZ8IXxE"],
    src:        "srdc",
    srId:       "y4w1keqm",
  },
  {
    playerId:   "V-_-iniciu-_-s",
    clearTime:  "2:08.000",
    uploadTime: "2019-10-20",
    videoUrls:  ["https://youtu.be/BN3BnEkoRAI"],
    src:        "srdc",
    srId:       "mk2dv9vm",
  },
  {
    playerId:   "silverdk",
    clearTime:  "2:12.000",
    uploadTime: "2019-06-10",
    videoUrls:  ["https://www.youtube.com/watch?v=WNSUZjX_0lY&feature=youtu.be"],
    src:        "srdc",
    srId:       "z57on9nm",
  },
  {
    playerId:   "--Q--EValueAction",
    clearTime:  "2:12.100",
    uploadTime: "2018-11-20",
    videoUrls:  ["https://www.youtube.com/watch?v=AKYrxgN2aJs"],
    src:        "srdc",
    srId:       "y926kvez",
  },
  {
    playerId:   "Icohedron",
    clearTime:  "2:15.000",
    uploadTime: "2019-06-18",
    videoUrls:  ["https://www.youtube.com/watch?v=iGeZInnhjSU"],
    src:        "srdc",
    srId:       "z1j1lpgz",
  },
  {
    playerId:   "lucasengenho",
    clearTime:  "2:15.000",
    uploadTime: "2019-09-14",
    videoUrls:  ["https://www.youtube.com/watch?v=UkF1VmWo5G0"],
    src:        "srdc",
    srId:       "y81jvpnz",
  },
  {
    playerId:   "zopney",
    clearTime:  "2:17.000",
    uploadTime: "2018-08-15",
    videoUrls:  ["https://www.youtube.com/watch?v=ZmXFq6aVhdI"],
    src:        "srdc",
    srId:       "zp0l5drm",
  },
  {
    playerId:   "Feltal",
    clearTime:  "2:18.000",
    uploadTime: "2019-06-07",
    videoUrls:  ["https://youtu.be/PZwHj3imYl8"],
    src:        "srdc",
    srId:       "z01edd4y",
  },
  {
    playerId:   "miqman1",
    clearTime:  "2:19.000",
    uploadTime: "2018-04-29",
    videoUrls:  ["https://www.youtube.com/watch?v=_g_r4dj-50k"],
    src:        "srdc",
    srId:       "yw195opz",
  },
  {
    playerId:   "mmaure",
    clearTime:  "2:19.000",
    uploadTime: "2019-07-09",
    videoUrls:  ["https://youtu.be/7CFTDX2l7sA"],
    src:        "srdc",
    srId:       "m3155owz",
  },
  {
    playerId:   "TheLonelyMan78",
    clearTime:  "2:31.000",
    uploadTime: "2018-05-09",
    videoUrls:  ["https://www.youtube.com/watch?v=va6gIZPwKy8"],
    src:        "srdc",
    srId:       "yj44q3oy",
  },
  {
    playerId:   "bungawunga",
    clearTime:  "2:46.500",
    uploadTime: "2017-06-13",
    videoUrls:  ["https://www.youtube.com/watch?v=jfyjRYHZrvM"],
    src:        "srdc",
    srId:       "y975p3nm",
  },
  {
    playerId:   "-Seiryu.",
    clearTime:  "2:59.000",
    uploadTime: "2018-03-18",
    videoUrls:  ["https://www.youtube.com/watch?v=HvV45lLa2K4&feature=youtu.be"],
    src:        "srdc",
    srId:       "mekpre0m",
  },
  {
    playerId:   "16Bitman",
    clearTime:  "3:59.000",
    uploadTime: "2017-05-03",
    videoUrls:  ["https://www.youtube.com/watch?v=1LACXk8uuYg"],
    src:        "srdc",
    srId:       "zpqq6p8y",
  },
  {
    playerId:   "Darthmufin",
    clearTime:  "4:46.000",
    uploadTime: "2017-07-04",
    videoUrls:  ["https://www.youtube.com/watch?v=asur2YAe7nI"],
    src:        "srdc",
    srId:       "y45d00nm",
  },
];