/* speedrun.com 原始抓取数据 — Spy Missions / Pavlov / Co-op */
/* level_id=rw6o7zrw | 共 16 条 */
var spy_missions_pavlov_coopRecords = [
  {
    playerId:   "FXCloud / L1ndell / Salat",
    clearTime:  "0:35.000",
    uploadTime: "2026-05-01",
    videoUrls:  ["https://www.youtube.com/watch?v=DeNpA6c7ROM", "https://www.youtube.com/watch?v=8qE7-fyi_UU", "https://youtu.be/0cs9AQfewug"],
    src:        "srdc",
    srId:       "zqndr15z",
  },
  {
    playerId:   "PrimedDarkeN / Akula / Boll",
    clearTime:  "0:42.000",
    uploadTime: "2022-11-13",
    videoUrls:  ["https://www.youtube.com/watch?v=C-nEhHy-lho"],
    src:        "srdc",
    srId:       "yodg8v1m",
  },
  {
    playerId:   "L1ndell / zxcMolniya / K1nky",
    clearTime:  "0:43.000",
    uploadTime: "2022-02-06",
    videoUrls:  ["https://youtu.be/lgEuvm53cqY"],
    src:        "srdc",
    srId:       "zgd8n1vz",
  },
  {
    playerId:   "Febi / Akula / PrimedDarkeN",
    clearTime:  "0:48.000",
    uploadTime: "2021-03-31",
    videoUrls:  ["https://www.youtube.com/watch?v=s2bhYOFs5Xg"],
    src:        "srdc",
    srId:       "zgx0e7em",
  },
  {
    playerId:   "Skrilljada / Quipp / Desky",
    clearTime:  "0:48.000",
    uploadTime: "2021-04-26",
    videoUrls:  ["https://www.youtube.com/watch?v=JeXXqOCMiiU"],
    src:        "srdc",
    srId:       "zq1rx89m",
  },
  {
    playerId:   "namenBARS / L1ndell",
    clearTime:  "0:48.000",
    uploadTime: "2021-10-28",
    videoUrls:  ["https://youtu.be/Iyu0Yaer3cM"],
    src:        "srdc",
    srId:       "ywk2jd3y",
  },
  {
    playerId:   "Wambo / Mortar",
    clearTime:  "0:55.000",
    uploadTime: "2021-04-29",
    videoUrls:  ["https://www.youtube.com/watch?v=mj2Ggd8R5AA", "https://www.youtube.com/watch?v=O6s-aRxMHdQ"],
    src:        "srdc",
    srId:       "y4rw64dz",
  },
  {
    playerId:   "PrimedDarkeN / Menadion / Boll",
    clearTime:  "0:56.000",
    uploadTime: "2020-09-26",
    videoUrls:  ["https://www.youtube.com/watch?v=-7fTKtdkeaY"],
    src:        "srdc",
    srId:       "ylv48n2m",
  },
  {
    playerId:   "Taiepii / Quipp / Prime01Jok3r",
    clearTime:  "0:58.000",
    uploadTime: "2021-04-23",
    videoUrls:  ["https://youtu.be/mNFvmqeK-kI"],
    src:        "srdc",
    srId:       "yjg3gedy",
  },
  {
    playerId:   "Nonqui / namenBARS",
    clearTime:  "0:58.916",
    uploadTime: "2018-12-31",
    videoUrls:  ["https://youtu.be/aCLYQBPXnn0"],
    src:        "srdc",
    srId:       "mk9qjevz",
  },
  {
    playerId:   "holleufer98 / Nusmag",
    clearTime:  "1:00.477",
    uploadTime: "2017-10-17",
    videoUrls:  ["https://www.youtube.com/watch?v=-Y3IYSMDd7M"],
    src:        "srdc",
    srId:       "y67q546m",
  },
  {
    playerId:   "Liuskur / --Prime01Jok3r-- / Skrilljada",
    clearTime:  "1:02.000",
    uploadTime: "2021-04-23",
    videoUrls:  ["https://www.youtube.com/watch?v=yoGVETUht98", "https://www.youtube.com/watch?v=ZxLG2afycbI"],
    src:        "srdc",
    srId:       "ydr6r4vz",
  },
  {
    playerId:   "Sealy / Akula / TheLostJoshua",
    clearTime:  "1:09.000",
    uploadTime: "2021-03-06",
    videoUrls:  ["https://youtu.be/rpFSTH6mn7o"],
    src:        "srdc",
    srId:       "zgxl79dm",
  },
  {
    playerId:   "Nusmag / holleufer98 / Senguash",
    clearTime:  "1:20.000",
    uploadTime: "2017-03-11",
    videoUrls:  ["https://youtu.be/X8RgsrEkrYs"],
    src:        "srdc",
    srId:       "y8qqe3ny",
  },
  {
    playerId:   "holleufer98 / Nusmag",
    clearTime:  "1:26.000",
    uploadTime: "2017-03-10",
    videoUrls:  ["https://www.youtube.com/watch?v=Bbkfb_FvvFs&t=39s"],
    src:        "srdc",
    srId:       "y237465m",
  },
  {
    playerId:   "Shiva / Blasher / dragon091521",
    clearTime:  "1:30.000",
    uploadTime: "2020-07-06",
    videoUrls:  ["https://www.youtube.com/watch?v=KzzYHT2nJRk"],
    src:        "srdc",
    srId:       "yv6vx0oz",
  },
];