/* speedrun.com 原始抓取数据 — Spy Missions / Pavlov / Solo */
/* level_id=rw6o7zrw | 共 71 条 */
var spy_missions_pavlov_soloRecords = [
  {
    playerId:   "L1ndell",
    clearTime:  "0:58.000",
    uploadTime: "2026-01-27",
    videoUrls:  ["https://youtu.be/jW_ti82F-zQ"],
    src:        "srdc",
    srId:       "y8nlrpwy",
  },
  {
    playerId:   "FXCloud",
    clearTime:  "1:01.000",
    uploadTime: "2026-01-21",
    videoUrls:  ["https://youtu.be/zlg0mF9CMuU"],
    src:        "srdc",
    srId:       "y688p5pz",
  },
  {
    playerId:   "Endryx_Ow",
    clearTime:  "1:08.000",
    uploadTime: "2024-08-31",
    videoUrls:  ["https://youtu.be/9YUKpiLqmOI?si=ELxgtx9RYr7P6Kyj"],
    src:        "srdc",
    srId:       "ylx7dgry",
  },
  {
    playerId:   "PrimedDarkeN",
    clearTime:  "1:13.000",
    uploadTime: "2021-07-19",
    videoUrls:  ["https://www.youtube.com/watch?v=Bo_PRzezLZg"],
    src:        "srdc",
    srId:       "y6d1kj0m",
  },
  {
    playerId:   "namenBARS",
    clearTime:  "1:15.000",
    uploadTime: "2021-10-15",
    videoUrls:  ["https://youtu.be/4Rzu1DhqH1c"],
    src:        "srdc",
    srId:       "ywkxkr2y",
  },
  {
    playerId:   "holleufer98",
    clearTime:  "1:16.260",
    uploadTime: "2017-10-19",
    videoUrls:  ["https://www.youtube.com/watch?v=cJugd-IdndQ"],
    src:        "srdc",
    srId:       "z5o2r05y",
  },
  {
    playerId:   "Nusmag",
    clearTime:  "1:18.745",
    uploadTime: "2017-09-24",
    videoUrls:  ["https://youtu.be/5PY9JkJvA0s"],
    src:        "srdc",
    srId:       "zn87809z",
  },
  {
    playerId:   "Mortar",
    clearTime:  "1:19.000",
    uploadTime: "2021-04-23",
    videoUrls:  ["https://www.youtube.com/watch?v=rKLhxe0dxuQ"],
    src:        "srdc",
    srId:       "yo7j615m",
  },
  {
    playerId:   "Desky",
    clearTime:  "1:22.000",
    uploadTime: "2021-04-26",
    videoUrls:  ["https://www.youtube.com/watch?v=pii-khgtS9w"],
    src:        "srdc",
    srId:       "m3r1e06m",
  },
  {
    playerId:   "Febi",
    clearTime:  "1:25.000",
    uploadTime: "2021-06-14",
    videoUrls:  ["https://www.youtube.com/watch?v=S-XnnMQoJfc"],
    src:        "srdc",
    srId:       "z0rxpdjz",
  },
  {
    playerId:   "Skrilljada",
    clearTime:  "1:26.000",
    uploadTime: "2021-04-24",
    videoUrls:  ["https://youtu.be/espBVNO0348"],
    src:        "srdc",
    srId:       "y2x16e7m",
  },
  {
    playerId:   "FaidZ",
    clearTime:  "1:26.637",
    uploadTime: "2022-03-07",
    videoUrls:  ["https://youtu.be/v0lwP5wWFXA"],
    src:        "srdc",
    srId:       "yjx786gz",
  },
  {
    playerId:   "Prime01Jok3r",
    clearTime:  "1:27.000",
    uploadTime: "2021-04-25",
    videoUrls:  ["https://youtu.be/RmBfTU49uDs"],
    src:        "srdc",
    srId:       "mkg21ovy",
  },
  {
    playerId:   "lucasengenho",
    clearTime:  "1:29.000",
    uploadTime: "2019-10-19",
    videoUrls:  ["https://youtu.be/_CEmAqxj5p8"],
    src:        "srdc",
    srId:       "mrerredy",
  },
  {
    playerId:   "Boll",
    clearTime:  "1:29.000",
    uploadTime: "2021-02-23",
    videoUrls:  ["https://www.youtube.com/watch?v=zIhghJCZ6tM&ab_channel=Mura"],
    src:        "srdc",
    srId:       "y8vx571z",
  },
  {
    playerId:   "WaterCar",
    clearTime:  "1:30.000",
    uploadTime: "2025-12-15",
    videoUrls:  ["https://www.youtube.com/watch?v=y3Pvz7p94OI"],
    src:        "srdc",
    srId:       "ydogvv0z",
  },
  {
    playerId:   "Nonqui",
    clearTime:  "1:31.000",
    uploadTime: "2019-01-27",
    videoUrls:  ["https://www.youtube.com/watch?v=V62f4MgaTis&feature=youtu.be"],
    src:        "srdc",
    srId:       "yo2xdd1z",
  },
  {
    playerId:   "Quipp",
    clearTime:  "1:31.000",
    uploadTime: "2021-04-24",
    videoUrls:  ["https://youtu.be/eIg4dhFxNc0"],
    src:        "srdc",
    srId:       "z1rjr0wm",
  },
  {
    playerId:   "excelion",
    clearTime:  "1:32.000",
    uploadTime: "2021-07-01",
    videoUrls:  ["https://youtu.be/3DWszER4iTc"],
    src:        "srdc",
    srId:       "m7dv7l0m",
  },
  {
    playerId:   "zxcMolniya",
    clearTime:  "1:32.000",
    uploadTime: "2021-07-27",
    videoUrls:  ["https://www.youtube.com/watch?v=cFg7Xb4lvzw"],
    src:        "srdc",
    srId:       "me4v270y",
  },
  {
    playerId:   "holleufer98",
    clearTime:  "1:32.809",
    uploadTime: "2017-11-24",
    videoUrls:  ["https://youtu.be/XbTbdbVEMUk"],
    src:        "srdc",
    srId:       "y9765wkm",
  },
  {
    playerId:   "Nusmag",
    clearTime:  "1:35.746",
    uploadTime: "2017-10-20",
    videoUrls:  ["https://youtu.be/uq34j54xj7o"],
    src:        "srdc",
    srId:       "ydqdrrxm",
  },
  {
    playerId:   "DeseerT",
    clearTime:  "1:39.000",
    uploadTime: "2021-02-06",
    videoUrls:  ["https://youtu.be/Hlypx24WNs4"],
    src:        "srdc",
    srId:       "yj1g5l3y",
  },
  {
    playerId:   "sakivali",
    clearTime:  "1:41.117",
    uploadTime: "2024-07-21",
    videoUrls:  ["https://youtu.be/ZyKFIKJaI7E"],
    src:        "srdc",
    srId:       "zxx4r75z",
  },
  {
    playerId:   "--RV--Faras",
    clearTime:  "1:42.000",
    uploadTime: "2021-04-24",
    videoUrls:  ["https://youtu.be/tRS-dPTTm1w"],
    src:        "srdc",
    srId:       "zq1r0l1m",
  },
  {
    playerId:   "Wasamii",
    clearTime:  "1:44.000",
    uploadTime: "2021-02-28",
    videoUrls:  ["https://youtu.be/qNNqmxF-fjU"],
    src:        "srdc",
    srId:       "yd9jevqz",
  },
  {
    playerId:   "iTrust",
    clearTime:  "1:45.000",
    uploadTime: "2017-03-10",
    videoUrls:  ["https://youtu.be/SMLa4KbSYW4"],
    src:        "srdc",
    srId:       "yjk5vrdm",
  },
  {
    playerId:   "Mebius",
    clearTime:  "1:46.000",
    uploadTime: "2021-04-24",
    videoUrls:  ["https://youtu.be/9G9jDoX6EUs"],
    src:        "srdc",
    srId:       "zgq6rkdy",
  },
  {
    playerId:   "Meln1K",
    clearTime:  "1:47.900",
    uploadTime: "2020-02-09",
    videoUrls:  ["https://www.youtube.com/watch?v=1p32A2G5k70&feature=youtu.be"],
    src:        "srdc",
    srId:       "yl05252y",
  },
  {
    playerId:   "biguglyboy420",
    clearTime:  "1:50.000",
    uploadTime: "2018-09-09",
    videoUrls:  ["https://www.youtube.com/watch?v=vlTnyMkZKzc"],
    src:        "srdc",
    srId:       "yj4gqx3y",
  },
  {
    playerId:   "felix_rs",
    clearTime:  "1:55.034",
    uploadTime: "2019-05-31",
    videoUrls:  ["https://youtu.be/gSCwqAREh60"],
    src:        "srdc",
    srId:       "zgknvnny",
  },
  {
    playerId:   "-CheffDegu",
    clearTime:  "1:56.000",
    uploadTime: "2018-09-07",
    videoUrls:  ["https://www.youtube.com/watch?v=PIgQ6jYsUcE&feature=youtu.be"],
    src:        "srdc",
    srId:       "yl4qelxm",
  },
  {
    playerId:   "BahamutVoid",
    clearTime:  "1:57.000",
    uploadTime: "2020-06-20",
    videoUrls:  ["https://www.youtube.com/watch?v=tSGxmHmDSsE"],
    src:        "srdc",
    srId:       "mrkok18y",
  },
  {
    playerId:   "Ebbtides",
    clearTime:  "1:58.000",
    uploadTime: "2018-06-25",
    videoUrls:  ["https://www.youtube.com/watch?v=f0OLhvHZDd8"],
    src:        "srdc",
    srId:       "yo22j01z",
  },
  {
    playerId:   "Helbrecht",
    clearTime:  "1:59.000",
    uploadTime: "2019-09-22",
    videoUrls:  ["https://www.youtube.com/watch?v=cD6X1zdKm7w&feature=youtu.be"],
    src:        "srdc",
    srId:       "y21081jz",
  },
  {
    playerId:   "Hamudi",
    clearTime:  "2:01.000",
    uploadTime: "2024-01-09",
    videoUrls:  ["https://youtu.be/an08gACY7TA"],
    src:        "srdc",
    srId:       "zn2w3l3z",
  },
  {
    playerId:   "shaleve_hakime",
    clearTime:  "2:02.000",
    uploadTime: "2023-03-24",
    videoUrls:  ["https://www.youtube.com/watch?v=c_IFOf9PazE"],
    src:        "srdc",
    srId:       "ydgoekwy",
  },
  {
    playerId:   "Fr3zzco",
    clearTime:  "2:04.000",
    uploadTime: "2024-02-28",
    videoUrls:  ["https://youtu.be/pQVOIqlSE9M"],
    src:        "srdc",
    srId:       "y6vp8x6m",
  },
  {
    playerId:   "xAlexTheGreat",
    clearTime:  "2:06.000",
    uploadTime: "2023-11-18",
    videoUrls:  ["https://youtu.be/vecHKXrbpSg"],
    src:        "srdc",
    srId:       "yvvr856y",
  },
  {
    playerId:   "sillyich",
    clearTime:  "2:07.000",
    uploadTime: "2018-09-10",
    videoUrls:  ["https://youtu.be/udXdUaMZc-o"],
    src:        "srdc",
    srId:       "y92960vz",
  },
  {
    playerId:   "Deltagon",
    clearTime:  "2:08.000",
    uploadTime: "2018-09-02",
    videoUrls:  ["https://www.youtube.com/watch?v=osgDGUCIsVY&feature=youtu.be"],
    src:        "srdc",
    srId:       "zg7g61ez",
  },
  {
    playerId:   "DrJaska",
    clearTime:  "2:08.000",
    uploadTime: "2020-07-10",
    videoUrls:  ["https://youtu.be/p0HjuDQDAHU"],
    src:        "srdc",
    srId:       "zgw9nvny",
  },
  {
    playerId:   "Plyonate",
    clearTime:  "2:08.000",
    uploadTime: "2026-06-01",
    videoUrls:  ["https://www.youtube.com/watch?v=_hnjOfvRsXI"],
    src:        "srdc",
    srId:       "m382jjwy",
  },
  {
    playerId:   "z03h",
    clearTime:  "2:10.000",
    uploadTime: "2018-09-02",
    videoUrls:  ["https://www.youtube.com/watch?v=V3HTsohrPdk"],
    src:        "srdc",
    srId:       "y6lrqdjy",
  },
  {
    playerId:   "Liuskur",
    clearTime:  "2:10.000",
    uploadTime: "2021-04-22",
    videoUrls:  ["https://www.youtube.com/watch?v=pMt4mHA5c9o"],
    src:        "srdc",
    srId:       "z0r1r09z",
  },
  {
    playerId:   "zopney",
    clearTime:  "2:12.000",
    uploadTime: "2018-08-13",
    videoUrls:  ["https://www.youtube.com/watch?v=P2gU4CjsQOo"],
    src:        "srdc",
    srId:       "mr890wgy",
  },
  {
    playerId:   "--Q--L3TK",
    clearTime:  "2:15.000",
    uploadTime: "2018-12-08",
    videoUrls:  ["https://www.youtube.com/watch?v=DgbA7gHNELA"],
    src:        "srdc",
    srId:       "yd3j60qz",
  },
  {
    playerId:   "Fix3kill",
    clearTime:  "2:15.000",
    uploadTime: "2021-06-22",
    videoUrls:  ["https://youtu.be/zRu4s_ny6_E"],
    src:        "srdc",
    srId:       "z1rn0k9m",
  },
  {
    playerId:   "LeChat930",
    clearTime:  "2:15.000",
    uploadTime: "2023-09-16",
    videoUrls:  ["https://www.youtube.com/watch?v=UlNWNBv1G4A"],
    src:        "srdc",
    srId:       "y9k7w9kz",
  },
  {
    playerId:   "Double.",
    clearTime:  "2:16.000",
    uploadTime: "2019-09-11",
    videoUrls:  ["https://www.youtube.com/watch?v=iqkodjaYPhw"],
    src:        "srdc",
    srId:       "zp4209nz",
  },
  {
    playerId:   "Feltal",
    clearTime:  "2:17.000",
    uploadTime: "2019-06-06",
    videoUrls:  ["https://youtu.be/KKFAU7qPVHA"],
    src:        "srdc",
    srId:       "mexkw09z",
  },
  {
    playerId:   "V-_-iniciu-_-s",
    clearTime:  "2:18.000",
    uploadTime: "2019-08-11",
    videoUrls:  ["https://youtu.be/y8khyEkJgS4"],
    src:        "srdc",
    srId:       "zqrgnw1y",
  },
  {
    playerId:   "Breadatarian",
    clearTime:  "2:26.000",
    uploadTime: "2018-09-13",
    videoUrls:  ["https://www.youtube.com/watch?v=vt20r9GjWCg"],
    src:        "srdc",
    srId:       "z11lrkrz",
  },
  {
    playerId:   "--PV--Kuburas",
    clearTime:  "2:27.000",
    uploadTime: "2018-09-08",
    videoUrls:  ["https://www.youtube.com/watch?v=9-L4AajeiME"],
    src:        "srdc",
    srId:       "mk91n95z",
  },
  {
    playerId:   "LithiumFrost",
    clearTime:  "2:30.000",
    uploadTime: "2017-04-26",
    videoUrls:  ["https://youtu.be/0bX9NRqeHXw"],
    src:        "srdc",
    srId:       "m799dwey",
  },
  {
    playerId:   "DarkestKnightz",
    clearTime:  "2:41.000",
    uploadTime: "2018-08-16",
    videoUrls:  ["https://www.youtube.com/watch?v=8QlyqjEIXaQ"],
    src:        "srdc",
    srId:       "m7p0d3wm",
  },
  {
    playerId:   "asis",
    clearTime:  "2:49.000",
    uploadTime: "2017-03-10",
    videoUrls:  ["https://www.youtube.com/watch?v=yVUM5gVNPqQ"],
    src:        "srdc",
    srId:       "zgnr01ey",
  },
  {
    playerId:   "ProudlyModified",
    clearTime:  "2:54.000",
    uploadTime: "2019-09-13",
    videoUrls:  ["https://www.youtube.com/watch?v=ZmJtMFd6b-Y"],
    src:        "srdc",
    srId:       "zxkl2dem",
  },
  {
    playerId:   "TheToolTod",
    clearTime:  "3:04.000",
    uploadTime: "2018-09-13",
    videoUrls:  ["https://www.youtube.com/watch?v=44GkU_uK1ho"],
    src:        "srdc",
    srId:       "y92945rz",
  },
  {
    playerId:   "F5-3EN6-MKJ7377",
    clearTime:  "3:12.000",
    uploadTime: "2018-09-03",
    videoUrls:  ["https://www.youtube.com/watch?v=WR2WekeAxrI"],
    src:        "srdc",
    srId:       "y43r23dz",
  },
  {
    playerId:   "16Bitman",
    clearTime:  "3:21.000",
    uploadTime: "2017-05-03",
    videoUrls:  ["https://www.youtube.com/watch?v=lOVebMqslWQ&feature=youtu.be"],
    src:        "srdc",
    srId:       "zgnnlv0y",
  },
  {
    playerId:   "Iglo",
    clearTime:  "3:30.000",
    uploadTime: "2017-03-09",
    videoUrls:  ["https://www.youtube.com/watch?v=8LHU4ACLpsU&feature=youtu.be"],
    src:        "srdc",
    srId:       "8y875gnz",
  },
  {
    playerId:   "SuedeTable",
    clearTime:  "3:38.000",
    uploadTime: "2021-07-13",
    videoUrls:  ["https://youtu.be/dzbi4Fp3bjE"],
    src:        "srdc",
    srId:       "mr1p54dz",
  },
  {
    playerId:   "MagsPrime",
    clearTime:  "3:39.000",
    uploadTime: "2022-01-14",
    videoUrls:  ["https://www.youtube.com/watch?v=4UUE7IgtU4Y"],
    src:        "srdc",
    srId:       "y6nn7gjz",
  },
  {
    playerId:   "KYLoooo",
    clearTime:  "4:07.000",
    uploadTime: "2017-05-03",
    videoUrls:  ["https://youtu.be/-aqST-LLLvc"],
    src:        "srdc",
    srId:       "yvggvn6y",
  },
  {
    playerId:   "Plikie",
    clearTime:  "4:32.000",
    uploadTime: "2019-04-07",
    videoUrls:  ["https://www.youtube.com/watch?v=i1VsLYVPB04"],
    src:        "srdc",
    srId:       "z514xrdm",
  },
  {
    playerId:   "-ZET-WindShy",
    clearTime:  "4:35.000",
    uploadTime: "2017-10-24",
    videoUrls:  ["https://www.youtube.com/watch?v=DNWPO8IOpD8&t=66s"],
    src:        "srdc",
    srId:       "zxv7n5gy",
  },
  {
    playerId:   "HFry",
    clearTime:  "4:55.890",
    uploadTime: "2017-10-28",
    videoUrls:  ["https://www.youtube.com/watch?v=AME1hlo_DAg"],
    src:        "srdc",
    srId:       "y45qn1km",
  },
  {
    playerId:   "Aeteros",
    clearTime:  "4:59.000",
    uploadTime: "2021-07-04",
    videoUrls:  ["https://youtu.be/WBkT1v522Pc"],
    src:        "srdc",
    srId:       "m3r2pgqm",
  },
  {
    playerId:   "DxDclomeDxD",
    clearTime:  "6:05.000",
    uploadTime: "2018-08-07",
    videoUrls:  ["https://www.youtube.com/watch?v=65jZfpJDKeE"],
    src:        "srdc",
    srId:       "zx43gw8y",
  },
  {
    playerId:   "YpsitheFlintsider",
    clearTime:  "7:28.000",
    uploadTime: "2018-05-09",
    videoUrls:  ["https://youtu.be/Qc2_MlJ-dpU"],
    src:        "srdc",
    srId:       "ydqk0lxm",
  },
];