/* speedrun.com 原始抓取数据 — Spy Missions / Rosalind / Co-op */
/* level_id=n934xrnd | 共 10 条 */
var spy_missions_rosalind_coopRecords = [
  {
    playerId:   "Salat / L1ndell",
    clearTime:  "0:47.000",
    uploadTime: "2026-02-19",
    videoUrls:  ["https://youtu.be/FAQQzeA1CG8,", "https://www.youtube.com/watch?v=_chjm3oNwS0"],
    src:        "srdc",
    srId:       "z10dqwjm",
  },
  {
    playerId:   "PrimedDarkeN / Febi",
    clearTime:  "0:53.000",
    uploadTime: "2023-01-21",
    videoUrls:  ["https://www.youtube.com/watch?v=xCyMhTAebMM"],
    src:        "srdc",
    srId:       "y4g76ddy",
  },
  {
    playerId:   "L1ndell / zxcMolniya",
    clearTime:  "0:57.000",
    uploadTime: "2022-03-04",
    videoUrls:  ["https://youtu.be/VprW1sBV-i8"],
    src:        "srdc",
    srId:       "y9ler52y",
  },
  {
    playerId:   "ThatBlue / -Rekken- / QuasarWF",
    clearTime:  "0:57.223",
    uploadTime: "2018-08-14",
    videoUrls:  ["https://youtu.be/f4AZ-jKqud4"],
    src:        "srdc",
    srId:       "y6prex1m",
  },
  {
    playerId:   "-Arcturus. / -Rekken- / Azynoth",
    clearTime:  "0:58.450",
    uploadTime: "2018-07-17",
    videoUrls:  ["https://youtu.be/_LAa40AelYI"],
    src:        "srdc",
    srId:       "z517g0dm",
  },
  {
    playerId:   "PrimedDarkeN / Boll / Menadion",
    clearTime:  "1:05.000",
    uploadTime: "2020-12-22",
    videoUrls:  ["https://www.youtube.com/watch?v=w4K5sIe3AzE&feature=youtu.be"],
    src:        "srdc",
    srId:       "zq4pdrxm",
  },
  {
    playerId:   "Wambo / CreepingChamp",
    clearTime:  "1:43.000",
    uploadTime: "2020-12-06",
    videoUrls:  ["https://www.youtube.com/watch?v=VYk8khAOEys"],
    src:        "srdc",
    srId:       "m75nd25z",
  },
  {
    playerId:   "Wambo / CreepingChamp",
    clearTime:  "1:43.000",
    uploadTime: "2020-12-06",
    videoUrls:  ["https://www.youtube.com/watch?v=VYk8khAOEys"],
    src:        "srdc",
    srId:       "mr9v1o4m",
  },
  {
    playerId:   "Panzof / LucianPlaysAllDay / Jay_aka_Tay420 / Only_01-left",
    clearTime:  "2:26.000",
    uploadTime: "2020-12-02",
    videoUrls:  ["https://www.twitch.tv/videos/825058181"],
    src:        "srdc",
    srId:       "z53k4n5y",
  },
  {
    playerId:   "LAMMborghini726 / NlCE ForEver",
    clearTime:  "3:01.181",
    uploadTime: "2020-12-03",
    videoUrls:  ["https://youtu.be/vZoovkwwYVA"],
    src:        "srdc",
    srId:       "zgv897nz",
  },
];