/* speedrun.com 原始抓取数据 — Spy Missions / Rosalind / Solo */
/* level_id=n934xrnd | 共 22 条 */
var spy_missions_rosalind_soloRecords = [
  {
    playerId:   "Salat",
    clearTime:  "0:44.683",
    uploadTime: "2026-03-05",
    videoUrls:  ["https://youtu.be/3sJCQdyCnCA"],
    src:        "srdc",
    srId:       "medx9lqy",
  },
  {
    playerId:   "Salat",
    clearTime:  "0:55.367",
    uploadTime: "2026-03-05",
    videoUrls:  ["https://youtu.be/e3gmJEWdFDc"],
    src:        "srdc",
    srId:       "m381nk6y",
  },
  {
    playerId:   "L1ndell",
    clearTime:  "0:59.250",
    uploadTime: "2026-02-18",
    videoUrls:  ["https://youtu.be/5Zj9MIFl8nw"],
    src:        "srdc",
    srId:       "y269xd9m",
  },
  {
    playerId:   "PrimedDarkeN",
    clearTime:  "1:11.000",
    uploadTime: "2022-06-08",
    videoUrls:  ["https://www.youtube.com/watch?v=xvjD7vO8l2M"],
    src:        "srdc",
    srId:       "y2pj756z",
  },
  {
    playerId:   "Febi",
    clearTime:  "1:21.000",
    uploadTime: "2021-07-06",
    videoUrls:  ["https://www.youtube.com/watch?v=ym5vdtzUl1A"],
    src:        "srdc",
    srId:       "yv1e9v4y",
  },
  {
    playerId:   ".cat",
    clearTime:  "1:31.000",
    uploadTime: "2020-06-04",
    videoUrls:  ["https://www.youtube.com/watch?v=PcvphJ4F63c"],
    src:        "srdc",
    srId:       "zqw0o08z",
  },
  {
    playerId:   "zukerben",
    clearTime:  "1:36.000",
    uploadTime: "2020-02-10",
    videoUrls:  ["https://www.youtube.com/watch?v=ywFmJsW6-kg"],
    src:        "srdc",
    srId:       "mrew887y",
  },
  {
    playerId:   "OverusedMemes",
    clearTime:  "1:39.866",
    uploadTime: "2018-08-09",
    videoUrls:  ["https://www.youtube.com/watch?v=yqcruwnK6Uc&feature=youtu.be"],
    src:        "srdc",
    srId:       "z5132dnm",
  },
  {
    playerId:   "Nonqui",
    clearTime:  "1:40.799",
    uploadTime: "2018-08-05",
    videoUrls:  ["https://www.youtube.com/watch?v=Dv07HW_a4YY&feature=youtu.be"],
    src:        "srdc",
    srId:       "yvj9gvey",
  },
  {
    playerId:   "NightWorrer",
    clearTime:  "1:44.604",
    uploadTime: "2018-07-22",
    videoUrls:  ["https://youtu.be/DXMwE6PjvqE"],
    src:        "srdc",
    srId:       "z115do7z",
  },
  {
    playerId:   "OverusedMemes",
    clearTime:  "1:48.241",
    uploadTime: "2018-07-18",
    videoUrls:  ["https://www.youtube.com/watch?v=2cGxt5H5rHU&feature=youtu.be"],
    src:        "srdc",
    srId:       "zp04ow8m",
  },
  {
    playerId:   "joshwaaaa_",
    clearTime:  "1:48.475",
    uploadTime: "2018-08-09",
    videoUrls:  ["https://www.youtube.com/watch?v=Qj0Go_dxSQk"],
    src:        "srdc",
    srId:       "yd30rgxz",
  },
  {
    playerId:   "-Rekken-",
    clearTime:  "1:51.328",
    uploadTime: "2018-07-18",
    videoUrls:  ["https://youtu.be/ZgzjxWw2XjI"],
    src:        "srdc",
    srId:       "z03182ez",
  },
  {
    playerId:   "Wasamii",
    clearTime:  "1:53.000",
    uploadTime: "2021-04-02",
    videoUrls:  ["https://youtu.be/rKM9s-UKipY"],
    src:        "srdc",
    srId:       "m3nporwy",
  },
  {
    playerId:   "MagsPrime",
    clearTime:  "1:56.000",
    uploadTime: "2022-01-19",
    videoUrls:  ["https://youtu.be/Fg_ljFRzLJk"],
    src:        "srdc",
    srId:       "zgdpwqjz",
  },
  {
    playerId:   "-Arcturus.",
    clearTime:  "1:57.694",
    uploadTime: "2018-07-16",
    videoUrls:  ["https://youtu.be/DOLx1zuf-6Y"],
    src:        "srdc",
    srId:       "y431692z",
  },
  {
    playerId:   "Fr3zzco",
    clearTime:  "2:09.000",
    uploadTime: "2024-02-28",
    videoUrls:  ["https://youtu.be/GymrPyzqdpI"],
    src:        "srdc",
    srId:       "y6vp8xpm",
  },
  {
    playerId:   "LeChat930",
    clearTime:  "2:23.000",
    uploadTime: "2023-07-10",
    videoUrls:  ["https://www.youtube.com/watch?v=QAhUwWfbbDk&t=6s"],
    src:        "srdc",
    srId:       "y4oo3o2z",
  },
  {
    playerId:   "holleufer98",
    clearTime:  "2:50.000",
    uploadTime: "2018-01-25",
    videoUrls:  ["https://youtu.be/jdAPoTuD_Gs"],
    src:        "srdc",
    srId:       "ydql350m",
  },
  {
    playerId:   "holleufer98",
    clearTime:  "2:50.000",
    uploadTime: "2018-01-25",
    videoUrls:  ["https://youtu.be/jdAPoTuD_Gs"],
    src:        "srdc",
    srId:       "y97d20nm",
  },
  {
    playerId:   "zopney",
    clearTime:  "3:59.760",
    uploadTime: "2018-01-21",
    videoUrls:  ["https://www.youtube.com/watch?v=TV1Ci8c-1W4"],
    src:        "srdc",
    srId:       "m79njp0y",
  },
  {
    playerId:   "zopney",
    clearTime:  "3:59.760",
    uploadTime: "2018-01-21",
    videoUrls:  ["https://www.youtube.com/watch?v=TV1Ci8c-1W4"],
    src:        "srdc",
    srId:       "mrqvw82y",
  },
];