/* speedrun.com 原始抓取数据 — Spy Missions / Unda / Solo */
/* level_id=kwj16z0w | 共 13 条 */
var spy_missions_unda_soloRecords = [
  {
    playerId:   "Salat",
    clearTime:  "0:42.783",
    uploadTime: "2025-11-19",
    videoUrls:  ["https://youtu.be/AFDE7AzjLpw"],
    src:        "srdc",
    srId:       "y6898x6z",
  },
  {
    playerId:   "L1ndell",
    clearTime:  "0:44.233",
    uploadTime: "2025-11-19",
    videoUrls:  ["https://youtu.be/pJOAB0ae67E"],
    src:        "srdc",
    srId:       "mr5ndg7y",
  },
  {
    playerId:   "PrimedDarkeN",
    clearTime:  "0:46.550",
    uploadTime: "2022-06-08",
    videoUrls:  ["https://www.youtube.com/watch?v=2h01qKpVrEs"],
    src:        "srdc",
    srId:       "y60o951y",
  },
  {
    playerId:   "Febi",
    clearTime:  "0:57.000",
    uploadTime: "2022-01-23",
    videoUrls:  ["https://www.youtube.com/watch?v=0bkjU5uhg48"],
    src:        "srdc",
    srId:       "z5v2n6nm",
  },
  {
    playerId:   "Kuremento",
    clearTime:  "1:01.000",
    uploadTime: "2021-04-05",
    videoUrls:  ["https://youtu.be/TG7ynilLN3c"],
    src:        "srdc",
    srId:       "z06v14oz",
  },
  {
    playerId:   "Mortar",
    clearTime:  "1:05.000",
    uploadTime: "2020-07-30",
    videoUrls:  ["https://www.youtube.com/watch?v=gi4WVgfsSWc"],
    src:        "srdc",
    srId:       "znkg7kvz",
  },
  {
    playerId:   "Mortar",
    clearTime:  "1:05.000",
    uploadTime: "2020-07-30",
    videoUrls:  ["https://www.youtube.com/watch?v=gi4WVgfsSWc"],
    src:        "srdc",
    srId:       "ylkjeq2z",
  },
  {
    playerId:   "Wasamii",
    clearTime:  "1:25.000",
    uploadTime: "2021-04-02",
    videoUrls:  ["https://youtu.be/EGKEct580PQ"],
    src:        "srdc",
    srId:       "yv2djo4m",
  },
  {
    playerId:   "Mano",
    clearTime:  "1:27.000",
    uploadTime: "2020-07-30",
    videoUrls:  ["https://www.youtube.com/watch?v=WAc3d6uqkDM&feature=youtu.be"],
    src:        "srdc",
    srId:       "yd54ekvm",
  },
  {
    playerId:   "silverdk",
    clearTime:  "1:30.000",
    uploadTime: "2020-07-30",
    videoUrls:  ["https://youtu.be/OIIKUF-kkJw"],
    src:        "srdc",
    srId:       "zgw6r0dy",
  },
  {
    playerId:   "LeChat930",
    clearTime:  "2:01.000",
    uploadTime: "2023-07-12",
    videoUrls:  ["https://www.youtube.com/watch?v=rrvlx3ONFw8"],
    src:        "srdc",
    srId:       "mk00v5vz",
  },
  {
    playerId:   "icegun784",
    clearTime:  "2:04.000",
    uploadTime: "2020-07-30",
    videoUrls:  ["https://youtu.be/YC1BR-0bQzI"],
    src:        "srdc",
    srId:       "mk3wee3z",
  },
  {
    playerId:   "TheLegacy___",
    clearTime:  "3:51.000",
    uploadTime: "2020-07-30",
    videoUrls:  ["https://youtu.be/KuMbU1rMMvc"],
    src:        "srdc",
    srId:       "y258vl5y",
  },
];