/* speedrun.com 原始抓取数据 — Exterminate / Acheron / Solo */
/* level_id=d7y8mevd | 共 9 条 */
var exterminate_acheron_soloRecords = [
  {
    playerId:   "Jagdtor",
    clearTime:  "0:18.983",
    uploadTime: "2026-04-30",
    videoUrls:  ["https://www.youtube.com/watch?v=up8bodFtGMY"],
    src:        "srdc",
    srId:       "y6w2krpz",
  },
  {
    playerId:   "Hvna",
    clearTime:  "0:20.000",
    uploadTime: "2026-02-19",
    videoUrls:  ["https://youtu.be/54SL6t0wh00"],
    src:        "srdc",
    srId:       "y6w3qljz",
  },
  {
    playerId:   "Salat",
    clearTime:  "0:20.000",
    uploadTime: "2026-02-20",
    videoUrls:  ["https://youtu.be/6r3H9vVnb44"],
    src:        "srdc",
    srId:       "z5no515z",
  },
  {
    playerId:   "_Phobos",
    clearTime:  "0:20.100",
    uploadTime: "2026-06-03",
    videoUrls:  ["https://youtu.be/GukvS4BNdjc?si=apX4cVvEo1Pxpovx&t=19"],
    src:        "srdc",
    srId:       "zpv5jorz",
  },
  {
    playerId:   "FrostMainer",
    clearTime:  "0:26.000",
    uploadTime: "2026-05-24",
    videoUrls:  ["https://www.youtube.com/watch?v=2iRbaEA2sb8"],
    src:        "srdc",
    srId:       "ywo2dn3m",
  },
  {
    playerId:   "NamelessDeity",
    clearTime:  "0:35.000",
    uploadTime: "2026-04-29",
    videoUrls:  ["https://www.youtube.com/watch?v=xfp6LcterC4"],
    src:        "srdc",
    srId:       "mrwl5edy",
  },
  {
    playerId:   "oTonJleHue",
    clearTime:  "0:36.000",
    uploadTime: "2026-02-12",
    videoUrls:  ["https://www.youtube.com/watch?v=XORNfK6W8WM"],
    src:        "srdc",
    srId:       "yo51kk0z",
  },
  {
    playerId:   "Salat",
    clearTime:  "0:39.000",
    uploadTime: "2026-01-26",
    videoUrls:  ["https://youtu.be/bE2-4_wCTx4"],
    src:        "srdc",
    srId:       "y8nn52dy",
  },
  {
    playerId:   "RoniPrime",
    clearTime:  "0:46.533",
    uploadTime: "2026-01-25",
    videoUrls:  ["https://youtu.be/6kq79Rbjdjw"],
    src:        "srdc",
    srId:       "m3228ngy",
  },
];