/* speedrun.com 原始抓取数据 — Exterminate / Oxomoco / Solo */
/* level_id=d0kx5219 | 共 10 条 */
var exterminate_oxomoco_soloRecords = [
  {
    playerId:   "Jagdtor",
    clearTime:  "0:11.467",
    uploadTime: "2026-05-28",
    videoUrls:  ["https://www.youtube.com/watch?v=uuwuOflqXXo"],
    src:        "srdc",
    srId:       "z02kw99m",
  },
  {
    playerId:   "yukkpo",
    clearTime:  "0:13.600",
    uploadTime: "2026-06-26",
    videoUrls:  ["https://youtu.be/WVMP9hl3CqI?si=CMi6wm36YXvGEDA5"],
    src:        "srdc",
    srId:       "z04w948y",
  },
  {
    playerId:   "nykroze",
    clearTime:  "0:17.767",
    uploadTime: "2026-05-01",
    videoUrls:  ["https://youtu.be/UGk9O04zalU"],
    src:        "srdc",
    srId:       "mkxql9vz",
  },
  {
    playerId:   "Salat",
    clearTime:  "0:18.383",
    uploadTime: "2026-04-09",
    videoUrls:  ["https://youtu.be/7NbovDEZSo8"],
    src:        "srdc",
    srId:       "ywo3drpm",
  },
  {
    playerId:   "_Phobos",
    clearTime:  "0:19.667",
    uploadTime: "2026-03-28",
    videoUrls:  ["https://youtu.be/zZzelKHmdKM"],
    src:        "srdc",
    srId:       "zn61l5vy",
  },
  {
    playerId:   "FrostMainer",
    clearTime:  "0:28.000",
    uploadTime: "2026-06-07",
    videoUrls:  ["https://www.youtube.com/watch?v=MhfHN7pNQxk"],
    src:        "srdc",
    srId:       "zpvvv4vz",
  },
  {
    playerId:   "NamelessDeity",
    clearTime:  "0:32.000",
    uploadTime: "2026-02-07",
    videoUrls:  ["https://www.youtube.com/watch?v=NY-Gj0VOH9M"],
    src:        "srdc",
    srId:       "z17e5qwz",
  },
  {
    playerId:   "RoniPrime",
    clearTime:  "0:38.000",
    uploadTime: "2026-02-05",
    videoUrls:  ["https://youtu.be/379RqeLDsbY"],
    src:        "srdc",
    srId:       "ydox4vjz",
  },
  {
    playerId:   "Salat",
    clearTime:  "0:47.000",
    uploadTime: "2026-01-07",
    videoUrls:  ["https://youtu.be/ws3wMH24tVo"],
    src:        "srdc",
    srId:       "y8npwxny",
  },
  {
    playerId:   "Clarn",
    clearTime:  "4:58.000",
    uploadTime: "2026-02-20",
    videoUrls:  ["https://www.youtube.com/watch?v=xc3o0kprJjc"],
    src:        "srdc",
    srId:       "ywoew6pm",
  },
];