/* speedrun.com 原始抓取数据 — Mastery Rank Tests / Test 09 / Solo */
/* level_id=ldy204rw | 共 12 条 */
var mastery_rank_tests_test_09_soloRecords = [
  {
    playerId:   "Mortar",
    clearTime:  "0:28.933",
    uploadTime: "2024-04-11",
    videoUrls:  ["https://www.youtube.com/watch?v=VAu4gwdine4"],
    src:        "srdc",
    srId:       "m30623gm",
  },
  {
    playerId:   "Mortar",
    clearTime:  "0:30.883",
    uploadTime: "2019-10-19",
    videoUrls:  ["https://www.youtube.com/watch?v=bf8WFKo_xqE"],
    src:        "srdc",
    srId:       "zp4d9jrz",
  },
  {
    playerId:   "Nusmag",
    clearTime:  "0:32.616",
    uploadTime: "2018-03-31",
    videoUrls:  ["https://youtu.be/zkobnF1Pd88"],
    src:        "srdc",
    srId:       "y8qlnkwy",
  },
  {
    playerId:   "-Rekken-",
    clearTime:  "0:32.750",
    uploadTime: "2018-03-29",
    videoUrls:  ["https://youtu.be/o0czhdG49Ro"],
    src:        "srdc",
    srId:       "zpqvxlvy",
  },
  {
    playerId:   "Reaper261292",
    clearTime:  "0:41.283",
    uploadTime: "2020-06-05",
    videoUrls:  ["https://youtu.be/5NAneNr046U"],
    src:        "srdc",
    srId:       "z5j2715m",
  },
  {
    playerId:   "OverusedMemes",
    clearTime:  "0:48.126",
    uploadTime: "2017-06-16",
    videoUrls:  ["https://www.youtube.com/watch?v=OUU64jb3RYA&feature=youtu.be"],
    src:        "srdc",
    srId:       "zpq4ejgy",
  },
  {
    playerId:   "Nononom12",
    clearTime:  "0:48.248",
    uploadTime: "2021-01-08",
    videoUrls:  ["https://youtu.be/_C52sE-Kv2g"],
    src:        "srdc",
    srId:       "me6qrj3z",
  },
  {
    playerId:   "lkrlemle",
    clearTime:  "0:52.380",
    uploadTime: "2020-06-30",
    videoUrls:  ["https://www.youtube.com/watch?v=rzfPBYfxUi8"],
    src:        "srdc",
    srId:       "mrklvw4y",
  },
  {
    playerId:   "MarcelloGammer",
    clearTime:  "0:55.355",
    uploadTime: "2019-03-25",
    videoUrls:  ["https://youtu.be/d14rURdcPGg"],
    src:        "srdc",
    srId:       "y6pwq56m",
  },
  {
    playerId:   "Reelix",
    clearTime:  "1:09.601",
    uploadTime: "2018-04-28",
    videoUrls:  ["https://www.youtube.com/watch?v=ypf5_k4SHQA"],
    src:        "srdc",
    srId:       "zn8ne8vz",
  },
  {
    playerId:   "JinnT4S",
    clearTime:  "1:25.233",
    uploadTime: "2018-12-27",
    videoUrls:  ["https://youtu.be/v9IGhf-uKYc"],
    src:        "srdc",
    srId:       "mr824gdy",
  },
  {
    playerId:   "Shredmachine",
    clearTime:  "1:51.783",
    uploadTime: "2025-09-26",
    videoUrls:  ["https://www.youtube.com/watch?v=UPsYwE744Nw"],
    src:        "srdc",
    srId:       "yv54deom",
  },
];