/* speedrun.com 原始抓取数据 — Mastery Rank Tests / Test 03 / Solo */
/* level_id=xd42xopw | 共 24 条 */
var mastery_rank_tests_test_03_soloRecords = [
  {
    playerId:   "Mortar",
    clearTime:  "0:43.750",
    uploadTime: "2024-04-11",
    videoUrls:  ["https://www.youtube.com/watch?v=0fY7yE4vNfs"],
    src:        "srdc",
    srId:       "zq80571z",
  },
  {
    playerId:   "OrangutanGaming",
    clearTime:  "0:44.140",
    uploadTime: "2017-09-24",
    videoUrls:  ["https://www.youtube.com/watch?v=gWz6r8OH2qU"],
    src:        "srdc",
    srId:       "y458e0nm",
  },
  {
    playerId:   "-Rekken-",
    clearTime:  "0:44.450",
    uploadTime: "2018-03-29",
    videoUrls:  ["https://youtu.be/U1rlc2yhygE"],
    src:        "srdc",
    srId:       "m79jnl0y",
  },
  {
    playerId:   "Salat",
    clearTime:  "0:44.517",
    uploadTime: "2019-09-20",
    videoUrls:  ["https://youtu.be/JUvXS5pskhQ"],
    src:        "srdc",
    srId:       "y41xj3ky",
  },
  {
    playerId:   "Nusmag",
    clearTime:  "0:44.778",
    uploadTime: "2017-07-26",
    videoUrls:  ["https://youtu.be/oveY-r5W4GM"],
    src:        "srdc",
    srId:       "z138dvgm",
  },
  {
    playerId:   "Mebius",
    clearTime:  "0:44.950",
    uploadTime: "2024-01-08",
    videoUrls:  ["https://youtu.be/momH176D49A"],
    src:        "srdc",
    srId:       "zqdp688m",
  },
  {
    playerId:   "holleufer98",
    clearTime:  "0:45.012",
    uploadTime: "2017-07-26",
    videoUrls:  ["https://www.youtube.com/watch?v=3TP_A308gJs&feature=youtu.be"],
    src:        "srdc",
    srId:       "mek9vg9m",
  },
  {
    playerId:   "Mortar",
    clearTime:  "0:45.879",
    uploadTime: "2019-10-11",
    videoUrls:  ["https://www.youtube.com/watch?v=l0oV-1TTJho"],
    src:        "srdc",
    srId:       "znrpnj8y",
  },
  {
    playerId:   "Chansey",
    clearTime:  "0:46.399",
    uploadTime: "2018-09-03",
    videoUrls:  ["https://www.youtube.com/watch?v=FUJxHpEKgzo"],
    src:        "srdc",
    srId:       "yj4gjngy",
  },
  {
    playerId:   "Andy.",
    clearTime:  "0:46.733",
    uploadTime: "2020-06-06",
    videoUrls:  ["https://youtu.be/UU5xal5u32s"],
    src:        "srdc",
    srId:       "yokpkqjz",
  },
  {
    playerId:   "HL_BAN",
    clearTime:  "0:47.014",
    uploadTime: "2023-05-14",
    videoUrls:  ["https://youtu.be/sX7A25LLZvo"],
    src:        "srdc",
    srId:       "yonjk7jz",
  },
  {
    playerId:   "Reaper261292",
    clearTime:  "0:47.750",
    uploadTime: "2020-06-06",
    videoUrls:  ["https://youtu.be/zl18FnaQe4w"],
    src:        "srdc",
    srId:       "zx272pqm",
  },
  {
    playerId:   "-FF-Drakulon",
    clearTime:  "0:48.032",
    uploadTime: "2018-03-29",
    videoUrls:  ["https://www.youtube.com/watch?v=NPKF_5zuDJg"],
    src:        "srdc",
    srId:       "zxvpq0qy",
  },
  {
    playerId:   "silverdk",
    clearTime:  "0:49.766",
    uploadTime: "2019-10-09",
    videoUrls:  ["https://youtu.be/E6rWp555wqk"],
    src:        "srdc",
    srId:       "yojpe00m",
  },
  {
    playerId:   "JayyRains",
    clearTime:  "0:50.200",
    uploadTime: "2020-02-21",
    videoUrls:  ["https://www.youtube.com/watch?v=I33UcAxOqvc"],
    src:        "srdc",
    srId:       "m7q496ez",
  },
  {
    playerId:   "-FF-Matke_Kotel",
    clearTime:  "0:50.650",
    uploadTime: "2018-03-26",
    videoUrls:  ["https://www.youtube.com/watch?v=G1X8Q7ptqRA&feature=youtu.be"],
    src:        "srdc",
    srId:       "yjkrdo3m",
  },
  {
    playerId:   "Goon",
    clearTime:  "0:51.686",
    uploadTime: "2018-05-09",
    videoUrls:  ["https://youtu.be/jD7OVOAIhKg"],
    src:        "srdc",
    srId:       "yw1l0n3z",
  },
  {
    playerId:   "WolfeXCIX",
    clearTime:  "0:52.083",
    uploadTime: "2020-01-21",
    videoUrls:  ["https://www.youtube.com/watch?v=wF-JCbdmklE"],
    src:        "srdc",
    srId:       "yd6408xz",
  },
  {
    playerId:   "TheLegacy___",
    clearTime:  "0:52.285",
    uploadTime: "2021-08-26",
    videoUrls:  ["https://www.youtube.com/watch?v=VShwImUAVR0"],
    src:        "srdc",
    srId:       "y27x9kjz",
  },
  {
    playerId:   "winnermindsetzzz",
    clearTime:  "0:54.067",
    uploadTime: "2026-05-24",
    videoUrls:  ["https://www.youtube.com/watch?v=gCYf-ze3bhc"],
    src:        "srdc",
    srId:       "ydp4eqqy",
  },
  {
    playerId:   "Meadowlion",
    clearTime:  "0:54.300",
    uploadTime: "2021-01-06",
    videoUrls:  ["https://www.youtube.com/watch?v=YoM6hmtRxQc&ab_channel=MeadowLion"],
    src:        "srdc",
    srId:       "mr9gr74m",
  },
  {
    playerId:   "yuki.",
    clearTime:  "0:57.466",
    uploadTime: "2020-04-27",
    videoUrls:  ["https://youtu.be/s_n0PFx5y8k"],
    src:        "srdc",
    srId:       "z155lk9y",
  },
  {
    playerId:   "Shredmachine",
    clearTime:  "1:20.180",
    uploadTime: "2025-04-02",
    videoUrls:  ["https://www.youtube.com/watch?v=8PMPMk5PzEs"],
    src:        "srdc",
    srId:       "m3w4786y",
  },
  {
    playerId:   "lucasengenho",
    clearTime:  "1:31.600",
    uploadTime: "2019-10-08",
    videoUrls:  ["https://youtu.be/UaY8XRU2uDo"],
    src:        "srdc",
    srId:       "mre7d2dy",
  },
];