/* speedrun.com 原始抓取数据 — Mastery Rank Tests / Test 05 / Solo */
/* level_id=xd0qx519 | 共 11 条 */
var mastery_rank_tests_test_05_soloRecords = [
  {
    playerId:   "Salat",
    clearTime:  "0:35.650",
    uploadTime: "2026-05-02",
    videoUrls:  ["https://youtu.be/6zBXTflY0fs"],
    src:        "srdc",
    srId:       "zn6eo23y",
  },
  {
    playerId:   "Mortar",
    clearTime:  "0:37.966",
    uploadTime: "2020-06-03",
    videoUrls:  ["https://www.youtube.com/watch?v=IM9KHskw1Qk"],
    src:        "srdc",
    srId:       "zqw0595z",
  },
  {
    playerId:   "HL_BAN",
    clearTime:  "0:42.109",
    uploadTime: "2023-05-14",
    videoUrls:  ["https://youtu.be/-K_Ff4TTkzs"],
    src:        "srdc",
    srId:       "z1lj5rrm",
  },
  {
    playerId:   "joshwaaaa_",
    clearTime:  "0:43.343",
    uploadTime: "2018-05-13",
    videoUrls:  ["https://www.youtube.com/watch?v=l5fR4mJaWpY"],
    src:        "srdc",
    srId:       "zxveno8y",
  },
  {
    playerId:   "-Rekken-",
    clearTime:  "0:44.494",
    uploadTime: "2018-05-11",
    videoUrls:  ["https://youtu.be/n60GTETGX-0"],
    src:        "srdc",
    srId:       "y8q5ee5y",
  },
  {
    playerId:   "Lloki_",
    clearTime:  "0:45.366",
    uploadTime: "2020-12-06",
    videoUrls:  ["https://www.youtube.com/watch?v=vR2bgioK_iU"],
    src:        "srdc",
    srId:       "z09d66oz",
  },
  {
    playerId:   "HesitantDwarf",
    clearTime:  "0:46.000",
    uploadTime: "2018-07-03",
    videoUrls:  ["https://www.youtube.com/watch?v=0epvOZItZ-s"],
    src:        "srdc",
    srId:       "zx44x78y",
  },
  {
    playerId:   "._blur_.",
    clearTime:  "0:47.550",
    uploadTime: "2018-01-24",
    videoUrls:  ["https://www.youtube.com/watch?v=iLtXV72A8FQ&t=2s"],
    src:        "srdc",
    srId:       "y97j4r2m",
  },
  {
    playerId:   "Nusmag",
    clearTime:  "0:48.191",
    uploadTime: "2017-06-15",
    videoUrls:  ["https://youtu.be/ZnDlBYb2awU"],
    src:        "srdc",
    srId:       "y8q1n0ny",
  },
  {
    playerId:   "TheLegacy___",
    clearTime:  "0:50.750",
    uploadTime: "2021-08-26",
    videoUrls:  ["https://www.youtube.com/watch?v=v-R3KVnJ9BY"],
    src:        "srdc",
    srId:       "yvo14vxz",
  },
  {
    playerId:   "Shredmachine",
    clearTime:  "1:21.080",
    uploadTime: "2025-04-07",
    videoUrls:  ["https://www.youtube.com/watch?v=SEL_hyubaC8"],
    src:        "srdc",
    srId:       "zgj5n8nz",
  },
];