/* speedrun.com 原始抓取数据 — Mastery Rank Tests / Test 25 / Solo */
/* level_id=xd12xkyw | 共 10 条 */
var mastery_rank_tests_test_25_soloRecords = [
  {
    playerId:   "Salat",
    clearTime:  "1:02.267",
    uploadTime: "2026-06-14",
    videoUrls:  ["https://youtu.be/Nw4sI49q9QI"],
    src:        "srdc",
    srId:       "zpvjr3xz",
  },
  {
    playerId:   "Salat",
    clearTime:  "1:03.883",
    uploadTime: "2019-09-17",
    videoUrls:  ["https://www.youtube.com/watch?v=HOnUdkKv0P4"],
    src:        "srdc",
    srId:       "y95lvvez",
  },
  {
    playerId:   "-Rekken-",
    clearTime:  "1:04.898",
    uploadTime: "2018-03-13",
    videoUrls:  ["https://youtu.be/nhpAQv7XYT4"],
    src:        "srdc",
    srId:       "y23r2q5m",
  },
  {
    playerId:   "Nusmag",
    clearTime:  "1:08.552",
    uploadTime: "2018-03-13",
    videoUrls:  ["https://youtu.be/BOHfhdpHmes"],
    src:        "srdc",
    srId:       "m3d2kl6z",
  },
  {
    playerId:   "Avate",
    clearTime:  "1:15.640",
    uploadTime: "2018-01-30",
    videoUrls:  ["https://youtu.be/7cs-fVPrfcg"],
    src:        "srdc",
    srId:       "y67e0vjm",
  },
  {
    playerId:   "LoneAi",
    clearTime:  "1:29.723",
    uploadTime: "2021-01-16",
    videoUrls:  ["https://youtu.be/gcShWrr9e_Y"],
    src:        "srdc",
    srId:       "yo94kn0y",
  },
  {
    playerId:   "HL_BAN",
    clearTime:  "1:30.056",
    uploadTime: "2023-05-14",
    videoUrls:  ["https://youtu.be/zwl3vbqWtys"],
    src:        "srdc",
    srId:       "y2g1x57z",
  },
  {
    playerId:   "Nononom12",
    clearTime:  "1:58.852",
    uploadTime: "2021-01-06",
    videoUrls:  ["https://youtu.be/H76g98l2gAU"],
    src:        "srdc",
    srId:       "z09gjroz",
  },
  {
    playerId:   "Jimmyghost",
    clearTime:  "2:02.022",
    uploadTime: "2021-01-06",
    videoUrls:  ["https://youtu.be/YjeZn4Rc1Ks"],
    src:        "srdc",
    srId:       "z53qe4ny",
  },
  {
    playerId:   "TheLegacy___",
    clearTime:  "2:04.491",
    uploadTime: "2020-07-30",
    videoUrls:  ["https://youtu.be/zPEUYOFMi3g"],
    src:        "srdc",
    srId:       "z05065om",
  },
];