/* speedrun.com 原始抓取数据 — Mastery Rank Tests / Test 06 / Solo */
/* level_id=rw6o367w | 共 13 条 */
var mastery_rank_tests_test_06_soloRecords = [
  {
    playerId:   "Salat",
    clearTime:  "1:19.750",
    uploadTime: "2026-05-01",
    videoUrls:  ["https://youtu.be/dRdOsqLjLQg"],
    src:        "srdc",
    srId:       "zxpwv6qy",
  },
  {
    playerId:   "Mortar",
    clearTime:  "1:19.833",
    uploadTime: "2025-04-21",
    videoUrls:  ["https://www.youtube.com/watch?v=ZowMjfsPy_c"],
    src:        "srdc",
    srId:       "yw2ev1py",
  },
  {
    playerId:   "forze33",
    clearTime:  "1:21.888",
    uploadTime: "2020-02-13",
    videoUrls:  ["https://youtu.be/JvAeC7BNO9k"],
    src:        "srdc",
    srId:       "mk2x7xxm",
  },
  {
    playerId:   "HesitantDwarf",
    clearTime:  "1:27.166",
    uploadTime: "2018-07-02",
    videoUrls:  ["https://www.youtube.com/watch?v=5b_JyhmMgkM"],
    src:        "srdc",
    srId:       "y899kj5m",
  },
  {
    playerId:   "Azynoth",
    clearTime:  "1:27.400",
    uploadTime: "2018-07-01",
    videoUrls:  ["https://youtu.be/CypobmHDrMQ"],
    src:        "srdc",
    srId:       "z111q4wz",
  },
  {
    playerId:   "joshwaaaa_",
    clearTime:  "1:28.180",
    uploadTime: "2018-05-13",
    videoUrls:  ["https://www.youtube.com/watch?v=F4HP65IcI-E&feature=youtu.behttps://www.youtube.com/watch?v=F4HP65IcI-E"],
    src:        "srdc",
    srId:       "mrq3oj8y",
  },
  {
    playerId:   "Ceejay",
    clearTime:  "1:29.450",
    uploadTime: "2018-05-15",
    videoUrls:  ["https://youtu.be/jLIqWsXnYLw"],
    src:        "srdc",
    srId:       "yjknojdm",
  },
  {
    playerId:   "-Rekken-",
    clearTime:  "1:30.066",
    uploadTime: "2018-05-13",
    videoUrls:  ["https://youtu.be/8Z58xWpJEMc"],
    src:        "srdc",
    srId:       "y8q5x7xy",
  },
  {
    playerId:   "Goon",
    clearTime:  "1:32.299",
    uploadTime: "2018-05-11",
    videoUrls:  ["https://youtu.be/lQhwjCIdONA"],
    src:        "srdc",
    srId:       "mekr4l3m",
  },
  {
    playerId:   "Nusmag",
    clearTime:  "1:36.958",
    uploadTime: "2017-06-15",
    videoUrls:  ["https://youtu.be/vGrTnHLBf00"],
    src:        "srdc",
    srId:       "y8q1n05y",
  },
  {
    playerId:   "OneManJack",
    clearTime:  "1:41.900",
    uploadTime: "2018-05-08",
    videoUrls:  ["https://youtu.be/d1gvDS3l2q4"],
    src:        "srdc",
    srId:       "ydqk59wm",
  },
  {
    playerId:   "Eurosion",
    clearTime:  "1:44.366",
    uploadTime: "2023-04-22",
    videoUrls:  ["https://youtu.be/q1THpXzeq60"],
    src:        "srdc",
    srId:       "y98oo22z",
  },
  {
    playerId:   "Shredmachine",
    clearTime:  "2:10.433",
    uploadTime: "2025-09-04",
    videoUrls:  ["https://www.youtube.com/watch?v=vD3OG7BVAfI"],
    src:        "srdc",
    srId:       "y4nd24km",
  },
];