/* speedrun.com 原始抓取数据 — Mastery Rank Tests / Test 11 / Solo */
/* level_id=5d748ned | 共 15 条 */
var mastery_rank_tests_test_11_soloRecords = [
  {
    playerId:   "Salat",
    clearTime:  "0:12.350",
    uploadTime: "2026-05-02",
    videoUrls:  ["https://youtu.be/86zrxbXuv0Q"],
    src:        "srdc",
    srId:       "y26kvw9m",
  },
  {
    playerId:   "VaclaF",
    clearTime:  "0:12.449",
    uploadTime: "2021-02-07",
    videoUrls:  ["https://www.youtube.com/watch?v=2r8jNalA6nI"],
    src:        "srdc",
    srId:       "yw0qg12m",
  },
  {
    playerId:   "Mortar",
    clearTime:  "0:12.767",
    uploadTime: "2020-06-18",
    videoUrls:  ["https://www.youtube.com/watch?v=1DbzKOCMt2s"],
    src:        "srdc",
    srId:       "z15g4qgy",
  },
  {
    playerId:   "Mortar",
    clearTime:  "0:13.949",
    uploadTime: "2019-08-21",
    videoUrls:  ["https://www.youtube.com/watch?v=C_EtCeJkMNI"],
    src:        "srdc",
    srId:       "mre1vq4y",
  },
  {
    playerId:   "-Rekken-",
    clearTime:  "0:14.300",
    uploadTime: "2018-04-05",
    videoUrls:  ["https://youtu.be/aqQn4xDIskA"],
    src:        "srdc",
    srId:       "y4541dqm",
  },
  {
    playerId:   "Aepul",
    clearTime:  "0:14.733",
    uploadTime: "2024-03-14",
    videoUrls:  ["https://www.youtube.com/watch?v=FueUngWFczk"],
    src:        "srdc",
    srId:       "yjo6183z",
  },
  {
    playerId:   "Nusmag",
    clearTime:  "0:14.898",
    uploadTime: "2018-03-31",
    videoUrls:  ["https://youtu.be/uaimQJgTeqg"],
    src:        "srdc",
    srId:       "zn86529z",
  },
  {
    playerId:   "Andy.",
    clearTime:  "0:15.467",
    uploadTime: "2020-06-17",
    videoUrls:  ["https://www.youtube.com/watch?v=JZsnakipvno&feature=youtu.be"],
    src:        "srdc",
    srId:       "yv605e8z",
  },
  {
    playerId:   "MagnusXL",
    clearTime:  "0:15.833",
    uploadTime: "2020-12-08",
    videoUrls:  ["https://youtu.be/pnGVrW-0QNU"],
    src:        "srdc",
    srId:       "yj6oe8dz",
  },
  {
    playerId:   "HesitantDwarf",
    clearTime:  "0:18.683",
    uploadTime: "2018-07-01",
    videoUrls:  ["https://www.youtube.com/watch?v=NxYkp9E6irw"],
    src:        "srdc",
    srId:       "zp00djvm",
  },
  {
    playerId:   "CPTBubbles",
    clearTime:  "0:18.899",
    uploadTime: "2021-04-13",
    videoUrls:  ["https://www.youtube.com/watch?v=RjSx1yr2McY"],
    src:        "srdc",
    srId:       "z1rd7njm",
  },
  {
    playerId:   "bing",
    clearTime:  "0:23.483",
    uploadTime: "2018-03-11",
    videoUrls:  ["https://www.youtube.com/watch?v=s9_vnUYD6ic&feature=youtu.be"],
    src:        "srdc",
    srId:       "zn85q39z",
  },
  {
    playerId:   "OverusedMemes",
    clearTime:  "0:26.977",
    uploadTime: "2017-06-23",
    videoUrls:  ["https://www.youtube.com/watch?v=5uRfcu8b5g0"],
    src:        "srdc",
    srId:       "ydq552qm",
  },
  {
    playerId:   "Nusmag",
    clearTime:  "0:48.830",
    uploadTime: "2017-06-16",
    videoUrls:  ["https://youtu.be/bJHJhZyUfEo"],
    src:        "srdc",
    srId:       "zpq4v68y",
  },
  {
    playerId:   "Shredmachine",
    clearTime:  "1:59.487",
    uploadTime: "2025-12-02",
    videoUrls:  ["https://www.youtube.com/watch?v=JhIVt6k4O4Y"],
    src:        "srdc",
    srId:       "zq57n4xz",
  },
];