/* speedrun.com 原始抓取数据 — Mastery Rank Tests / Test 01 / Solo */
/* level_id=xd12xq6w | 共 21 条 */
var mastery_rank_tests_test_01_soloRecords = [
  {
    playerId:   "Salat",
    clearTime:  "0:44.067",
    uploadTime: "2026-05-01",
    videoUrls:  ["https://youtu.be/0DKq0KHWvYE"],
    src:        "srdc",
    srId:       "y8lkqv5m",
  },
  {
    playerId:   "Mortar",
    clearTime:  "0:44.583",
    uploadTime: "2024-01-21",
    videoUrls:  ["https://www.youtube.com/watch?v=6YY7JL1bKao"],
    src:        "srdc",
    srId:       "y9kg1gvz",
  },
  {
    playerId:   "Mebius",
    clearTime:  "0:44.822",
    uploadTime: "2023-10-08",
    videoUrls:  ["https://youtu.be/rQLZejHj8t0"],
    src:        "srdc",
    srId:       "y6qrrpqz",
  },
  {
    playerId:   "-VS-Silv0r",
    clearTime:  "0:45.133",
    uploadTime: "2018-10-24",
    videoUrls:  ["https://www.youtube.com/watch?v=zq98WeYprWU"],
    src:        "srdc",
    srId:       "mr877j2y",
  },
  {
    playerId:   "19Lion",
    clearTime:  "0:45.299",
    uploadTime: "2022-04-23",
    videoUrls:  ["https://youtu.be/EGxFE6YnV50"],
    src:        "srdc",
    srId:       "zgpk2wjz",
  },
  {
    playerId:   "Octostarx",
    clearTime:  "0:45.500",
    uploadTime: "2019-07-24",
    videoUrls:  ["https://www.twitch.tv/videos/457232879"],
    src:        "srdc",
    srId:       "znr30j7y",
  },
  {
    playerId:   "Chansey",
    clearTime:  "0:45.928",
    uploadTime: "2018-08-27",
    videoUrls:  ["https://www.youtube.com/watch?v=2ULNzRjr2SA"],
    src:        "srdc",
    srId:       "zn4oj69m",
  },
  {
    playerId:   "OneManJack",
    clearTime:  "0:46.066",
    uploadTime: "2018-05-08",
    videoUrls:  ["https://www.youtube.com/watch?v=NVO7YA47lNs&feature=youtu.be"],
    src:        "srdc",
    srId:       "y8q52r5y",
  },
  {
    playerId:   "Butt_er",
    clearTime:  "0:46.681",
    uploadTime: "2018-05-21",
    videoUrls:  ["https://www.youtube.com/watch?v=D0AG1Fy49ws&feature=youtu.be"],
    src:        "srdc",
    srId:       "mrq3g32y",
  },
  {
    playerId:   "Murder_Frog",
    clearTime:  "0:46.900",
    uploadTime: "2025-09-12",
    videoUrls:  ["https://youtu.be/AUUIjwYZR5k"],
    src:        "srdc",
    srId:       "y28lv59y",
  },
  {
    playerId:   "biochronicle",
    clearTime:  "0:47.967",
    uploadTime: "2019-08-31",
    videoUrls:  ["https://www.youtube.com/watch?v=zfgGjZ-LruQ"],
    src:        "srdc",
    srId:       "mk255o3m",
  },
  {
    playerId:   "Spectrons4",
    clearTime:  "0:48.398",
    uploadTime: "2018-02-22",
    videoUrls:  ["https://youtu.be/g5gqO1nKJg4"],
    src:        "srdc",
    srId:       "y238v0wm",
  },
  {
    playerId:   "Nusmag",
    clearTime:  "0:48.830",
    uploadTime: "2017-06-15",
    videoUrls:  ["https://youtu.be/Rgniw-yrHJw"],
    src:        "srdc",
    srId:       "zgnk9dny",
  },
  {
    playerId:   "Assassin_Knight",
    clearTime:  "0:55.266",
    uploadTime: "2022-05-23",
    videoUrls:  ["https://youtu.be/xsjfjr_pvO0"],
    src:        "srdc",
    srId:       "y9vl5jrm",
  },
  {
    playerId:   "W1CK",
    clearTime:  "0:55.967",
    uploadTime: "2025-03-14",
    videoUrls:  ["https://www.youtube.com/watch?v=SkjRaJlTvYA"],
    src:        "srdc",
    srId:       "yww2p10y",
  },
  {
    playerId:   "albaniandeath",
    clearTime:  "1:00.300",
    uploadTime: "2026-05-24",
    videoUrls:  ["https://www.youtube.com/watch?v=5BAwu4fcgVY"],
    src:        "srdc",
    srId:       "zxp0grky",
  },
  {
    playerId:   "winnermindsetzzz",
    clearTime:  "1:03.200",
    uploadTime: "2026-05-23",
    videoUrls:  ["https://www.youtube.com/watch?v=wg5W8ASrc2w"],
    src:        "srdc",
    srId:       "mednr83y",
  },
  {
    playerId:   "snapperboot",
    clearTime:  "1:07.766",
    uploadTime: "2021-05-19",
    videoUrls:  ["https://youtu.be/rtz1mRStGIY"],
    src:        "srdc",
    srId:       "m3r7p44m",
  },
  {
    playerId:   "Eurosion",
    clearTime:  "1:09.533",
    uploadTime: "2023-04-06",
    videoUrls:  ["https://www.youtube.com/watch?v=Fi35a9TBWd0"],
    src:        "srdc",
    srId:       "zg202nvy",
  },
  {
    playerId:   "xanzath",
    clearTime:  "1:49.867",
    uploadTime: "2025-12-17",
    videoUrls:  ["https://www.youtube.com/watch?v=7rd76SD1yY8"],
    src:        "srdc",
    srId:       "meplvv8y",
  },
  {
    playerId:   "Shredmachine",
    clearTime:  "2:02.756",
    uploadTime: "2021-12-26",
    videoUrls:  ["https://youtu.be/3buHT-B3oik"],
    src:        "srdc",
    srId:       "zgdw09nz",
  },
];