/* speedrun.com 原始抓取数据 — Mastery Rank Tests / Test 02 / Solo */
/* level_id=29v72rn9 | 共 12 条 */
var mastery_rank_tests_test_02_soloRecords = [
  {
    playerId:   "Mortar",
    clearTime:  "0:43.766",
    uploadTime: "2024-01-15",
    videoUrls:  ["https://www.youtube.com/watch?v=XMBjGt5k0nc"],
    src:        "srdc",
    srId:       "mkqr2xvm",
  },
  {
    playerId:   "Salat",
    clearTime:  "0:43.867",
    uploadTime: "2026-05-01",
    videoUrls:  ["https://youtu.be/fLHDsyzgeJM"],
    src:        "srdc",
    srId:       "y9gk79km",
  },
  {
    playerId:   "HesitantDwarf",
    clearTime:  "0:44.016",
    uploadTime: "2018-07-03",
    videoUrls:  ["https://www.youtube.com/watch?v=OX7ohmmo-_Y"],
    src:        "srdc",
    srId:       "yl44xnkm",
  },
  {
    playerId:   "Mebius",
    clearTime:  "0:44.016",
    uploadTime: "2024-01-06",
    videoUrls:  ["https://youtu.be/9gpndOlt1aE"],
    src:        "srdc",
    srId:       "y8kog2wy",
  },
  {
    playerId:   "Azynoth",
    clearTime:  "0:44.511",
    uploadTime: "2018-07-01",
    videoUrls:  ["https://www.youtube.com/watch?v=HJy3B5AVns4"],
    src:        "srdc",
    srId:       "yd33ggjz",
  },
  {
    playerId:   "Nyxary",
    clearTime:  "0:44.873",
    uploadTime: "2018-03-20",
    videoUrls:  ["https://www.youtube.com/watch?v=_nakI21JdE0"],
    src:        "srdc",
    srId:       "yvgegexy",
  },
  {
    playerId:   "OrangutanGaming",
    clearTime:  "0:45.161",
    uploadTime: "2017-10-01",
    videoUrls:  ["https://youtu.be/dILGg2DpUtM"],
    src:        "srdc",
    srId:       "z132pqwm",
  },
  {
    playerId:   "DrunkenNevskij",
    clearTime:  "0:45.445",
    uploadTime: "2019-06-07",
    videoUrls:  ["https://youtu.be/NkyD67hvg3I"],
    src:        "srdc",
    srId:       "y81qp9xz",
  },
  {
    playerId:   "Chansey",
    clearTime:  "0:46.450",
    uploadTime: "2018-09-03",
    videoUrls:  ["https://www.youtube.com/watch?v=G6U-3JLa758"],
    src:        "srdc",
    srId:       "ywpqel0z",
  },
  {
    playerId:   "Nusmag",
    clearTime:  "0:50.366",
    uploadTime: "2017-06-15",
    videoUrls:  ["https://youtu.be/1gZgdIAkzHw"],
    src:        "srdc",
    srId:       "m79qvxwy",
  },
  {
    playerId:   "TheLegacy___",
    clearTime:  "0:58.925",
    uploadTime: "2021-08-26",
    videoUrls:  ["https://www.youtube.com/watch?v=OOvX5Vllcuo"],
    src:        "srdc",
    srId:       "m77d135m",
  },
  {
    playerId:   "Shredmachine",
    clearTime:  "1:15.753",
    uploadTime: "2025-08-07",
    videoUrls:  ["https://www.youtube.com/watch?v=HH8gSiX-Fpk"],
    src:        "srdc",
    srId:       "mrd0ldgz",
  },
];