/* speedrun.com 原始抓取数据 — Capture Missions / Abaddon / Co-op */
/* level_id=r9gx45kw | 共 9 条 */
var capture_missions_abaddon_coopRecords = [
  {
    playerId:   "Salat / L1ndell",
    clearTime:  "0:22.283",
    uploadTime: "2025-12-24",
    videoUrls:  ["https://www.youtube.com/watch?v=-tjR6dcPL9o", "https://youtu.be/TBXLMZrs0_s"],
    src:        "srdc",
    srId:       "zp5prrry",
  },
  {
    playerId:   "PrimedDarkeN / Akula",
    clearTime:  "0:24.567",
    uploadTime: "2022-11-15",
    videoUrls:  ["https://www.youtube.com/watch?v=LN2IukWuhlg"],
    src:        "srdc",
    srId:       "znqno87z",
  },
  {
    playerId:   "Kuremento / Febi",
    clearTime:  "0:26.233",
    uploadTime: "2021-04-09",
    videoUrls:  ["https://www.youtube.com/watch?v=a21MwuhAqpE", "https://www.youtube.com/watch?v=MVaDVVAHBcA"],
    src:        "srdc",
    srId:       "y2vllrjz",
  },
  {
    playerId:   "PrimedDarkeN / Mortar",
    clearTime:  "0:26.667",
    uploadTime: "2020-11-03",
    videoUrls:  ["https://www.youtube.com/watch?v=Nyw_Qy52p50"],
    src:        "srdc",
    srId:       "z0978o8z",
  },
  {
    playerId:   "Salat / Mortar",
    clearTime:  "0:32.000",
    uploadTime: "2019-09-16",
    videoUrls:  ["https://www.youtube.com/watch?v=tC5UX1EUAAQ"],
    src:        "srdc",
    srId:       "mk2ekkxm",
  },
  {
    playerId:   "lucasengenho / silverdk",
    clearTime:  "0:34.000",
    uploadTime: "2019-07-03",
    videoUrls:  ["https://youtu.be/b4gSI2YFvmc"],
    src:        "srdc",
    srId:       "y411jqky",
  },
  {
    playerId:   "1-12-16-8-1 / IceFollower",
    clearTime:  "0:51.000",
    uploadTime: "2020-10-27",
    videoUrls:  ["https://youtu.be/UmalXilP0Ow"],
    src:        "srdc",
    srId:       "me67l03z",
  },
  {
    playerId:   "ShiftDelete / CreepingChamp",
    clearTime:  "0:57.000",
    uploadTime: "2020-08-20",
    videoUrls:  ["https://youtu.be/BfLNqKcyb_0?list=PLOoCYdaYurpzssoavUuncOcivAmO4XJcr"],
    src:        "srdc",
    srId:       "z53oo9ey",
  },
  {
    playerId:   "zopney / MunchkinMel",
    clearTime:  "1:20.000",
    uploadTime: "2018-12-11",
    videoUrls:  ["https://www.youtube.com/watch?v=_hU56wJuAIk"],
    src:        "srdc",
    srId:       "y43k76kz",
  },
];