/* speedrun.com 原始抓取数据 — Capture Missions / Abaddon / Solo */
/* level_id=r9gx45kw | 共 28 条 */
var capture_missions_abaddon_soloRecords = [
  {
    playerId:   "Salat",
    clearTime:  "0:18.667",
    uploadTime: "2025-03-04",
    videoUrls:  ["https://youtu.be/Rki7F6QXba4"],
    src:        "srdc",
    srId:       "y8opj3wm",
  },
  {
    playerId:   "Hera4v",
    clearTime:  "0:21.050",
    uploadTime: "2026-07-03",
    videoUrls:  ["https://www.youtube.com/watch?v=gYopFbIKMx4"],
    src:        "srdc",
    srId:       "ydxqvkxz",
  },
  {
    playerId:   "Mortar",
    clearTime:  "0:21.933",
    uploadTime: "2021-01-25",
    videoUrls:  ["https://www.youtube.com/watch?v=ctl3ew4dUaw"],
    src:        "srdc",
    srId:       "yv23ed4m",
  },
  {
    playerId:   "L1ndell",
    clearTime:  "0:22.183",
    uploadTime: "2022-03-08",
    videoUrls:  ["https://youtu.be/HwTsH8l07T8"],
    src:        "srdc",
    srId:       "yle5x22z",
  },
  {
    playerId:   "Febi",
    clearTime:  "0:26.000",
    uploadTime: "2021-04-07",
    videoUrls:  ["https://www.youtube.com/watch?v=ln8ad9P2Qrk"],
    src:        "srdc",
    srId:       "zp37degm",
  },
  {
    playerId:   "TheLostGuthix",
    clearTime:  "0:26.000",
    uploadTime: "2023-05-27",
    videoUrls:  ["https://www.youtube.com/watch?v=enKzqZPDUVU"],
    src:        "srdc",
    srId:       "znv33w9m",
  },
  {
    playerId:   "AresWrath562",
    clearTime:  "0:27.000",
    uploadTime: "2024-03-01",
    videoUrls:  ["https://www.youtube.com/watch?v=lZDDT52LKeI"],
    src:        "srdc",
    srId:       "mrveqe4z",
  },
  {
    playerId:   "Andy.",
    clearTime:  "0:28.000",
    uploadTime: "2020-04-20",
    videoUrls:  ["https://www.youtube.com/watch?v=OyzcsIJbXVY"],
    src:        "srdc",
    srId:       "meox0n3z",
  },
  {
    playerId:   "zukerben",
    clearTime:  "0:29.000",
    uploadTime: "2020-02-16",
    videoUrls:  ["https://www.youtube.com/watch?v=ANniU0iUFAo"],
    src:        "srdc",
    srId:       "y41vo6ky",
  },
  {
    playerId:   "nev546",
    clearTime:  "0:30.000",
    uploadTime: "2024-02-25",
    videoUrls:  ["https://youtube.com/clip/UgkxD_mxIWeuarJPH3gw2KtJRESjYxq3gPyX?si=yEvunDNXYh5tzIXl"],
    src:        "srdc",
    srId:       "zp602o8m",
  },
  {
    playerId:   "RoboSt3alth",
    clearTime:  "0:32.000",
    uploadTime: "2021-02-07",
    videoUrls:  ["https://youtu.be/YfaJx8xrwho"],
    src:        "srdc",
    srId:       "mk7g0evy",
  },
  {
    playerId:   "Theotim",
    clearTime:  "0:32.000",
    uploadTime: "2023-04-29",
    videoUrls:  ["https://youtu.be/6X_IYwOP6TM"],
    src:        "srdc",
    srId:       "y98owprz",
  },
  {
    playerId:   "DivineSunder",
    clearTime:  "0:34.000",
    uploadTime: "2018-12-06",
    videoUrls:  ["https://www.youtube.com/watch?v=3poBE18bwyI"],
    src:        "srdc",
    srId:       "yl469r3m",
  },
  {
    playerId:   "-VS-Silv0r",
    clearTime:  "0:36.000",
    uploadTime: "2018-10-27",
    videoUrls:  ["https://www.youtube.com/watch?v=j0h1RVKyEUY"],
    src:        "srdc",
    srId:       "zp09wxvm",
  },
  {
    playerId:   "DARK_BlackSun",
    clearTime:  "0:38.000",
    uploadTime: "2021-09-29",
    videoUrls:  ["https://www.youtube.com/watch?v=0ILOPqUXjmA"],
    src:        "srdc",
    srId:       "m7700l9m",
  },
  {
    playerId:   "Nonqui",
    clearTime:  "0:39.000",
    uploadTime: "2018-12-01",
    videoUrls:  ["https://www.youtube.com/watch?v=u1WoU5cQpME&feature=youtu.be"],
    src:        "srdc",
    srId:       "me8en22m",
  },
  {
    playerId:   "GEGOBADI",
    clearTime:  "0:40.000",
    uploadTime: "2023-01-25",
    videoUrls:  ["https://youtu.be/PLdsOlcnFdU"],
    src:        "srdc",
    srId:       "y4g8rn3y",
  },
  {
    playerId:   "Avate",
    clearTime:  "0:41.000",
    uploadTime: "2018-12-05",
    videoUrls:  ["https://youtu.be/8cnZtOBooEU"],
    src:        "srdc",
    srId:       "mr8o372y",
  },
  {
    playerId:   "Jmdl",
    clearTime:  "0:42.000",
    uploadTime: "2025-10-22",
    videoUrls:  ["https://youtu.be/yagG5ahC7is"],
    src:        "srdc",
    srId:       "z56jg7gy",
  },
  {
    playerId:   "hammerpt",
    clearTime:  "0:44.000",
    uploadTime: "2021-12-31",
    videoUrls:  ["https://www.youtube.com/watch?v=4e_1WJjCGTI"],
    src:        "srdc",
    srId:       "ydw0xwxm",
  },
  {
    playerId:   "LeChat930",
    clearTime:  "0:44.000",
    uploadTime: "2023-07-13",
    videoUrls:  ["https://www.youtube.com/watch?v=O716ldDbpn8"],
    src:        "srdc",
    srId:       "mk00qe5z",
  },
  {
    playerId:   "Vici",
    clearTime:  "0:45.000",
    uploadTime: "2018-10-10",
    videoUrls:  ["https://www.youtube.com/watch?v=KdrD0N9KSfg"],
    src:        "srdc",
    srId:       "y2q0g6jy",
  },
  {
    playerId:   "Negabite",
    clearTime:  "0:46.000",
    uploadTime: "2018-10-10",
    videoUrls:  ["https://www.youtube.com/watch?v=JCXAEJswab0&feature=youtu.be"],
    src:        "srdc",
    srId:       "y89j0j1m",
  },
  {
    playerId:   "dragonsmoocher",
    clearTime:  "0:46.000",
    uploadTime: "2020-04-28",
    videoUrls:  ["https://www.twitch.tv/videos/605637200"],
    src:        "srdc",
    srId:       "mrkk0ddy",
  },
  {
    playerId:   "simonplays52",
    clearTime:  "1:09.000",
    uploadTime: "2026-01-24",
    videoUrls:  ["https://youtu.be/AaI0ZmKkdLI?si=q8nxod7yUc2TCjjq"],
    src:        "srdc",
    srId:       "yv5582em",
  },
  {
    playerId:   "Poli4543",
    clearTime:  "1:12.000",
    uploadTime: "2019-04-06",
    videoUrls:  ["https://youtu.be/eb3bqw58nZQ"],
    src:        "srdc",
    srId:       "yvjko1ey",
  },
  {
    playerId:   "MrAndyPants",
    clearTime:  "1:39.000",
    uploadTime: "2018-09-09",
    videoUrls:  ["https://youtu.be/oSX3ZLXwvPA"],
    src:        "srdc",
    srId:       "y43rqdkz",
  },
  {
    playerId:   "Pdvg",
    clearTime:  "1:54.000",
    uploadTime: "2021-05-27",
    videoUrls:  ["https://youtu.be/C6K7RR-RP4E"],
    src:        "srdc",
    srId:       "ylq7x2nz",
  },
];