/* speedrun.com 原始抓取数据 — Capture Missions / Ananke / Solo */
/* level_id=rdq37jmw | 共 21 条 */
var capture_missions_ananke_soloRecords = [
  {
    playerId:   "Salat",
    clearTime:  "0:17.617",
    uploadTime: "2026-06-10",
    videoUrls:  ["https://youtu.be/mEN2xiMisHc"],
    src:        "srdc",
    srId:       "z104qjrm",
  },
  {
    playerId:   "Mortar",
    clearTime:  "0:17.733",
    uploadTime: "2024-03-17",
    videoUrls:  ["https://www.youtube.com/watch?v=D2y8ZhYY5So"],
    src:        "srdc",
    srId:       "zxqdx8km",
  },
  {
    playerId:   "L1ndell",
    clearTime:  "0:19.583",
    uploadTime: "2022-03-05",
    videoUrls:  ["https://youtu.be/Y7h3Kq9r3iM"],
    src:        "srdc",
    srId:       "zgd9kr0z",
  },
  {
    playerId:   "Txdo",
    clearTime:  "0:20.300",
    uploadTime: "2024-03-04",
    videoUrls:  ["https://www.youtube.com/watch?v=QUnusKryTy0"],
    src:        "srdc",
    srId:       "zq8r8k5z",
  },
  {
    playerId:   "Theotim",
    clearTime:  "0:24.000",
    uploadTime: "2023-04-29",
    videoUrls:  ["https://youtu.be/K6UTVVwA0cs"],
    src:        "srdc",
    srId:       "mk0lrwlz",
  },
  {
    playerId:   "TheLostGuthix",
    clearTime:  "0:24.000",
    uploadTime: "2023-05-27",
    videoUrls:  ["https://www.youtube.com/watch?v=oeq8q1ryv4Q"],
    src:        "srdc",
    srId:       "yon3341z",
  },
  {
    playerId:   "RoniPrime",
    clearTime:  "0:24.817",
    uploadTime: "2026-01-06",
    videoUrls:  ["https://youtu.be/7Z8g3W-CVnE?si=diXOlH4y1RGmdv_x"],
    src:        "srdc",
    srId:       "y40l83qz",
  },
  {
    playerId:   "AresWrath562",
    clearTime:  "0:25.000",
    uploadTime: "2024-03-01",
    videoUrls:  ["https://www.youtube.com/watch?v=Ke5M6pmlWh0"],
    src:        "srdc",
    srId:       "z0d1e8ey",
  },
  {
    playerId:   "zukerben",
    clearTime:  "0:27.000",
    uploadTime: "2019-12-09",
    videoUrls:  ["https://www.youtube.com/watch?v=7ZskU5RDG3o"],
    src:        "srdc",
    srId:       "zqrdow8y",
  },
  {
    playerId:   "Febi",
    clearTime:  "0:27.000",
    uploadTime: "2021-03-15",
    videoUrls:  ["https://www.youtube.com/watch?v=85j9dC3Y_Ds"],
    src:        "srdc",
    srId:       "yj1egq3y",
  },
  {
    playerId:   "Zeeddoom",
    clearTime:  "0:27.000",
    uploadTime: "2023-02-19",
    videoUrls:  ["https://youtu.be/3DLhNxb37zo"],
    src:        "srdc",
    srId:       "y806k4xm",
  },
  {
    playerId:   "Wakaaa",
    clearTime:  "0:28.000",
    uploadTime: "2024-02-07",
    videoUrls:  ["https://www.youtube.com/watch?v=C86hKv39mWs&ab_channel=Stupid_waka"],
    src:        "srdc",
    srId:       "yvvw6joy",
  },
  {
    playerId:   "Fr3zzco",
    clearTime:  "0:28.000",
    uploadTime: "2024-06-30",
    videoUrls:  ["https://www.youtube.com/watch?v=VWxfJzNNuQY"],
    src:        "srdc",
    srId:       "mrv39v7z",
  },
  {
    playerId:   "LeChat930",
    clearTime:  "0:29.000",
    uploadTime: "2023-07-18",
    videoUrls:  ["https://www.youtube.com/watch?v=7elLL-9BSmc"],
    src:        "srdc",
    srId:       "yj2wo5nm",
  },
  {
    playerId:   "RoboSt3alth",
    clearTime:  "0:30.000",
    uploadTime: "2021-02-07",
    videoUrls:  ["https://youtu.be/mpMdPHbNgR0"],
    src:        "srdc",
    srId:       "y8vd6e5z",
  },
  {
    playerId:   "Wiktoryk",
    clearTime:  "0:30.000",
    uploadTime: "2023-03-17",
    videoUrls:  ["https://www.youtube.com/watch?v=OGeCNhbsPoY"],
    src:        "srdc",
    srId:       "yole930y",
  },
  {
    playerId:   "SuiEXE",
    clearTime:  "0:32.000",
    uploadTime: "2021-02-05",
    videoUrls:  ["https://youtu.be/4vysW3YVOvQ"],
    src:        "srdc",
    srId:       "m3nro4qy",
  },
  {
    playerId:   "Rigsmal",
    clearTime:  "0:37.000",
    uploadTime: "2023-02-26",
    videoUrls:  ["https://www.youtube.com/watch?v=HKkX0efKY9s"],
    src:        "srdc",
    srId:       "znjen79m",
  },
  {
    playerId:   "-slarega-",
    clearTime:  "0:38.000",
    uploadTime: "2020-05-23",
    videoUrls:  ["https://www.youtube.com/watch?v=imjvvfOgclI&feature=youtu.be"],
    src:        "srdc",
    srId:       "mrkn807y",
  },
  {
    playerId:   "GEGOBADI",
    clearTime:  "0:41.000",
    uploadTime: "2023-01-25",
    videoUrls:  ["https://youtu.be/bqYYp3YUhpQ"],
    src:        "srdc",
    srId:       "y4g8rj3y",
  },
  {
    playerId:   "singedeiru",
    clearTime:  "0:53.000",
    uploadTime: "2021-05-18",
    videoUrls:  ["https://youtu.be/64GPhzD7qwY"],
    src:        "srdc",
    srId:       "zxgopp5y",
  },
];