/* speedrun.com 原始抓取数据 — Capture Missions / Ara / Solo */
/* level_id=n93o4xe9 | 共 38 条 */
var capture_missions_ara_soloRecords = [
  {
    playerId:   "Salat",
    clearTime:  "0:15.067",
    uploadTime: "2025-09-29",
    videoUrls:  ["https://youtu.be/cWNspYpqbuE"],
    src:        "srdc",
    srId:       "y2r37q9m",
  },
  {
    playerId:   "L1ndell",
    clearTime:  "0:15.767",
    uploadTime: "2022-05-30",
    videoUrls:  ["https://youtu.be/dBwkgrxeeAE"],
    src:        "srdc",
    srId:       "y600x10y",
  },
  {
    playerId:   "Mortar",
    clearTime:  "0:16.967",
    uploadTime: "2021-02-28",
    videoUrls:  ["https://www.youtube.com/watch?v=Gj5wy66O6uo"],
    src:        "srdc",
    srId:       "zqgd929m",
  },
  {
    playerId:   "Kuremento",
    clearTime:  "0:19.000",
    uploadTime: "2021-04-20",
    videoUrls:  ["https://youtu.be/Sp30pX587hE"],
    src:        "srdc",
    srId:       "yo73lg0m",
  },
  {
    playerId:   "Febi",
    clearTime:  "0:19.000",
    uploadTime: "2021-12-10",
    videoUrls:  ["https://www.youtube.com/watch?v=vQuzeu2zCWE"],
    src:        "srdc",
    srId:       "zp2qke8y",
  },
  {
    playerId:   "RoniPrime",
    clearTime:  "0:19.583",
    uploadTime: "2026-01-06",
    videoUrls:  ["https://youtu.be/bzHjlCVQCyw"],
    src:        "srdc",
    srId:       "zq5q069z",
  },
  {
    playerId:   "Andy.",
    clearTime:  "0:20.000",
    uploadTime: "2020-11-27",
    videoUrls:  ["https://youtu.be/QQyCTJlEIPw"],
    src:        "srdc",
    srId:       "y918kxem",
  },
  {
    playerId:   "AresWrath562",
    clearTime:  "0:20.000",
    uploadTime: "2024-03-01",
    videoUrls:  ["https://www.youtube.com/watch?v=PNcC8mSDG9M"],
    src:        "srdc",
    srId:       "zp64qkxm",
  },
  {
    playerId:   "zukerben",
    clearTime:  "0:21.000",
    uploadTime: "2020-02-16",
    videoUrls:  ["https://www.youtube.com/watch?v=v_HXIKqKPOE"],
    src:        "srdc",
    srId:       "mk2x0rvm",
  },
  {
    playerId:   "Menadion",
    clearTime:  "0:21.000",
    uploadTime: "2020-09-20",
    videoUrls:  ["https://www.youtube.com/watch?v=zQbdjZeacfo"],
    src:        "srdc",
    srId:       "me68688z",
  },
  {
    playerId:   "FXCloud",
    clearTime:  "0:21.000",
    uploadTime: "2022-10-05",
    videoUrls:  ["https://youtu.be/DUdOYiirnFA"],
    src:        "srdc",
    srId:       "y8xw5l1m",
  },
  {
    playerId:   "Wasamii",
    clearTime:  "0:21.000",
    uploadTime: "2022-11-19",
    videoUrls:  ["https://youtu.be/HMJ3Thpwngw"],
    src:        "srdc",
    srId:       "zpdjol8z",
  },
  {
    playerId:   "Yangoo",
    clearTime:  "0:21.000",
    uploadTime: "2023-04-19",
    videoUrls:  ["https://youtu.be/pLr1lR9dtJQ"],
    src:        "srdc",
    srId:       "ywvljknz",
  },
  {
    playerId:   "--Q--DankNinja",
    clearTime:  "0:22.000",
    uploadTime: "2019-07-30",
    videoUrls:  ["https://www.youtube.com/watch?v=yxOMmzObio8"],
    src:        "srdc",
    srId:       "z1jo08jz",
  },
  {
    playerId:   "LiAXiM",
    clearTime:  "0:23.000",
    uploadTime: "2021-11-08",
    videoUrls:  ["https://youtu.be/U5L60z487to"],
    src:        "srdc",
    srId:       "z072rrjy",
  },
  {
    playerId:   "DivineSunder",
    clearTime:  "0:24.000",
    uploadTime: "2018-12-04",
    videoUrls:  ["https://www.youtube.com/watch?v=r5g3q_Ea05A"],
    src:        "srdc",
    srId:       "yj480p3y",
  },
  {
    playerId:   "Afterburner_X",
    clearTime:  "0:24.000",
    uploadTime: "2020-05-20",
    videoUrls:  ["https://www.youtube.com/watch?v=dhUefVg-Tho"],
    src:        "srdc",
    srId:       "mk3gp85z",
  },
  {
    playerId:   "LuxeWF",
    clearTime:  "0:24.000",
    uploadTime: "2021-01-21",
    videoUrls:  ["https://www.youtube.com/watch?v=jyHyYcNmMT4&ab_channel=hi"],
    src:        "srdc",
    srId:       "yd93jeqz",
  },
  {
    playerId:   "RoboSt3alth",
    clearTime:  "0:24.000",
    uploadTime: "2021-02-07",
    videoUrls:  ["https://youtu.be/8RChoTs9sF4"],
    src:        "srdc",
    srId:       "zp31w28m",
  },
  {
    playerId:   "WOShiXiaoChengYa",
    clearTime:  "0:24.000",
    uploadTime: "2025-04-13",
    videoUrls:  ["https://www.youtube.com/watch?v=fDJAYsQA_nY"],
    src:        "srdc",
    srId:       "zq2x3j8z",
  },
  {
    playerId:   "toSa_xd",
    clearTime:  "0:25.000",
    uploadTime: "2021-01-08",
    videoUrls:  ["https://youtu.be/dLzzTFpDtwk"],
    src:        "srdc",
    srId:       "yj6nk07z",
  },
  {
    playerId:   "_Red_0",
    clearTime:  "0:25.000",
    uploadTime: "2025-05-09",
    videoUrls:  ["https://www.youtube.com/watch?v=9YbNG3klFOY"],
    src:        "srdc",
    srId:       "yv73656y",
  },
  {
    playerId:   "VaclaF",
    clearTime:  "0:26.000",
    uploadTime: "2020-12-15",
    videoUrls:  ["https://www.youtube.com/watch?v=XYYPaemuVKk&feature=youtu.be"],
    src:        "srdc",
    srId:       "yd0v37vz",
  },
  {
    playerId:   "Wiktoryk",
    clearTime:  "0:26.000",
    uploadTime: "2022-08-22",
    videoUrls:  ["https://www.youtube.com/watch?v=V6WTaT37DiY"],
    src:        "srdc",
    srId:       "y8xvojxm",
  },
  {
    playerId:   "silverdk",
    clearTime:  "0:27.000",
    uploadTime: "2019-07-04",
    videoUrls:  ["https://www.youtube.com/watch?v=v11msEQ740M&feature=youtu.be"],
    src:        "srdc",
    srId:       "yj33eegz",
  },
  {
    playerId:   "striker350z",
    clearTime:  "0:27.000",
    uploadTime: "2021-01-09",
    videoUrls:  ["https://youtu.be/fccpfQasxqo"],
    src:        "srdc",
    srId:       "y8r5rp1m",
  },
  {
    playerId:   "LeChat930",
    clearTime:  "0:27.000",
    uploadTime: "2023-07-10",
    videoUrls:  ["https://www.youtube.com/watch?v=5b8AOvu8Bu8"],
    src:        "srdc",
    srId:       "yj2248om",
  },
  {
    playerId:   "-Rekken-",
    clearTime:  "0:28.000",
    uploadTime: "2018-08-26",
    videoUrls:  ["https://youtu.be/Sw93CSyBYTc"],
    src:        "srdc",
    srId:       "zx4682qy",
  },
  {
    playerId:   "Nonqui",
    clearTime:  "0:29.000",
    uploadTime: "2018-12-01",
    videoUrls:  ["https://www.youtube.com/watch?v=JeeQgc1umw0&feature=youtu.be"],
    src:        "srdc",
    srId:       "mr8o042y",
  },
  {
    playerId:   "ShadowDrache",
    clearTime:  "0:29.000",
    uploadTime: "2024-01-20",
    videoUrls:  ["https://youtu.be/5Qq0pwDO5M0"],
    src:        "srdc",
    srId:       "m3k2ekwy",
  },
  {
    playerId:   "Avate",
    clearTime:  "0:30.000",
    uploadTime: "2018-12-05",
    videoUrls:  ["https://youtu.be/1H0SvysCN2M"],
    src:        "srdc",
    srId:       "zx4ne7qy",
  },
  {
    playerId:   "SaikoStef",
    clearTime:  "0:30.000",
    uploadTime: "2023-07-07",
    videoUrls:  ["https://youtu.be/RcGf3qkSXug"],
    src:        "srdc",
    srId:       "y2gjj85z",
  },
  {
    playerId:   "ThatBlue",
    clearTime:  "0:31.000",
    uploadTime: "2018-08-26",
    videoUrls:  ["https://youtu.be/9xPalts6lwQ"],
    src:        "srdc",
    srId:       "m7p8x50m",
  },
  {
    playerId:   "Chansey",
    clearTime:  "0:31.000",
    uploadTime: "2018-08-28",
    videoUrls:  ["https://www.youtube.com/watch?v=lzFm-28tGvs"],
    src:        "srdc",
    srId:       "zn4oe08m",
  },
  {
    playerId:   "Kongren",
    clearTime:  "0:40.000",
    uploadTime: "2018-11-04",
    videoUrls:  ["https://youtu.be/xpAcenxGee4"],
    src:        "srdc",
    srId:       "yl4149xm",
  },
  {
    playerId:   "iamfumii",
    clearTime:  "0:51.000",
    uploadTime: "2020-12-13",
    videoUrls:  ["https://www.youtube.com/watch?v=_MQFtMUDS24&feature=youtu.be"],
    src:        "srdc",
    srId:       "z1on9x7m",
  },
  {
    playerId:   "hariviknesh",
    clearTime:  "0:58.000",
    uploadTime: "2021-05-20",
    videoUrls:  ["https://youtu.be/d3H0YeLZSRA"],
    src:        "srdc",
    srId:       "ylqe9gkz",
  },
  {
    playerId:   "chadagwing",
    clearTime:  "1:13.000",
    uploadTime: "2019-02-07",
    videoUrls:  ["https://youtu.be/n2PHl8disHU"],
    src:        "srdc",
    srId:       "zx4j69ky",
  },
];