/* speedrun.com 原始抓取数据 — Capture Missions / Ara / Co-op */
/* level_id=n93o4xe9 | 共 13 条 */
var capture_missions_ara_coopRecords = [
  {
    playerId:   "Salat / L1ndell",
    clearTime:  "0:15.733",
    uploadTime: "2025-12-21",
    videoUrls:  ["https://www.youtube.com/watch?v=WikNghWf0Ao", "https://youtu.be/ETtWzL7ZdrE"],
    src:        "srdc",
    srId:       "meplr30y",
  },
  {
    playerId:   "PrimedDarkeN / Febi",
    clearTime:  "0:16.967",
    uploadTime: "2023-01-21",
    videoUrls:  ["https://www.youtube.com/watch?v=EgDgkxzC_Iw"],
    src:        "srdc",
    srId:       "znj0xkvm",
  },
  {
    playerId:   "PrimedDarkeN / Mortar",
    clearTime:  "0:18.867",
    uploadTime: "2020-09-14",
    videoUrls:  ["https://www.youtube.com/watch?v=rIN_YYs_MqI"],
    src:        "srdc",
    srId:       "z1o1lrjm",
  },
  {
    playerId:   "Mortar / Salat",
    clearTime:  "0:19.000",
    uploadTime: "2019-09-20",
    videoUrls:  ["https://www.youtube.com/watch?v=ys4NFDvrW3c"],
    src:        "srdc",
    srId:       "y81jwj1z",
  },
  {
    playerId:   "-Rekken- / ThatBlue",
    clearTime:  "0:20.000",
    uploadTime: "2018-08-27",
    videoUrls:  ["https://youtu.be/KElwwNBiY20"],
    src:        "srdc",
    srId:       "zg7xepdz",
  },
  {
    playerId:   "Cryogenian / silverdk",
    clearTime:  "0:25.000",
    uploadTime: "2019-06-30",
    videoUrls:  ["https://youtu.be/WxZKsvfBnX8"],
    src:        "srdc",
    srId:       "yojjp85m",
  },
  {
    playerId:   "SuiEXE / KaiMartin",
    clearTime:  "0:25.633",
    uploadTime: "2021-04-07",
    videoUrls:  ["https://www.youtube.com/watch?v=Ta8o2dZbjdM"],
    src:        "srdc",
    srId:       "z509e15y",
  },
  {
    playerId:   "zopney / Akemi",
    clearTime:  "0:28.000",
    uploadTime: "2018-08-26",
    videoUrls:  ["https://youtu.be/pAPdZgRzGbI"],
    src:        "srdc",
    srId:       "z510xwjm",
  },
  {
    playerId:   "Caphtor / Andy.",
    clearTime:  "0:28.000",
    uploadTime: "2020-06-08",
    videoUrls:  ["https://youtu.be/pDUsNDDlflE"],
    src:        "srdc",
    srId:       "y8280oxy",
  },
  {
    playerId:   "toSa_xd / Dacami",
    clearTime:  "0:28.000",
    uploadTime: "2021-01-08",
    videoUrls:  ["https://www.youtube.com/watch?v=qKw1cTv--FM"],
    src:        "srdc",
    srId:       "zpl7njnm",
  },
  {
    playerId:   "Andy. / c0unter",
    clearTime:  "0:29.000",
    uploadTime: "2020-12-10",
    videoUrls:  ["https://youtu.be/VERaetZvb7g"],
    src:        "srdc",
    srId:       "yd0l6w0z",
  },
  {
    playerId:   "ThatBlue / Ceejay / ZitexZ",
    clearTime:  "0:38.000",
    uploadTime: "2018-08-27",
    videoUrls:  ["https://www.youtube.com/watch?v=sbembR8yEnE"],
    src:        "srdc",
    srId:       "mk9700xz",
  },
  {
    playerId:   "Akemi / zopney / Relli5000",
    clearTime:  "0:45.000",
    uploadTime: "2018-08-25",
    videoUrls:  ["https://www.youtube.com/watch?v=EOObRxDyAm4"],
    src:        "srdc",
    srId:       "z510xoem",
  },
];