/* speedrun.com 原始抓取数据 — Capture Missions / Ariel / Co-op */
/* level_id=z98n7ol9 | 共 9 条 */
var capture_missions_ariel_coopRecords = [
  {
    playerId:   "L1ndell / Salat",
    clearTime:  "0:25.433",
    uploadTime: "2025-12-24",
    videoUrls:  ["https://www.youtube.com/watch?v=sDPPwbMtKJc", "https://youtu.be/j9NgeBT5whI"],
    src:        "srdc",
    srId:       "y68q74qz",
  },
  {
    playerId:   "Salat / Mortar",
    clearTime:  "0:27.000",
    uploadTime: "2019-09-20",
    videoUrls:  ["https://www.youtube.com/watch?v=Ju5lGyGVzqM"],
    src:        "srdc",
    srId:       "mk2epv1m",
  },
  {
    playerId:   "Salat / L1ndell",
    clearTime:  "0:27.967",
    uploadTime: "2025-12-21",
    videoUrls:  ["https://www.youtube.com/watch?v=43_SFN2GzW0", "https://youtu.be/jht_8tb7TG8"],
    src:        "srdc",
    srId:       "yw5rl33y",
  },
  {
    playerId:   "PrimedDarkeN / Mortar",
    clearTime:  "0:29.884",
    uploadTime: "2020-11-03",
    videoUrls:  ["https://youtu.be/Nyw_Qy52p50?t=132"],
    src:        "srdc",
    srId:       "y6r9gn1y",
  },
  {
    playerId:   "lucasengenho / silverdk",
    clearTime:  "0:37.000",
    uploadTime: "2019-07-03",
    videoUrls:  ["https://youtu.be/PZz857DnoNM"],
    src:        "srdc",
    srId:       "y211npwz",
  },
  {
    playerId:   "Maktoob / Seiso / LeChat930",
    clearTime:  "0:40.284",
    uploadTime: "2023-08-14",
    videoUrls:  ["https://www.youtube.com/watch?v=uKzTdKx2CAY"],
    src:        "srdc",
    srId:       "mrlwex7m",
  },
  {
    playerId:   "Likhann_ / LeChat930",
    clearTime:  "0:51.698",
    uploadTime: "2023-07-20",
    videoUrls:  ["https://youtu.be/bLbjXLrNJAY"],
    src:        "srdc",
    srId:       "mrlxq3dm",
  },
  {
    playerId:   "zopney / MunchkinMel",
    clearTime:  "1:23.000",
    uploadTime: "2018-12-11",
    videoUrls:  ["https://www.youtube.com/watch?v=pEmSXr1QDWk"],
    src:        "srdc",
    srId:       "yvjvvooy",
  },
  {
    playerId:   "willy69892 / TheEnd0802",
    clearTime:  "1:47.000",
    uploadTime: "2020-06-17",
    videoUrls:  ["https://youtu.be/ulMrk9Xjn6E"],
    src:        "srdc",
    srId:       "y25e8g9y",
  },
];