/* speedrun.com 原始抓取数据 — Capture Missions / Ariel / Solo */
/* level_id=z98n7ol9 | 共 19 条 */
var capture_missions_ariel_soloRecords = [
  {
    playerId:   "Salat",
    clearTime:  "0:23.400",
    uploadTime: "2025-12-29",
    videoUrls:  ["https://youtu.be/gCtM0lbzaWk"],
    src:        "srdc",
    srId:       "yj7okooy",
  },
  {
    playerId:   "Mortar",
    clearTime:  "0:24.100",
    uploadTime: "2024-01-25",
    videoUrls:  ["https://www.youtube.com/watch?v=4MRBb6P5SKQ"],
    src:        "srdc",
    srId:       "z5kn4dez",
  },
  {
    playerId:   "L1ndell",
    clearTime:  "0:25.850",
    uploadTime: "2022-04-03",
    videoUrls:  ["https://youtu.be/XqP7mi_R2VI"],
    src:        "srdc",
    srId:       "me3vx19z",
  },
  {
    playerId:   "zukerben",
    clearTime:  "0:30.933",
    uploadTime: "2019-08-10",
    videoUrls:  ["https://www.youtube.com/watch?v=I6IcWDFWS7k"],
    src:        "srdc",
    srId:       "zp43o8rz",
  },
  {
    playerId:   "RoniPrime",
    clearTime:  "0:34.667",
    uploadTime: "2026-02-19",
    videoUrls:  ["https://youtu.be/RuXFZzvdvLc"],
    src:        "srdc",
    srId:       "yjrj8ooz",
  },
  {
    playerId:   "Wasamii",
    clearTime:  "0:37.000",
    uploadTime: "2021-06-24",
    videoUrls:  ["https://youtu.be/7dyOjMlEnus"],
    src:        "srdc",
    srId:       "z0r8rjjz",
  },
  {
    playerId:   "silverdk",
    clearTime:  "0:40.000",
    uploadTime: "2019-07-08",
    videoUrls:  ["https://www.youtube.com/watch?v=wP9XtkO2Oww"],
    src:        "srdc",
    srId:       "zxk2v6em",
  },
  {
    playerId:   "Bombatack017",
    clearTime:  "0:42.000",
    uploadTime: "2024-03-12",
    videoUrls:  ["https://www.youtube.com/watch?v=4qIu3GNXIEY"],
    src:        "srdc",
    srId:       "y6v51opm",
  },
  {
    playerId:   "RoboSt3alth",
    clearTime:  "0:43.000",
    uploadTime: "2021-03-04",
    videoUrls:  ["https://youtu.be/WDcBB1c3EnU"],
    src:        "srdc",
    srId:       "zgx8k9vm",
  },
  {
    playerId:   "Wakaaa",
    clearTime:  "0:43.000",
    uploadTime: "2024-02-08",
    videoUrls:  ["https://www.youtube.com/watch?v=PAKetT2UYpo&ab_channel=Stupid_waka"],
    src:        "srdc",
    srId:       "y2kl7kjy",
  },
  {
    playerId:   "Nonqui",
    clearTime:  "0:47.000",
    uploadTime: "2018-12-01",
    videoUrls:  ["https://www.youtube.com/watch?v=1JB_DgGfX88&feature=youtu.be"],
    src:        "srdc",
    srId:       "y890ov5m",
  },
  {
    playerId:   "DivineSunder",
    clearTime:  "0:47.000",
    uploadTime: "2018-12-10",
    videoUrls:  ["https://www.youtube.com/watch?v=-_LgJHbyYk8"],
    src:        "srdc",
    srId:       "z03j6roz",
  },
  {
    playerId:   "LeChat930",
    clearTime:  "0:47.000",
    uploadTime: "2023-07-13",
    videoUrls:  ["https://www.youtube.com/watch?v=guWOtP89ZQU"],
    src:        "srdc",
    srId:       "ydjjv0qy",
  },
  {
    playerId:   "Chansey",
    clearTime:  "0:48.000",
    uploadTime: "2018-09-03",
    videoUrls:  ["https://www.youtube.com/watch?v=-qtNuVXw6KA"],
    src:        "srdc",
    srId:       "yl4q3grm",
  },
  {
    playerId:   "Ceejay",
    clearTime:  "0:48.000",
    uploadTime: "2018-09-05",
    videoUrls:  ["https://youtu.be/gSoQRfmSqxQ"],
    src:        "srdc",
    srId:       "y43r14nz",
  },
  {
    playerId:   "-VS-Silv0r",
    clearTime:  "0:50.000",
    uploadTime: "2018-10-27",
    videoUrls:  ["https://www.youtube.com/watch?v=CyracwVE9cY"],
    src:        "srdc",
    srId:       "y92vk7nz",
  },
  {
    playerId:   "Avate",
    clearTime:  "0:52.000",
    uploadTime: "2018-12-05",
    videoUrls:  ["https://youtu.be/cVsluHsbqWo"],
    src:        "srdc",
    srId:       "z51e92gm",
  },
  {
    playerId:   "SaikoStef",
    clearTime:  "0:56.000",
    uploadTime: "2023-07-07",
    videoUrls:  ["https://youtu.be/bataHvWD_s0"],
    src:        "srdc",
    srId:       "yvp887oy",
  },
  {
    playerId:   "Spacegirl",
    clearTime:  "1:25.000",
    uploadTime: "2018-09-03",
    videoUrls:  ["https://youtu.be/xe2kdQH9QuY"],
    src:        "srdc",
    srId:       "zp01ngrm",
  },
];