/* speedrun.com 原始抓取数据 — Capture Missions / Cassini / Solo */
/* level_id=29vlkqqw | 共 36 条 */
var capture_missions_cassini_soloRecords = [
  {
    playerId:   "Salat",
    clearTime:  "0:18.433",
    uploadTime: "2025-11-25",
    videoUrls:  ["https://youtu.be/cATuVBHQd84"],
    src:        "srdc",
    srId:       "yv5qn7em",
  },
  {
    playerId:   "L1ndell",
    clearTime:  "0:19.267",
    uploadTime: "2021-11-18",
    videoUrls:  ["https://youtu.be/n_TK1ViSP2w"],
    src:        "srdc",
    srId:       "z07ge68y",
  },
  {
    playerId:   "Mortar",
    clearTime:  "0:20.933",
    uploadTime: "2021-01-20",
    videoUrls:  ["https://www.youtube.com/watch?v=69DdM6vhXQs"],
    src:        "srdc",
    srId:       "yv2jq4xm",
  },
  {
    playerId:   "Kuremento",
    clearTime:  "0:24.000",
    uploadTime: "2021-04-20",
    videoUrls:  ["https://youtu.be/YJI3bPgCb0w"],
    src:        "srdc",
    srId:       "zp1lgexz",
  },
  {
    playerId:   "Febi",
    clearTime:  "0:25.000",
    uploadTime: "2021-03-27",
    videoUrls:  ["https://www.youtube.com/watch?v=SYAqazfQOq4"],
    src:        "srdc",
    srId:       "y42vl3dm",
  },
  {
    playerId:   "Txdo",
    clearTime:  "0:25.000",
    uploadTime: "2023-07-23",
    videoUrls:  ["https://www.youtube.com/watch?v=og1wtDnGoNs"],
    src:        "srdc",
    srId:       "mrlvx2dm",
  },
  {
    playerId:   "FrostMainer",
    clearTime:  "0:25.000",
    uploadTime: "2026-06-09",
    videoUrls:  ["https://www.youtube.com/watch?v=cBht9QzIUrw"],
    src:        "srdc",
    srId:       "y9gq10km",
  },
  {
    playerId:   "RoniPrime",
    clearTime:  "0:25.217",
    uploadTime: "2026-01-06",
    videoUrls:  ["https://youtu.be/ivkSirqBaGQ?si=BrfEIDPXaHgekND8"],
    src:        "srdc",
    srId:       "zg9odpvm",
  },
  {
    playerId:   "Yangoo",
    clearTime:  "0:27.000",
    uploadTime: "2023-04-18",
    videoUrls:  ["https://youtu.be/5p8FYi6jjCc"],
    src:        "srdc",
    srId:       "ylngo4nz",
  },
  {
    playerId:   "HL_Unknown",
    clearTime:  "0:27.000",
    uploadTime: "2024-03-13",
    videoUrls:  ["https://youtu.be/WOW5N_VNmHU?feature=shared"],
    src:        "srdc",
    srId:       "zglvnedm",
  },
  {
    playerId:   "zukerben",
    clearTime:  "0:28.000",
    uploadTime: "2019-11-29",
    videoUrls:  ["https://www.youtube.com/watch?v=V16-8yI0tmE"],
    src:        "srdc",
    srId:       "yw4ndgpz",
  },
  {
    playerId:   "Wasamii",
    clearTime:  "0:28.000",
    uploadTime: "2021-03-28",
    videoUrls:  ["https://youtu.be/n0hSplMyZLo"],
    src:        "srdc",
    srId:       "zno6xlly",
  },
  {
    playerId:   "Theotim",
    clearTime:  "0:28.000",
    uploadTime: "2023-04-29",
    videoUrls:  ["https://youtu.be/ZJoeDfl_YOA"],
    src:        "srdc",
    srId:       "m3q92vgy",
  },
  {
    playerId:   "agrub",
    clearTime:  "0:29.000",
    uploadTime: "2020-04-16",
    videoUrls:  ["https://youtu.be/rL9oc8PVSp0"],
    src:        "srdc",
    srId:       "y8219q5y",
  },
  {
    playerId:   "Andy.",
    clearTime:  "0:29.000",
    uploadTime: "2020-09-09",
    videoUrls:  ["https://www.youtube.com/watch?v=56dpeTinZ3E"],
    src:        "srdc",
    srId:       "z09w8e9z",
  },
  {
    playerId:   "RoboSt3alth",
    clearTime:  "0:29.000",
    uploadTime: "2021-03-04",
    videoUrls:  ["https://youtu.be/qWox7JKRdPk"],
    src:        "srdc",
    srId:       "yj1w373y",
  },
  {
    playerId:   "zxcMolniya",
    clearTime:  "0:29.000",
    uploadTime: "2021-07-26",
    videoUrls:  ["https://www.youtube.com/watch?v=APtOk9qinsE"],
    src:        "srdc",
    srId:       "mrnj60dy",
  },
  {
    playerId:   "Wakaaa",
    clearTime:  "0:29.000",
    uploadTime: "2024-03-12",
    videoUrls:  ["https://www.youtube.com/watch?v=0AW5essw2V4&ab_channel=Stupid_waka"],
    src:        "srdc",
    srId:       "y9j043vm",
  },
  {
    playerId:   "Double_Baconator",
    clearTime:  "0:31.000",
    uploadTime: "2022-08-16",
    videoUrls:  ["https://youtu.be/nDt-hmLDQ9s"],
    src:        "srdc",
    srId:       "z5x3j85y",
  },
  {
    playerId:   "Fr3zzco",
    clearTime:  "0:31.000",
    uploadTime: "2024-02-28",
    videoUrls:  ["https://youtu.be/e23VbcUv30Q"],
    src:        "srdc",
    srId:       "z0d3koey",
  },
  {
    playerId:   "-Rekken-",
    clearTime:  "0:33.000",
    uploadTime: "2018-08-16",
    videoUrls:  ["https://youtu.be/j9MqN85CLQI"],
    src:        "srdc",
    srId:       "y921wn2z",
  },
  {
    playerId:   "LeChat930",
    clearTime:  "0:33.000",
    uploadTime: "2023-07-10",
    videoUrls:  ["https://www.youtube.com/watch?v=cVFGjgcCWHE"],
    src:        "srdc",
    srId:       "zgee72jy",
  },
  {
    playerId:   "Chansey",
    clearTime:  "0:34.000",
    uploadTime: "2018-08-16",
    videoUrls:  ["https://www.youtube.com/watch?v=KGPFNTFaXlk"],
    src:        "srdc",
    srId:       "m7p5vd5m",
  },
  {
    playerId:   "-VS-Silv0r",
    clearTime:  "0:35.000",
    uploadTime: "2018-10-14",
    videoUrls:  ["https://www.youtube.com/watch?v=lRPNSlc-hEM"],
    src:        "srdc",
    srId:       "ywpj5d9z",
  },
  {
    playerId:   ".cat",
    clearTime:  "0:35.000",
    uploadTime: "2018-12-17",
    videoUrls:  ["https://www.youtube.com/watch?v=DyBJxPi96HA&feature=youtu.be"],
    src:        "srdc",
    srId:       "m3oq06dm",
  },
  {
    playerId:   "namenBARS",
    clearTime:  "0:36.000",
    uploadTime: "2018-08-16",
    videoUrls:  ["https://youtu.be/Yz8IsUrz43w"],
    src:        "srdc",
    srId:       "ywpd273z",
  },
  {
    playerId:   "QuasarWF",
    clearTime:  "0:37.000",
    uploadTime: "2018-08-15",
    videoUrls:  ["https://www.youtube.com/watch?v=mDydBXox7Cc&feature=youtu.be"],
    src:        "srdc",
    srId:       "yd3046qz",
  },
  {
    playerId:   "Avate",
    clearTime:  "0:38.000",
    uploadTime: "2018-12-06",
    videoUrls:  ["https://youtu.be/PA0mzyJK2EM"],
    src:        "srdc",
    srId:       "zq3j631y",
  },
  {
    playerId:   "SaikoStef",
    clearTime:  "0:39.000",
    uploadTime: "2023-07-07",
    videoUrls:  ["https://youtu.be/PUJlDTd-ex8"],
    src:        "srdc",
    srId:       "ywrvv23m",
  },
  {
    playerId:   "Sleigh",
    clearTime:  "0:49.000",
    uploadTime: "2021-05-20",
    videoUrls:  ["https://youtu.be/9R4hpMv0UBo"],
    src:        "srdc",
    srId:       "yo7rko1m",
  },
  {
    playerId:   "iamfumii",
    clearTime:  "0:52.000",
    uploadTime: "2020-12-12",
    videoUrls:  ["https://youtu.be/9v2duVlrQN8"],
    src:        "srdc",
    srId:       "mk81dw5m",
  },
  {
    playerId:   "BloodyMoonZPrime",
    clearTime:  "0:58.000",
    uploadTime: "2021-05-20",
    videoUrls:  ["https://youtu.be/5a0bHD__SiA"],
    src:        "srdc",
    srId:       "zxglkjgy",
  },
  {
    playerId:   "DisguisedKoala",
    clearTime:  "1:10.000",
    uploadTime: "2021-05-18",
    videoUrls:  ["https://youtu.be/WYsqTbRf9gg"],
    src:        "srdc",
    srId:       "y2x7r49m",
  },
  {
    playerId:   "1beer",
    clearTime:  "1:11.000",
    uploadTime: "2020-08-29",
    videoUrls:  ["https://youtu.be/PHvSvXLtOvs"],
    src:        "srdc",
    srId:       "zpr7nenm",
  },
  {
    playerId:   "VinterasBote",
    clearTime:  "1:15.000",
    uploadTime: "2020-06-10",
    videoUrls:  ["https://youtu.be/4x9XYcshqbM"],
    src:        "srdc",
    srId:       "yw83o42y",
  },
  {
    playerId:   "RbieTinn",
    clearTime:  "1:18.000",
    uploadTime: "2020-05-25",
    videoUrls:  ["https://www.youtube.com/watch?v=n2StA9giPRQ"],
    src:        "srdc",
    srId:       "mrkn7k2y",
  },
];