/* speedrun.com 原始抓取数据 — Capture Missions / Copernicus / Solo */
/* level_id=n93o4xz9 | 共 21 条 */
var capture_missions_copernicus_soloRecords = [
  {
    playerId:   "Salat",
    clearTime:  "0:15.850",
    uploadTime: "2026-03-11",
    videoUrls:  ["https://youtu.be/wJOgoRMloZ8"],
    src:        "srdc",
    srId:       "yjrlp27z",
  },
  {
    playerId:   "Mortar",
    clearTime:  "0:16.683",
    uploadTime: "2024-01-30",
    videoUrls:  ["https://www.youtube.com/watch?v=H5X23drfecE"],
    src:        "srdc",
    srId:       "m3k446qy",
  },
  {
    playerId:   "FXCloud",
    clearTime:  "0:16.856",
    uploadTime: "2025-11-25",
    videoUrls:  ["https://youtu.be/KAkLJWat4KA"],
    src:        "srdc",
    srId:       "zn57g07z",
  },
  {
    playerId:   "L1ndell",
    clearTime:  "0:19.000",
    uploadTime: "2022-01-09",
    videoUrls:  ["https://youtu.be/b8eKxagN2aQ"],
    src:        "srdc",
    srId:       "mr6njqdm",
  },
  {
    playerId:   "PrimedDarkeN",
    clearTime:  "0:20.000",
    uploadTime: "2020-09-29",
    videoUrls:  ["https://www.youtube.com/watch?v=OvzCeJFMFBU"],
    src:        "srdc",
    srId:       "z1ojp3jm",
  },
  {
    playerId:   "Boll",
    clearTime:  "0:22.000",
    uploadTime: "2020-09-28",
    videoUrls:  ["https://www.youtube.com/watch?v=RVTS2RwWguw&feature=youtu.be"],
    src:        "srdc",
    srId:       "zq4rg7xm",
  },
  {
    playerId:   "Wasamii",
    clearTime:  "0:24.000",
    uploadTime: "2021-09-29",
    videoUrls:  ["https://youtu.be/zZmC1GrIjJA"],
    src:        "srdc",
    srId:       "zp8wppxy",
  },
  {
    playerId:   "Andy.",
    clearTime:  "0:25.000",
    uploadTime: "2020-04-21",
    videoUrls:  ["https://www.youtube.com/watch?v=R8j3VeaVEiI"],
    src:        "srdc",
    srId:       "y905e7ey",
  },
  {
    playerId:   "zukerben",
    clearTime:  "0:26.000",
    uploadTime: "2019-05-16",
    videoUrls:  ["https://www.youtube.com/watch?v=EBFfr2GNpDk"],
    src:        "srdc",
    srId:       "y219qrjz",
  },
  {
    playerId:   "Wakaaa",
    clearTime:  "0:26.000",
    uploadTime: "2024-03-13",
    videoUrls:  ["https://www.youtube.com/watch?v=QYkEVToRNrM&ab_channel=Stupid_waka"],
    src:        "srdc",
    srId:       "y6v5k80m",
  },
  {
    playerId:   "Chansey",
    clearTime:  "0:27.000",
    uploadTime: "2019-01-30",
    videoUrls:  ["https://www.youtube.com/watch?v=bDxJ-wAVgiA"],
    src:        "srdc",
    srId:       "yd3lnp0z",
  },
  {
    playerId:   "-CheffDegu",
    clearTime:  "0:29.000",
    uploadTime: "2018-12-16",
    videoUrls:  ["https://youtu.be/kHYaHoNpsk8"],
    src:        "srdc",
    srId:       "yd3jjkwz",
  },
  {
    playerId:   "DivineSunder",
    clearTime:  "0:30.000",
    uploadTime: "2018-12-05",
    videoUrls:  ["https://www.youtube.com/watch?v=mdX1E_6OMEg"],
    src:        "srdc",
    srId:       "zg7e370z",
  },
  {
    playerId:   "AzZazell",
    clearTime:  "0:32.000",
    uploadTime: "2021-03-02",
    videoUrls:  ["https://youtu.be/Ytgbd4tHnzg"],
    src:        "srdc",
    srId:       "zqgdk78m",
  },
  {
    playerId:   "LeChat930",
    clearTime:  "0:32.000",
    uploadTime: "2023-07-13",
    videoUrls:  ["https://www.youtube.com/watch?v=MyqmyKRJGuw"],
    src:        "srdc",
    srId:       "yl66lk2y",
  },
  {
    playerId:   "DARK_BlackSun",
    clearTime:  "0:33.000",
    uploadTime: "2021-09-29",
    videoUrls:  ["https://youtu.be/tPKo-mVHIB0"],
    src:        "srdc",
    srId:       "zp8ww0ry",
  },
  {
    playerId:   "Nonqui",
    clearTime:  "0:34.000",
    uploadTime: "2018-12-01",
    videoUrls:  ["https://www.youtube.com/watch?v=A43b8bh7xJw&feature=youtu.be"],
    src:        "srdc",
    srId:       "yl4npqrm",
  },
  {
    playerId:   "Avate",
    clearTime:  "0:34.000",
    uploadTime: "2018-12-06",
    videoUrls:  ["https://youtu.be/sZqI4h9fZwk"],
    src:        "srdc",
    srId:       "yo2l1odz",
  },
  {
    playerId:   "Miyoki",
    clearTime:  "0:35.000",
    uploadTime: "2018-09-14",
    videoUrls:  ["https://youtu.be/doUHV4e7d1c"],
    src:        "srdc",
    srId:       "zg7gj6ez",
  },
  {
    playerId:   "Behem07h",
    clearTime:  "0:36.000",
    uploadTime: "2021-05-19",
    videoUrls:  ["https://youtu.be/RUZCbUHiNTM"],
    src:        "srdc",
    srId:       "me74rk0y",
  },
  {
    playerId:   "-VS-Silv0r",
    clearTime:  "0:40.000",
    uploadTime: "2018-10-26",
    videoUrls:  ["https://www.youtube.com/watch?v=HYd0RgqkmBk"],
    src:        "srdc",
    srId:       "z03pn8jz",
  },
];