/* speedrun.com 原始抓取数据 — Capture Missions / Elion / Co-op */
/* level_id=nwl3omrw | 共 10 条 */
var capture_missions_elion_coopRecords = [
  {
    playerId:   "Salat / lucasengenho / Mortar",
    clearTime:  "0:19.000",
    uploadTime: "2019-09-16",
    videoUrls:  ["https://www.youtube.com/watch?v=7Om3PQEnk6c"],
    src:        "srdc",
    srId:       "zp4292xz",
  },
  {
    playerId:   "Salat / L1ndell",
    clearTime:  "0:21.967",
    uploadTime: "2025-12-19",
    videoUrls:  ["https://youtu.be/iHQAV5g5URE"],
    src:        "srdc",
    srId:       "mr5l9k7y",
  },
  {
    playerId:   "PrimedDarkeN / Mortar",
    clearTime:  "0:26.733",
    uploadTime: "2020-11-03",
    videoUrls:  ["https://youtu.be/Nyw_Qy52p50?t=41"],
    src:        "srdc",
    srId:       "y2d7n06z",
  },
  {
    playerId:   ".cat / Nonqui",
    clearTime:  "0:28.000",
    uploadTime: "2019-06-30",
    videoUrls:  ["https://www.youtube.com/watch?v=87XRUz-sVHE&feature=youtu.be"],
    src:        "srdc",
    srId:       "znrrqrly",
  },
  {
    playerId:   "SuiEXE / RoboSt3alth",
    clearTime:  "0:33.367",
    uploadTime: "2021-03-04",
    videoUrls:  ["https://youtu.be/etuHCw4VHX4"],
    src:        "srdc",
    srId:       "y9nk5wvz",
  },
  {
    playerId:   "--Q--EValueAction / .cat",
    clearTime:  "0:35.000",
    uploadTime: "2018-12-20",
    videoUrls:  ["https://www.youtube.com/watch?v=QiBAJz7XB7o&feature=youtu.be"],
    src:        "srdc",
    srId:       "z03j2vjz",
  },
  {
    playerId:   "Maktoob / Seiso / LeChat930",
    clearTime:  "0:35.533",
    uploadTime: "2023-08-14",
    videoUrls:  ["https://www.youtube.com/watch?v=SXqs6A5P7bc"],
    src:        "srdc",
    srId:       "yl62k72y",
  },
  {
    playerId:   "Likhann_ / LeChat930",
    clearTime:  "0:48.000",
    uploadTime: "2023-07-20",
    videoUrls:  ["https://youtu.be/gdim2Znefu0"],
    src:        "srdc",
    srId:       "yvpxj46y",
  },
  {
    playerId:   "zopney / MunchkinMel",
    clearTime:  "1:05.000",
    uploadTime: "2018-12-11",
    videoUrls:  ["https://www.youtube.com/watch?v=nsTBW5ZbhH8"],
    src:        "srdc",
    srId:       "z11kkx7z",
  },
  {
    playerId:   "ShiftDelete / CreepingChamp",
    clearTime:  "1:08.000",
    uploadTime: "2020-08-20",
    videoUrls:  ["https://youtu.be/M05qBH1eQ28?list=PLOoCYdaYurpzssoavUuncOcivAmO4XJcr"],
    src:        "srdc",
    srId:       "zq466x8m",
  },
];