/* speedrun.com 原始抓取数据 — Capture Missions / Elion / Solo */
/* level_id=nwl3omrw | 共 19 条 */
var capture_missions_elion_soloRecords = [
  {
    playerId:   "Salat",
    clearTime:  "0:16.633",
    uploadTime: "2026-06-13",
    videoUrls:  ["https://youtu.be/RF5Jtfa_DYs"],
    src:        "srdc",
    srId:       "y9gr2enm",
  },
  {
    playerId:   "L1ndell",
    clearTime:  "0:19.467",
    uploadTime: "2023-01-08",
    videoUrls:  ["https://youtu.be/k4P4Ud3jBUM"],
    src:        "srdc",
    srId:       "mee9ee8m",
  },
  {
    playerId:   "Mortar",
    clearTime:  "0:20.833",
    uploadTime: "2020-09-28",
    videoUrls:  ["https://www.youtube.com/watch?v=WzNMzSCiYMU"],
    src:        "srdc",
    srId:       "m3g1roqz",
  },
  {
    playerId:   "YaroLynx",
    clearTime:  "0:26.000",
    uploadTime: "2023-04-09",
    videoUrls:  ["https://www.youtube.com/watch?v=W6ZyyWRag7E&ab_channel=YaroLynx"],
    src:        "srdc",
    srId:       "mroppvdm",
  },
  {
    playerId:   "--Q--DankNinja",
    clearTime:  "0:27.000",
    uploadTime: "2019-07-30",
    videoUrls:  ["https://www.youtube.com/watch?v=HuGwlL9LcWo"],
    src:        "srdc",
    srId:       "yd60p3xz",
  },
  {
    playerId:   "zukerben",
    clearTime:  "0:27.000",
    uploadTime: "2020-02-22",
    videoUrls:  ["https://www.youtube.com/watch?v=EmkXXlEEr1g"],
    src:        "srdc",
    srId:       "mex5xw0z",
  },
  {
    playerId:   "kucjlo_mojlo4hblu",
    clearTime:  "0:27.000",
    uploadTime: "2022-03-06",
    videoUrls:  ["https://youtu.be/Kn3UJ0kTV_Y"],
    src:        "srdc",
    srId:       "y8jnd51z",
  },
  {
    playerId:   "Wakaaa",
    clearTime:  "0:27.000",
    uploadTime: "2024-03-12",
    videoUrls:  ["https://www.youtube.com/watch?v=2yg0XWejqS8&ab_channel=Stupid_waka"],
    src:        "srdc",
    srId:       "y6v51wqm",
  },
  {
    playerId:   ".cat",
    clearTime:  "0:28.000",
    uploadTime: "2020-01-28",
    videoUrls:  ["https://www.youtube.com/watch?v=OsT-BryY86Y"],
    src:        "srdc",
    srId:       "z57wqqdm",
  },
  {
    playerId:   "Bombatack017",
    clearTime:  "0:29.000",
    uploadTime: "2024-03-12",
    videoUrls:  ["https://www.youtube.com/watch?v=RrGAFsBQwhc"],
    src:        "srdc",
    srId:       "y8w277wy",
  },
  {
    playerId:   "-VS-Silv0r",
    clearTime:  "0:30.000",
    uploadTime: "2018-10-27",
    videoUrls:  ["https://www.youtube.com/watch?v=eJ0RX4_6zlM"],
    src:        "srdc",
    srId:       "yo2pn81z",
  },
  {
    playerId:   "Chansey",
    clearTime:  "0:33.000",
    uploadTime: "2018-09-07",
    videoUrls:  ["https://www.youtube.com/watch?v=ob0Encm_bdo"],
    src:        "srdc",
    srId:       "zq31158y",
  },
  {
    playerId:   "Ceejay",
    clearTime:  "0:34.000",
    uploadTime: "2018-09-07",
    videoUrls:  ["https://youtu.be/2zFXA8JhqMo"],
    src:        "srdc",
    srId:       "y2qxxkjy",
  },
  {
    playerId:   "DivineSunder",
    clearTime:  "0:36.000",
    uploadTime: "2018-12-10",
    videoUrls:  ["https://www.youtube.com/watch?v=gqMZSzzmLpI"],
    src:        "srdc",
    srId:       "yl46od3m",
  },
  {
    playerId:   "LeChat930",
    clearTime:  "0:36.000",
    uploadTime: "2023-07-14",
    videoUrls:  ["https://www.youtube.com/watch?v=ERlMQChWDc8"],
    src:        "srdc",
    srId:       "mrllp02m",
  },
  {
    playerId:   "Nonqui",
    clearTime:  "0:37.000",
    uploadTime: "2018-12-01",
    videoUrls:  ["https://www.youtube.com/watch?v=O23l00AgTt0&feature=youtu.be"],
    src:        "srdc",
    srId:       "y890oe1m",
  },
  {
    playerId:   "Wiktoryk",
    clearTime:  "0:37.000",
    uploadTime: "2022-09-21",
    videoUrls:  ["https://www.youtube.com/watch?v=35BkPrBcTd4"],
    src:        "srdc",
    srId:       "yodn0w5m",
  },
  {
    playerId:   "Avate",
    clearTime:  "0:38.000",
    uploadTime: "2018-12-06",
    videoUrls:  ["https://youtu.be/JDOhWgDODHs"],
    src:        "srdc",
    srId:       "y8963x5m",
  },
  {
    playerId:   "red_ninja8",
    clearTime:  "0:57.000",
    uploadTime: "2018-08-30",
    videoUrls:  ["https://youtu.be/dsktW6N729g"],
    src:        "srdc",
    srId:       "y2qvnp6y",
  },
];