/* speedrun.com 原始抓取数据 — Capture Missions / Galatea / Co-op */
/* level_id=o9x47q1d | 共 12 条 */
var capture_missions_galatea_coopRecords = [
  {
    playerId:   "Salat / L1ndell",
    clearTime:  "0:19.050",
    uploadTime: "2026-01-04",
    videoUrls:  ["https://www.youtube.com/watch?v=FCXXcgV-eEY", "https://youtu.be/DnDBsoXAqbM"],
    src:        "srdc",
    srId:       "y40l92dz",
  },
  {
    playerId:   "PrimedDarkeN / Akula",
    clearTime:  "0:19.400",
    uploadTime: "2022-11-15",
    videoUrls:  ["https://www.youtube.com/watch?v=sXdBaNgxiMc"],
    src:        "srdc",
    srId:       "yw69013m",
  },
  {
    playerId:   "Salat / Mortar",
    clearTime:  "0:22.000",
    uploadTime: "2019-09-17",
    videoUrls:  ["https://www.youtube.com/watch?v=szmj4RMety0"],
    src:        "srdc",
    srId:       "mk2edolm",
  },
  {
    playerId:   "Salat / Mortar",
    clearTime:  "0:22.000",
    uploadTime: "2019-09-17",
    videoUrls:  ["https://www.youtube.com/watch?v=o4Iy58kyeoY"],
    src:        "srdc",
    srId:       "z01ol8oy",
  },
  {
    playerId:   "L1ndell / K1nky",
    clearTime:  "0:22.750",
    uploadTime: "2022-01-16",
    videoUrls:  ["https://youtu.be/L6kXyQdzq78"],
    src:        "srdc",
    srId:       "y200j1jm",
  },
  {
    playerId:   ".cat / Nonqui",
    clearTime:  "0:23.000",
    uploadTime: "2019-06-29",
    videoUrls:  ["https://www.youtube.com/watch?v=VNIO61RvVeg"],
    src:        "srdc",
    srId:       "yj33pg3z",
  },
  {
    playerId:   "PrimedDarkeN / Mortar",
    clearTime:  "0:26.417",
    uploadTime: "2020-11-03",
    videoUrls:  ["https://youtu.be/Nyw_Qy52p50?t=176"],
    src:        "srdc",
    srId:       "y8reoj5m",
  },
  {
    playerId:   ".cat / Nonqui",
    clearTime:  "0:28.000",
    uploadTime: "2019-06-19",
    videoUrls:  ["https://www.youtube.com/watch?v=aU-b1jQEaNo&feature=youtu.be"],
    src:        "srdc",
    srId:       "y952jorz",
  },
  {
    playerId:   "ThatBlue / -Rekken-",
    clearTime:  "0:31.000",
    uploadTime: "2018-08-14",
    videoUrls:  ["https://youtu.be/LpftBNDVpR0"],
    src:        "srdc",
    srId:       "y2qdwn9y",
  },
  {
    playerId:   "-Falco- / -Vergilius-",
    clearTime:  "0:34.000",
    uploadTime: "2019-06-19",
    videoUrls:  ["https://youtu.be/riOFop29-5w"],
    src:        "srdc",
    srId:       "y21qk45z",
  },
  {
    playerId:   "ShiftDelete / CreepingChamp",
    clearTime:  "0:55.000",
    uploadTime: "2020-08-20",
    videoUrls:  ["https://youtu.be/OmCMJDjNeew?list=PLOoCYdaYurpzssoavUuncOcivAmO4XJcr"],
    src:        "srdc",
    srId:       "y2d33lwz",
  },
  {
    playerId:   "zopney / MunchkinMel",
    clearTime:  "1:08.000",
    uploadTime: "2018-12-11",
    videoUrls:  ["https://www.youtube.com/watch?v=-lOa67-ufMo"],
    src:        "srdc",
    srId:       "zg788rez",
  },
];