/* speedrun.com 原始抓取数据 — Capture Missions / Galatea / Solo */
/* level_id=o9x47q1d | 共 32 条 */
var capture_missions_galatea_soloRecords = [
  {
    playerId:   "Salat",
    clearTime:  "0:16.866",
    uploadTime: "2025-12-24",
    videoUrls:  ["https://youtu.be/pvPF-OLcwXo"],
    src:        "srdc",
    srId:       "yo5o941z",
  },
  {
    playerId:   "L1ndell",
    clearTime:  "0:19.917",
    uploadTime: "2022-03-09",
    videoUrls:  ["https://youtu.be/h0H8RF9O-Qw"],
    src:        "srdc",
    srId:       "ywj5o92z",
  },
  {
    playerId:   "Mortar",
    clearTime:  "0:19.933",
    uploadTime: "2021-01-25",
    videoUrls:  ["https://www.youtube.com/watch?v=R_2L-eWMPeE"],
    src:        "srdc",
    srId:       "yw04532m",
  },
  {
    playerId:   "zukerben",
    clearTime:  "0:25.000",
    uploadTime: "2019-06-30",
    videoUrls:  ["https://www.youtube.com/watch?v=mHl3u1IzPvg"],
    src:        "srdc",
    srId:       "yd66g2jz",
  },
  {
    playerId:   "Salat",
    clearTime:  "0:25.000",
    uploadTime: "2019-09-18",
    videoUrls:  ["https://www.youtube.com/watch?v=QWca8HXZCS0"],
    src:        "srdc",
    srId:       "z01oj54y",
  },
  {
    playerId:   "zukerben",
    clearTime:  "0:26.000",
    uploadTime: "2019-06-30",
    videoUrls:  ["https://www.youtube.com/watch?v=TPJuW5riMBw"],
    src:        "srdc",
    srId:       "y95568kz",
  },
  {
    playerId:   "--taterD--",
    clearTime:  "0:26.000",
    uploadTime: "2019-08-16",
    videoUrls:  ["https://youtu.be/6KDa0_vh9jY"],
    src:        "srdc",
    srId:       "zp413wvz",
  },
  {
    playerId:   "Nonqui",
    clearTime:  "0:27.000",
    uploadTime: "2019-06-27",
    videoUrls:  ["https://www.youtube.com/watch?v=DnSrCL2wtqQ&feature=youtu.be"],
    src:        "srdc",
    srId:       "yj331pdz",
  },
  {
    playerId:   "Theotim",
    clearTime:  "0:27.000",
    uploadTime: "2023-04-29",
    videoUrls:  ["https://youtu.be/FHuJjv0m0IY"],
    src:        "srdc",
    srId:       "yonv5q5z",
  },
  {
    playerId:   "-Vergilius-",
    clearTime:  "0:28.000",
    uploadTime: "2019-06-21",
    videoUrls:  ["https://youtu.be/LW6ek-v52Wk"],
    src:        "srdc",
    srId:       "yl0450xy",
  },
  {
    playerId:   ".cat",
    clearTime:  "0:28.000",
    uploadTime: "2019-06-30",
    videoUrls:  ["https://www.youtube.com/watch?v=OzseHps-ipA&feature=youtu.be"],
    src:        "srdc",
    srId:       "zxkk775m",
  },
  {
    playerId:   "kucjlo_mojlo4hblu",
    clearTime:  "0:28.000",
    uploadTime: "2021-06-13",
    videoUrls:  ["https://youtu.be/_J2nsNzud2k"],
    src:        "srdc",
    srId:       "z5rk375y",
  },
  {
    playerId:   "-Rekken-",
    clearTime:  "0:29.000",
    uploadTime: "2018-08-16",
    videoUrls:  ["https://youtu.be/mH69F1S7h1w"],
    src:        "srdc",
    srId:       "zg7v9v0z",
  },
  {
    playerId:   "ThatBlue",
    clearTime:  "0:29.000",
    uploadTime: "2018-08-25",
    videoUrls:  ["https://youtu.be/hBMOAIdDYEo"],
    src:        "srdc",
    srId:       "m7p8650m",
  },
  {
    playerId:   "RoboSt3alth",
    clearTime:  "0:29.000",
    uploadTime: "2021-03-04",
    videoUrls:  ["https://youtu.be/HQQvMKfDrYk"],
    src:        "srdc",
    srId:       "z18kj7gy",
  },
  {
    playerId:   "DivineSunder",
    clearTime:  "0:31.000",
    uploadTime: "2018-12-08",
    videoUrls:  ["https://www.youtube.com/watch?v=zk-ZZ4eqn0E"],
    src:        "srdc",
    srId:       "y43ow53z",
  },
  {
    playerId:   "-slarega-",
    clearTime:  "0:31.000",
    uploadTime: "2020-05-17",
    videoUrls:  ["https://www.youtube.com/watch?v=RkST-av5KcI&feature=youtu.be"],
    src:        "srdc",
    srId:       "znk1o6lz",
  },
  {
    playerId:   "namenBARS",
    clearTime:  "0:32.000",
    uploadTime: "2018-08-15",
    videoUrls:  ["https://youtu.be/lYrDPbr7LhE"],
    src:        "srdc",
    srId:       "y6prgw6m",
  },
  {
    playerId:   "zukerben",
    clearTime:  "0:32.000",
    uploadTime: "2019-05-17",
    videoUrls:  ["https://www.youtube.com/watch?v=yu36Z9m7awI"],
    src:        "srdc",
    srId:       "mk2l3olm",
  },
  {
    playerId:   "Chansey",
    clearTime:  "0:34.000",
    uploadTime: "2018-08-16",
    videoUrls:  ["https://www.youtube.com/watch?v=KtqiHCdCd6w"],
    src:        "srdc",
    srId:       "y43e012z",
  },
  {
    playerId:   "Miyoki",
    clearTime:  "0:34.000",
    uploadTime: "2018-09-23",
    videoUrls:  ["https://youtu.be/n4uEqM1mCas"],
    src:        "srdc",
    srId:       "y89ej7nm",
  },
  {
    playerId:   "Avate",
    clearTime:  "0:34.000",
    uploadTime: "2018-12-07",
    videoUrls:  ["https://youtu.be/M7MF5-hVOH0"],
    src:        "srdc",
    srId:       "zp0wq4nm",
  },
  {
    playerId:   "Nonqui",
    clearTime:  "0:35.000",
    uploadTime: "2018-12-01",
    videoUrls:  ["https://www.youtube.com/watch?v=-CZYuUk3Y00&feature=youtu.be"],
    src:        "srdc",
    srId:       "yl4nperm",
  },
  {
    playerId:   "LeChat930",
    clearTime:  "0:35.000",
    uploadTime: "2023-07-24",
    videoUrls:  ["https://www.youtube.com/watch?v=Vl6TEVxyx7Q"],
    src:        "srdc",
    srId:       "m70n4vey",
  },
  {
    playerId:   "joshwaaaa_",
    clearTime:  "0:38.000",
    uploadTime: "2018-10-09",
    videoUrls:  ["https://youtu.be/VqhvX3OUAhA"],
    src:        "srdc",
    srId:       "zp02gwvm",
  },
  {
    playerId:   "-VS-Silv0r",
    clearTime:  "0:38.000",
    uploadTime: "2018-10-27",
    videoUrls:  ["https://www.youtube.com/watch?v=SNE0LCrswC0"],
    src:        "srdc",
    srId:       "y6p02kjm",
  },
  {
    playerId:   "SaikoStef",
    clearTime:  "0:38.000",
    uploadTime: "2023-07-07",
    videoUrls:  ["https://youtu.be/GGdlDZL_KZw"],
    src:        "srdc",
    srId:       "zge226ey",
  },
  {
    playerId:   "DivineSunder",
    clearTime:  "0:39.000",
    uploadTime: "2018-09-21",
    videoUrls:  ["https://www.youtube.com/watch?v=xWu5MLyXbp4"],
    src:        "srdc",
    srId:       "y6p962qm",
  },
  {
    playerId:   "Avate",
    clearTime:  "0:39.000",
    uploadTime: "2018-12-06",
    videoUrls:  ["https://youtu.be/YPYcRGuE3Tc"],
    src:        "srdc",
    srId:       "mk90l0vz",
  },
  {
    playerId:   "Chansey",
    clearTime:  "0:43.000",
    uploadTime: "2018-09-19",
    videoUrls:  ["https://www.youtube.com/watch?v=PXkclDs419w"],
    src:        "srdc",
    srId:       "yl4r09nm",
  },
  {
    playerId:   "zopney",
    clearTime:  "0:51.000",
    uploadTime: "2018-08-13",
    videoUrls:  ["https://youtu.be/JANPdknXrKk"],
    src:        "srdc",
    srId:       "ywpdxg0z",
  },
  {
    playerId:   "naomidesuuu",
    clearTime:  "1:20.000",
    uploadTime: "2019-06-26",
    videoUrls:  ["https://vimeo.com/344559430"],
    src:        "srdc",
    srId:       "y6ll520y",
  },
];