/* speedrun.com 原始抓取数据 — Capture Missions / Horend / Solo */
/* level_id=z98n7op9 | 共 21 条 */
var capture_missions_horend_soloRecords = [
  {
    playerId:   "Salat",
    clearTime:  "0:12.800",
    uploadTime: "2025-06-08",
    videoUrls:  ["https://youtu.be/crHFAYH4PeY"],
    src:        "srdc",
    srId:       "m7ld3d4y",
  },
  {
    playerId:   "Mortar",
    clearTime:  "0:13.733",
    uploadTime: "2021-03-04",
    videoUrls:  ["https://www.youtube.com/watch?v=BVBnOdcvaXk"],
    src:        "srdc",
    srId:       "z50krvjy",
  },
  {
    playerId:   "L1ndell",
    clearTime:  "0:16.050",
    uploadTime: "2022-01-18",
    videoUrls:  ["https://youtu.be/iQ0otnZgdC4"],
    src:        "srdc",
    srId:       "ywjjll0z",
  },
  {
    playerId:   "Febi",
    clearTime:  "0:16.100",
    uploadTime: "2021-03-22",
    videoUrls:  ["https://www.youtube.com/watch?v=yoONOOJ4Bio"],
    src:        "srdc",
    srId:       "y9nw502z",
  },
  {
    playerId:   "DivineSunder",
    clearTime:  "0:20.000",
    uploadTime: "2018-12-06",
    videoUrls:  ["https://www.youtube.com/watch?v=3k0rXaTPP4k"],
    src:        "srdc",
    srId:       "yl46942m",
  },
  {
    playerId:   "zukerben",
    clearTime:  "0:20.000",
    uploadTime: "2019-06-14",
    videoUrls:  ["https://www.youtube.com/watch?v=Dsl0K4WyoYg"],
    src:        "srdc",
    srId:       "mk2973vm",
  },
  {
    playerId:   "pixdie",
    clearTime:  "0:20.000",
    uploadTime: "2024-03-13",
    videoUrls:  ["https://www.youtube.com/watch?v=ALZ9l9tOo1o"],
    src:        "srdc",
    srId:       "y46wp42z",
  },
  {
    playerId:   "LiAXiM",
    clearTime:  "0:21.000",
    uploadTime: "2021-11-08",
    videoUrls:  ["https://youtu.be/jPGvA76fyHQ"],
    src:        "srdc",
    srId:       "me4d73qy",
  },
  {
    playerId:   "-VS-Silv0r",
    clearTime:  "0:23.000",
    uploadTime: "2018-10-13",
    videoUrls:  ["https://www.youtube.com/watch?v=4uq9UaKmks0"],
    src:        "srdc",
    srId:       "zp02okxm",
  },
  {
    playerId:   "Wakaaa",
    clearTime:  "0:23.000",
    uploadTime: "2024-03-14",
    videoUrls:  ["https://www.youtube.com/watch?v=3d3mbfUtbes&ab_channel=Stupid_waka"],
    src:        "srdc",
    srId:       "yo03kv5y",
  },
  {
    playerId:   "Chansey",
    clearTime:  "0:24.000",
    uploadTime: "2018-08-28",
    videoUrls:  ["https://www.youtube.com/watch?v=IN0flfA_9PQ"],
    src:        "srdc",
    srId:       "mr842n2y",
  },
  {
    playerId:   "LeChat930",
    clearTime:  "0:24.000",
    uploadTime: "2023-06-07",
    videoUrls:  ["https://www.youtube.com/watch?v=zLxOJLxYcJ4"],
    src:        "srdc",
    srId:       "yon91vjz",
  },
  {
    playerId:   "joshwaaaa_",
    clearTime:  "0:25.000",
    uploadTime: "2018-08-27",
    videoUrls:  ["https://www.youtube.com/watch?v=UguY5vghb48"],
    src:        "srdc",
    srId:       "yl4o61rm",
  },
  {
    playerId:   "RoboSt3alth",
    clearTime:  "0:25.000",
    uploadTime: "2021-03-04",
    videoUrls:  ["https://youtu.be/8JndAj7OV0g"],
    src:        "srdc",
    srId:       "m783qv0z",
  },
  {
    playerId:   "ShadowDrache",
    clearTime:  "0:27.000",
    uploadTime: "2024-01-20",
    videoUrls:  ["https://youtu.be/UhuD20GKftI&t=41"],
    src:        "srdc",
    srId:       "y6q8ke1z",
  },
  {
    playerId:   "Avate",
    clearTime:  "0:29.000",
    uploadTime: "2018-12-06",
    videoUrls:  ["https://youtu.be/H_okKDE593g"],
    src:        "srdc",
    srId:       "m3oqdogm",
  },
  {
    playerId:   "Dorpax",
    clearTime:  "0:29.000",
    uploadTime: "2021-01-11",
    videoUrls:  ["https://www.twitch.tv/dorpax/clip/RamshackleHotTarsierDoggo?filter=clips&range=30d&sort=time"],
    src:        "srdc",
    srId:       "y8v381xz",
  },
  {
    playerId:   "QuasarWF",
    clearTime:  "0:30.000",
    uploadTime: "2018-08-27",
    videoUrls:  ["https://youtu.be/Yvr6T5TQ0kI"],
    src:        "srdc",
    srId:       "y89v6x1m",
  },
  {
    playerId:   "Ceejay",
    clearTime:  "0:33.000",
    uploadTime: "2018-08-27",
    videoUrls:  ["https://youtu.be/NzLWvdGqYUU"],
    src:        "srdc",
    srId:       "zp03w9gm",
  },
  {
    playerId:   "iamfumii",
    clearTime:  "0:39.000",
    uploadTime: "2020-12-13",
    videoUrls:  ["https://www.youtube.com/watch?v=BXn7Wef0aWc&feature=youtu.be"],
    src:        "srdc",
    srId:       "m3gj06dz",
  },
  {
    playerId:   "zopney",
    clearTime:  "0:42.000",
    uploadTime: "2018-08-25",
    videoUrls:  ["https://www.youtube.com/watch?v=yiSsabBcP0c"],
    src:        "srdc",
    srId:       "yo29d4jz",
  },
];