/* speedrun.com 原始抓取数据 — Capture Missions / Hydra / Solo */
/* level_id=ywel5vr9 | 共 29 条 */
var capture_missions_hydra_soloRecords = [
  {
    playerId:   "Salat",
    clearTime:  "0:17.883",
    uploadTime: "2025-10-28",
    videoUrls:  ["https://youtu.be/Y9waylBru3M"],
    src:        "srdc",
    srId:       "mep62g2y",
  },
  {
    playerId:   "L1ndell",
    clearTime:  "0:17.967",
    uploadTime: "2023-01-23",
    videoUrls:  ["https://youtu.be/AZ0iIG8kQ5s"],
    src:        "srdc",
    srId:       "z1q2d1gy",
  },
  {
    playerId:   "PrimedDarkeN",
    clearTime:  "0:19.167",
    uploadTime: "2021-07-06",
    videoUrls:  ["https://www.youtube.com/watch?v=Mm8qwI_VDpI"],
    src:        "srdc",
    srId:       "y2x6v0wm",
  },
  {
    playerId:   "Mortar",
    clearTime:  "0:21.000",
    uploadTime: "2019-10-20",
    videoUrls:  ["https://www.youtube.com/watch?v=af24MUTkVvE"],
    src:        "srdc",
    srId:       "z01ln28y",
  },
  {
    playerId:   "Mortar",
    clearTime:  "0:21.000",
    uploadTime: "2021-02-08",
    videoUrls:  ["https://www.youtube.com/watch?v=ZxGl_024SMY"],
    src:        "srdc",
    srId:       "yo978j5y",
  },
  {
    playerId:   "Salat",
    clearTime:  "0:23.000",
    uploadTime: "2019-11-17",
    videoUrls:  ["https://youtu.be/roqdKXaR4uM"],
    src:        "srdc",
    srId:       "yj3288oz",
  },
  {
    playerId:   "Kuremento",
    clearTime:  "0:23.000",
    uploadTime: "2021-04-20",
    videoUrls:  ["https://youtu.be/_Mvwg85JjM8"],
    src:        "srdc",
    srId:       "mkg8vnxy",
  },
  {
    playerId:   "RoniPrime",
    clearTime:  "0:23.000",
    uploadTime: "2026-01-12",
    videoUrls:  ["https://youtu.be/drwaTcAmJXw"],
    src:        "srdc",
    srId:       "y40j8qnz",
  },
  {
    playerId:   "Febi",
    clearTime:  "0:24.000",
    uploadTime: "2021-04-10",
    videoUrls:  ["https://www.youtube.com/watch?v=k0Wcwc-BeRY"],
    src:        "srdc",
    srId:       "yv143voy",
  },
  {
    playerId:   "Yangoo",
    clearTime:  "0:24.000",
    uploadTime: "2023-04-19",
    videoUrls:  ["https://youtu.be/PMPv46hKXUo"],
    src:        "srdc",
    srId:       "y805jexm",
  },
  {
    playerId:   "zukerben",
    clearTime:  "0:25.000",
    uploadTime: "2019-11-29",
    videoUrls:  ["https://www.youtube.com/watch?v=LmxA3KN-P40"],
    src:        "srdc",
    srId:       "yj3w6q3z",
  },
  {
    playerId:   "Wambo",
    clearTime:  "0:25.000",
    uploadTime: "2020-06-21",
    videoUrls:  ["https://www.youtube.com/watch?v=NwYLNdAtc2U"],
    src:        "srdc",
    srId:       "y820dxwy",
  },
  {
    playerId:   "zxcMolniya",
    clearTime:  "0:25.000",
    uploadTime: "2021-07-24",
    videoUrls:  ["https://www.youtube.com/watch?v=w1SXSP8Pnlk"],
    src:        "srdc",
    srId:       "zq1xl9rm",
  },
  {
    playerId:   "Wasamii",
    clearTime:  "0:25.000",
    uploadTime: "2022-07-02",
    videoUrls:  ["https://youtu.be/qHPdnVqDxYQ"],
    src:        "srdc",
    srId:       "m76e639y",
  },
  {
    playerId:   "FXCloud",
    clearTime:  "0:26.000",
    uploadTime: "2019-09-17",
    videoUrls:  ["https://youtu.be/Sfoe6GBiQ1M"],
    src:        "srdc",
    srId:       "yv3q016z",
  },
  {
    playerId:   "Threezeeh_",
    clearTime:  "0:26.000",
    uploadTime: "2019-10-26",
    videoUrls:  ["https://www.youtube.com/watch?v=6Fl88621-3c&feature=youtu.be"],
    src:        "srdc",
    srId:       "m7qx4oez",
  },
  {
    playerId:   "Toriac",
    clearTime:  "0:26.000",
    uploadTime: "2020-06-27",
    videoUrls:  ["https://www.youtube.com/watch?v=XiVziTkpuD4"],
    src:        "srdc",
    srId:       "zgwevxjy",
  },
  {
    playerId:   "-Rekken-",
    clearTime:  "0:28.000",
    uploadTime: "2018-09-08",
    videoUrls:  ["https://youtu.be/Uo8he1pdt_A"],
    src:        "srdc",
    srId:       "y89djedm",
  },
  {
    playerId:   "-slarega-",
    clearTime:  "0:28.000",
    uploadTime: "2020-05-24",
    videoUrls:  ["https://www.youtube.com/watch?v=jeRRSaWjEo0"],
    src:        "srdc",
    srId:       "m7g7510m",
  },
  {
    playerId:   "zukerben",
    clearTime:  "0:28.000",
    uploadTime: "2020-06-17",
    videoUrls:  ["https://www.youtube.com/watch?v=ABVphPZVCPw"],
    src:        "srdc",
    srId:       "yv60k7oz",
  },
  {
    playerId:   "RoboSt3alth",
    clearTime:  "0:29.000",
    uploadTime: "2021-03-04",
    videoUrls:  ["https://youtu.be/fY5yie5uhWY"],
    src:        "srdc",
    srId:       "z50k76gy",
  },
  {
    playerId:   "Chansey",
    clearTime:  "0:30.000",
    uploadTime: "2018-09-08",
    videoUrls:  ["https://www.youtube.com/watch?v=zuS_TE8Z8D8"],
    src:        "srdc",
    srId:       "zg7grkdz",
  },
  {
    playerId:   "DivineSunder",
    clearTime:  "0:30.000",
    uploadTime: "2018-12-08",
    videoUrls:  ["https://www.youtube.com/watch?v=xdifTQiERJk"],
    src:        "srdc",
    srId:       "mk902k5z",
  },
  {
    playerId:   ".cat",
    clearTime:  "0:30.000",
    uploadTime: "2018-12-15",
    videoUrls:  ["https://www.youtube.com/watch?v=g4hIxt2TpAY&feature=youtu.be"],
    src:        "srdc",
    srId:       "mr8log2y",
  },
  {
    playerId:   "LuxeWF",
    clearTime:  "0:30.000",
    uploadTime: "2021-01-22",
    videoUrls:  ["https://www.youtube.com/watch?v=KEuE7ynzBrc&ab_channel=hi"],
    src:        "srdc",
    srId:       "zx6454ez",
  },
  {
    playerId:   "Ceejay",
    clearTime:  "0:32.000",
    uploadTime: "2018-09-01",
    videoUrls:  ["https://www.youtube.com/watch?v=VzsO0lncBDE&feature=youtu.be"],
    src:        "srdc",
    srId:       "zq3gor1y",
  },
  {
    playerId:   "Nonqui",
    clearTime:  "0:32.000",
    uploadTime: "2018-12-01",
    videoUrls:  ["https://www.youtube.com/watch?v=bj_uabXV7WE&feature=youtu.be"],
    src:        "srdc",
    srId:       "yl4np1nm",
  },
  {
    playerId:   "Avate",
    clearTime:  "0:32.000",
    uploadTime: "2018-12-06",
    videoUrls:  ["https://youtu.be/0PpeeLUaVtk"],
    src:        "srdc",
    srId:       "y2qg929y",
  },
  {
    playerId:   "LeChat930",
    clearTime:  "0:33.000",
    uploadTime: "2023-07-13",
    videoUrls:  ["https://www.youtube.com/watch?v=vffWREii6Gw"],
    src:        "srdc",
    srId:       "zqjj298m",
  },
];