/* speedrun.com 原始抓取数据 — Capture Missions / Isos / Solo */
/* level_id=rdnnzm7d | 共 18 条 */
var capture_missions_isos_soloRecords = [
  {
    playerId:   "Salat",
    clearTime:  "0:20.517",
    uploadTime: "2026-06-09",
    videoUrls:  ["https://youtu.be/_c9DC9nPnig"],
    src:        "srdc",
    srId:       "mkxn7x3z",
  },
  {
    playerId:   "Hera4v",
    clearTime:  "0:20.517",
    uploadTime: "2026-07-03",
    videoUrls:  ["https://www.youtube.com/watch?v=g7FnYl3mhmo"],
    src:        "srdc",
    srId:       "znl8ee7y",
  },
  {
    playerId:   "Mortar",
    clearTime:  "0:21.733",
    uploadTime: "2021-03-07",
    videoUrls:  ["https://www.youtube.com/watch?v=MjdROzRLVfA"],
    src:        "srdc",
    srId:       "zqg8r79m",
  },
  {
    playerId:   "L1ndell",
    clearTime:  "0:25.033",
    uploadTime: "2021-11-07",
    videoUrls:  ["https://youtu.be/3jX2ZH2EL44"],
    src:        "srdc",
    srId:       "y47v152y",
  },
  {
    playerId:   "Andy.",
    clearTime:  "0:27.417",
    uploadTime: "2020-02-26",
    videoUrls:  ["https://www.youtube.com/watch?v=MZBpFLk6q50&feature=youtu.be"],
    src:        "srdc",
    srId:       "zxkrn55m",
  },
  {
    playerId:   "silverdk",
    clearTime:  "0:27.933",
    uploadTime: "2019-09-10",
    videoUrls:  ["https://youtu.be/CBZXWQKB_6o"],
    src:        "srdc",
    srId:       "m316936z",
  },
  {
    playerId:   "zukerben",
    clearTime:  "0:30.000",
    uploadTime: "2019-07-09",
    videoUrls:  ["https://www.youtube.com/watch?v=Ovsux0onISk"],
    src:        "srdc",
    srId:       "y41we9ny",
  },
  {
    playerId:   "RoboSt3alth",
    clearTime:  "0:33.000",
    uploadTime: "2021-03-04",
    videoUrls:  ["https://youtu.be/sN1j1A81mGo"],
    src:        "srdc",
    srId:       "y2vk1r6z",
  },
  {
    playerId:   "Nonqui",
    clearTime:  "0:35.000",
    uploadTime: "2018-12-01",
    videoUrls:  ["https://www.youtube.com/watch?v=ZSU5-SttNNs&feature=youtu.be"],
    src:        "srdc",
    srId:       "zn4j9j7m",
  },
  {
    playerId:   "DivineSunder",
    clearTime:  "0:35.000",
    uploadTime: "2018-12-10",
    videoUrls:  ["https://www.youtube.com/watch?v=6L24OJh9gsA"],
    src:        "srdc",
    srId:       "ywpr0j2z",
  },
  {
    playerId:   "LeChat930",
    clearTime:  "0:38.000",
    uploadTime: "2023-07-18",
    videoUrls:  ["https://www.youtube.com/watch?v=1cVDtcaE6ck"],
    src:        "srdc",
    srId:       "mk0qw4lz",
  },
  {
    playerId:   "joshwaaaa_",
    clearTime:  "0:39.000",
    uploadTime: "2018-10-21",
    videoUrls:  ["https://youtu.be/vgh3M-gb45g"],
    src:        "srdc",
    srId:       "yvjr9joy",
  },
  {
    playerId:   "LectoRR",
    clearTime:  "0:39.000",
    uploadTime: "2018-11-26",
    videoUrls:  ["https://www.youtube.com/watch?v=3Qf8bNuLUgM"],
    src:        "srdc",
    srId:       "y2qjp8wy",
  },
  {
    playerId:   "Ceejay",
    clearTime:  "0:41.000",
    uploadTime: "2018-11-29",
    videoUrls:  ["https://youtu.be/4ESOkYQDCR0"],
    src:        "srdc",
    srId:       "me8e058m",
  },
  {
    playerId:   "Avate",
    clearTime:  "0:41.000",
    uploadTime: "2018-12-06",
    videoUrls:  ["https://youtu.be/klLMGcaH0pY"],
    src:        "srdc",
    srId:       "zg7e3odz",
  },
  {
    playerId:   "-VS-Silv0r",
    clearTime:  "0:42.000",
    uploadTime: "2018-10-14",
    videoUrls:  ["https://www.youtube.com/watch?v=VF1IrxjKtUs"],
    src:        "srdc",
    srId:       "m7pwvgwm",
  },
  {
    playerId:   "RoxVort",
    clearTime:  "0:49.000",
    uploadTime: "2018-10-14",
    videoUrls:  ["https://youtu.be/4CJCVCGlRnE"],
    src:        "srdc",
    srId:       "zp02v28m",
  },
  {
    playerId:   "walkman23",
    clearTime:  "0:50.000",
    uploadTime: "2018-09-23",
    videoUrls:  ["https://www.youtube.com/watch?v=pexoW2_xe0A"],
    src:        "srdc",
    srId:       "m7p76w4m",
  },
];