/* speedrun.com 原始抓取数据 — Capture Missions / Lex / Solo */
/* level_id=ldy2grrw | 共 24 条 */
var capture_missions_lex_soloRecords = [
  {
    playerId:   "Salat",
    clearTime:  "0:11.467",
    uploadTime: "2026-02-15",
    videoUrls:  ["https://youtu.be/Hsj9pY5h_UY"],
    src:        "srdc",
    srId:       "yj7nv5ny",
  },
  {
    playerId:   "Mortar",
    clearTime:  "0:12.367",
    uploadTime: "2024-04-04",
    videoUrls:  ["https://www.youtube.com/watch?v=5TpqORNKBDs"],
    src:        "srdc",
    srId:       "zpo1x6nm",
  },
  {
    playerId:   "Endryx_Ow",
    clearTime:  "0:12.496",
    uploadTime: "2025-06-08",
    videoUrls:  ["https://youtu.be/j_diyucA9e4?si=sIj5Eysr59zqhpQ6"],
    src:        "srdc",
    srId:       "zpo1ddnm",
  },
  {
    playerId:   "Febi",
    clearTime:  "0:19.000",
    uploadTime: "2021-07-15",
    videoUrls:  ["https://www.youtube.com/watch?v=Gcv_j0NXVM4"],
    src:        "srdc",
    srId:       "mr1g13gz",
  },
  {
    playerId:   "RoniPrime",
    clearTime:  "0:21.033",
    uploadTime: "2026-01-04",
    videoUrls:  ["https://youtu.be/23uEciU3uR4"],
    src:        "srdc",
    srId:       "y2rw975m",
  },
  {
    playerId:   "FXCloud",
    clearTime:  "0:22.000",
    uploadTime: "2019-09-18",
    videoUrls:  ["https://youtu.be/0cFhCUBR-mo"],
    src:        "srdc",
    srId:       "y95l6vez",
  },
  {
    playerId:   "zukerben",
    clearTime:  "0:22.000",
    uploadTime: "2020-02-21",
    videoUrls:  ["https://www.youtube.com/watch?v=1TeenYy87zQ"],
    src:        "srdc",
    srId:       "z014e4jy",
  },
  {
    playerId:   "Afterburner_X",
    clearTime:  "0:24.000",
    uploadTime: "2020-05-16",
    videoUrls:  ["https://youtu.be/1jGu19h-Y-w"],
    src:        "srdc",
    srId:       "m35r1d4y",
  },
  {
    playerId:   "-slarega-",
    clearTime:  "0:24.000",
    uploadTime: "2020-05-30",
    videoUrls:  ["https://www.youtube.com/watch?v=WVQIqoH-reU&feature=youtu.be"],
    src:        "srdc",
    srId:       "meoj6d8z",
  },
  {
    playerId:   "RoboSt3alth",
    clearTime:  "0:24.000",
    uploadTime: "2021-03-04",
    videoUrls:  ["https://youtu.be/YxIJ7TUu7Cw"],
    src:        "srdc",
    srId:       "yw0n45pm",
  },
  {
    playerId:   "InductiveBag46",
    clearTime:  "0:25.000",
    uploadTime: "2025-02-24",
    videoUrls:  ["https://youtu.be/Tb1aj8vgPVg?si=5m_uW8L8PTL6HjEz"],
    src:        "srdc",
    srId:       "zn9en7vy",
  },
  {
    playerId:   "-Rekken-",
    clearTime:  "0:26.000",
    uploadTime: "2018-09-02",
    videoUrls:  ["https://youtu.be/wiakeBqnqIA"],
    src:        "srdc",
    srId:       "zq3gx85y",
  },
  {
    playerId:   "Nonqui",
    clearTime:  "0:26.000",
    uploadTime: "2018-12-01",
    videoUrls:  ["https://www.youtube.com/watch?v=J06ceZCSS4A"],
    src:        "srdc",
    srId:       "zg72jeez",
  },
  {
    playerId:   ".cat",
    clearTime:  "0:26.000",
    uploadTime: "2018-12-20",
    videoUrls:  ["https://www.youtube.com/watch?v=UypPdLEUSPg&feature=youtu.be"],
    src:        "srdc",
    srId:       "y2qg6ljy",
  },
  {
    playerId:   "-VS-Silv0r",
    clearTime:  "0:26.000",
    uploadTime: "2019-06-27",
    videoUrls:  ["https://www.youtube.com/watch?v=O7iclsMDOnc"],
    src:        "srdc",
    srId:       "mexx9l0z",
  },
  {
    playerId:   "Megami_infini",
    clearTime:  "0:27.000",
    uploadTime: "2019-09-17",
    videoUrls:  ["https://www.youtube.com/watch?v=tSytpmIfjoA"],
    src:        "srdc",
    srId:       "z01ol0jy",
  },
  {
    playerId:   "Ceejay",
    clearTime:  "0:28.000",
    uploadTime: "2018-09-02",
    videoUrls:  ["https://youtu.be/fBtPk7a7bzs"],
    src:        "srdc",
    srId:       "y432d2qz",
  },
  {
    playerId:   "Chansey",
    clearTime:  "0:29.000",
    uploadTime: "2018-09-02",
    videoUrls:  ["https://www.youtube.com/watch?v=1EmESr1Mf18"],
    src:        "srdc",
    srId:       "mr84pv2y",
  },
  {
    playerId:   "Avate",
    clearTime:  "0:30.000",
    uploadTime: "2018-12-06",
    videoUrls:  ["https://youtu.be/ZjGrRfwupgk"],
    src:        "srdc",
    srId:       "m7p01eem",
  },
  {
    playerId:   "LeChat930",
    clearTime:  "0:30.000",
    uploadTime: "2023-06-07",
    videoUrls:  ["https://www.youtube.com/watch?v=qBj5hqrbmuI"],
    src:        "srdc",
    srId:       "mk07jl5z",
  },
  {
    playerId:   "DivineSunder",
    clearTime:  "0:31.000",
    uploadTime: "2018-12-10",
    videoUrls:  ["https://www.youtube.com/watch?v=na9GFNlr6_w"],
    src:        "srdc",
    srId:       "yj421wny",
  },
  {
    playerId:   "SaikoStef",
    clearTime:  "0:32.000",
    uploadTime: "2023-07-07",
    videoUrls:  ["https://youtu.be/C6MNFvFuFew"],
    src:        "srdc",
    srId:       "melee20z",
  },
  {
    playerId:   "fusto",
    clearTime:  "0:47.000",
    uploadTime: "2018-09-01",
    videoUrls:  ["https://youtu.be/YPgK0eMKj-I"],
    src:        "srdc",
    srId:       "mk97xxxz",
  },
  {
    playerId:   "VinterasBote",
    clearTime:  "1:02.000",
    uploadTime: "2020-06-10",
    videoUrls:  ["https://youtu.be/6budwptkvaM"],
    src:        "srdc",
    srId:       "y4wqv1qm",
  },
];