/* speedrun.com 原始抓取数据 — Capture Missions / Mantle / Solo */
/* level_id=ldy2grzw | 共 54 条 */
var capture_missions_mantle_soloRecords = [
  {
    playerId:   "Salat",
    clearTime:  "0:12.966",
    uploadTime: "2025-10-27",
    videoUrls:  ["https://youtu.be/ebYdIqf7iTg"],
    src:        "srdc",
    srId:       "m32gvjgy",
  },
  {
    playerId:   "Mortar",
    clearTime:  "0:13.933",
    uploadTime: "2022-05-30",
    videoUrls:  ["https://www.youtube.com/watch?v=aXJW0KLRqK0"],
    src:        "srdc",
    srId:       "yw33n3pm",
  },
  {
    playerId:   "OgvDams",
    clearTime:  "0:14.707",
    uploadTime: "2024-01-06",
    videoUrls:  ["https://www.youtube.com/watch?v=5zjxGEhNJmQ"],
    src:        "srdc",
    srId:       "y6qge86z",
  },
  {
    playerId:   "Kuremento",
    clearTime:  "0:18.000",
    uploadTime: "2021-03-20",
    videoUrls:  ["https://www.youtube.com/watch?v=JFGD53bTZzw"],
    src:        "srdc",
    srId:       "y9nedqnz",
  },
  {
    playerId:   "Febi",
    clearTime:  "0:18.000",
    uploadTime: "2022-09-29",
    videoUrls:  ["https://www.youtube.com/watch?v=1a3J6rkmLfk"],
    src:        "srdc",
    srId:       "mrr2w77m",
  },
  {
    playerId:   "Txdo",
    clearTime:  "0:18.000",
    uploadTime: "2023-07-22",
    videoUrls:  ["https://www.youtube.com/watch?v=jT8XhT5XVjw"],
    src:        "srdc",
    srId:       "m3q0jdgy",
  },
  {
    playerId:   "Wasamii",
    clearTime:  "0:18.000",
    uploadTime: "2024-02-15",
    videoUrls:  ["https://youtu.be/MnjZEgVTBro"],
    src:        "srdc",
    srId:       "zp6nd2vm",
  },
  {
    playerId:   "L1ndell",
    clearTime:  "0:19.000",
    uploadTime: "2021-09-27",
    videoUrls:  ["https://youtu.be/1uW8V4tpl2g"],
    src:        "srdc",
    srId:       "mk508p3m",
  },
  {
    playerId:   "Yangoo",
    clearTime:  "0:19.000",
    uploadTime: "2022-07-03",
    videoUrls:  ["https://www.youtube.com/watch?v=tzcy3CmAkSA"],
    src:        "srdc",
    srId:       "znp9q6lm",
  },
  {
    playerId:   "RoniPrime",
    clearTime:  "0:19.667",
    uploadTime: "2026-01-04",
    videoUrls:  ["https://youtu.be/buU-c-yZkPM"],
    src:        "srdc",
    srId:       "z56g5jny",
  },
  {
    playerId:   "Menadion",
    clearTime:  "0:20.000",
    uploadTime: "2020-09-12",
    videoUrls:  ["https://www.youtube.com/watch?v=53n_l5nbaj4"],
    src:        "srdc",
    srId:       "y2d3187z",
  },
  {
    playerId:   ".Ren",
    clearTime:  "0:20.000",
    uploadTime: "2020-12-29",
    videoUrls:  ["https://www.youtube.com/watch?v=LBmr60TgByQ"],
    src:        "srdc",
    srId:       "z1o08kgm",
  },
  {
    playerId:   "CreepingChamp",
    clearTime:  "0:20.000",
    uploadTime: "2021-02-24",
    videoUrls:  ["https://youtu.be/pYpwFP-mMXM"],
    src:        "srdc",
    srId:       "y66o656y",
  },
  {
    playerId:   "zukerben",
    clearTime:  "0:21.000",
    uploadTime: "2019-08-10",
    videoUrls:  ["https://www.youtube.com/watch?v=PZ6d-YqONiM"],
    src:        "srdc",
    srId:       "y412nrky",
  },
  {
    playerId:   "Downfall",
    clearTime:  "0:21.000",
    uploadTime: "2020-09-06",
    videoUrls:  ["https://www.youtube.com/watch?v=-sGlNf__wIA&feature=youtu.be"],
    src:        "srdc",
    srId:       "y2d9ddwz",
  },
  {
    playerId:   "Andy.",
    clearTime:  "0:21.000",
    uploadTime: "2020-09-09",
    videoUrls:  ["https://youtu.be/vdL1XTh1bCI"],
    src:        "srdc",
    srId:       "y6r3g76y",
  },
  {
    playerId:   "RoboSt3alth",
    clearTime:  "0:21.000",
    uploadTime: "2021-03-04",
    videoUrls:  ["https://youtu.be/yJaYOuVAIYk"],
    src:        "srdc",
    srId:       "y66qlj1y",
  },
  {
    playerId:   "Nalviscoming14",
    clearTime:  "0:21.000",
    uploadTime: "2023-03-07",
    videoUrls:  ["https://youtu.be/M_8DPKxH12g"],
    src:        "srdc",
    srId:       "z5eg8knz",
  },
  {
    playerId:   "Wiktoryk",
    clearTime:  "0:21.000",
    uploadTime: "2024-02-19",
    videoUrls:  ["https://www.youtube.com/watch?v=X7RQNw72bYg"],
    src:        "srdc",
    srId:       "y22357jy",
  },
  {
    playerId:   "--Q--DankNinja",
    clearTime:  "0:22.000",
    uploadTime: "2019-07-30",
    videoUrls:  ["https://www.youtube.com/watch?v=EzkFnniI0GQ"],
    src:        "srdc",
    srId:       "zp4lvnxz",
  },
  {
    playerId:   "VaclaF",
    clearTime:  "0:22.000",
    uploadTime: "2020-12-15",
    videoUrls:  ["https://www.youtube.com/watch?v=pm0zcHoBKb8"],
    src:        "srdc",
    srId:       "yv9n348z",
  },
  {
    playerId:   "admiral_ackbar47",
    clearTime:  "0:22.000",
    uploadTime: "2021-02-21",
    videoUrls:  ["https://www.youtube.com/watch?v=U3aX7_Mn4kA"],
    src:        "srdc",
    srId:       "y66xdeqy",
  },
  {
    playerId:   "LuxeWF",
    clearTime:  "0:22.000",
    uploadTime: "2021-03-08",
    videoUrls:  ["https://www.youtube.com/watch?v=aDQl1oAUO4w&ab_channel=hi"],
    src:        "srdc",
    srId:       "zno2v48y",
  },
  {
    playerId:   "Zeeddoom",
    clearTime:  "0:22.000",
    uploadTime: "2023-01-30",
    videoUrls:  ["https://youtu.be/Qg6j21KLLik"],
    src:        "srdc",
    srId:       "z0np1g8m",
  },
  {
    playerId:   "LeChat930",
    clearTime:  "0:22.000",
    uploadTime: "2023-07-23",
    videoUrls:  ["https://www.youtube.com/watch?v=HIQKepByREE"],
    src:        "srdc",
    srId:       "yon0825z",
  },
  {
    playerId:   "WOShiXiaoChengYa",
    clearTime:  "0:22.000",
    uploadTime: "2025-04-13",
    videoUrls:  ["https://www.youtube.com/watch?v=XPyM7rbqNas"],
    src:        "srdc",
    srId:       "yvnwjvem",
  },
  {
    playerId:   "Chansey",
    clearTime:  "0:23.000",
    uploadTime: "2019-01-28",
    videoUrls:  ["https://youtu.be/lK0AUeHbz4Q"],
    src:        "srdc",
    srId:       "zq3q9o5y",
  },
  {
    playerId:   "FXCloud",
    clearTime:  "0:23.000",
    uploadTime: "2019-09-15",
    videoUrls:  ["https://youtu.be/DqXTkeFp1uU"],
    src:        "srdc",
    srId:       "z01ordjy",
  },
  {
    playerId:   "Afterburner_X",
    clearTime:  "0:23.000",
    uploadTime: "2020-05-20",
    videoUrls:  ["https://www.youtube.com/watch?v=kJhzvPrtI4Y"],
    src:        "srdc",
    srId:       "m35r0gqy",
  },
  {
    playerId:   "Dr_Skullyy",
    clearTime:  "0:23.000",
    uploadTime: "2025-09-20",
    videoUrls:  ["https://www.youtube.com/watch?v=Swde9Mfd38Q"],
    src:        "srdc",
    srId:       "yo5vkl1z",
  },
  {
    playerId:   "Ceejay",
    clearTime:  "0:24.000",
    uploadTime: "2018-08-30",
    videoUrls:  ["https://youtu.be/tGGyNrD3KVM"],
    src:        "srdc",
    srId:       "z510legm",
  },
  {
    playerId:   "SuiEXE",
    clearTime:  "0:24.000",
    uploadTime: "2021-02-05",
    videoUrls:  ["https://youtu.be/39k6Uf4yXTM"],
    src:        "srdc",
    srId:       "me97890z",
  },
  {
    playerId:   "joshwaaaa_",
    clearTime:  "0:25.000",
    uploadTime: "2018-08-29",
    videoUrls:  ["https://www.youtube.com/watch?v=S7awmDlL6_c"],
    src:        "srdc",
    srId:       "me89gn0m",
  },
  {
    playerId:   "Nonqui",
    clearTime:  "0:25.000",
    uploadTime: "2018-12-01",
    videoUrls:  ["https://www.youtube.com/watch?v=oN7d7GSSdpo&feature=youtu.be"],
    src:        "srdc",
    srId:       "m7p2e34m",
  },
  {
    playerId:   "Avate",
    clearTime:  "0:25.000",
    uploadTime: "2018-12-06",
    videoUrls:  ["https://youtu.be/CmIQR6Z5EE8"],
    src:        "srdc",
    srId:       "yj42jrdy",
  },
  {
    playerId:   "DivineSunder",
    clearTime:  "0:25.000",
    uploadTime: "2018-12-05",
    videoUrls:  ["https://www.youtube.com/watch?v=ZfGVEzGNXqs"],
    src:        "srdc",
    srId:       "zg7eg8nz",
  },
  {
    playerId:   "SquishyFishy",
    clearTime:  "0:25.000",
    uploadTime: "2024-02-05",
    videoUrls:  ["https://www.youtube.com/watch?v=WI6w-d95Wvg&ab_channel=SquishyFishy"],
    src:        "srdc",
    srId:       "yoow5kjy",
  },
  {
    playerId:   "AzZazell",
    clearTime:  "0:26.000",
    uploadTime: "2021-03-03",
    videoUrls:  ["https://youtu.be/prSxVfsprq0"],
    src:        "srdc",
    srId:       "mr42802z",
  },
  {
    playerId:   "fitilok",
    clearTime:  "0:26.000",
    uploadTime: "2026-06-13",
    videoUrls:  ["https://youtu.be/q9sOgoJm66M"],
    src:        "srdc",
    srId:       "y2646w6m",
  },
  {
    playerId:   "FerdinantFritz",
    clearTime:  "0:28.000",
    uploadTime: "2020-04-24",
    videoUrls:  ["https://youtu.be/8lFLNZgHpyE"],
    src:        "srdc",
    srId:       "zqww3x5z",
  },
  {
    playerId:   "hampster",
    clearTime:  "0:28.000",
    uploadTime: "2020-08-06",
    videoUrls:  ["https://www.youtube.com/watch?v=EnMtAY3cuSs&feature=youtu.be"],
    src:        "srdc",
    srId:       "yok5rojz",
  },
  {
    playerId:   "SaikoStef",
    clearTime:  "0:28.000",
    uploadTime: "2023-07-07",
    videoUrls:  ["https://youtu.be/BbKR_EPo_nU"],
    src:        "srdc",
    srId:       "yonlle0z",
  },
  {
    playerId:   "V-_-iniciu-_-s",
    clearTime:  "0:29.000",
    uploadTime: "2019-09-30",
    videoUrls:  ["https://youtu.be/VLuMWVdecso"],
    src:        "srdc",
    srId:       "y21pvwwz",
  },
  {
    playerId:   "Onkel_Shrimp",
    clearTime:  "0:29.000",
    uploadTime: "2021-05-19",
    videoUrls:  ["https://youtu.be/1Ot1jLTSx50"],
    src:        "srdc",
    srId:       "zn10n2lm",
  },
  {
    playerId:   "Fari",
    clearTime:  "0:33.000",
    uploadTime: "2020-08-10",
    videoUrls:  ["https://www.youtube.com/watch?v=_NzMjEIEX_Y"],
    src:        "srdc",
    srId:       "y658k9pz",
  },
  {
    playerId:   "VeeToo",
    clearTime:  "0:34.000",
    uploadTime: "2021-05-20",
    videoUrls:  ["https://www.youtube.com/watch?v=UKIzfGnpyLQ"],
    src:        "srdc",
    srId:       "y2x016wm",
  },
  {
    playerId:   "sakokusho",
    clearTime:  "0:40.000",
    uploadTime: "2022-07-19",
    videoUrls:  ["https://youtu.be/F90Elam4aSo"],
    src:        "srdc",
    srId:       "mr7p148z",
  },
  {
    playerId:   "ExiledTears",
    clearTime:  "0:48.000",
    uploadTime: "2022-10-27",
    videoUrls:  ["https://www.youtube.com/watch?v=vJUJ9ZZTQEc"],
    src:        "srdc",
    srId:       "yjd7x4gy",
  },
  {
    playerId:   "Monstratorfull",
    clearTime:  "0:51.000",
    uploadTime: "2019-04-07",
    videoUrls:  ["https://www.youtube.com/watch?v=JV0Ap9T6fH8"],
    src:        "srdc",
    srId:       "y894x7dm",
  },
  {
    playerId:   "R2D2_Rus",
    clearTime:  "0:58.000",
    uploadTime: "2020-06-16",
    videoUrls:  ["https://www.youtube.com/watch?v=algRCeeHGqI&feature=emb_logo"],
    src:        "srdc",
    srId:       "y4wxk7dm",
  },
  {
    playerId:   "CrackedGamer69420",
    clearTime:  "1:01.000",
    uploadTime: "2022-05-23",
    videoUrls:  ["https://www.youtube.com/watch?v=QXd6Htevfqw"],
    src:        "srdc",
    srId:       "mkke4qlm",
  },
  {
    playerId:   "vamptee",
    clearTime:  "1:02.000",
    uploadTime: "2025-04-06",
    videoUrls:  ["https://youtu.be/Vf7N9tfmci0"],
    src:        "srdc",
    srId:       "mr0pw67m",
  },
  {
    playerId:   "Original_Don",
    clearTime:  "1:10.000",
    uploadTime: "2018-08-28",
    videoUrls:  ["https://youtu.be/3hKIVA-yb0I"],
    src:        "srdc",
    srId:       "y6p6qkqm",
  },
  {
    playerId:   "Shredmachine",
    clearTime:  "1:19.000",
    uploadTime: "2025-04-04",
    videoUrls:  ["https://www.youtube.com/watch?v=F2DmX0GeePo"],
    src:        "srdc",
    srId:       "yww7vxny",
  },
];