/* speedrun.com 原始抓取数据 — Capture Missions / Mantle / Co-op */
/* level_id=ldy2grzw | 共 14 条 */
var capture_missions_mantle_coopRecords = [
  {
    playerId:   "Mortar / Salat",
    clearTime:  "0:16.000",
    uploadTime: "2019-09-20",
    videoUrls:  ["https://www.youtube.com/watch?v=7GrplDoSPmk"],
    src:        "srdc",
    srId:       "y6lnvnpy",
  },
  {
    playerId:   "Salat / L1ndell",
    clearTime:  "0:16.500",
    uploadTime: "2025-12-20",
    videoUrls:  ["https://www.youtube.com/watch?v=XWamCTBtYEM", "https://youtu.be/HvFRWB2pez4"],
    src:        "srdc",
    srId:       "zp5w29ry",
  },
  {
    playerId:   "--Q--Luk / --Q--DankNinja / TopperHarley69 / --Q--Animan8000",
    clearTime:  "0:18.000",
    uploadTime: "2019-07-30",
    videoUrls:  ["https://www.youtube.com/watch?v=I4NQAmcmzt4"],
    src:        "srdc",
    srId:       "mk28x6xm",
  },
  {
    playerId:   "PrimedDarkeN / Mortar",
    clearTime:  "0:18.167",
    uploadTime: "2020-07-18",
    videoUrls:  ["https://www.youtube.com/watch?v=3uX3id0tlyg"],
    src:        "srdc",
    srId:       "y82p091y",
  },
  {
    playerId:   "--Q--Luk / --Q--DankNinja",
    clearTime:  "0:19.000",
    uploadTime: "2019-07-29",
    videoUrls:  ["https://www.youtube.com/watch?v=KECrhcPCHSU"],
    src:        "srdc",
    srId:       "zp4l5drz",
  },
  {
    playerId:   ".cat / Nonqui",
    clearTime:  "0:21.000",
    uploadTime: "2019-06-29",
    videoUrls:  ["https://www.youtube.com/watch?v=649IzI5T9i0&feature=youtu.be"],
    src:        "srdc",
    srId:       "z011p64y",
  },
  {
    playerId:   "SuiEXE / RoboSt3alth / Shronkle",
    clearTime:  "0:22.617",
    uploadTime: "2021-03-04",
    videoUrls:  ["https://youtu.be/5r19RmFQ5Ko"],
    src:        "srdc",
    srId:       "y8vk1l1z",
  },
  {
    playerId:   "Ceejay / QuasarWF",
    clearTime:  "0:23.000",
    uploadTime: "2018-08-28",
    videoUrls:  ["https://youtu.be/GEo2KQ6p__A"],
    src:        "srdc",
    srId:       "y2qv2p6y",
  },
  {
    playerId:   "Zeeddoom / LeChat930",
    clearTime:  "0:23.200",
    uploadTime: "2023-06-23",
    videoUrls:  ["https://www.youtube.com/watch?v=ROi4HjcqXaI"],
    src:        "srdc",
    srId:       "mk0erelz",
  },
  {
    playerId:   "SaikoStef / LeChat930",
    clearTime:  "0:25.000",
    uploadTime: "2023-07-19",
    videoUrls:  ["https://youtu.be/vIzJGhdH8kQ"],
    src:        "srdc",
    srId:       "yl6l28ry",
  },
  {
    playerId:   "RoboSt3alth / SuiEXE",
    clearTime:  "0:27.000",
    uploadTime: "2021-02-13",
    videoUrls:  ["https://youtu.be/OhmRLiQPWLs"],
    src:        "srdc",
    srId:       "y8vjrpwz",
  },
  {
    playerId:   "YiiXou / Touds_",
    clearTime:  "0:27.000",
    uploadTime: "2024-04-20",
    videoUrls:  ["https://www.youtube.com/watch?v=Rtubq0dnOiI"],
    src:        "srdc",
    srId:       "y8wxj05y",
  },
  {
    playerId:   "zopney / Akemi",
    clearTime:  "0:28.000",
    uploadTime: "2018-08-26",
    videoUrls:  ["https://youtu.be/Zb0ByFi7E-A"],
    src:        "srdc",
    srId:       "y432xn2z",
  },
  {
    playerId:   "Thornax / Wambo",
    clearTime:  "1:27.000",
    uploadTime: "2020-05-23",
    videoUrls:  ["https://youtu.be/nyZVoIte0iA`-", "https://youtu.be/CzQaTsjPiYU"],
    src:        "srdc",
    srId:       "m357d5dy",
  },
];