/* speedrun.com 原始抓取数据 — Capture Missions / Ukko / Solo */
/* level_id=29v278ld | 共 177 条 */
var capture_missions_ukko_soloRecords = [
  {
    playerId:   "Endryx_Ow",
    clearTime:  "0:14.483",
    uploadTime: "2026-05-04",
    videoUrls:  ["https://youtu.be/bUbV3RATLC8"],
    src:        "srdc",
    srId:       "y6wqg90z",
  },
  {
    playerId:   "PrimedDarkeN",
    clearTime:  "0:15.033",
    uploadTime: "2023-10-12",
    videoUrls:  ["https://www.youtube.com/watch?v=8R0e3DngN4s"],
    src:        "srdc",
    srId:       "y6qrevqz",
  },
  {
    playerId:   "AresWrath562",
    clearTime:  "0:15.067",
    uploadTime: "2025-04-28",
    videoUrls:  ["https://www.youtube.com/watch?v=aEBBgbnQMYs"],
    src:        "srdc",
    srId:       "z00elqjz",
  },
  {
    playerId:   "OgvDams",
    clearTime:  "0:15.467",
    uploadTime: "2024-03-17",
    videoUrls:  ["https://www.youtube.com/watch?v=IYZVNXvWbNI"],
    src:        "srdc",
    srId:       "ywgdx40z",
  },
  {
    playerId:   "Mortar",
    clearTime:  "0:15.767",
    uploadTime: "2021-02-13",
    videoUrls:  ["https://www.youtube.com/watch?v=jXu4nBnW6z4"],
    src:        "srdc",
    srId:       "y8vjrr1z",
  },
  {
    playerId:   "_Gabriel",
    clearTime:  "0:16.033",
    uploadTime: "2023-01-30",
    videoUrls:  ["https://www.youtube.com/watch?v=zfzFpLGgB8s"],
    src:        "srdc",
    srId:       "m7268d0z",
  },
  {
    playerId:   "Mebius",
    clearTime:  "0:16.267",
    uploadTime: "2023-10-03",
    videoUrls:  ["https://youtu.be/UryxrJdpKAg?si=cUkHnkFCmfoY-c1_"],
    src:        "srdc",
    srId:       "y9k0v4kz",
  },
  {
    playerId:   "LinCorde",
    clearTime:  "0:17.000",
    uploadTime: "2023-03-02",
    videoUrls:  ["https://youtu.be/i5wWwctUHYQ"],
    src:        "srdc",
    srId:       "ylnd682z",
  },
  {
    playerId:   "Kuremento",
    clearTime:  "0:18.000",
    uploadTime: "2021-06-27",
    videoUrls:  ["https://youtu.be/VpCJuCr5JHA"],
    src:        "srdc",
    srId:       "y99ej1ky",
  },
  {
    playerId:   "L1ndell",
    clearTime:  "0:18.000",
    uploadTime: "2021-11-01",
    videoUrls:  ["https://youtu.be/-No77uIaJ_w"],
    src:        "srdc",
    srId:       "y6987gpy",
  },
  {
    playerId:   "lakua",
    clearTime:  "0:18.000",
    uploadTime: "2022-02-26",
    videoUrls:  ["https://www.bilibili.com/video/BV1LS4y167km?share_source=copy_web"],
    src:        "srdc",
    srId:       "ydwvopxm",
  },
  {
    playerId:   "Akula",
    clearTime:  "0:18.000",
    uploadTime: "2022-11-13",
    videoUrls:  ["https://www.youtube.com/watch?v=gqfmilxVEyk&ab_channel=someone"],
    src:        "srdc",
    srId:       "yjdvr9dy",
  },
  {
    playerId:   "Yangoo",
    clearTime:  "0:18.000",
    uploadTime: "2023-04-21",
    videoUrls:  ["https://www.youtube.com/watch?v=cWSwPDJB9sI"],
    src:        "srdc",
    srId:       "m3levoqm",
  },
  {
    playerId:   "TheLostGuthix",
    clearTime:  "0:18.000",
    uploadTime: "2023-07-29",
    videoUrls:  ["https://youtu.be/AnI9d1UJK8Q"],
    src:        "srdc",
    srId:       "yonxwojz",
  },
  {
    playerId:   "HL_Unknown",
    clearTime:  "0:18.000",
    uploadTime: "2025-07-05",
    videoUrls:  ["https://youtu.be/m6KY7aCU42s?si=PRJJMwp3FQcAIWPd"],
    src:        "srdc",
    srId:       "zx081xkz",
  },
  {
    playerId:   "Menadion",
    clearTime:  "0:19.000",
    uploadTime: "2020-11-18",
    videoUrls:  ["https://www.youtube.com/watch?v=jkn0IbOF3f4"],
    src:        "srdc",
    srId:       "mr9rvj4m",
  },
  {
    playerId:   "darkinmaui",
    clearTime:  "0:19.000",
    uploadTime: "2021-04-15",
    videoUrls:  ["https://youtu.be/7mRVgBR1MwM"],
    src:        "srdc",
    srId:       "zxgvnr5y",
  },
  {
    playerId:   "Febi",
    clearTime:  "0:19.000",
    uploadTime: "2021-06-14",
    videoUrls:  ["https://www.youtube.com/watch?v=rKe9ZugclvY"],
    src:        "srdc",
    srId:       "ywqnqg2y",
  },
  {
    playerId:   "namenBARS",
    clearTime:  "0:19.000",
    uploadTime: "2021-10-14",
    videoUrls:  ["https://youtu.be/5ePOCWV7Qf4"],
    src:        "srdc",
    srId:       "z07q7jjy",
  },
  {
    playerId:   "Haxboi",
    clearTime:  "0:19.000",
    uploadTime: "2022-09-22",
    videoUrls:  ["https://www.youtube.com/watch?v=cyzTG20yFmw"],
    src:        "srdc",
    srId:       "z0ljd58z",
  },
  {
    playerId:   "TheLostJoshua",
    clearTime:  "0:19.000",
    uploadTime: "2023-01-06",
    videoUrls:  ["https://www.youtube.com/watch?v=ICxJc0OUgDE"],
    src:        "srdc",
    srId:       "y2jvqj9z",
  },
  {
    playerId:   "Wasamii",
    clearTime:  "0:19.000",
    uploadTime: "2023-01-24",
    videoUrls:  ["https://youtu.be/8E1oyru-tDo"],
    src:        "srdc",
    srId:       "zpg246vz",
  },
  {
    playerId:   "GrowFlowerAllTheWay",
    clearTime:  "0:19.000",
    uploadTime: "2023-10-03",
    videoUrls:  ["https://www.bilibili.com/video/BV1Mm4y137ie/?spm_id_from=333.999.0.0"],
    src:        "srdc",
    srId:       "z5kjr6nz",
  },
  {
    playerId:   "_Aauriell",
    clearTime:  "0:19.000",
    uploadTime: "2024-01-09",
    videoUrls:  ["https://youtu.be/EwanIcX0bgU"],
    src:        "srdc",
    srId:       "z5kw38dz",
  },
  {
    playerId:   "felix_rs",
    clearTime:  "0:19.000",
    uploadTime: "2024-02-02",
    videoUrls:  ["https://www.youtube.com/watch?v=9JeGV4C4jd8"],
    src:        "srdc",
    srId:       "znen77vz",
  },
  {
    playerId:   "solalune",
    clearTime:  "0:19.000",
    uploadTime: "2024-04-01",
    videoUrls:  ["https://youtu.be/Hr9lW61mdag"],
    src:        "srdc",
    srId:       "yo06980y",
  },
  {
    playerId:   "Dejiek",
    clearTime:  "0:19.000",
    uploadTime: "2024-04-22",
    videoUrls:  ["https://www.youtube.com/watch?v=ACCO0NygleM"],
    src:        "srdc",
    srId:       "mrvrvwdz",
  },
  {
    playerId:   "Theotim",
    clearTime:  "0:19.000",
    uploadTime: "2024-05-07",
    videoUrls:  ["https://youtu.be/PECgZ6mr7Yw"],
    src:        "srdc",
    srId:       "yldl0orm",
  },
  {
    playerId:   "Aepul",
    clearTime:  "0:19.000",
    uploadTime: "2025-02-09",
    videoUrls:  ["https://www.youtube.com/watch?v=PrzHt0J4ZMY"],
    src:        "srdc",
    srId:       "yoql900z",
  },
  {
    playerId:   "--taterD--",
    clearTime:  "0:20.000",
    uploadTime: "2020-02-27",
    videoUrls:  ["https://youtu.be/uYhwi1FxjUQ"],
    src:        "srdc",
    srId:       "yojwoljm",
  },
  {
    playerId:   "Wambo",
    clearTime:  "0:20.000",
    uploadTime: "2020-06-12",
    videoUrls:  ["https://www.youtube.com/watch?v=-4_c9J4XH58&feature=youtu.be"],
    src:        "srdc",
    srId:       "y4wx3e2m",
  },
  {
    playerId:   "Dacami",
    clearTime:  "0:20.000",
    uploadTime: "2021-01-08",
    videoUrls:  ["https://www.youtube.com/watch?v=-poFrawfpBE"],
    src:        "srdc",
    srId:       "zn3d84ly",
  },
  {
    playerId:   "KaiMartin",
    clearTime:  "0:20.000",
    uploadTime: "2021-04-12",
    videoUrls:  ["https://www.youtube.com/watch?v=OahZcIWGAH0"],
    src:        "srdc",
    srId:       "zq1kd55m",
  },
  {
    playerId:   "Zulnaa",
    clearTime:  "0:20.000",
    uploadTime: "2021-06-08",
    videoUrls:  ["https://www.youtube.com/watch?v=j3lVsfsFm7I"],
    src:        "srdc",
    srId:       "ylq6kexz",
  },
  {
    playerId:   "LiAXiM",
    clearTime:  "0:20.000",
    uploadTime: "2021-12-16",
    videoUrls:  ["https://youtu.be/QXjD27hWSPc"],
    src:        "srdc",
    srId:       "y6np8o0z",
  },
  {
    playerId:   "Xo4yYMePetb",
    clearTime:  "0:20.000",
    uploadTime: "2022-06-11",
    videoUrls:  ["https://youtu.be/LZGWdr-E2Nc"],
    src:        "srdc",
    srId:       "z1pqegjz",
  },
  {
    playerId:   "Ada_m",
    clearTime:  "0:20.000",
    uploadTime: "2024-03-10",
    videoUrls:  ["https://youtu.be/FKqQLccgG7A"],
    src:        "srdc",
    srId:       "mewo162m",
  },
  {
    playerId:   "SapphireWarframe",
    clearTime:  "0:20.000",
    uploadTime: "2024-05-12",
    videoUrls:  ["https://youtu.be/5s4xtiY77Ac"],
    src:        "srdc",
    srId:       "z199do7m",
  },
  {
    playerId:   "RoniPrime",
    clearTime:  "0:20.917",
    uploadTime: "2026-01-03",
    videoUrls:  ["https://youtu.be/CiaD6lZye4U"],
    src:        "srdc",
    srId:       "y9wjeknz",
  },
  {
    playerId:   "Salat",
    clearTime:  "0:21.000",
    uploadTime: "2019-08-05",
    videoUrls:  ["https://www.youtube.com/watch?v=BL6PGEk7qZs"],
    src:        "srdc",
    srId:       "yd69epqz",
  },
  {
    playerId:   "--Q--DankNinja",
    clearTime:  "0:21.000",
    uploadTime: "2020-02-08",
    videoUrls:  ["https://www.youtube.com/watch?v=lEQk3_rR31o"],
    src:        "srdc",
    srId:       "yd6oppqz",
  },
  {
    playerId:   "Wholesuhm",
    clearTime:  "0:21.000",
    uploadTime: "2021-04-06",
    videoUrls:  ["https://www.youtube.com/watch?v=FoHrk4GspqQ"],
    src:        "srdc",
    srId:       "z06vo7jz",
  },
  {
    playerId:   "RoboSt3alth",
    clearTime:  "0:21.000",
    uploadTime: "2021-07-06",
    videoUrls:  ["https://youtu.be/2WldSXkN9eo"],
    src:        "srdc",
    srId:       "m3r8nn6m",
  },
  {
    playerId:   "LuxeWF",
    clearTime:  "0:21.000",
    uploadTime: "2021-10-24",
    videoUrls:  ["https://www.youtube.com/watch?v=_1QSsljzQ0A&ab_channel=Thunder"],
    src:        "srdc",
    srId:       "z07808oy",
  },
  {
    playerId:   "SuiEXE",
    clearTime:  "0:21.000",
    uploadTime: "2023-07-29",
    videoUrls:  ["https://youtu.be/WBMInzSMzpw"],
    src:        "srdc",
    srId:       "ydjl7lwy",
  },
  {
    playerId:   "Jyunameko",
    clearTime:  "0:21.000",
    uploadTime: "2024-07-25",
    videoUrls:  ["https://youtu.be/9KaKIfv_gkg"],
    src:        "srdc",
    srId:       "z1nj0l7y",
  },
  {
    playerId:   "Jttt",
    clearTime:  "0:21.000",
    uploadTime: "2024-09-12",
    videoUrls:  ["https://www.youtube.com/watch?v=8wU-cDgCi-Y"],
    src:        "srdc",
    srId:       "y6eogejz",
  },
  {
    playerId:   "Nonqui",
    clearTime:  "0:22.000",
    uploadTime: "2019-07-27",
    videoUrls:  ["https://www.youtube.com/watch?v=dYCFR3HFNuo&feature=youtu.be"],
    src:        "srdc",
    srId:       "y21dkdwz",
  },
  {
    playerId:   ".cat",
    clearTime:  "0:22.000",
    uploadTime: "2020-01-28",
    videoUrls:  ["https://www.youtube.com/watch?v=VP-4LYHs8J0"],
    src:        "srdc",
    srId:       "m31vpp6z",
  },
  {
    playerId:   "agrub",
    clearTime:  "0:22.000",
    uploadTime: "2020-05-10",
    videoUrls:  ["https://youtu.be/qehfkraIsn8"],
    src:        "srdc",
    srId:       "yd59070m",
  },
  {
    playerId:   "TehNuby",
    clearTime:  "0:22.000",
    uploadTime: "2020-08-09",
    videoUrls:  ["https://youtu.be/p_1QLYWNALM"],
    src:        "srdc",
    srId:       "y65421pz",
  },
  {
    playerId:   "Reliquary",
    clearTime:  "0:22.000",
    uploadTime: "2020-12-30",
    videoUrls:  ["https://www.youtube.com/watch?v=wyjRzdvPv3E&feature=youtu.be"],
    src:        "srdc",
    srId:       "ylv268km",
  },
  {
    playerId:   "Shiva",
    clearTime:  "0:22.000",
    uploadTime: "2021-06-18",
    videoUrls:  ["https://www.youtube.com/watch?v=XVJCNK6MBY0"],
    src:        "srdc",
    srId:       "zq1qw11m",
  },
  {
    playerId:   "excelion",
    clearTime:  "0:22.000",
    uploadTime: "2021-06-21",
    videoUrls:  ["https://www.youtube.com/watch?v=F9KHbNyP_uI"],
    src:        "srdc",
    srId:       "yo7x0n0m",
  },
  {
    playerId:   "Fransitoh",
    clearTime:  "0:22.000",
    uploadTime: "2021-10-11",
    videoUrls:  ["https://youtu.be/GsqZZRX0pAA"],
    src:        "srdc",
    srId:       "me4w043y",
  },
  {
    playerId:   "DisconnectedJay",
    clearTime:  "0:22.000",
    uploadTime: "2021-12-08",
    videoUrls:  ["https://youtu.be/iQPngYsCXDs"],
    src:        "srdc",
    srId:       "zq060pxy",
  },
  {
    playerId:   "dantheman_on_sky",
    clearTime:  "0:22.000",
    uploadTime: "2023-11-03",
    videoUrls:  ["https://youtu.be/g9HRJt_fIdg"],
    src:        "srdc",
    srId:       "z1kx937y",
  },
  {
    playerId:   "FrostMainer",
    clearTime:  "0:22.000",
    uploadTime: "2025-03-12",
    videoUrls:  ["https://www.youtube.com/watch?v=jQyoGg-Pmxg"],
    src:        "srdc",
    srId:       "y9pppjvm",
  },
  {
    playerId:   "PeterLG",
    clearTime:  "0:22.000",
    uploadTime: "2025-10-25",
    videoUrls:  ["https://youtu.be/puVqZw7_ZYk"],
    src:        "srdc",
    srId:       "yj76kogy",
  },
  {
    playerId:   "Ko.Jl.b.a.c.kA",
    clearTime:  "0:23.000",
    uploadTime: "2019-02-13",
    videoUrls:  ["https://youtu.be/zOv8B0T2pWA"],
    src:        "srdc",
    srId:       "yd3v4qwz",
  },
  {
    playerId:   "lucasengenho",
    clearTime:  "0:23.000",
    uploadTime: "2019-07-27",
    videoUrls:  ["https://youtu.be/CC71XvKA-Jo"],
    src:        "srdc",
    srId:       "y951keez",
  },
  {
    playerId:   "Mano",
    clearTime:  "0:23.000",
    uploadTime: "2020-05-20",
    videoUrls:  ["https://www.youtube.com/watch?v=HzmURqxmhKI&feature=youtu.be"],
    src:        "srdc",
    srId:       "mrk1xn7y",
  },
  {
    playerId:   "zukerben",
    clearTime:  "0:23.000",
    uploadTime: "2020-05-23",
    videoUrls:  ["https://www.youtube.com/watch?v=7iXuLPGREPE"],
    src:        "srdc",
    srId:       "y9031p2y",
  },
  {
    playerId:   "Toriac",
    clearTime:  "0:23.000",
    uploadTime: "2020-06-02",
    videoUrls:  ["https://www.youtube.com/watch?v=Wmj5ZWZ8XQI&feature=youtu.be"],
    src:        "srdc",
    srId:       "yd5w2vxm",
  },
  {
    playerId:   "Andy.",
    clearTime:  "0:23.000",
    uploadTime: "2020-08-14",
    videoUrls:  ["https://youtu.be/pwGGJQx1HnM"],
    src:        "srdc",
    srId:       "z1509kjy",
  },
  {
    playerId:   "jestmi",
    clearTime:  "0:23.000",
    uploadTime: "2021-07-06",
    videoUrls:  ["https://www.youtube.com/watch?v=82ekTi3q9AM"],
    src:        "srdc",
    srId:       "z0r2oq4z",
  },
  {
    playerId:   "TLChaos",
    clearTime:  "0:23.000",
    uploadTime: "2022-07-11",
    videoUrls:  ["https://www.youtube.com/watch?v=mr5PXsmmsKs"],
    src:        "srdc",
    srId:       "yjp7p8oy",
  },
  {
    playerId:   "Celiastral",
    clearTime:  "0:23.000",
    uploadTime: "2023-07-31",
    videoUrls:  ["https://www.youtube.com/watch?v=3ZohcRifkW8"],
    src:        "srdc",
    srId:       "y98p65nz",
  },
  {
    playerId:   "-Rekken-",
    clearTime:  "0:24.000",
    uploadTime: "2018-08-14",
    videoUrls:  ["https://youtu.be/LxQKqkLop78"],
    src:        "srdc",
    srId:       "yvj9x4xy",
  },
  {
    playerId:   "Koto",
    clearTime:  "0:24.000",
    uploadTime: "2018-12-20",
    videoUrls:  ["https://www.youtube.com/watch?v=yqMKsMzPRr4"],
    src:        "srdc",
    srId:       "m3oq4wdm",
  },
  {
    playerId:   "Chansey",
    clearTime:  "0:24.000",
    uploadTime: "2019-01-30",
    videoUrls:  ["https://youtu.be/iuaCj6ENhio"],
    src:        "srdc",
    srId:       "zx4xx58y",
  },
  {
    playerId:   "-CheffDegu",
    clearTime:  "0:24.000",
    uploadTime: "2019-05-06",
    videoUrls:  ["https://youtu.be/yfG7gWIqgSU"],
    src:        "srdc",
    srId:       "m7pr619m",
  },
  {
    playerId:   "LectoRR",
    clearTime:  "0:24.000",
    uploadTime: "2019-05-28",
    videoUrls:  ["https://www.youtube.com/watch?v=FFHGLvEv-Iw"],
    src:        "srdc",
    srId:       "yv34kg6z",
  },
  {
    playerId:   "FXCloud",
    clearTime:  "0:24.000",
    uploadTime: "2019-09-17",
    videoUrls:  ["https://youtu.be/vNxRNSq-Hc0"],
    src:        "srdc",
    srId:       "m316xn4z",
  },
  {
    playerId:   "hexd",
    clearTime:  "0:24.000",
    uploadTime: "2019-10-07",
    videoUrls:  ["https://youtu.be/eWIoS85TxzI"],
    src:        "srdc",
    srId:       "yv3rn14z",
  },
  {
    playerId:   "Meln1K",
    clearTime:  "0:24.000",
    uploadTime: "2020-05-15",
    videoUrls:  ["https://www.youtube.com/watch?v=wrJ_AzJ5nUE&feature=youtu.be"],
    src:        "srdc",
    srId:       "z5j0njjm",
  },
  {
    playerId:   "Afterburner_X",
    clearTime:  "0:24.000",
    uploadTime: "2020-05-18",
    videoUrls:  ["https://www.youtube.com/watch?v=HcUE4ByiFPE"],
    src:        "srdc",
    srId:       "yjlgxwoz",
  },
  {
    playerId:   "toSa_xd",
    clearTime:  "0:24.000",
    uploadTime: "2021-01-08",
    videoUrls:  ["https://www.youtube.com/watch?v=nFc69urBUGA&feature=youtu.be"],
    src:        "srdc",
    srId:       "zn3d8q3y",
  },
  {
    playerId:   "Bloody_001",
    clearTime:  "0:24.000",
    uploadTime: "2021-02-28",
    videoUrls:  ["https://www.youtube.com/watch?v=z13Ao5_HrUs"],
    src:        "srdc",
    srId:       "y9n8ld2z",
  },
  {
    playerId:   "UnlitCandle",
    clearTime:  "0:24.000",
    uploadTime: "2021-10-20",
    videoUrls:  ["https://youtu.be/RH6AVfRGvIs"],
    src:        "srdc",
    srId:       "zgrjkenm",
  },
  {
    playerId:   "TheDriftKing",
    clearTime:  "0:24.000",
    uploadTime: "2021-10-31",
    videoUrls:  ["https://www.youtube.com/watch?v=Ggk_A9uYG2c&ab_channel=speedruns"],
    src:        "srdc",
    srId:       "mrnd3q4y",
  },
  {
    playerId:   "H_ex",
    clearTime:  "0:24.000",
    uploadTime: "2021-12-31",
    videoUrls:  ["https://youtu.be/wWltqXzXkcg"],
    src:        "srdc",
    srId:       "ydw0l8vm",
  },
  {
    playerId:   "zLeventastic",
    clearTime:  "0:24.000",
    uploadTime: "2022-02-14",
    videoUrls:  ["https://youtu.be/ZDDXGc_uBVM"],
    src:        "srdc",
    srId:       "mr6vv42m",
  },
  {
    playerId:   "FritureExpresse",
    clearTime:  "0:24.000",
    uploadTime: "2022-03-24",
    videoUrls:  ["https://www.youtube.com/watch?v=zrsATT39orY"],
    src:        "srdc",
    srId:       "yjx0gq3z",
  },
  {
    playerId:   "--Q--HLixir",
    clearTime:  "0:25.000",
    uploadTime: "2019-02-23",
    videoUrls:  ["https://youtu.be/vrUOTwMDo6s"],
    src:        "srdc",
    srId:       "zq3p9xxy",
  },
  {
    playerId:   "Mekarazium",
    clearTime:  "0:25.000",
    uploadTime: "2019-09-14",
    videoUrls:  ["https://youtu.be/YTzFOLWDo4c"],
    src:        "srdc",
    srId:       "yv3q99oz",
  },
  {
    playerId:   "Prime01Jok3r",
    clearTime:  "0:25.000",
    uploadTime: "2021-05-16",
    videoUrls:  ["https://youtu.be/vHFTbATYDBM"],
    src:        "srdc",
    srId:       "y8de295z",
  },
  {
    playerId:   "apellsin",
    clearTime:  "0:25.000",
    uploadTime: "2021-03-12",
    videoUrls:  ["https://youtu.be/08Xo_Osk6gY"],
    src:        "srdc",
    srId:       "z1rgj19m",
  },
  {
    playerId:   "Long_Shuwen",
    clearTime:  "0:25.000",
    uploadTime: "2022-01-31",
    videoUrls:  ["https://www.bilibili.com/video/BV1Gr4y1Y7dg?spm_id_from=333.999.0.0"],
    src:        "srdc",
    srId:       "zgd26odz",
  },
  {
    playerId:   "Damii005",
    clearTime:  "0:25.000",
    uploadTime: "2022-03-14",
    videoUrls:  ["https://www.youtube.com/watch?v=UoJoaAR9yts"],
    src:        "srdc",
    srId:       "y9lgpdry",
  },
  {
    playerId:   "XadaPrime",
    clearTime:  "0:25.000",
    uploadTime: "2023-04-16",
    videoUrls:  ["https://youtu.be/rnIyUdZu4-0"],
    src:        "srdc",
    srId:       "y4gp52qy",
  },
  {
    playerId:   "LeChat930",
    clearTime:  "0:25.000",
    uploadTime: "2023-07-17",
    videoUrls:  ["https://www.youtube.com/watch?v=40JQVZZhVx0"],
    src:        "srdc",
    srId:       "y98kl0vz",
  },
  {
    playerId:   "nev546",
    clearTime:  "0:25.000",
    uploadTime: "2024-02-26",
    videoUrls:  ["https://youtube.com/clip/UgkxDGj39qGCIMqpvu8FuEr-yai-2uzQPTr0?si=UJUwPRtqAPUXwJED"],
    src:        "srdc",
    srId:       "ydn3d2qm",
  },
  {
    playerId:   "--Q--L3TK",
    clearTime:  "0:26.000",
    uploadTime: "2018-11-19",
    videoUrls:  ["https://www.youtube.com/watch?v=KdMQqCMVucc"],
    src:        "srdc",
    srId:       "z03lgxez",
  },
  {
    playerId:   "Dawiddym",
    clearTime:  "0:26.000",
    uploadTime: "2019-08-16",
    videoUrls:  ["https://youtu.be/QzHq98Lhcm0"],
    src:        "srdc",
    srId:       "yd6r6o0z",
  },
  {
    playerId:   "BlacknessFRAME",
    clearTime:  "0:26.000",
    uploadTime: "2021-03-02",
    videoUrls:  ["https://youtu.be/SO5ghilYQvU"],
    src:        "srdc",
    srId:       "y42ovn3m",
  },
  {
    playerId:   "striker350z",
    clearTime:  "0:26.000",
    uploadTime: "2021-03-28",
    videoUrls:  ["https://youtu.be/Gs_fI-nNZGc"],
    src:        "srdc",
    srId:       "me9d293z",
  },
  {
    playerId:   "QuesoRuso",
    clearTime:  "0:26.000",
    uploadTime: "2021-06-28",
    videoUrls:  ["https://www.youtube.com/watch?v=adi-Ynkudxo"],
    src:        "srdc",
    srId:       "yjg724gy",
  },
  {
    playerId:   "CurryPaste",
    clearTime:  "0:26.000",
    uploadTime: "2021-12-18",
    videoUrls:  ["https://youtu.be/wkkbY7YZioE"],
    src:        "srdc",
    srId:       "mr698lgm",
  },
  {
    playerId:   "brandi003",
    clearTime:  "0:26.000",
    uploadTime: "2023-09-28",
    videoUrls:  ["https://clips.twitch.tv/GracefulCuriousSrirachaOhMyDog-Tm-AfhktOrUVnA4k"],
    src:        "srdc",
    srId:       "mkq2041m",
  },
  {
    playerId:   "ShadowDrache",
    clearTime:  "0:26.000",
    uploadTime: "2024-01-19",
    videoUrls:  ["https://www.youtube.com/watch?v=lGzmPPRtnbo&t=123"],
    src:        "srdc",
    srId:       "ywn5oj9y",
  },
  {
    playerId:   "Critey",
    clearTime:  "0:26.000",
    uploadTime: "2024-03-05",
    videoUrls:  ["https://www.youtube.com/watch?v=rRz3v5hxd0Y"],
    src:        "srdc",
    srId:       "zxqkxnkm",
  },
  {
    playerId:   "17_07700900514",
    clearTime:  "0:27.000",
    uploadTime: "2020-05-13",
    videoUrls:  ["https://youtu.be/WbL7StzUWbU"],
    src:        "srdc",
    srId:       "yjl1e1nz",
  },
  {
    playerId:   "Slim_Fatteh",
    clearTime:  "0:27.000",
    uploadTime: "2021-02-21",
    videoUrls:  ["https://youtu.be/KzpSyVP--2Q"],
    src:        "srdc",
    srId:       "zqg94e1m",
  },
  {
    playerId:   "AzZazell",
    clearTime:  "0:27.000",
    uploadTime: "2021-03-03",
    videoUrls:  ["https://youtu.be/10gLTWxWj0c"],
    src:        "srdc",
    srId:       "mk7q2ovy",
  },
  {
    playerId:   "Bero667",
    clearTime:  "0:27.000",
    uploadTime: "2021-09-22",
    videoUrls:  ["https://www.youtube.com/watch?v=0AQpSZtqxQQ&ab_channel=NotBero"],
    src:        "srdc",
    srId:       "mk5ver3m",
  },
  {
    playerId:   "PEPSIIOVA",
    clearTime:  "0:27.000",
    uploadTime: "2021-09-30",
    videoUrls:  ["https://www.youtube.com/watch?v=SE9T_eIthGM"],
    src:        "srdc",
    srId:       "mrnlxvgy",
  },
  {
    playerId:   "Wiktoryk",
    clearTime:  "0:27.000",
    uploadTime: "2022-12-27",
    videoUrls:  ["https://www.youtube.com/watch?v=vgNKsfIY7d0"],
    src:        "srdc",
    srId:       "ydg5j7jy",
  },
  {
    playerId:   "Quitestern",
    clearTime:  "0:27.000",
    uploadTime: "2026-06-08",
    videoUrls:  ["https://youtu.be/AYpupDfdZHI"],
    src:        "srdc",
    srId:       "zn66lkvy",
  },
  {
    playerId:   "Avate",
    clearTime:  "0:28.000",
    uploadTime: "2018-08-14",
    videoUrls:  ["https://youtu.be/ocYkP1k5ufk"],
    src:        "srdc",
    srId:       "yo23015z",
  },
  {
    playerId:   "Ceejay",
    clearTime:  "0:28.000",
    uploadTime: "2019-01-18",
    videoUrls:  ["https://www.twitch.tv/videos/365745648"],
    src:        "srdc",
    srId:       "z518wkjm",
  },
  {
    playerId:   "UnOriginalGN",
    clearTime:  "0:28.000",
    uploadTime: "2021-08-21",
    videoUrls:  ["https://youtu.be/9nn43LSH_N4"],
    src:        "srdc",
    srId:       "zp8lj9vy",
  },
  {
    playerId:   "zopney",
    clearTime:  "0:29.000",
    uploadTime: "2018-08-13",
    videoUrls:  ["https://www.youtube.com/watch?v=J3iM1Rselg0"],
    src:        "srdc",
    srId:       "y43ek7nz",
  },
  {
    playerId:   "Altale",
    clearTime:  "0:29.000",
    uploadTime: "2018-08-16",
    videoUrls:  ["https://youtu.be/OAv_mx5muaw"],
    src:        "srdc",
    srId:       "yd30o9qz",
  },
  {
    playerId:   "-dicht.Arogamers-",
    clearTime:  "0:29.000",
    uploadTime: "2018-08-20",
    videoUrls:  ["https://www.youtube.com/watch?v=H4yWzSUtU08"],
    src:        "srdc",
    srId:       "yvj2ge4y",
  },
  {
    playerId:   "--Q--EValueAction",
    clearTime:  "0:29.000",
    uploadTime: "2018-11-19",
    videoUrls:  ["https://www.twitch.tv/7egor4_ik/clip/WealthyHandsomePastaPanicVis"],
    src:        "srdc",
    srId:       "y89037dm",
  },
  {
    playerId:   "okay",
    clearTime:  "0:29.000",
    uploadTime: "2019-07-11",
    videoUrls:  ["https://www.youtube.com/watch?v=YdkH_jkWK7c"],
    src:        "srdc",
    srId:       "znrk059y",
  },
  {
    playerId:   "fckdaniel",
    clearTime:  "0:29.000",
    uploadTime: "2019-08-15",
    videoUrls:  ["https://www.youtube.com/watch?v=iybZWmmKCTA&feature=youtu.be"],
    src:        "srdc",
    srId:       "z1jr1ljz",
  },
  {
    playerId:   "Ashen",
    clearTime:  "0:29.000",
    uploadTime: "2019-09-19",
    videoUrls:  ["https://www.youtube.com/watch?v=deEOLVJNFCo"],
    src:        "srdc",
    srId:       "m7qw045z",
  },
  {
    playerId:   "Tennoskull",
    clearTime:  "0:29.000",
    uploadTime: "2020-08-07",
    videoUrls:  ["https://www.youtube.com/watch?v=vFJUqWIhTK0"],
    src:        "srdc",
    srId:       "zqw5999z",
  },
  {
    playerId:   "--Q--Neurofrost",
    clearTime:  "0:29.000",
    uploadTime: "2020-11-14",
    videoUrls:  ["https://youtu.be/c3YprlSZ84s"],
    src:        "srdc",
    srId:       "ylv75r3m",
  },
  {
    playerId:   "deoje299",
    clearTime:  "0:29.000",
    uploadTime: "2021-11-17",
    videoUrls:  ["https://www.youtube.com/watch?v=geIQqS6NJ_8"],
    src:        "srdc",
    srId:       "z5d44oem",
  },
  {
    playerId:   "MagsPrime",
    clearTime:  "0:29.000",
    uploadTime: "2022-01-15",
    videoUrls:  ["https://youtu.be/JWtvYqEn4U8"],
    src:        "srdc",
    srId:       "y9lv7d2y",
  },
  {
    playerId:   "Ivarra",
    clearTime:  "0:29.000",
    uploadTime: "2023-05-26",
    videoUrls:  ["https://www.youtube.com/watch?v=Dbsd3R7fKSE"],
    src:        "srdc",
    srId:       "mrlkgj7m",
  },
  {
    playerId:   "novembered",
    clearTime:  "0:30.000",
    uploadTime: "2019-02-20",
    videoUrls:  ["https://www.youtube.com/watch?v=qeNg5myeO1I"],
    src:        "srdc",
    srId:       "y89gr5xm",
  },
  {
    playerId:   "Atmosquake",
    clearTime:  "0:30.000",
    uploadTime: "2019-05-26",
    videoUrls:  ["https://youtu.be/8g4x-zv2pMA"],
    src:        "srdc",
    srId:       "y419nnny",
  },
  {
    playerId:   "Thornax",
    clearTime:  "0:30.000",
    uploadTime: "2020-04-19",
    videoUrls:  ["https://youtu.be/oOhXOmkUX10"],
    src:        "srdc",
    srId:       "zpr48pxm",
  },
  {
    playerId:   "-slarega-",
    clearTime:  "0:30.000",
    uploadTime: "2020-05-17",
    videoUrls:  ["https://www.youtube.com/watch?v=PPgXZa_tVX4&feature=youtu.be"],
    src:        "srdc",
    srId:       "y82dvq5y",
  },
  {
    playerId:   "Blankowich",
    clearTime:  "0:30.000",
    uploadTime: "2021-05-05",
    videoUrls:  ["https://youtu.be/hCmG4rPklzg"],
    src:        "srdc",
    srId:       "y6d6pn6m",
  },
  {
    playerId:   "distones",
    clearTime:  "0:31.000",
    uploadTime: "2018-08-13",
    videoUrls:  ["https://www.youtube.com/watch?v=qDUF4vHu2qE"],
    src:        "srdc",
    srId:       "yvj9vd8y",
  },
  {
    playerId:   "Icohedron",
    clearTime:  "0:31.000",
    uploadTime: "2018-09-22",
    videoUrls:  ["https://www.youtube.com/watch?v=EUTTGYfXLHE"],
    src:        "srdc",
    srId:       "z51dv25m",
  },
  {
    playerId:   "Electric_",
    clearTime:  "0:31.000",
    uploadTime: "2020-12-29",
    videoUrls:  ["https://youtu.be/YeJC6CD_L2k"],
    src:        "srdc",
    srId:       "y2d6vg6z",
  },
  {
    playerId:   "RasenARG",
    clearTime:  "0:31.000",
    uploadTime: "2021-06-11",
    videoUrls:  ["https://www.youtube.com/watch?v=4oLyTOyw2z4"],
    src:        "srdc",
    srId:       "m3rq216m",
  },
  {
    playerId:   "SuchMeister",
    clearTime:  "0:32.000",
    uploadTime: "2019-09-11",
    videoUrls:  ["https://youtu.be/bFS_YziQ5pI"],
    src:        "srdc",
    srId:       "yv3qggoz",
  },
  {
    playerId:   "Basi.",
    clearTime:  "0:32.000",
    uploadTime: "2020-03-10",
    videoUrls:  ["https://www.youtube.com/watch?v=EASWvsv8Pl4&feature=youtu.be"],
    src:        "srdc",
    srId:       "zp4jxwnz",
  },
  {
    playerId:   "deathcurzo",
    clearTime:  "0:33.000",
    uploadTime: "2019-07-19",
    videoUrls:  ["https://youtu.be/zm4Hl1ujhSg"],
    src:        "srdc",
    srId:       "zxk2e2em",
  },
  {
    playerId:   "lMP0ST0R",
    clearTime:  "0:34.000",
    uploadTime: "2020-10-29",
    videoUrls:  ["https://drive.google.com/file/d/1XyKM6TLW6i1K3sTFetwd4gEc_yai15WW/view?usp=sharing"],
    src:        "srdc",
    srId:       "z53rn3jy",
  },
  {
    playerId:   "Frostkralle",
    clearTime:  "0:34.000",
    uploadTime: "2021-04-21",
    videoUrls:  ["https://youtu.be/hrfu1ZjfTaA"],
    src:        "srdc",
    srId:       "ydr3k4qz",
  },
  {
    playerId:   "Eddos",
    clearTime:  "0:36.000",
    uploadTime: "2019-07-23",
    videoUrls:  ["https://youtu.be/kOP7MhAkSxs"],
    src:        "srdc",
    srId:       "mex69w2z",
  },
  {
    playerId:   "RazorTalon",
    clearTime:  "0:36.000",
    uploadTime: "2021-10-24",
    videoUrls:  ["https://youtu.be/V7R6DmcUCHA"],
    src:        "srdc",
    srId:       "y47jo4ky",
  },
  {
    playerId:   "LollypopTwist",
    clearTime:  "0:37.000",
    uploadTime: "2019-06-05",
    videoUrls:  ["https://www.youtube.com/watch?v=j3s7eueAwyM"],
    src:        "srdc",
    srId:       "zqr69e5y",
  },
  {
    playerId:   "InductiveBag46",
    clearTime:  "0:37.000",
    uploadTime: "2021-05-16",
    videoUrls:  ["https://youtu.be/wyxqUU-aoMU"],
    src:        "srdc",
    srId:       "z1rxoqwm",
  },
  {
    playerId:   "S1lentStriker",
    clearTime:  "0:37.000",
    uploadTime: "2021-05-19",
    videoUrls:  ["https://youtu.be/8pn05pttlcQ"],
    src:        "srdc",
    srId:       "y6d9160m",
  },
  {
    playerId:   "--Q--roissant",
    clearTime:  "0:37.000",
    uploadTime: "2021-11-15",
    videoUrls:  ["https://www.youtube.com/watch?v=g1GLEvZkTqU"],
    src:        "srdc",
    srId:       "ylrwl8ky",
  },
  {
    playerId:   "YiiXou",
    clearTime:  "0:38.000",
    uploadTime: "2023-04-18",
    videoUrls:  ["https://youtu.be/JaV_PBppNzw"],
    src:        "srdc",
    srId:       "y805dewm",
  },
  {
    playerId:   "Ming732",
    clearTime:  "0:39.000",
    uploadTime: "2021-04-06",
    videoUrls:  ["https://youtu.be/69wOVpJSdf8"],
    src:        "srdc",
    srId:       "z18ewdry",
  },
  {
    playerId:   "VaultedRelic",
    clearTime:  "0:39.000",
    uploadTime: "2022-08-12",
    videoUrls:  ["https://youtu.be/NoPf3QvFGmg"],
    src:        "srdc",
    srId:       "y2e53n7y",
  },
  {
    playerId:   "BoChecker",
    clearTime:  "0:39.000",
    uploadTime: "2024-10-27",
    videoUrls:  ["https://youtu.be/YsPJus1DBTw"],
    src:        "srdc",
    srId:       "znx5vj3y",
  },
  {
    playerId:   "ivancjto",
    clearTime:  "0:40.000",
    uploadTime: "2021-05-13",
    videoUrls:  ["https://www.youtube.com/watch?v=28hdBmvJFpM"],
    src:        "srdc",
    srId:       "m3rr244m",
  },
  {
    playerId:   "Omnimble",
    clearTime:  "0:41.000",
    uploadTime: "2018-11-08",
    videoUrls:  ["https://youtu.be/L112_va07DE"],
    src:        "srdc",
    srId:       "y43xrkqz",
  },
  {
    playerId:   "cosmo_dragons_",
    clearTime:  "0:41.000",
    uploadTime: "2025-02-04",
    videoUrls:  ["https://youtu.be/1BEuIw5Nxts"],
    src:        "srdc",
    srId:       "zn9qp8vy",
  },
  {
    playerId:   "Raskolnikow",
    clearTime:  "0:42.000",
    uploadTime: "2019-06-09",
    videoUrls:  ["https://youtu.be/dHeab5Ptc7Y"],
    src:        "srdc",
    srId:       "mexkp62z",
  },
  {
    playerId:   "Dr.Jan-Itor",
    clearTime:  "0:42.000",
    uploadTime: "2020-12-25",
    videoUrls:  ["https://youtu.be/OwcBliTLQ9Q"],
    src:        "srdc",
    srId:       "me6p7l8z",
  },
  {
    playerId:   "iAmReflex",
    clearTime:  "0:43.000",
    uploadTime: "2018-08-13",
    videoUrls:  ["https://youtu.be/dz0EXywYjJI"],
    src:        "srdc",
    srId:       "y43e62kz",
  },
  {
    playerId:   "fedlav",
    clearTime:  "0:43.000",
    uploadTime: "2024-02-01",
    videoUrls:  ["https://www.youtube.com/watch?v=eaRh5Fy6B_U"],
    src:        "srdc",
    srId:       "znen3elz",
  },
  {
    playerId:   "Radncat",
    clearTime:  "0:44.000",
    uploadTime: "2020-12-25",
    videoUrls:  ["https://youtu.be/aD5TtsuU5gA"],
    src:        "srdc",
    srId:       "y2drxo5z",
  },
  {
    playerId:   "ElbowBaz",
    clearTime:  "0:44.000",
    uploadTime: "2024-04-02",
    videoUrls:  ["https://youtu.be/sf_Xd4JfRs4"],
    src:        "srdc",
    srId:       "ywgk373z",
  },
  {
    playerId:   "keraven",
    clearTime:  "0:45.000",
    uploadTime: "2018-12-18",
    videoUrls:  ["https://www.youtube.com/watch?v=buU-7xP1OKY"],
    src:        "srdc",
    srId:       "z11klegz",
  },
  {
    playerId:   "-Prodygy-",
    clearTime:  "0:45.000",
    uploadTime: "2019-02-06",
    videoUrls:  ["https://www.youtube.com/watch?v=H0_GJpPnyjo&t=1s"],
    src:        "srdc",
    srId:       "mk9o8k5z",
  },
  {
    playerId:   "--.Ophelia.nVbs.--",
    clearTime:  "0:45.000",
    uploadTime: "2022-04-16",
    videoUrls:  ["https://www.youtube.com/watch?v=8nBtzNjY2xQ&ab_channel=HannahWade"],
    src:        "srdc",
    srId:       "z0p3o5jy",
  },
  {
    playerId:   "Dark_Lugia",
    clearTime:  "0:48.000",
    uploadTime: "2024-07-12",
    videoUrls:  ["https://www.youtube.com/watch?v=14eHraUEXeQ"],
    src:        "srdc",
    srId:       "y6e769qz",
  },
  {
    playerId:   "PandoraDC",
    clearTime:  "0:49.000",
    uploadTime: "2018-08-12",
    videoUrls:  ["https://youtu.be/Yksgv9j93S0"],
    src:        "srdc",
    srId:       "z039nq9z",
  },
  {
    playerId:   "Hellhound15x",
    clearTime:  "0:49.000",
    uploadTime: "2018-08-15",
    videoUrls:  ["https://www.twitch.tv/videos/297804201"],
    src:        "srdc",
    srId:       "zn43g0lm",
  },
  {
    playerId:   "xXgabri83Xx",
    clearTime:  "0:49.000",
    uploadTime: "2019-03-04",
    videoUrls:  ["https://youtu.be/iDysSCk_KZM"],
    src:        "srdc",
    srId:       "y4303gdz",
  },
  {
    playerId:   "BountyV",
    clearTime:  "0:49.000",
    uploadTime: "2020-06-27",
    videoUrls:  ["https://youtu.be/mv1AlPmaBVo"],
    src:        "srdc",
    srId:       "zx236gkm",
  },
  {
    playerId:   "LapisBlaze15",
    clearTime:  "0:50.000",
    uploadTime: "2018-08-12",
    videoUrls:  ["https://youtu.be/xXOMbH_8nVs"],
    src:        "srdc",
    srId:       "y9216grz",
  },
  {
    playerId:   "RSalata",
    clearTime:  "0:51.000",
    uploadTime: "2019-05-17",
    videoUrls:  ["https://www.youtube.com/watch?v=hp-fGDxgnwE&t=2s"],
    src:        "srdc",
    srId:       "yv3435xz",
  },
  {
    playerId:   "iamfumii",
    clearTime:  "0:52.000",
    uploadTime: "2020-12-12",
    videoUrls:  ["https://www.youtube.com/watch?v=dUS9cRJjx0w&feature=youtu.be"],
    src:        "srdc",
    srId:       "zn3xq29y",
  },
  {
    playerId:   "Zexal",
    clearTime:  "0:52.000",
    uploadTime: "2021-11-15",
    videoUrls:  ["https://youtu.be/krWs8pe0Hrw"],
    src:        "srdc",
    srId:       "zp8epkny",
  },
  {
    playerId:   "Kerberax",
    clearTime:  "0:53.000",
    uploadTime: "2022-04-16",
    videoUrls:  ["https://www.youtube.com/watch?v=l91tp8_YF38"],
    src:        "srdc",
    srId:       "y60pn50y",
  },
  {
    playerId:   "--sleepy--",
    clearTime:  "0:54.000",
    uploadTime: "2020-06-27",
    videoUrls:  ["https://www.youtube.com/watch?v=U9oUrJVGuQk"],
    src:        "srdc",
    srId:       "y25gdjwy",
  },
  {
    playerId:   "Phanini",
    clearTime:  "0:59.000",
    uploadTime: "2018-09-19",
    videoUrls:  ["https://www.youtube.com/watch?v=Y0npvjdehQU"],
    src:        "srdc",
    srId:       "z51d7vjm",
  },
  {
    playerId:   "_Dopa",
    clearTime:  "1:00.000",
    uploadTime: "2024-12-14",
    videoUrls:  ["https://youtu.be/Fhp927yCcvg"],
    src:        "srdc",
    srId:       "yoq2dkdz",
  },
  {
    playerId:   "mmaure",
    clearTime:  "1:01.000",
    uploadTime: "2018-09-01",
    videoUrls:  ["https://www.youtube.com/watch?v=nXbUFFBlz5M&t=5s"],
    src:        "srdc",
    srId:       "mk97n3lz",
  },
  {
    playerId:   "R96",
    clearTime:  "1:06.000",
    uploadTime: "2020-01-30",
    videoUrls:  ["https://www.youtube.com/watch?v=8PX-GCD2Hsc"],
    src:        "srdc",
    srId:       "znr54rly",
  },
  {
    playerId:   "Guift",
    clearTime:  "1:59.000",
    uploadTime: "2022-07-13",
    videoUrls:  ["https://www.youtube.com/watch?v=PzAwOsoUO7I"],
    src:        "srdc",
    srId:       "zp9vq5gm",
  },
  {
    playerId:   "AdaroNeverChanges",
    clearTime:  "9:36.000",
    uploadTime: "2018-12-08",
    videoUrls:  ["https://www.youtube.com/watch?v=0D6cFviUog0&lc=z233cfjzkyeqg5x5304t1aokgbk4t5ss0gpttwcvuarfrk0h00410"],
    src:        "srdc",
    srId:       "yvjp31xy",
  },
];