/* speedrun.com 原始抓取数据 — Capture Missions / Ukko / Co-op */
/* level_id=29v278ld | 共 24 条 */
var capture_missions_ukko_coopRecords = [
  {
    playerId:   "L1ndell / Salat",
    clearTime:  "0:15.000",
    uploadTime: "2026-01-03",
    videoUrls:  ["https://www.youtube.com/watch?v=iCAwEMhmZlM", "https://youtu.be/kiVXIXAPKpc"],
    src:        "srdc",
    srId:       "y8nw421y",
  },
  {
    playerId:   "Salat / lucasengenho / Mortar",
    clearTime:  "0:16.000",
    uploadTime: "2019-09-16",
    videoUrls:  ["https://www.youtube.com/watch?v=BaWT-Jdx5fY"],
    src:        "srdc",
    srId:       "mexj340z",
  },
  {
    playerId:   "PrimedDarkeN / Akula",
    clearTime:  "0:16.700",
    uploadTime: "2022-11-12",
    videoUrls:  ["https://www.youtube.com/watch?v=jqIg8MKS_Mo"],
    src:        "srdc",
    srId:       "z0l4qqoz",
  },
  {
    playerId:   "zxcMolniya / L1ndell",
    clearTime:  "0:17.717",
    uploadTime: "2021-12-02",
    videoUrls:  ["https://youtu.be/Cz3UJ9v9igY"],
    src:        "srdc",
    srId:       "y9lov7ey",
  },
  {
    playerId:   "--Q--Luk / --Q--DankNinja",
    clearTime:  "0:18.000",
    uploadTime: "2019-07-26",
    videoUrls:  ["https://www.youtube.com/watch?v=CPrz3s0jCjU"],
    src:        "srdc",
    srId:       "zp4lwwgz",
  },
  {
    playerId:   "Febi / Kuremento",
    clearTime:  "0:19.000",
    uploadTime: "2021-02-11",
    videoUrls:  ["https://youtu.be/x9OYlF4K6kc"],
    src:        "srdc",
    srId:       "me94238z",
  },
  {
    playerId:   "PrimedDarkeN / Mortar",
    clearTime:  "0:20.000",
    uploadTime: "2020-08-15",
    videoUrls:  ["https://www.youtube.com/watch?v=4j9Dukgm-tE"],
    src:        "srdc",
    srId:       "yjlrr1gz",
  },
  {
    playerId:   ".cat / Nonqui",
    clearTime:  "0:21.000",
    uploadTime: "2019-07-16",
    videoUrls:  ["https://www.youtube.com/watch?v=FrMnehSX01E"],
    src:        "srdc",
    srId:       "y812oo1z",
  },
  {
    playerId:   "Frumkin / L1ndell",
    clearTime:  "0:21.000",
    uploadTime: "2021-10-27",
    videoUrls:  ["https://youtu.be/nwMZd1NQVmM"],
    src:        "srdc",
    srId:       "z0709w9y",
  },
  {
    playerId:   "Voltage / Koto",
    clearTime:  "0:22.000",
    uploadTime: "2018-12-20",
    videoUrls:  ["https://www.youtube.com/watch?v=uKcV14ubzqA"],
    src:        "srdc",
    srId:       "ywpr7n3z",
  },
  {
    playerId:   "namenBARS / Nonqui",
    clearTime:  "0:22.000",
    uploadTime: "2019-02-06",
    videoUrls:  ["https://www.youtube.com/watch?v=L-tW20QOczM&feature=youtu.be"],
    src:        "srdc",
    srId:       "y6pgrjpm",
  },
  {
    playerId:   "--Q--Nani / _Gabriel",
    clearTime:  "0:22.000",
    uploadTime: "2021-05-02",
    videoUrls:  ["https://www.youtube.com/watch?v=tugJ99pctLI"],
    src:        "srdc",
    srId:       "ywqd642y",
  },
  {
    playerId:   "RoboSt3alth / diminish",
    clearTime:  "0:22.000",
    uploadTime: "2021-05-28",
    videoUrls:  ["https://youtu.be/cKtcrSOueyU"],
    src:        "srdc",
    srId:       "zxg7q7qy",
  },
  {
    playerId:   "agrub / RoboSt3alth",
    clearTime:  "0:24.000",
    uploadTime: "2020-05-08",
    videoUrls:  ["https://youtu.be/WAObvsk7DUs"],
    src:        "srdc",
    srId:       "zgwg8dvy",
  },
  {
    playerId:   "Kuremento / Menadion",
    clearTime:  "0:24.000",
    uploadTime: "2020-07-31",
    videoUrls:  ["https://www.youtube.com/watch?v=aiXqlpf7KOE"],
    src:        "srdc",
    srId:       "yoken4dz",
  },
  {
    playerId:   "RoboSt3alth / SuiEXE",
    clearTime:  "0:26.000",
    uploadTime: "2021-02-13",
    videoUrls:  ["https://youtu.be/O0ulxB4uQdU"],
    src:        "srdc",
    srId:       "zgxdvpjm",
  },
  {
    playerId:   "SuiEXE / RoboSt3alth / Shronkle",
    clearTime:  "0:26.000",
    uploadTime: "2021-03-04",
    videoUrls:  ["https://youtu.be/zuX1SBX7TJQ"],
    src:        "srdc",
    srId:       "y2vk186z",
  },
  {
    playerId:   "--Q--EValueAction / namenBARS",
    clearTime:  "0:27.000",
    uploadTime: "2018-11-15",
    videoUrls:  ["https://youtu.be/mKHmYiBAOh8"],
    src:        "srdc",
    srId:       "yd314pxz",
  },
  {
    playerId:   "--Q--EValueAction / .cat",
    clearTime:  "0:27.000",
    uploadTime: "2018-12-18",
    videoUrls:  ["https://www.youtube.com/watch?v=rAs0ZGklV4o&feature=youtu.be"],
    src:        "srdc",
    srId:       "yvjp74ey",
  },
  {
    playerId:   "toSa_xd / Dacami",
    clearTime:  "0:27.000",
    uploadTime: "2021-01-08",
    videoUrls:  ["https://www.youtube.com/watch?v=du4phhK0aAE"],
    src:        "srdc",
    srId:       "ylvg3jxm",
  },
  {
    playerId:   "RoboSt3alth / Shronkle",
    clearTime:  "0:27.000",
    uploadTime: "2021-03-04",
    videoUrls:  ["https://youtu.be/YZBfVOi0t0M"],
    src:        "srdc",
    srId:       "z06x12ez",
  },
  {
    playerId:   "Ceejay / -Rekken-",
    clearTime:  "0:30.000",
    uploadTime: "2018-08-13",
    videoUrls:  ["https://youtu.be/oWcLa0sTtGc"],
    src:        "srdc",
    srId:       "zp0lp18m",
  },
  {
    playerId:   "zopney / MunchkinMel",
    clearTime:  "0:36.000",
    uploadTime: "2018-08-11",
    videoUrls:  ["https://www.youtube.com/watch?v=rSYi4zBWmms"],
    src:        "srdc",
    srId:       "z11oqg9z",
  },
  {
    playerId:   "--RV--Goddess / distones",
    clearTime:  "1:18.000",
    uploadTime: "2018-09-02",
    videoUrls:  ["https://www.youtube.com/watch?v=icsDbglxMzE"],
    src:        "srdc",
    srId:       "y6pd3l6m",
  },
];