/* speedrun.com 原始抓取数据 — Bosses / Alad V / Co-op */
/* level_id=xd12xo6w | 共 11 条 */
var bosses_alad_v_coopRecords = [
  {
    playerId:   "lucasengenho / Mortar",
    clearTime:  "0:21.350",
    uploadTime: "2019-10-20",
    videoUrls:  ["https://www.youtube.com/watch?v=wxKYHNEftVc"],
    src:        "srdc",
    srId:       "z1jgq4rz",
  },
  {
    playerId:   "Salat / L1ndell",
    clearTime:  "0:24.000",
    uploadTime: "2025-12-20",
    videoUrls:  ["https://www.youtube.com/watch?v=_sEAeQO0mDo", "https://youtu.be/3kE2hR__bfM"],
    src:        "srdc",
    srId:       "y40opedz",
  },
  {
    playerId:   "Txdo / DishonoredFNG / _Dopa",
    clearTime:  "0:26.000",
    uploadTime: "2025-02-26",
    videoUrls:  ["https://www.youtube.com/watch?v=6g4wD79tG3c&ab_channel=Txdo"],
    src:        "srdc",
    srId:       "y4j6w0qy",
  },
  {
    playerId:   "PrimedDarkeN / Mortar",
    clearTime:  "0:28.000",
    uploadTime: "2020-09-12",
    videoUrls:  ["https://www.youtube.com/watch?v=Ha8iMp8gdXw"],
    src:        "srdc",
    srId:       "y8rq1j1m",
  },
  {
    playerId:   "Akemi / IRojaz / Nusmag",
    clearTime:  "0:31.000",
    uploadTime: "2018-03-15",
    videoUrls:  ["https://youtu.be/rqNmwvVKPkQ"],
    src:        "srdc",
    srId:       "z0e2dq4m",
  },
  {
    playerId:   "silverdk / Ceejay",
    clearTime:  "0:31.000",
    uploadTime: "2019-07-04",
    videoUrls:  ["https://youtu.be/Hk_Dj0aqh7g"],
    src:        "srdc",
    srId:       "znrrg19y",
  },
  {
    playerId:   "LiAXiM / pitruxa43",
    clearTime:  "0:36.000",
    uploadTime: "2022-02-17",
    videoUrls:  ["https://youtu.be/fsF4sfmJdwg"],
    src:        "srdc",
    srId:       "z0oq15oz",
  },
  {
    playerId:   "WOShiXiaoChengYa / DOK304",
    clearTime:  "0:37.000",
    uploadTime: "2025-04-14",
    videoUrls:  ["https://www.youtube.com/watch?v=TEfWB4SC-F8"],
    src:        "srdc",
    srId:       "y4jp1e3y",
  },
  {
    playerId:   "GlydeFox / LapisBlaze15",
    clearTime:  "1:04.000",
    uploadTime: "2018-10-17",
    videoUrls:  ["https://www.youtube.com/watch?v=h-pmNM33Ej0"],
    src:        "srdc",
    srId:       "z03pew9z",
  },
  {
    playerId:   "ShiftDelete / CreepingChamp",
    clearTime:  "1:12.000",
    uploadTime: "2020-08-20",
    videoUrls:  ["https://youtu.be/LG_mv9VOae0?list=PLOoCYdaYurpzssoavUuncOcivAmO4XJcr"],
    src:        "srdc",
    srId:       "zgvnn4nz",
  },
  {
    playerId:   "ASmallPotato / Leigh",
    clearTime:  "1:34.610",
    uploadTime: "2017-05-03",
    videoUrls:  ["https://youtu.be/ZTnrDspUj_E"],
    src:        "srdc",
    srId:       "yo44o0dm",
  },
];