/* speedrun.com 原始抓取数据 — Bosses / Alad V / Solo */
/* level_id=xd12xo6w | 共 67 条 */
var bosses_alad_v_soloRecords = [
  {
    playerId:   "Salat",
    clearTime:  "0:16.017",
    uploadTime: "2026-04-25",
    videoUrls:  ["https://youtu.be/B7AM_CMXQ3w"],
    src:        "srdc",
    srId:       "z10l1k7m",
  },
  {
    playerId:   "Mortar",
    clearTime:  "0:18.000",
    uploadTime: "2024-03-20",
    videoUrls:  ["https://www.youtube.com/watch?v=dRt1V2lRk-8"],
    src:        "srdc",
    srId:       "z58031dz",
  },
  {
    playerId:   "Endryx_Ow",
    clearTime:  "0:18.000",
    uploadTime: "2024-11-21",
    videoUrls:  ["https://youtu.be/yqDWwBKtTyw"],
    src:        "srdc",
    srId:       "zxxe6v5z",
  },
  {
    playerId:   "L1ndell",
    clearTime:  "0:20.000",
    uploadTime: "2022-04-17",
    videoUrls:  ["https://youtu.be/Vgoz5vutFTM"],
    src:        "srdc",
    srId:       "zp90go8m",
  },
  {
    playerId:   "Txdo",
    clearTime:  "0:20.000",
    uploadTime: "2024-02-04",
    videoUrls:  ["https://www.youtube.com/watch?v=cSZdjmABQK4"],
    src:        "srdc",
    srId:       "yoowoe1y",
  },
  {
    playerId:   "holleufer98",
    clearTime:  "0:21.188",
    uploadTime: "2018-02-04",
    videoUrls:  ["https://youtu.be/wGq6bf3bB1Q"],
    src:        "srdc",
    srId:       "m3djvv6z",
  },
  {
    playerId:   "OgvDams",
    clearTime:  "0:22.000",
    uploadTime: "2024-03-17",
    videoUrls:  ["https://www.youtube.com/watch?v=ww3_6KGE-v4"],
    src:        "srdc",
    srId:       "zn23xr3z",
  },
  {
    playerId:   "Kuremento",
    clearTime:  "0:23.000",
    uploadTime: "2021-04-20",
    videoUrls:  ["https://youtu.be/PgobY2lLYeo"],
    src:        "srdc",
    srId:       "yjg68vdy",
  },
  {
    playerId:   "Meln1K",
    clearTime:  "0:23.067",
    uploadTime: "2020-05-09",
    videoUrls:  ["https://www.youtube.com/watch?v=B59nMe6O-7s&feature=youtu.be"],
    src:        "srdc",
    srId:       "z05611em",
  },
  {
    playerId:   "Yangoo",
    clearTime:  "0:25.000",
    uploadTime: "2023-04-18",
    videoUrls:  ["https://youtu.be/lrDdqpkF63w"],
    src:        "srdc",
    srId:       "znjdo47m",
  },
  {
    playerId:   "Nusmag",
    clearTime:  "0:25.092",
    uploadTime: "2017-12-02",
    videoUrls:  ["https://youtu.be/0Zwje2lN-aM"],
    src:        "srdc",
    srId:       "y8q06gny",
  },
  {
    playerId:   "zukerben",
    clearTime:  "0:26.000",
    uploadTime: "2019-05-04",
    videoUrls:  ["https://www.youtube.com/watch?v=5c0uSPSqmcg"],
    src:        "srdc",
    srId:       "yvjw2q4y",
  },
  {
    playerId:   "zukerben",
    clearTime:  "0:26.000",
    uploadTime: "2019-12-07",
    videoUrls:  ["https://www.youtube.com/watch?v=fbnKwUSWB1A"],
    src:        "srdc",
    srId:       "m7q3l9wz",
  },
  {
    playerId:   "Febi",
    clearTime:  "0:26.000",
    uploadTime: "2021-03-28",
    videoUrls:  ["https://www.youtube.com/watch?v=s1FpX9Rk23U"],
    src:        "srdc",
    srId:       "z0622oez",
  },
  {
    playerId:   "LiAXiM",
    clearTime:  "0:26.000",
    uploadTime: "2022-02-23",
    videoUrls:  ["https://youtu.be/qZC8xKU7_OA"],
    src:        "srdc",
    srId:       "zq021e9y",
  },
  {
    playerId:   "Akemi",
    clearTime:  "0:26.400",
    uploadTime: "2017-12-02",
    videoUrls:  ["https://youtu.be/l-KJdD1XMFI"],
    src:        "srdc",
    srId:       "zgn2eo0y",
  },
  {
    playerId:   "-CheffDegu",
    clearTime:  "0:26.876",
    uploadTime: "2019-01-12",
    videoUrls:  ["https://www.youtube.com/watch?v=Ov8gKML0-ys"],
    src:        "srdc",
    srId:       "ywpgk5pz",
  },
  {
    playerId:   "TheLostGuthix",
    clearTime:  "0:27.000",
    uploadTime: "2021-03-05",
    videoUrls:  ["https://www.youtube.com/watch?v=RiTih6TkJQc"],
    src:        "srdc",
    srId:       "zgx8j2dm",
  },
  {
    playerId:   "zxcMolniya",
    clearTime:  "0:27.000",
    uploadTime: "2021-07-29",
    videoUrls:  ["https://www.youtube.com/watch?v=t8qVbzZYc7M"],
    src:        "srdc",
    srId:       "z5do7vgm",
  },
  {
    playerId:   "Frostyy19",
    clearTime:  "0:27.000",
    uploadTime: "2025-07-27",
    videoUrls:  ["https://www.youtube.com/watch?v=tcG44_mhZOk&ab_channel=Shimo"],
    src:        "srdc",
    srId:       "ywrd9nnm",
  },
  {
    playerId:   "Dini",
    clearTime:  "0:27.811",
    uploadTime: "2019-01-11",
    videoUrls:  ["https://www.youtube.com/watch?v=cuyS5D6YEEM"],
    src:        "srdc",
    srId:       "zx4qgw8y",
  },
  {
    playerId:   "-Rekken-",
    clearTime:  "0:27.861",
    uploadTime: "2018-05-04",
    videoUrls:  ["https://youtu.be/nXrMyorM2NI"],
    src:        "srdc",
    srId:       "z13eewgm",
  },
  {
    playerId:   "Vici",
    clearTime:  "0:28.145",
    uploadTime: "2018-10-10",
    videoUrls:  ["https://www.youtube.com/watch?v=sRy4FTdjSVo"],
    src:        "srdc",
    srId:       "yo2rn81z",
  },
  {
    playerId:   "Nonqui",
    clearTime:  "0:29.000",
    uploadTime: "2018-12-01",
    videoUrls:  ["https://www.youtube.com/watch?v=c5R9zAcQmwQ&feature=youtu.be"],
    src:        "srdc",
    srId:       "yd3gv7qz",
  },
  {
    playerId:   "Chansey",
    clearTime:  "0:29.866",
    uploadTime: "2018-09-04",
    videoUrls:  ["https://www.youtube.com/watch?v=MsUJDD1ouRY"],
    src:        "srdc",
    srId:       "y89d96nm",
  },
  {
    playerId:   "Hamudi",
    clearTime:  "0:30.000",
    uploadTime: "2024-01-06",
    videoUrls:  ["https://youtu.be/iQpQYOPUTn8"],
    src:        "srdc",
    srId:       "mkpl8n1y",
  },
  {
    playerId:   "mashor2004",
    clearTime:  "0:31.000",
    uploadTime: "2019-08-19",
    videoUrls:  ["https://youtu.be/nL7gaD4-5cA"],
    src:        "srdc",
    srId:       "yl0qerry",
  },
  {
    playerId:   "zukerben",
    clearTime:  "0:31.000",
    uploadTime: "2019-12-01",
    videoUrls:  ["https://www.youtube.com/watch?v=y5TVfryUrho"],
    src:        "srdc",
    srId:       "yv3voo8z",
  },
  {
    playerId:   "SuiEXE",
    clearTime:  "0:31.000",
    uploadTime: "2021-03-06",
    videoUrls:  ["https://youtu.be/Ydp0SJ8fPc0"],
    src:        "srdc",
    srId:       "y426552m",
  },
  {
    playerId:   "RoboSt3alth",
    clearTime:  "0:33.000",
    uploadTime: "2021-03-04",
    videoUrls:  ["https://youtu.be/CAPjLudJq_M"],
    src:        "srdc",
    srId:       "me90xp9z",
  },
  {
    playerId:   "zopney",
    clearTime:  "0:33.316",
    uploadTime: "2018-02-05",
    videoUrls:  ["https://www.youtube.com/watch?v=MQsa24x2QME"],
    src:        "srdc",
    srId:       "z0eqgd9m",
  },
  {
    playerId:   "NinjaMann",
    clearTime:  "0:34.134",
    uploadTime: "2018-02-05",
    videoUrls:  ["https://youtu.be/xA-BrToQxCc"],
    src:        "srdc",
    srId:       "ydql7ejm",
  },
  {
    playerId:   "striker350z",
    clearTime:  "0:35.000",
    uploadTime: "2021-04-10",
    videoUrls:  ["https://www.youtube.com/watch?v=cp9MATvq0SI"],
    src:        "srdc",
    srId:       "y99o902y",
  },
  {
    playerId:   "Wiktoryk",
    clearTime:  "0:36.000",
    uploadTime: "2022-09-01",
    videoUrls:  ["https://www.youtube.com/watch?v=ewz-rPKeyU0"],
    src:        "srdc",
    srId:       "znq71q3z",
  },
  {
    playerId:   "Founder",
    clearTime:  "0:37.000",
    uploadTime: "2021-02-21",
    videoUrls:  ["https://www.youtube.com/watch?v=E7azYEFQFWE&ab_channel=-Founder"],
    src:        "srdc",
    srId:       "y2vee87z",
  },
  {
    playerId:   "PrimedDarkeN",
    clearTime:  "0:38.000",
    uploadTime: "2021-11-15",
    videoUrls:  ["https://www.youtube.com/watch?v=vPciAx0IiIQ"],
    src:        "srdc",
    srId:       "y694oppy",
  },
  {
    playerId:   "Dr_Skullyy",
    clearTime:  "0:39.000",
    uploadTime: "2022-07-25",
    videoUrls:  ["https://www.youtube.com/watch?v=c1HRrqHGyEo"],
    src:        "srdc",
    srId:       "yvrdng4z",
  },
  {
    playerId:   "LeChat930",
    clearTime:  "0:39.000",
    uploadTime: "2023-07-06",
    videoUrls:  ["https://www.youtube.com/watch?v=2eBSjwTRKMs"],
    src:        "srdc",
    srId:       "ydjg50jy",
  },
  {
    playerId:   "Negabite",
    clearTime:  "0:39.260",
    uploadTime: "2018-10-09",
    videoUrls:  ["https://www.youtube.com/watch?v=44dBQmQ_GRw&feature=youtu.be"],
    src:        "srdc",
    srId:       "yl4e76xm",
  },
  {
    playerId:   "V-_-iniciu-_-s",
    clearTime:  "0:40.000",
    uploadTime: "2019-11-13",
    videoUrls:  ["https://youtu.be/Lfvn2ZCLwIQ"],
    src:        "srdc",
    srId:       "yw4r470z",
  },
  {
    playerId:   "Lepitar",
    clearTime:  "0:41.000",
    uploadTime: "2019-08-17",
    videoUrls:  ["https://youtu.be/q33STq0G-6Q"],
    src:        "srdc",
    srId:       "y21xv75z",
  },
  {
    playerId:   "issaFoxy",
    clearTime:  "0:41.000",
    uploadTime: "2019-09-02",
    videoUrls:  ["https://www.youtube.com/watch?v=6H2g9WRL68k"],
    src:        "srdc",
    srId:       "zp48gkvz",
  },
  {
    playerId:   "-VS-WeebusRussus",
    clearTime:  "0:42.000",
    uploadTime: "2019-08-14",
    videoUrls:  ["https://youtu.be/8UqSrkDVhPw"],
    src:        "srdc",
    srId:       "zxkgv4em",
  },
  {
    playerId:   "AzZazell",
    clearTime:  "0:42.000",
    uploadTime: "2021-03-02",
    videoUrls:  ["https://youtu.be/U14uLr8fmPc"],
    src:        "srdc",
    srId:       "y8vk3xnz",
  },
  {
    playerId:   "Outomic",
    clearTime:  "0:44.000",
    uploadTime: "2019-08-07",
    videoUrls:  ["https://www.youtube.com/watch?v=7C-_uquLqks"],
    src:        "srdc",
    srId:       "mex91k8z",
  },
  {
    playerId:   "ShadowDrache",
    clearTime:  "0:49.000",
    uploadTime: "2023-08-19",
    videoUrls:  ["https://youtu.be/9wdp06qSXUE"],
    src:        "srdc",
    srId:       "y2g6or9z",
  },
  {
    playerId:   "SABBA_HOSTUMEX",
    clearTime:  "0:49.000",
    uploadTime: "2026-01-01",
    videoUrls:  ["https://youtu.be/wscQ5VRjMgw"],
    src:        "srdc",
    srId:       "m320604y",
  },
  {
    playerId:   "Ming732",
    clearTime:  "0:50.000",
    uploadTime: "2021-02-11",
    videoUrls:  ["https://youtu.be/781u9JrfUDw"],
    src:        "srdc",
    srId:       "m3n7kpgy",
  },
  {
    playerId:   "LapisBlaze15",
    clearTime:  "0:51.000",
    uploadTime: "2018-10-18",
    videoUrls:  ["https://www.youtube.com/watch?v=NCJgKSm03c8"],
    src:        "srdc",
    srId:       "zx4746ky",
  },
  {
    playerId:   "hendraf",
    clearTime:  "0:52.000",
    uploadTime: "2019-12-11",
    videoUrls:  ["https://youtu.be/SMVCH8C8SsA"],
    src:        "srdc",
    srId:       "yd627xxz",
  },
  {
    playerId:   "D3648",
    clearTime:  "0:53.000",
    uploadTime: "2021-10-19",
    videoUrls:  ["https://youtu.be/cRQQX8zTRM0"],
    src:        "srdc",
    srId:       "ydel7jwm",
  },
  {
    playerId:   "Killatomate",
    clearTime:  "0:54.667",
    uploadTime: "2016-11-06",
    videoUrls:  ["https://www.youtube.com/watch?v=u7HySxUfILI"],
    src:        "srdc",
    srId:       "y2qvng9y",
  },
  {
    playerId:   "FearOmnicide",
    clearTime:  "0:55.000",
    uploadTime: "2018-05-06",
    videoUrls:  ["https://youtu.be/WNNHm70qO_g"],
    src:        "srdc",
    srId:       "z0ev38om",
  },
  {
    playerId:   "Loyaal",
    clearTime:  "0:57.000",
    uploadTime: "2021-11-15",
    videoUrls:  ["https://youtu.be/0ay-2SPy_QA"],
    src:        "srdc",
    srId:       "y8e4kvdy",
  },
  {
    playerId:   "biochronicle",
    clearTime:  "0:59.000",
    uploadTime: "2019-08-29",
    videoUrls:  ["https://www.youtube.com/watch?v=Gfc-EA7qyVY"],
    src:        "srdc",
    srId:       "y417w0ky",
  },
  {
    playerId:   "Kish0214",
    clearTime:  "1:02.000",
    uploadTime: "2020-09-01",
    videoUrls:  ["https://www.youtube.com/watch?v=kPNauRH9ygM"],
    src:        "srdc",
    srId:       "m7gr630m",
  },
  {
    playerId:   "simonplays52",
    clearTime:  "1:05.000",
    uploadTime: "2026-01-22",
    videoUrls:  ["https://youtu.be/VQrmBxo9qXo?si=xVcDym25H8L3FM10"],
    src:        "srdc",
    srId:       "y4002vqz",
  },
  {
    playerId:   "Wasamii",
    clearTime:  "1:07.000",
    uploadTime: "2021-11-08",
    videoUrls:  ["https://youtu.be/9BULkO5xF4I"],
    src:        "srdc",
    srId:       "y8elevxy",
  },
  {
    playerId:   "A1exGamer",
    clearTime:  "1:10.000",
    uploadTime: "2018-09-02",
    videoUrls:  ["https://streamable.com/0665y"],
    src:        "srdc",
    srId:       "z510qjjm",
  },
  {
    playerId:   "ViiSari",
    clearTime:  "1:10.000",
    uploadTime: "2021-11-09",
    videoUrls:  ["https://www.youtube.com/watch?v=BkuRtuDoz08"],
    src:        "srdc",
    srId:       "z5dneejm",
  },
  {
    playerId:   "Volkolakros",
    clearTime:  "1:16.000",
    uploadTime: "2020-05-06",
    videoUrls:  ["https://www.youtube.com/watch?v=ayosJvz2pq8"],
    src:        "srdc",
    srId:       "y901dqey",
  },
  {
    playerId:   "Euphoria3843",
    clearTime:  "1:17.000",
    uploadTime: "2021-03-16",
    videoUrls:  ["https://streamable.com/09m3b2"],
    src:        "srdc",
    srId:       "z068q9ez",
  },
  {
    playerId:   "ulusa",
    clearTime:  "1:18.000",
    uploadTime: "2018-03-21",
    videoUrls:  ["https://youtu.be/qUEBDzqZHcQ"],
    src:        "srdc",
    srId:       "y97g5o2m",
  },
  {
    playerId:   "HippoSapien",
    clearTime:  "1:19.000",
    uploadTime: "2021-05-19",
    videoUrls:  ["https://youtu.be/yoLN3sQAWwc"],
    src:        "srdc",
    srId:       "ywqjp29y",
  },
  {
    playerId:   "TheDaxis",
    clearTime:  "1:20.000",
    uploadTime: "2019-07-09",
    videoUrls:  ["https://www.youtube.com/watch?v=VVb9tfM__uY"],
    src:        "srdc",
    srId:       "znrkk29y",
  },
  {
    playerId:   "Kratosqt",
    clearTime:  "1:31.000",
    uploadTime: "2021-11-15",
    videoUrls:  ["https://youtu.be/JAr_ZEEsJNk"],
    src:        "srdc",
    srId:       "z074x88y",
  },
  {
    playerId:   "the1Kronos",
    clearTime:  "1:57.000",
    uploadTime: "2020-01-14",
    videoUrls:  ["https://youtu.be/8tR7HUyvAYE"],
    src:        "srdc",
    srId:       "yojq0o1m",
  },
];