/* speedrun.com 原始抓取数据 — Bosses / Ambulas / Solo */
/* level_id=29v72vn9 | 共 25 条 */
var bosses_ambulas_soloRecords = [
  {
    playerId:   "Salat",
    clearTime:  "7:18.516",
    uploadTime: "2025-11-12",
    videoUrls:  ["https://youtu.be/52kCbgL2etQ"],
    src:        "srdc",
    srId:       "zx5gpl5m",
  },
  {
    playerId:   "Txdo",
    clearTime:  "7:19.933",
    uploadTime: "2025-01-28",
    videoUrls:  ["https://www.youtube.com/watch?v=Z-vFfK2q5YE&ab_channel=Txdo"],
    src:        "srdc",
    srId:       "yvnr96em",
  },
  {
    playerId:   "PrimedDarkeN",
    clearTime:  "7:23.000",
    uploadTime: "2024-01-02",
    videoUrls:  ["https://www.youtube.com/watch?v=VUSPYCfrc-U"],
    src:        "srdc",
    srId:       "yllp9vny",
  },
  {
    playerId:   "solalune",
    clearTime:  "7:29.000",
    uploadTime: "2024-01-12",
    videoUrls:  ["https://www.youtube.com/watch?v=ZWxYon-FMpU"],
    src:        "srdc",
    srId:       "zppo6qnz",
  },
  {
    playerId:   "nonwf",
    clearTime:  "7:29.000",
    uploadTime: "2024-07-09",
    videoUrls:  ["https://youtu.be/iZ21FZ8Azk4"],
    src:        "srdc",
    srId:       "yvx4l16z",
  },
  {
    playerId:   "Wasamii",
    clearTime:  "7:30.000",
    uploadTime: "2023-12-04",
    videoUrls:  ["https://youtu.be/OkbrdMb5tRU"],
    src:        "srdc",
    srId:       "zg8215dy",
  },
  {
    playerId:   "AkiraAwoo",
    clearTime:  "7:39.566",
    uploadTime: "2023-11-29",
    videoUrls:  ["https://youtu.be/Mu2KcGNEEsQ"],
    src:        "srdc",
    srId:       "yjw86qom",
  },
  {
    playerId:   "SABBA_HOSTUMEX",
    clearTime:  "7:41.000",
    uploadTime: "2026-01-06",
    videoUrls:  ["https://youtu.be/nkoCgSu4Bvg"],
    src:        "srdc",
    srId:       "zn5x0q3z",
  },
  {
    playerId:   "Bombatack017",
    clearTime:  "7:43.000",
    uploadTime: "2024-03-14",
    videoUrls:  ["https://www.youtube.com/watch?v=pmkmXkDc6hA"],
    src:        "srdc",
    srId:       "mrv99j8z",
  },
  {
    playerId:   "Wakaaa",
    clearTime:  "7:45.000",
    uploadTime: "2024-03-12",
    videoUrls:  ["https://www.youtube.com/watch?v=WZXhkkRWsJ8&ab_channel=Stupid_waka"],
    src:        "srdc",
    srId:       "yjolrddz",
  },
  {
    playerId:   "Wiktoryk",
    clearTime:  "7:47.000",
    uploadTime: "2024-02-22",
    videoUrls:  ["https://www.youtube.com/watch?v=PjWKbfxpPf0"],
    src:        "srdc",
    srId:       "mrvqw7dz",
  },
  {
    playerId:   "he_who_rows",
    clearTime:  "7:49.000",
    uploadTime: "2023-11-23",
    videoUrls:  ["https://youtu.be/frf9EfWYA0c?si=9pL2-RmbzVdFBKBd"],
    src:        "srdc",
    srId:       "y4kxw7dm",
  },
  {
    playerId:   "SkiCosmic",
    clearTime:  "8:10.000",
    uploadTime: "2023-12-24",
    videoUrls:  ["https://www.twitch.tv/skicosmic/v/2012896197?sr=a&t=82s"],
    src:        "srdc",
    srId:       "zpp6p1rz",
  },
  {
    playerId:   "Nusmag",
    clearTime:  "11:30.383",
    uploadTime: "2018-07-05",
    videoUrls:  ["https://youtu.be/hpPgzKhne38"],
    src:        "srdc",
    srId:       "mk99xovz",
  },
  {
    playerId:   "zukerben",
    clearTime:  "11:32.000",
    uploadTime: "2019-04-29",
    videoUrls:  ["https://www.youtube.com/watch?v=5hQmRXmiVSE"],
    src:        "srdc",
    srId:       "m7pkkjwm",
  },
  {
    playerId:   "Koto",
    clearTime:  "11:32.224",
    uploadTime: "2018-04-10",
    videoUrls:  ["https://www.youtube.com/watch?v=4c7Iv2inJQA"],
    src:        "srdc",
    srId:       "y8q46qxy",
  },
  {
    playerId:   "-GC-YourEmoGirl-GC-",
    clearTime:  "11:38.000",
    uploadTime: "2020-07-27",
    videoUrls:  ["https://www.youtube.com/watch?v=5lsAV2Czq8g"],
    src:        "srdc",
    srId:       "yw8w2l9y",
  },
  {
    playerId:   "-Rekken-",
    clearTime:  "11:38.183",
    uploadTime: "2018-04-30",
    videoUrls:  ["https://youtu.be/76WUhIyiH7I"],
    src:        "srdc",
    srId:       "yw19wk2z",
  },
  {
    playerId:   "IRojaz",
    clearTime:  "11:39.830",
    uploadTime: "2017-12-05",
    videoUrls:  ["https://youtu.be/YRYnauJlPC0"],
    src:        "srdc",
    srId:       "yjk8qddm",
  },
  {
    playerId:   "Budderchew",
    clearTime:  "11:46.000",
    uploadTime: "2021-05-19",
    videoUrls:  ["https://youtu.be/sTIRfQbL6Ak"],
    src:        "srdc",
    srId:       "mkg56n1y",
  },
  {
    playerId:   "cloudindy",
    clearTime:  "11:55.000",
    uploadTime: "2020-02-16",
    videoUrls:  ["https://www.youtube.com/watch?v=6EMTnvnhimc"],
    src:        "srdc",
    srId:       "y216gw6z",
  },
  {
    playerId:   "Akemi",
    clearTime:  "11:56.400",
    uploadTime: "2017-09-20",
    videoUrls:  ["https://www.twitch.tv/videos/176199259"],
    src:        "srdc",
    srId:       "mrqnwdgy",
  },
  {
    playerId:   "-_-mehrovar-_-",
    clearTime:  "12:03.000",
    uploadTime: "2020-07-11",
    videoUrls:  ["https://www.youtube.com/watch?v=lCeVRmgE_9Q"],
    src:        "srdc",
    srId:       "zx2qxnem",
  },
  {
    playerId:   "MineplantVN",
    clearTime:  "12:40.000",
    uploadTime: "2023-06-08",
    videoUrls:  ["https://youtu.be/ysWEbY0RGoY"],
    src:        "srdc",
    srId:       "y62d3kjz",
  },
  {
    playerId:   "Hejryt12",
    clearTime:  "15:17.410",
    uploadTime: "2017-09-16",
    videoUrls:  ["https://youtu.be/Ib4RdxTJcl4"],
    src:        "srdc",
    srId:       "mek4g49m",
  },
];