/* speedrun.com 原始抓取数据 — Bosses / Ambulas / Co-op */
/* level_id=29v72vn9 | 共 9 条 */
var bosses_ambulas_coopRecords = [
  {
    playerId:   "ASmallPotato / Leigh",
    clearTime:  "1:25.500",
    uploadTime: "2017-05-03",
    videoUrls:  ["https://youtu.be/XXzP68DinMw"],
    src:        "srdc",
    srId:       "zgnn8ldy",
  },
  {
    playerId:   "Salat / L1ndell",
    clearTime:  "7:30.767",
    uploadTime: "2025-12-19",
    videoUrls:  ["https://youtu.be/2AVEBsny4Hg"],
    src:        "srdc",
    srId:       "zp5w28ry",
  },
  {
    playerId:   "Txdo / DishonoredFNG / _Dopa",
    clearTime:  "7:43.000",
    uploadTime: "2025-02-26",
    videoUrls:  ["https://www.youtube.com/watch?v=9ccBbJ1dhBU&ab_channel=Txdo"],
    src:        "srdc",
    srId:       "y6gv58qm",
  },
  {
    playerId:   "Titoxx / NightmarePlays",
    clearTime:  "7:48.000",
    uploadTime: "2024-01-05",
    videoUrls:  ["https://www.youtube.com/watch?v=Eb-CpYnNDLg"],
    src:        "srdc",
    srId:       "y4kjg3km",
  },
  {
    playerId:   "PrimedDarkeN / Boll",
    clearTime:  "11:28.666",
    uploadTime: "2020-09-25",
    videoUrls:  ["https://www.youtube.com/watch?v=TlQ_504lnJU&"],
    src:        "srdc",
    srId:       "yo32w30y",
  },
  {
    playerId:   "Salat / Mortar",
    clearTime:  "11:31.916",
    uploadTime: "2019-10-23",
    videoUrls:  ["https://www.youtube.com/watch?v=mETqwlvDSfU"],
    src:        "srdc",
    srId:       "mex1nqqz",
  },
  {
    playerId:   "-dicht.Arogamers- / -Rekken-",
    clearTime:  "11:49.000",
    uploadTime: "2018-05-09",
    videoUrls:  ["https://youtu.be/RPaUJOd6sgA"],
    src:        "srdc",
    srId:       "yl9gvpxy",
  },
  {
    playerId:   "Nusmag / Akemi / lovesz / OverusedMemes",
    clearTime:  "11:53.726",
    uploadTime: "2018-03-30",
    videoUrls:  ["https://www.youtube.com/watch?v=7Z9SA04_psw&feature=youtu.be"],
    src:        "srdc",
    srId:       "zq6npe9y",
  },
  {
    playerId:   "dimo145 / -Rekken-",
    clearTime:  "11:57.783",
    uploadTime: "2018-03-28",
    videoUrls:  ["https://youtu.be/kxxK7MjX-Zo"],
    src:        "srdc",
    srId:       "z130kvgm",
  },
];