/* speedrun.com 原始抓取数据 — Bosses / Jackal / Co-op */
/* level_id=495540j9 | 共 14 条 */
var bosses_jackal_coopRecords = [
  {
    playerId:   "silverdk / Ceejay",
    clearTime:  "0:28.000",
    uploadTime: "2019-07-07",
    videoUrls:  ["https://youtu.be/eV6UQ-tBguM"],
    src:        "srdc",
    srId:       "znrrdl8y",
  },
  {
    playerId:   "Akemi / IRojaz / Mekarazium / Nusmag",
    clearTime:  "0:31.000",
    uploadTime: "2018-03-29",
    videoUrls:  ["https://youtu.be/AcOYK3YlTj0"],
    src:        "srdc",
    srId:       "z5on8lgy",
  },
  {
    playerId:   "issaFoxy / V-_-iniciu-_-s",
    clearTime:  "0:44.000",
    uploadTime: "2020-02-20",
    videoUrls:  ["https://www.youtube.com/watch?v=KVzXOlbaZeQ"],
    src:        "srdc",
    srId:       "z012vgjy",
  },
  {
    playerId:   "GlydeFox / LapisBlaze15",
    clearTime:  "0:49.000",
    uploadTime: "2019-01-16",
    videoUrls:  ["https://www.twitch.tv/videos/365127997"],
    src:        "srdc",
    srId:       "m3o0j14m",
  },
  {
    playerId:   "titouan2512 / ._blur_.",
    clearTime:  "0:59.640",
    uploadTime: "2018-01-23",
    videoUrls:  ["https://www.youtube.com/watch?v=IzXAC_aVD5I"],
    src:        "srdc",
    srId:       "yl9d85xy",
  },
  {
    playerId:   "SlowCrow / Hejryt12 / zopney / MunchkinMel",
    clearTime:  "1:27.000",
    uploadTime: "2017-11-23",
    videoUrls:  ["https://www.youtube.com/watch?v=mQQkNtMm-H8"],
    src:        "srdc",
    srId:       "zq6e1j8y",
  },
  {
    playerId:   "LarryElPollo / Jorrak",
    clearTime:  "1:53.000",
    uploadTime: "2018-08-01",
    videoUrls:  ["https://www.youtube.com/watch?v=z2xWZY-q2sI"],
    src:        "srdc",
    srId:       "y2qxv19y",
  },
  {
    playerId:   "Salat / L1ndell",
    clearTime:  "2:13.767",
    uploadTime: "2025-12-20",
    videoUrls:  ["https://youtu.be/UZrG5m6Jj1o"],
    src:        "srdc",
    srId:       "meplw62y",
  },
  {
    playerId:   "PrimedDarkeN / Mortar",
    clearTime:  "2:18.000",
    uploadTime: "2020-09-12",
    videoUrls:  ["https://www.youtube.com/watch?v=LBnSQ_FpoHo"],
    src:        "srdc",
    srId:       "zq46r7xm",
  },
  {
    playerId:   "kinthehuman / Aura0451",
    clearTime:  "2:34.000",
    uploadTime: "2025-06-18",
    videoUrls:  ["https://youtu.be/KyM5bnJm5xM?si=ZLZvj0wfuGiVQgF8"],
    src:        "srdc",
    srId:       "mkwe9kvm",
  },
  {
    playerId:   "Lucinator239 / DiiigooW",
    clearTime:  "2:35.000",
    uploadTime: "2023-07-23",
    videoUrls:  ["https://youtu.be/nmTsp4vtMkI"],
    src:        "srdc",
    srId:       "zx3qp88z",
  },
  {
    playerId:   "ShiftDelete / CreepingChamp",
    clearTime:  "2:43.000",
    uploadTime: "2020-08-20",
    videoUrls:  ["https://youtu.be/6kcBvluUQ2g?list=PLOoCYdaYurpzssoavUuncOcivAmO4XJcr"],
    src:        "srdc",
    srId:       "z1o33wrm",
  },
  {
    playerId:   "Lucinator239 / DiiigooW",
    clearTime:  "2:57.000",
    uploadTime: "2023-03-05",
    videoUrls:  ["https://www.youtube.com/watch?v=lb5bT_ToBIE"],
    src:        "srdc",
    srId:       "znjxk83m",
  },
  {
    playerId:   "Malthael535 / xTrap_silas",
    clearTime:  "3:48.000",
    uploadTime: "2021-10-19",
    videoUrls:  ["https://youtu.be/GMjbgkznSWE"],
    src:        "srdc",
    srId:       "y93dqrry",
  },
];