/* speedrun.com 原始抓取数据 — Bosses / Jackal / Solo */
/* level_id=495540j9 | 共 58 条 */
var bosses_jackal_soloRecords = [
  {
    playerId:   "Salat",
    clearTime:  "0:11.700",
    uploadTime: "2019-11-10",
    videoUrls:  ["https://youtu.be/TxnmrdQB--w"],
    src:        "srdc",
    srId:       "z01n2xey",
  },
  {
    playerId:   "Mortar",
    clearTime:  "0:12.983",
    uploadTime: "2019-10-15",
    videoUrls:  ["https://www.youtube.com/watch?v=M2C66n15J9I"],
    src:        "srdc",
    srId:       "z01lgk9y",
  },
  {
    playerId:   ".cat",
    clearTime:  "0:14.550",
    uploadTime: "2019-08-25",
    videoUrls:  ["https://www.youtube.com/watch?v=DEWgecEiWyQ&feature=youtu.be"],
    src:        "srdc",
    srId:       "yoj7wgdm",
  },
  {
    playerId:   "Nonqui",
    clearTime:  "0:18.000",
    uploadTime: "2019-06-21",
    videoUrls:  ["https://www.youtube.com/watch?v=bpNlGT2poUs&feature=youtu.be"],
    src:        "srdc",
    srId:       "yv3j568z",
  },
  {
    playerId:   "Violetist",
    clearTime:  "0:20.000",
    uploadTime: "2019-11-14",
    videoUrls:  ["https://youtu.be/xe2w-kVCNzU"],
    src:        "srdc",
    srId:       "z01j5gey",
  },
  {
    playerId:   "zukerben",
    clearTime:  "0:20.000",
    uploadTime: "2019-12-01",
    videoUrls:  ["https://www.youtube.com/watch?v=_WQU53Sb4cI"],
    src:        "srdc",
    srId:       "yj3w55oz",
  },
  {
    playerId:   "ViiSari",
    clearTime:  "0:25.000",
    uploadTime: "2019-11-17",
    videoUrls:  ["https://youtu.be/VxCYH3OR-qw"],
    src:        "srdc",
    srId:       "z01j708y",
  },
  {
    playerId:   "holleufer98",
    clearTime:  "0:26.643",
    uploadTime: "2018-02-03",
    videoUrls:  ["https://youtu.be/zGRGsIuUzH8"],
    src:        "srdc",
    srId:       "z13nvvjm",
  },
  {
    playerId:   "Nusmag",
    clearTime:  "0:28.729",
    uploadTime: "2017-11-06",
    videoUrls:  ["https://youtu.be/9B_2JvT-kmc?t=37s"],
    src:        "srdc",
    srId:       "zq69r19y",
  },
  {
    playerId:   "-Rekken-",
    clearTime:  "0:31.966",
    uploadTime: "2018-03-27",
    videoUrls:  ["https://youtu.be/fQCaJlCXoFk"],
    src:        "srdc",
    srId:       "y97g6qkm",
  },
  {
    playerId:   "issaFoxy",
    clearTime:  "0:34.000",
    uploadTime: "2019-07-27",
    videoUrls:  ["https://www.youtube.com/watch?v=SdtuA6zM_9w"],
    src:        "srdc",
    srId:       "yv39lr4z",
  },
  {
    playerId:   "fckdaniel",
    clearTime:  "0:34.000",
    uploadTime: "2019-08-18",
    videoUrls:  ["https://www.youtube.com/watch?v=PGSuUn0g5_Q&feature=youtu.be"],
    src:        "srdc",
    srId:       "z01r6g4y",
  },
  {
    playerId:   "Chansey",
    clearTime:  "0:35.150",
    uploadTime: "2018-09-01",
    videoUrls:  ["https://www.youtube.com/watch?v=f4fNLu0TUOE"],
    src:        "srdc",
    srId:       "zq3g5xry",
  },
  {
    playerId:   "-dicht.Arogamers-",
    clearTime:  "0:37.299",
    uploadTime: "2018-06-20",
    videoUrls:  ["https://www.youtube.com/watch?v=houtRakXfUY&feature=youtu.be"],
    src:        "srdc",
    srId:       "ywp1or9z",
  },
  {
    playerId:   "The.Boogeyman",
    clearTime:  "0:41.000",
    uploadTime: "2019-06-22",
    videoUrls:  ["https://www.youtube.com/watch?v=Dr2AQIqgyfY"],
    src:        "srdc",
    srId:       "y6ro0jqy",
  },
  {
    playerId:   "LapisBlaze15",
    clearTime:  "0:43.000",
    uploadTime: "2018-10-28",
    videoUrls:  ["https://www.youtube.com/watch?v=ieFooBrUB7w"],
    src:        "srdc",
    srId:       "m7p6o50m",
  },
  {
    playerId:   "zopney",
    clearTime:  "0:49.000",
    uploadTime: "2018-05-08",
    videoUrls:  ["https://www.youtube.com/watch?v=lrl_SGK1EkQ"],
    src:        "srdc",
    srId:       "y23l5e5m",
  },
  {
    playerId:   "El_Nacho",
    clearTime:  "0:55.000",
    uploadTime: "2019-04-13",
    videoUrls:  ["https://www.youtube.com/watch?v=MGaVAD99u6Y"],
    src:        "srdc",
    srId:       "m3o484qm",
  },
  {
    playerId:   "dbrandt01",
    clearTime:  "0:59.000",
    uploadTime: "2018-08-30",
    videoUrls:  ["https://www.twitch.tv/videos/303964718"],
    src:        "srdc",
    srId:       "m7p8l44m",
  },
  {
    playerId:   "TheLegacy",
    clearTime:  "1:00.000",
    uploadTime: "2018-04-29",
    videoUrls:  ["https://youtu.be/z2GpUqwkGEc"],
    src:        "srdc",
    srId:       "mk4613ly",
  },
  {
    playerId:   "Derpy_Aura115",
    clearTime:  "1:05.900",
    uploadTime: "2018-11-20",
    videoUrls:  ["https://www.youtube.com/watch?v=iPIn8CuPQsQ"],
    src:        "srdc",
    srId:       "ywpvelnz",
  },
  {
    playerId:   "silentdrumr",
    clearTime:  "1:08.000",
    uploadTime: "2013-11-21",
    videoUrls:  ["https://www.youtube.com/watch?v=m3y7Xacfaf4"],
    src:        "srdc",
    srId:       "ydq7oowm",
  },
  {
    playerId:   "Jcygan",
    clearTime:  "1:12.000",
    uploadTime: "2019-03-12",
    videoUrls:  ["https://youtu.be/Ao0tZvhwvec"],
    src:        "srdc",
    srId:       "zp05xxrm",
  },
  {
    playerId:   "Dys",
    clearTime:  "1:12.210",
    uploadTime: "2018-05-20",
    videoUrls:  ["https://youtu.be/E9DXfDIuEB0"],
    src:        "srdc",
    srId:       "y67k456m",
  },
  {
    playerId:   "iiShadow87",
    clearTime:  "1:17.000",
    uploadTime: "2019-12-06",
    videoUrls:  ["https://www.youtube.com/watch?v=4IFKAVg8RZg&feature=youtu.be"],
    src:        "srdc",
    srId:       "m31kklgz",
  },
  {
    playerId:   "HyperDoge",
    clearTime:  "1:18.000",
    uploadTime: "2018-04-21",
    videoUrls:  ["https://www.youtube.com/watch?v=gvZGZqr1Y3w&feature=youtu.be"],
    src:        "srdc",
    srId:       "mekqo69m",
  },
  {
    playerId:   "-p4p-",
    clearTime:  "1:19.000",
    uploadTime: "2018-03-13",
    videoUrls:  ["https://youtu.be/DIIyiXPH5sU"],
    src:        "srdc",
    srId:       "yl95lx3y",
  },
  {
    playerId:   "ASmallPotato",
    clearTime:  "1:32.430",
    uploadTime: "2017-04-30",
    videoUrls:  ["https://www.youtube.com/watch?v=tYJxeuvYytw"],
    src:        "srdc",
    srId:       "y677xpqm",
  },
  {
    playerId:   "Talosaurus",
    clearTime:  "1:57.860",
    uploadTime: "2017-05-03",
    videoUrls:  ["https://www.youtube.com/watch?v=djrWMXy6OIY"],
    src:        "srdc",
    srId:       "mrqqv77y",
  },
  {
    playerId:   "Salat",
    clearTime:  "2:04.000",
    uploadTime: "2026-01-20",
    videoUrls:  ["https://youtu.be/q0xoFixEGEo"],
    src:        "srdc",
    srId:       "mr5gpr7y",
  },
  {
    playerId:   "_Gabriel",
    clearTime:  "2:12.000",
    uploadTime: "2023-01-09",
    videoUrls:  ["https://www.youtube.com/watch?v=Hj7O0bIKmR0"],
    src:        "srdc",
    srId:       "z1q89vgy",
  },
  {
    playerId:   "sakivali",
    clearTime:  "2:13.300",
    uploadTime: "2024-11-05",
    videoUrls:  ["https://youtu.be/-ovGwPVDYCQ"],
    src:        "srdc",
    srId:       "yvxeex6z",
  },
  {
    playerId:   "Mortar",
    clearTime:  "2:14.000",
    uploadTime: "2020-09-13",
    videoUrls:  ["https://www.youtube.com/watch?v=Y1OjTtk7jE8"],
    src:        "srdc",
    srId:       "z1o3xl9m",
  },
  {
    playerId:   "Wasamii",
    clearTime:  "2:15.916",
    uploadTime: "2022-01-24",
    videoUrls:  ["https://youtu.be/WE_YZmTBQKY"],
    src:        "srdc",
    srId:       "z0olodoz",
  },
  {
    playerId:   "L1ndell",
    clearTime:  "2:16.000",
    uploadTime: "2021-11-01",
    videoUrls:  ["https://youtu.be/kzdfiwoMo-M"],
    src:        "srdc",
    srId:       "zgr9njdm",
  },
  {
    playerId:   "Febi",
    clearTime:  "2:16.467",
    uploadTime: "2021-03-28",
    videoUrls:  ["https://www.youtube.com/watch?v=TDLJkr14pGQ"],
    src:        "srdc",
    srId:       "z50nnk5y",
  },
  {
    playerId:   "PrimedDarkeN",
    clearTime:  "2:20.000",
    uploadTime: "2020-09-13",
    videoUrls:  ["https://www.youtube.com/watch?v=0bn17n7TD7k"],
    src:        "srdc",
    srId:       "zxdvg4gy",
  },
  {
    playerId:   "--Q--roissant",
    clearTime:  "2:23.000",
    uploadTime: "2021-01-03",
    videoUrls:  ["https://www.youtube.com/watch?v=UgI6HSb5m6Q&feature=youtu.be"],
    src:        "srdc",
    srId:       "z1o4627m",
  },
  {
    playerId:   "RoniPrime",
    clearTime:  "2:23.000",
    uploadTime: "2026-04-01",
    videoUrls:  ["https://youtu.be/IXIJseDSc7A"],
    src:        "srdc",
    srId:       "mrwnvx4y",
  },
  {
    playerId:   "LuisGuerra",
    clearTime:  "2:24.000",
    uploadTime: "2022-03-28",
    videoUrls:  ["https://youtu.be/q5b5nXI9fMc"],
    src:        "srdc",
    srId:       "z0ov3xez",
  },
  {
    playerId:   "KateBishop",
    clearTime:  "2:25.000",
    uploadTime: "2022-03-05",
    videoUrls:  ["https://youtu.be/1pfQ4WRsKW0"],
    src:        "srdc",
    srId:       "yore17jy",
  },
  {
    playerId:   "Onyxl",
    clearTime:  "2:26.000",
    uploadTime: "2023-08-27",
    videoUrls:  ["https://www.youtube.com/watch?v=xyYBskifNNM"],
    src:        "srdc",
    srId:       "yonw665z",
  },
  {
    playerId:   "HALEHYDRA",
    clearTime:  "2:27.000",
    uploadTime: "2018-07-20",
    videoUrls:  ["https://youtu.be/98lXXlx0n8Q"],
    src:        "srdc",
    srId:       "y2q1417y",
  },
  {
    playerId:   "-LayFeyson-",
    clearTime:  "2:27.000",
    uploadTime: "2020-12-01",
    videoUrls:  ["https://www.youtube.com/watch?v=rnq-I3HhH5U&feature=youtu.be"],
    src:        "srdc",
    srId:       "zgv8g20z",
  },
  {
    playerId:   "haryx7",
    clearTime:  "2:29.000",
    uploadTime: "2020-09-13",
    videoUrls:  ["https://youtu.be/garDswY4Ggw"],
    src:        "srdc",
    srId:       "y6r7d7qy",
  },
  {
    playerId:   "SABBA_HOSTUMEX",
    clearTime:  "2:29.000",
    uploadTime: "2026-01-11",
    videoUrls:  ["https://youtu.be/Umz9KjPr6Sg"],
    src:        "srdc",
    srId:       "zn59rxvz",
  },
  {
    playerId:   "Founder",
    clearTime:  "2:30.000",
    uploadTime: "2021-02-21",
    videoUrls:  ["https://www.youtube.com/watch?v=XYrrH4dqKck&ab_channel=-Founder"],
    src:        "srdc",
    srId:       "y8vxxgwz",
  },
  {
    playerId:   "LeChat930",
    clearTime:  "2:33.000",
    uploadTime: "2023-07-06",
    videoUrls:  ["https://www.youtube.com/watch?v=s1aCUQZlFQA"],
    src:        "srdc",
    srId:       "y62o6v6z",
  },
  {
    playerId:   "TCCH",
    clearTime:  "2:39.000",
    uploadTime: "2020-06-14",
    videoUrls:  ["https://www.youtube.com/watch?v=KFnWWj2ZbbA"],
    src:        "srdc",
    srId:       "yw8609py",
  },
  {
    playerId:   "Kyshiro_Explorer",
    clearTime:  "2:40.000",
    uploadTime: "2025-09-06",
    videoUrls:  ["https://youtu.be/_TsSaQiBEUM?si=uGQNl4Ikk4IM681_"],
    src:        "srdc",
    srId:       "zg6581jm",
  },
  {
    playerId:   "Whatisreal",
    clearTime:  "2:42.000",
    uploadTime: "2020-06-14",
    videoUrls:  ["https://youtu.be/AznqnZZbu_E"],
    src:        "srdc",
    srId:       "znkq029z",
  },
  {
    playerId:   "TheLegacy___",
    clearTime:  "2:53.000",
    uploadTime: "2020-07-28",
    videoUrls:  ["https://youtu.be/QVljer2TSbY"],
    src:        "srdc",
    srId:       "zprk7nnm",
  },
  {
    playerId:   "CorgtheMighty",
    clearTime:  "2:53.000",
    uploadTime: "2021-02-15",
    videoUrls:  ["https://www.twitch.tv/videos/916404736"],
    src:        "srdc",
    srId:       "yv2rjg6m",
  },
  {
    playerId:   "EV012",
    clearTime:  "3:05.000",
    uploadTime: "2021-05-23",
    videoUrls:  ["https://youtu.be/kFw8zZO-hE8"],
    src:        "srdc",
    srId:       "me7jpv2y",
  },
  {
    playerId:   "crashkiller089824",
    clearTime:  "3:07.000",
    uploadTime: "2021-05-23",
    videoUrls:  ["https://www.youtube.com/watch?v=5TsWLeS-Kkg"],
    src:        "srdc",
    srId:       "yjgxqndy",
  },
  {
    playerId:   "Protuniks",
    clearTime:  "3:27.000",
    uploadTime: "2020-06-13",
    videoUrls:  ["https://youtu.be/sbLS8z_jXkM"],
    src:        "srdc",
    srId:       "yokd9xjz",
  },
  {
    playerId:   "LieutenantKermit2",
    clearTime:  "4:02.000",
    uploadTime: "2021-12-11",
    videoUrls:  ["https://m.twitch.tv/videos/1230677663"],
    src:        "srdc",
    srId:       "zgd73eez",
  },
  {
    playerId:   "Shredmachine",
    clearTime:  "4:15.000",
    uploadTime: "2025-04-04",
    videoUrls:  ["https://www.youtube.com/watch?v=aI8NTUM6Xy4"],
    src:        "srdc",
    srId:       "yww7vdpy",
  },
];