/* speedrun.com 原始抓取数据 — Bosses / Lephantis / Co-op */
/* level_id=n934oped | 共 14 条 */
var bosses_lephantis_coopRecords = [
  {
    playerId:   "Salat / Mortar",
    clearTime:  "1:07.716",
    uploadTime: "2019-09-20",
    videoUrls:  ["https://www.youtube.com/watch?v=xLch03XtIpc", "https://www.youtube.com/watch?v=QngVtsTt8nY"],
    src:        "srdc",
    srId:       "yj3xoeoz",
  },
  {
    playerId:   "Salat / L1ndell",
    clearTime:  "1:13.000",
    uploadTime: "2025-12-20",
    videoUrls:  ["https://www.youtube.com/watch?v=q9UeY4luikU", "https://youtu.be/R039k5Nh0Ac"],
    src:        "srdc",
    srId:       "z0kjd7jm",
  },
  {
    playerId:   "Txdo / DishonoredFNG / _Dopa",
    clearTime:  "1:15.000",
    uploadTime: "2025-02-26",
    videoUrls:  ["https://www.youtube.com/watch?v=B3IWGjmXKLk&ab_channel=Txdo"],
    src:        "srdc",
    srId:       "yvnl65xm",
  },
  {
    playerId:   "PrimedDarkeN / Mortar",
    clearTime:  "1:18.000",
    uploadTime: "2021-02-09",
    videoUrls:  ["https://www.youtube.com/watch?v=t1rACPLwz0k"],
    src:        "srdc",
    srId:       "yv2o308m",
  },
  {
    playerId:   "_Q_JS / SuiEXE",
    clearTime:  "1:27.000",
    uploadTime: "2021-02-06",
    videoUrls:  ["https://youtu.be/ZvTJU6Q1chE"],
    src:        "srdc",
    srId:       "m3nr31qy",
  },
  {
    playerId:   "xanzath / Ceejay",
    clearTime:  "1:38.000",
    uploadTime: "2019-03-20",
    videoUrls:  ["https://youtu.be/tR20bAEOywI"],
    src:        "srdc",
    srId:       "yj4r6edy",
  },
  {
    playerId:   "Koto / Divlyn",
    clearTime:  "1:40.000",
    uploadTime: "2018-04-08",
    videoUrls:  ["https://www.youtube.com/watch?v=S8Y1b7kNvUc"],
    src:        "srdc",
    srId:       "y674npqm",
  },
  {
    playerId:   "OverusedMemes / lovesz / Nusmag",
    clearTime:  "1:42.000",
    uploadTime: "2018-03-29",
    videoUrls:  ["https://youtu.be/qcSUbZ3cS8w"],
    src:        "srdc",
    srId:       "mk4xpwvy",
  },
  {
    playerId:   "PrimedDarkeN / Boll",
    clearTime:  "1:42.000",
    uploadTime: "2020-12-31",
    videoUrls:  ["https://www.youtube.com/watch?v=P576AWDpv3o&feature=youtu.be"],
    src:        "srdc",
    srId:       "zgv11ejz",
  },
  {
    playerId:   "chroamy / hampster",
    clearTime:  "1:57.000",
    uploadTime: "2021-02-14",
    videoUrls:  ["https://youtu.be/e-D4vFFEdsI"],
    src:        "srdc",
    srId:       "m3n6k2dy",
  },
  {
    playerId:   "sadkdawu / Fr0z3nTempest",
    clearTime:  "2:04.000",
    uploadTime: "2025-11-28",
    videoUrls:  ["https://youtu.be/GNHHzufPHBI"],
    src:        "srdc",
    srId:       "y6805g6z",
  },
  {
    playerId:   "AuhertBrahma / death666213 / Skywardslaser",
    clearTime:  "2:20.000",
    uploadTime: "2018-08-18",
    videoUrls:  ["https://www.youtube.com/watch?v=RoxWB0JTQZ8"],
    src:        "srdc",
    srId:       "yd307wqz",
  },
  {
    playerId:   "ShiftDelete / CreepingChamp",
    clearTime:  "2:29.000",
    uploadTime: "2020-08-20",
    videoUrls:  ["https://youtu.be/PT2PqEvvh-c?list=PLOoCYdaYurpzssoavUuncOcivAmO4XJcr"],
    src:        "srdc",
    srId:       "m7599rwz",
  },
  {
    playerId:   "desmond-_- / spaghettigio69",
    clearTime:  "4:16.000",
    uploadTime: "2020-12-06",
    videoUrls:  ["https://youtu.be/Mt_IqWcUcHk"],
    src:        "srdc",
    srId:       "zn327gly",
  },
];