/* speedrun.com 原始抓取数据 — Bosses / Lephantis / Solo */
/* level_id=n934oped | 共 29 条 */
var bosses_lephantis_soloRecords = [
  {
    playerId:   "Endryx_Ow",
    clearTime:  "0:59.833",
    uploadTime: "2025-06-08",
    videoUrls:  ["https://youtu.be/sEgEzoMyYo8?si=CC0BlhKaBeDLNSkG"],
    src:        "srdc",
    srId:       "mkwgd5lm",
  },
  {
    playerId:   "Salat",
    clearTime:  "1:02.083",
    uploadTime: "2025-06-06",
    videoUrls:  ["https://youtu.be/ZRUEuSK5ank"],
    src:        "srdc",
    srId:       "y9e9nwkz",
  },
  {
    playerId:   "DishonoredFNG",
    clearTime:  "1:06.933",
    uploadTime: "2025-01-04",
    videoUrls:  ["https://youtu.be/kxA2FDG4D3o"],
    src:        "srdc",
    srId:       "ylpolvnm",
  },
  {
    playerId:   "Titoxx",
    clearTime:  "1:07.700",
    uploadTime: "2024-07-14",
    videoUrls:  ["https://www.youtube.com/watch?v=mAVWTjXT-2A"],
    src:        "srdc",
    srId:       "y9d784nm",
  },
  {
    playerId:   "-VS-Silv0r",
    clearTime:  "1:12.766",
    uploadTime: "2019-06-19",
    videoUrls:  ["https://www.youtube.com/watch?v=MQQyecdC2nQ"],
    src:        "srdc",
    srId:       "zgk7eldy",
  },
  {
    playerId:   "Miister",
    clearTime:  "1:14.150",
    uploadTime: "2021-08-16",
    videoUrls:  ["https://www.youtube.com/watch?v=Y4XUotC5uaU"],
    src:        "srdc",
    srId:       "zgrvgqdm",
  },
  {
    playerId:   "KhungLongSamSeggs",
    clearTime:  "1:15.000",
    uploadTime: "2025-06-12",
    videoUrls:  ["https://youtu.be/zB7kR82jaXU"],
    src:        "srdc",
    srId:       "zg6r75jm",
  },
  {
    playerId:   "Chansey",
    clearTime:  "1:15.850",
    uploadTime: "2018-09-07",
    videoUrls:  ["https://www.youtube.com/watch?v=FDuoYPBgbiY"],
    src:        "srdc",
    srId:       "yj4g1xoy",
  },
  {
    playerId:   "zukerben",
    clearTime:  "1:20.000",
    uploadTime: "2019-05-09",
    videoUrls:  ["https://www.youtube.com/watch?v=CjJ8qzWnJEE"],
    src:        "srdc",
    srId:       "m7prne0m",
  },
  {
    playerId:   "malkiium",
    clearTime:  "1:24.000",
    uploadTime: "2025-05-30",
    videoUrls:  ["https://www.youtube.com/watch?v=PsTpQKP_U14"],
    src:        "srdc",
    srId:       "y28vdewy",
  },
  {
    playerId:   "-VS-Biergrills",
    clearTime:  "1:25.000",
    uploadTime: "2018-08-28",
    videoUrls:  ["https://youtu.be/NEIxBvJT_-4"],
    src:        "srdc",
    srId:       "me890g0m",
  },
  {
    playerId:   "Prtsscout",
    clearTime:  "1:26.000",
    uploadTime: "2021-06-07",
    videoUrls:  ["https://youtu.be/4GznBm-xPNQ"],
    src:        "srdc",
    srId:       "ydrgow0z",
  },
  {
    playerId:   "striker350z",
    clearTime:  "1:27.000",
    uploadTime: "2021-04-07",
    videoUrls:  ["https://youtu.be/w4BIkn8FG4E"],
    src:        "srdc",
    srId:       "yo91d10y",
  },
  {
    playerId:   "Negabite",
    clearTime:  "1:29.133",
    uploadTime: "2018-10-11",
    videoUrls:  ["https://www.youtube.com/watch?v=7-rCWNLGLhM"],
    src:        "srdc",
    srId:       "mr862j7y",
  },
  {
    playerId:   "Divlyn",
    clearTime:  "1:32.000",
    uploadTime: "2018-04-15",
    videoUrls:  ["https://www.youtube.com/watch?v=8X4x_uNDgJ4"],
    src:        "srdc",
    srId:       "z0e4k7om",
  },
  {
    playerId:   "Founder",
    clearTime:  "1:33.000",
    uploadTime: "2021-02-21",
    videoUrls:  ["https://www.youtube.com/watch?v=gzcVCcemc1M&ab_channel=-Founder"],
    src:        "srdc",
    srId:       "yw06622m",
  },
  {
    playerId:   "-Rekken-",
    clearTime:  "1:34.166",
    uploadTime: "2018-06-28",
    videoUrls:  ["https://youtu.be/q8QbFOQcXeU"],
    src:        "srdc",
    srId:       "z111xp9z",
  },
  {
    playerId:   "Arkados",
    clearTime:  "1:38.000",
    uploadTime: "2018-05-30",
    videoUrls:  ["https://www.youtube.com/watch?v=fmEU-BUztos"],
    src:        "srdc",
    srId:       "y2q9j97y",
  },
  {
    playerId:   "LeChat930",
    clearTime:  "1:41.000",
    uploadTime: "2023-07-06",
    videoUrls:  ["https://www.youtube.com/watch?v=iLTLCrZAudY&t=3s"],
    src:        "srdc",
    srId:       "z0jnr54y",
  },
  {
    playerId:   "FearOmnicide",
    clearTime:  "1:44.000",
    uploadTime: "2020-09-03",
    videoUrls:  ["https://youtu.be/wDiP3a7q0pg"],
    src:        "srdc",
    srId:       "z05v0d8m",
  },
  {
    playerId:   "Fungdoobit",
    clearTime:  "1:44.000",
    uploadTime: "2023-07-03",
    videoUrls:  ["https://youtu.be/T-TOxwtNqi4"],
    src:        "srdc",
    srId:       "yl61x3ny",
  },
  {
    playerId:   "LurkyOfAstora",
    clearTime:  "1:46.006",
    uploadTime: "2018-12-26",
    videoUrls:  ["https://www.youtube.com/watch?v=Ma5BUVHheVQ"],
    src:        "srdc",
    srId:       "y43kerqz",
  },
  {
    playerId:   "Nusmag",
    clearTime:  "1:46.907",
    uploadTime: "2017-09-21",
    videoUrls:  ["https://youtu.be/Mbax6jOgdU0"],
    src:        "srdc",
    srId:       "zq6vodxy",
  },
  {
    playerId:   "lovesz",
    clearTime:  "1:48.375",
    uploadTime: "2017-09-01",
    videoUrls:  ["https://www.youtube.com/watch?v=3qFIBpW2tg0&feature=youtu.be"],
    src:        "srdc",
    srId:       "z0ervw9m",
  },
  {
    playerId:   "D3648",
    clearTime:  "1:56.000",
    uploadTime: "2021-10-19",
    videoUrls:  ["https://youtu.be/ser8jzf-Hi4"],
    src:        "srdc",
    srId:       "y8ep705y",
  },
  {
    playerId:   "HaventMetYou",
    clearTime:  "2:26.000",
    uploadTime: "2021-02-26",
    videoUrls:  ["https://youtu.be/wxeDS04zfKs"],
    src:        "srdc",
    srId:       "y8v0lrnz",
  },
  {
    playerId:   "Nightey3s",
    clearTime:  "2:57.066",
    uploadTime: "2018-02-01",
    videoUrls:  ["https://www.youtube.com/watch?v=7E_z0Cd3g18"],
    src:        "srdc",
    srId:       "yo22ej5z",
  },
  {
    playerId:   "Ucyra",
    clearTime:  "4:42.000",
    uploadTime: "2019-01-04",
    videoUrls:  ["https://www.youtube.com/watch?v=lflnJhivgyo"],
    src:        "srdc",
    srId:       "yvjl4l6y",
  },
  {
    playerId:   "ReoSpark",
    clearTime:  "4:50.000",
    uploadTime: "2018-05-13",
    videoUrls:  ["https://www.bilibili.com/video/av21795068?from=search&seid=5153318192355301392"],
    src:        "srdc",
    srId:       "yjknp83m",
  },
];