/* speedrun.com 原始抓取数据 — Bosses / Raptors / Solo */
/* level_id=ewpxrvzd | 共 22 条 */
var bosses_raptors_soloRecords = [
  {
    playerId:   "Salat",
    clearTime:  "0:30.966",
    uploadTime: "2025-11-30",
    videoUrls:  ["https://youtu.be/-MomuTQxsg0"],
    src:        "srdc",
    srId:       "m7v6265m",
  },
  {
    playerId:   "L1ndell",
    clearTime:  "0:32.000",
    uploadTime: "2023-01-30",
    videoUrls:  ["https://youtu.be/zuuKUD_vXT4"],
    src:        "srdc",
    srId:       "zg2pw10y",
  },
  {
    playerId:   "PrimedDarkeN",
    clearTime:  "0:35.200",
    uploadTime: "2021-04-19",
    videoUrls:  ["https://www.youtube.com/watch?v=FsH8dc3CT0w"],
    src:        "srdc",
    srId:       "z5r1e0dy",
  },
  {
    playerId:   "Mortar",
    clearTime:  "0:36.800",
    uploadTime: "2021-04-11",
    videoUrls:  ["https://www.youtube.com/watch?v=jb-7juRvTcI"],
    src:        "srdc",
    srId:       "zn1wvd3m",
  },
  {
    playerId:   "Wasamii",
    clearTime:  "0:41.000",
    uploadTime: "2022-11-09",
    videoUrls:  ["https://youtu.be/sGNzPFaBN-A"],
    src:        "srdc",
    srId:       "y6x497py",
  },
  {
    playerId:   "Nusmag",
    clearTime:  "0:45.829",
    uploadTime: "2018-03-08",
    videoUrls:  ["https://youtu.be/erav7hXYRmg"],
    src:        "srdc",
    srId:       "y97wnpem",
  },
  {
    playerId:   "zukerben",
    clearTime:  "0:48.000",
    uploadTime: "2019-05-03",
    videoUrls:  ["https://www.youtube.com/watch?v=Gtn3NTcDmtg"],
    src:        "srdc",
    srId:       "zp07ldgm",
  },
  {
    playerId:   "-Rekken-",
    clearTime:  "0:48.949",
    uploadTime: "2018-05-10",
    videoUrls:  ["https://youtu.be/vuAGCqV4ACY"],
    src:        "srdc",
    srId:       "yl9gq43y",
  },
  {
    playerId:   "Dawiddym",
    clearTime:  "0:49.000",
    uploadTime: "2021-04-11",
    videoUrls:  ["https://youtu.be/D8PCaNeVuoE"],
    src:        "srdc",
    srId:       "ywqev2py",
  },
  {
    playerId:   "OgvDams",
    clearTime:  "0:49.000",
    uploadTime: "2022-08-26",
    videoUrls:  ["https://www.youtube.com/watch?v=5NQUt79OLmw"],
    src:        "srdc",
    srId:       "znq1gj9z",
  },
  {
    playerId:   "Akemi",
    clearTime:  "0:53.203",
    uploadTime: "2018-03-04",
    videoUrls:  ["https://youtu.be/At93LpmKc3U"],
    src:        "srdc",
    srId:       "zpqo7qry",
  },
  {
    playerId:   "V-_-iniciu-_-s",
    clearTime:  "0:56.000",
    uploadTime: "2019-09-21",
    videoUrls:  ["https://youtu.be/3cIe7EkMZQU"],
    src:        "srdc",
    srId:       "m7qwon4z",
  },
  {
    playerId:   "holleufer98",
    clearTime:  "0:56.723",
    uploadTime: "2017-09-19",
    videoUrls:  ["https://www.youtube.com/watch?v=94oLYIBaV_0&feature=youtu.be"],
    src:        "srdc",
    srId:       "y457v92m",
  },
  {
    playerId:   "Wiktoryk",
    clearTime:  "0:57.000",
    uploadTime: "2022-08-20",
    videoUrls:  ["https://www.youtube.com/watch?v=DSRxd98rs5g"],
    src:        "srdc",
    srId:       "z0l6exoz",
  },
  {
    playerId:   "Chansey",
    clearTime:  "0:59.600",
    uploadTime: "2018-09-05",
    videoUrls:  ["https://www.youtube.com/watch?v=pDZlSyEvEnI"],
    src:        "srdc",
    srId:       "yo27j95z",
  },
  {
    playerId:   "LeChat930",
    clearTime:  "1:13.000",
    uploadTime: "2023-07-06",
    videoUrls:  ["https://www.youtube.com/watch?v=dkxDWZ4bgOE"],
    src:        "srdc",
    srId:       "y62o53jz",
  },
  {
    playerId:   "FXCloud",
    clearTime:  "1:16.000",
    uploadTime: "2019-09-08",
    videoUrls:  ["https://youtu.be/Wau0NULr6Uw"],
    src:        "srdc",
    srId:       "mex4548z",
  },
  {
    playerId:   "Ming732",
    clearTime:  "1:17.000",
    uploadTime: "2021-02-11",
    videoUrls:  ["https://youtu.be/FV6k3TZ5cVo"],
    src:        "srdc",
    srId:       "y2v72dwz",
  },
  {
    playerId:   "FearOmnicide",
    clearTime:  "1:26.000",
    uploadTime: "2019-05-30",
    videoUrls:  ["https://youtu.be/mtlATO_Ce5Q"],
    src:        "srdc",
    srId:       "zp4q01gz",
  },
  {
    playerId:   "zopney",
    clearTime:  "1:40.000",
    uploadTime: "2018-05-15",
    videoUrls:  ["https://www.youtube.com/watch?v=ZIDD4jjEMMo"],
    src:        "srdc",
    srId:       "zq3k1l9y",
  },
  {
    playerId:   "LapisBlaze15",
    clearTime:  "1:40.000",
    uploadTime: "2019-01-14",
    videoUrls:  ["https://www.twitch.tv/videos/364127877"],
    src:        "srdc",
    srId:       "m3o0lpwm",
  },
  {
    playerId:   "ASmallPotato",
    clearTime:  "1:48.290",
    uploadTime: "2017-04-30",
    videoUrls:  ["https://youtu.be/ZOmsqFo1rGU"],
    src:        "srdc",
    srId:       "zpqqd4ry",
  },
];