/* speedrun.com 原始抓取数据 — Bosses / Ropalolyst / Solo */
/* level_id=r9grp4kw | 共 38 条 */
var bosses_ropalolyst_soloRecords = [
  {
    playerId:   "Txdo",
    clearTime:  "2:30.000",
    uploadTime: "2025-01-26",
    videoUrls:  ["https://www.youtube.com/watch?v=gfw8RNE40GI&ab_channel=Txdo"],
    src:        "srdc",
    srId:       "yoqr8p0z",
  },
  {
    playerId:   "SarcasticPengwuin",
    clearTime:  "2:32.200",
    uploadTime: "2023-11-10",
    videoUrls:  ["https://www.youtube.com/watch?v=H49wVBjB-pQ"],
    src:        "srdc",
    srId:       "yd2wjvwm",
  },
  {
    playerId:   "_Gabriel",
    clearTime:  "2:36.000",
    uploadTime: "2023-01-22",
    videoUrls:  ["https://www.youtube.com/watch?v=kd_UfxjUZFQ"],
    src:        "srdc",
    srId:       "ywvk243z",
  },
  {
    playerId:   "zukerben",
    clearTime:  "2:37.000",
    uploadTime: "2019-07-10",
    videoUrls:  ["https://www.youtube.com/watch?v=oakfruOeuF4"],
    src:        "srdc",
    srId:       "y9509vez",
  },
  {
    playerId:   "aamoew",
    clearTime:  "2:39.000",
    uploadTime: "2026-04-28",
    videoUrls:  ["https://youtu.be/eKqS4sbs_rg"],
    src:        "srdc",
    srId:       "zxp3qj8y",
  },
  {
    playerId:   "SAVentox",
    clearTime:  "2:40.000",
    uploadTime: "2025-06-05",
    videoUrls:  ["https://youtu.be/mdcspUDwQ9M?si=grak1fKRfJX6thSJ"],
    src:        "srdc",
    srId:       "yljq0e3m",
  },
  {
    playerId:   "_BaJIMaTbE_",
    clearTime:  "2:43.000",
    uploadTime: "2026-06-01",
    videoUrls:  ["https://www.youtube.com/watch?v=oAFp4jCmd6E"],
    src:        "srdc",
    srId:       "y26rn35m",
  },
  {
    playerId:   "L1ndell",
    clearTime:  "2:44.464",
    uploadTime: "2021-06-07",
    videoUrls:  ["https://www.youtube.com/watch?v=6Lyo6p4G86o&ab_channel=LindellFTWCore"],
    src:        "srdc",
    srId:       "zn1jd09m",
  },
  {
    playerId:   "xAlexTheGreat",
    clearTime:  "2:46.000",
    uploadTime: "2023-03-23",
    videoUrls:  ["https://youtu.be/w5E3vGnsJoI"],
    src:        "srdc",
    srId:       "z5e6dpjz",
  },
  {
    playerId:   "Nalviscoming14",
    clearTime:  "2:46.132",
    uploadTime: "2022-07-13",
    videoUrls:  ["https://www.youtube.com/watch?v=X-feWy3iyhc"],
    src:        "srdc",
    srId:       "yw3577nm",
  },
  {
    playerId:   "tobias9876542",
    clearTime:  "2:49.202",
    uploadTime: "2021-04-29",
    videoUrls:  ["https://youtu.be/bEzMdfpEqPs"],
    src:        "srdc",
    srId:       "z5rjg6ny",
  },
  {
    playerId:   "The_Lord_222",
    clearTime:  "2:51.000",
    uploadTime: "2022-10-12",
    videoUrls:  ["https://youtu.be/oLf5LVE2pPA"],
    src:        "srdc",
    srId:       "y9xp02ey",
  },
  {
    playerId:   "Gravity_Assist",
    clearTime:  "2:52.000",
    uploadTime: "2023-08-19",
    videoUrls:  ["https://youtu.be/5J2BGVgzYtU"],
    src:        "srdc",
    srId:       "meldqe9z",
  },
  {
    playerId:   "Wasamii",
    clearTime:  "2:53.000",
    uploadTime: "2021-03-28",
    videoUrls:  ["https://youtu.be/_OeYXfD_U5k"],
    src:        "srdc",
    srId:       "zno66r8y",
  },
  {
    playerId:   "Azuthrax",
    clearTime:  "2:56.000",
    uploadTime: "2024-05-30",
    videoUrls:  ["https://www.youtube.com/watch?v=IYNXBHSFMcM"],
    src:        "srdc",
    srId:       "m7nl9lwz",
  },
  {
    playerId:   "Febi",
    clearTime:  "3:02.000",
    uploadTime: "2021-03-28",
    videoUrls:  ["https://www.youtube.com/watch?v=ZK93GczthEc"],
    src:        "srdc",
    srId:       "yj1r70ny",
  },
  {
    playerId:   "MyFaceHz",
    clearTime:  "3:03.000",
    uploadTime: "2022-07-01",
    videoUrls:  ["https://youtu.be/bRdTrvh_k-A"],
    src:        "srdc",
    srId:       "znp915lm",
  },
  {
    playerId:   "striker350z",
    clearTime:  "3:08.000",
    uploadTime: "2021-03-31",
    videoUrls:  ["https://youtu.be/2mQgSVkbVL8"],
    src:        "srdc",
    srId:       "z1849xwy",
  },
  {
    playerId:   "LeChat930",
    clearTime:  "3:08.000",
    uploadTime: "2023-07-22",
    videoUrls:  ["https://www.youtube.com/watch?v=I5R6jb3Qh3E"],
    src:        "srdc",
    srId:       "zqj8915m",
  },
  {
    playerId:   "V-_-iniciu-_-s",
    clearTime:  "3:10.000",
    uploadTime: "2019-10-26",
    videoUrls:  ["https://youtu.be/riXRvDF2nqQ"],
    src:        "srdc",
    srId:       "y6lx17qy",
  },
  {
    playerId:   "FearOmnicide",
    clearTime:  "3:11.000",
    uploadTime: "2022-06-21",
    videoUrls:  ["https://youtu.be/eMjhoL2x6_s"],
    src:        "srdc",
    srId:       "me30dn3z",
  },
  {
    playerId:   "PonasKugelis",
    clearTime:  "3:14.000",
    uploadTime: "2021-10-24",
    videoUrls:  ["https://youtu.be/DMTnO1stPSo"],
    src:        "srdc",
    srId:       "z1xvnl7m",
  },
  {
    playerId:   "BlackMechs",
    clearTime:  "3:14.000",
    uploadTime: "2024-06-03",
    videoUrls:  ["https://youtu.be/OsNjndvGr7w?si=GLDp1-9kPxVL3qNr"],
    src:        "srdc",
    srId:       "zxq0w28m",
  },
  {
    playerId:   "DeweySalt",
    clearTime:  "3:21.000",
    uploadTime: "2020-12-07",
    videoUrls:  ["https://www.youtube.com/watch?v=9y9wDARlAJE"],
    src:        "srdc",
    srId:       "zn32213y",
  },
  {
    playerId:   "mp3pleiar",
    clearTime:  "3:22.000",
    uploadTime: "2022-07-15",
    videoUrls:  ["https://www.youtube.com/watch?v=XeJ1Tq0TPsI"],
    src:        "srdc",
    srId:       "yjprd27y",
  },
  {
    playerId:   "-LayFeyson-",
    clearTime:  "3:28.000",
    uploadTime: "2020-12-03",
    videoUrls:  ["https://www.youtube.com/watch?v=rBDNMvnkhEc&feature=youtu.be"],
    src:        "srdc",
    srId:       "ylvll22m",
  },
  {
    playerId:   "Thonytricks",
    clearTime:  "3:35.000",
    uploadTime: "2023-03-17",
    videoUrls:  ["https://www.twitch.tv/videos/1767833752"],
    src:        "srdc",
    srId:       "y80g2wnm",
  },
  {
    playerId:   "Reliquary",
    clearTime:  "3:36.000",
    uploadTime: "2020-03-05",
    videoUrls:  ["https://www.youtube.com/watch?v=Wm4xMYRRZd8&feature=youtu.be"],
    src:        "srdc",
    srId:       "zp4j3oxz",
  },
  {
    playerId:   "Aboba_Fett",
    clearTime:  "3:38.000",
    uploadTime: "2021-02-11",
    videoUrls:  ["https://youtu.be/biqqbTN8Mmw"],
    src:        "srdc",
    srId:       "y4276d2m",
  },
  {
    playerId:   "TheBlackParrot",
    clearTime:  "3:40.000",
    uploadTime: "2020-08-08",
    videoUrls:  ["https://www.youtube.com/watch?v=c_tAcilJO7o"],
    src:        "srdc",
    srId:       "y25r2p7y",
  },
  {
    playerId:   "Yutiply",
    clearTime:  "3:46.000",
    uploadTime: "2022-01-03",
    videoUrls:  ["https://www.youtube.com/watch?v=RF3KwT-27Gk"],
    src:        "srdc",
    srId:       "y6n6xj6z",
  },
  {
    playerId:   "Zexal",
    clearTime:  "3:48.000",
    uploadTime: "2021-01-05",
    videoUrls:  ["https://www.youtube.com/watch?v=eHu__sFMQBc"],
    src:        "srdc",
    srId:       "mr9g4n7m",
  },
  {
    playerId:   "Creepysaurus",
    clearTime:  "3:55.000",
    uploadTime: "2022-09-13",
    videoUrls:  ["https://youtu.be/ZoLvL4fIUTU"],
    src:        "srdc",
    srId:       "mkddr3ly",
  },
  {
    playerId:   "Pog_to_the_Champ",
    clearTime:  "3:58.000",
    uploadTime: "2021-01-04",
    videoUrls:  ["https://youtu.be/GF1oK-l3KgA"],
    src:        "srdc",
    srId:       "yo3g14jy",
  },
  {
    playerId:   "Aurax",
    clearTime:  "4:10.000",
    uploadTime: "2021-04-19",
    videoUrls:  ["https://youtu.be/bEmnAOdecCg"],
    src:        "srdc",
    srId:       "zgg7prnz",
  },
  {
    playerId:   "Sever_K12",
    clearTime:  "4:14.000",
    uploadTime: "2020-12-24",
    videoUrls:  ["https://youtu.be/mulaohkn79A"],
    src:        "srdc",
    srId:       "z09k1o8z",
  },
  {
    playerId:   "Yuzumi",
    clearTime:  "4:31.000",
    uploadTime: "2019-07-22",
    videoUrls:  ["https://youtu.be/LMdSSEGpYZU"],
    src:        "srdc",
    srId:       "z01950jy",
  },
  {
    playerId:   "ErgoGlast",
    clearTime:  "4:39.000",
    uploadTime: "2019-07-26",
    videoUrls:  ["https://youtu.be/H8f7lYCnsek"],
    src:        "srdc",
    srId:       "zxkdnjem",
  },
];