/* speedrun.com 原始抓取数据 — Legacy Categories / Teralyst / Solo */
/* level_id=nwlomj0w | 共 58 条 */
var legacy_categories_teralyst_soloRecords = [
  {
    playerId:   "_VOLT_PRIME_",
    clearTime:  "2:25.800",
    uploadTime: "2023-08-09",
    videoUrls:  ["https://www.bilibili.com/video/BV1yj411z7n2"],
    src:        "srdc",
    srId:       "zge9vdjy",
  },
  {
    playerId:   "Froj",
    clearTime:  "2:25.816",
    uploadTime: "2022-11-28",
    videoUrls:  ["https://www.youtube.com/watch?v=6coPCtZSEU8&ab_channel=Masta"],
    src:        "srdc",
    srId:       "meev142m",
  },
  {
    playerId:   "xvzzzz",
    clearTime:  "2:25.816",
    uploadTime: "2022-12-23",
    videoUrls:  ["https://youtu.be/XhKfPys6YPE"],
    src:        "srdc",
    srId:       "mroe3e2m",
  },
  {
    playerId:   "Mige",
    clearTime:  "2:25.833",
    uploadTime: "2022-08-19",
    videoUrls:  ["https://www.youtube.com/watch?v=1ZDonGOKCbM"],
    src:        "srdc",
    srId:       "m3xg89wm",
  },
  {
    playerId:   "krys715",
    clearTime:  "2:26.100",
    uploadTime: "2022-10-14",
    videoUrls:  ["https://www.youtube.com/watch?v=bj3aipj5Yl8"],
    src:        "srdc",
    srId:       "yjde863y",
  },
  {
    playerId:   "lajixianyuplay",
    clearTime:  "2:26.133",
    uploadTime: "2022-05-30",
    videoUrls:  ["https://www.youtube.com/watch?v=RxHza3FZa0g"],
    src:        "srdc",
    srId:       "yl7no4km",
  },
  {
    playerId:   "Damii005",
    clearTime:  "2:26.266",
    uploadTime: "2022-05-24",
    videoUrls:  ["https://www.youtube.com/watch?v=Mj7dxZNEDkw"],
    src:        "srdc",
    srId:       "y2p0x3wz",
  },
  {
    playerId:   "Nalviscoming14",
    clearTime:  "2:26.496",
    uploadTime: "2022-06-08",
    videoUrls:  ["https://www.youtube.com/watch?v=1c3ATBg_RmY"],
    src:        "srdc",
    srId:       "yvr8q0oz",
  },
  {
    playerId:   "OgvDams",
    clearTime:  "2:27.800",
    uploadTime: "2022-09-16",
    videoUrls:  ["https://www.youtube.com/watch?v=lqp3FKLGLYo"],
    src:        "srdc",
    srId:       "m7x2734y",
  },
  {
    playerId:   "KILLYOURSELFPXII",
    clearTime:  "2:27.833",
    uploadTime: "2021-11-23",
    videoUrls:  ["https://www.youtube.com/watch?v=f3hB-lSpMb0"],
    src:        "srdc",
    srId:       "mrngpogy",
  },
  {
    playerId:   "Bunni",
    clearTime:  "2:29.067",
    uploadTime: "2021-08-09",
    videoUrls:  ["https://youtu.be/RHfpecgnlSs"],
    src:        "srdc",
    srId:       "y271r46z",
  },
  {
    playerId:   "Sparkle",
    clearTime:  "2:29.266",
    uploadTime: "2022-01-27",
    videoUrls:  ["https://www.youtube.com/watch?v=qteFoXkvq10"],
    src:        "srdc",
    srId:       "zq0ek79y",
  },
  {
    playerId:   "Bloody_001",
    clearTime:  "2:29.500",
    uploadTime: "2021-07-09",
    videoUrls:  ["https://www.youtube.com/watch?v=H--D2kOyNfA"],
    src:        "srdc",
    srId:       "zxgrw1qy",
  },
  {
    playerId:   "MonsieurApple",
    clearTime:  "2:29.567",
    uploadTime: "2022-02-13",
    videoUrls:  ["https://youtu.be/VHj5YZxPuuk"],
    src:        "srdc",
    srId:       "y9lj36ry",
  },
  {
    playerId:   "tdaniel1992",
    clearTime:  "2:29.867",
    uploadTime: "2020-08-28",
    videoUrls:  ["https://www.youtube.com/watch?v=D908DX3nboo"],
    src:        "srdc",
    srId:       "y25o4rwy",
  },
  {
    playerId:   "Blunt.",
    clearTime:  "2:29.950",
    uploadTime: "2021-01-30",
    videoUrls:  ["https://youtu.be/Mf3eznK51dc"],
    src:        "srdc",
    srId:       "zp3l4erm",
  },
  {
    playerId:   "123Ivy_Mike321",
    clearTime:  "2:30.150",
    uploadTime: "2022-04-07",
    videoUrls:  ["https://www.youtube.com/watch?v=BWeq_fl558s&t=1s"],
    src:        "srdc",
    srId:       "y603e96y",
  },
  {
    playerId:   "Aznvasions",
    clearTime:  "2:30.300",
    uploadTime: "2020-08-18",
    videoUrls:  ["https://www.youtube.com/watch?v=wZJEJC1UkRs", "https://www.youtube.com/watch?v=SUmS8e757bE"],
    src:        "srdc",
    srId:       "mrkp1e4y",
  },
  {
    playerId:   "Utolic",
    clearTime:  "2:30.344",
    uploadTime: "2022-03-09",
    videoUrls:  ["https://www.youtube.com/watch?v=hd_-RrZCn6A"],
    src:        "srdc",
    srId:       "z0ok258z",
  },
  {
    playerId:   "Zulnaa",
    clearTime:  "2:30.366",
    uploadTime: "2021-10-06",
    videoUrls:  ["https://youtu.be/lIb7O2FLb4M"],
    src:        "srdc",
    srId:       "m773l15m",
  },
  {
    playerId:   "Lazyy",
    clearTime:  "2:31.000",
    uploadTime: "2021-11-02",
    videoUrls:  ["https://youtu.be/6hNeKd2NHDY"],
    src:        "srdc",
    srId:       "z07kr24y",
  },
  {
    playerId:   "yasumoru",
    clearTime:  "2:31.283",
    uploadTime: "2022-06-10",
    videoUrls:  ["https://www.youtube.com/watch?v=V0VVSeRu_hk"],
    src:        "srdc",
    srId:       "z1pqnrrz",
  },
  {
    playerId:   "ddavid9",
    clearTime:  "2:31.433",
    uploadTime: "2021-01-11",
    videoUrls:  ["https://www.youtube.com/watch?v=mkXVylgpz1c"],
    src:        "srdc",
    srId:       "znok8p7y",
  },
  {
    playerId:   "-Grognak-",
    clearTime:  "2:32.030",
    uploadTime: "2021-04-03",
    videoUrls:  ["https://youtu.be/HaNv9qgB7OI"],
    src:        "srdc",
    srId:       "m78kd00z",
  },
  {
    playerId:   "MaxPoXer",
    clearTime:  "2:32.483",
    uploadTime: "2021-08-29",
    videoUrls:  ["https://youtu.be/IeTeLXs5AME"],
    src:        "srdc",
    srId:       "yj5g2wgm",
  },
  {
    playerId:   "Aurax",
    clearTime:  "2:32.686",
    uploadTime: "2021-10-17",
    videoUrls:  ["https://youtu.be/NY9lbRL7hdI"],
    src:        "srdc",
    srId:       "y93djxey",
  },
  {
    playerId:   "Penguin103",
    clearTime:  "2:34.000",
    uploadTime: "2021-01-31",
    videoUrls:  ["https://youtu.be/S_dPqEWRXNI"],
    src:        "srdc",
    srId:       "y2vdp76z",
  },
  {
    playerId:   "Blackspell1998",
    clearTime:  "2:34.000",
    uploadTime: "2024-01-29",
    videoUrls:  ["https://youtu.be/fn481dAbTYA"],
    src:        "srdc",
    srId:       "y6q4e2pz",
  },
  {
    playerId:   "--AbsoluteZeRo--",
    clearTime:  "2:34.099",
    uploadTime: "2021-01-23",
    videoUrls:  ["https://youtu.be/boX7g9KywLQ"],
    src:        "srdc",
    srId:       "yo9j3w1y",
  },
  {
    playerId:   "Feitan",
    clearTime:  "2:36.317",
    uploadTime: "2020-06-22",
    videoUrls:  ["https://www.youtube.com/watch?v=Hq5sA4HqmDE"],
    src:        "srdc",
    srId:       "zqwe7rxz",
  },
  {
    playerId:   "MrOlolosh",
    clearTime:  "2:36.452",
    uploadTime: "2020-03-09",
    videoUrls:  ["https://www.youtube.com/watch?v=ZLr5n4huB5Q"],
    src:        "srdc",
    srId:       "y21ogk6z",
  },
  {
    playerId:   "19Lion",
    clearTime:  "2:38.000",
    uploadTime: "2022-05-06",
    videoUrls:  ["https://youtu.be/WmvKIQfuvHI"],
    src:        "srdc",
    srId:       "y60rv60y",
  },
  {
    playerId:   "yasumoru",
    clearTime:  "2:41.317",
    uploadTime: "2020-08-17",
    videoUrls:  ["https://youtu.be/tau_0jzPto0"],
    src:        "srdc",
    srId:       "y254q67y",
  },
  {
    playerId:   "asd12332",
    clearTime:  "2:42.199",
    uploadTime: "2021-03-10",
    videoUrls:  ["https://streamable.com/p6kjur"],
    src:        "srdc",
    srId:       "mk7183ly",
  },
  {
    playerId:   "_SlowMotion",
    clearTime:  "2:44.000",
    uploadTime: "2022-04-30",
    videoUrls:  ["https://youtu.be/lScGrKGirtM"],
    src:        "srdc",
    srId:       "yw38ww9m",
  },
  {
    playerId:   "Demon3King",
    clearTime:  "2:44.300",
    uploadTime: "2022-05-25",
    videoUrls:  ["https://www.youtube.com/watch?v=1L0ByfGxY80"],
    src:        "srdc",
    srId:       "m33634gm",
  },
  {
    playerId:   "CharmForLuck",
    clearTime:  "2:46.433",
    uploadTime: "2020-08-23",
    videoUrls:  ["https://www.youtube.com/watch?v=6Sc4qTY4-RQ&t=133s"],
    src:        "srdc",
    srId:       "mk7keqly",
  },
  {
    playerId:   "Crowley_Z",
    clearTime:  "2:55.000",
    uploadTime: "2020-08-18",
    videoUrls:  ["https://youtu.be/cuH3xh_LOxw"],
    src:        "srdc",
    srId:       "y824ep1y",
  },
  {
    playerId:   "PillowValleyMushroom",
    clearTime:  "2:56.167",
    uploadTime: "2022-02-27",
    videoUrls:  ["https://youtu.be/3uIThnawiJA"],
    src:        "srdc",
    srId:       "ydw48e0m",
  },
  {
    playerId:   "Supremusul",
    clearTime:  "3:02.000",
    uploadTime: "2020-05-31",
    videoUrls:  ["https://www.twitch.tv/videos/637279587"],
    src:        "srdc",
    srId:       "zpr244xm",
  },
  {
    playerId:   "Pheonoxe",
    clearTime:  "3:07.533",
    uploadTime: "2020-10-02",
    videoUrls:  ["https://www.youtube.com/watch?v=KNsoH7kWHlw"],
    src:        "srdc",
    srId:       "z1oj649m",
  },
  {
    playerId:   "Dawiddym",
    clearTime:  "3:15.000",
    uploadTime: "2021-04-11",
    videoUrls:  ["https://youtu.be/nmnuGCmmml8"],
    src:        "srdc",
    srId:       "mkgld1vy",
  },
  {
    playerId:   "screemer2017",
    clearTime:  "3:28.876",
    uploadTime: "2019-02-08",
    videoUrls:  ["https://www.youtube.com/watch?v=TxQio9UwRhc&t=1s"],
    src:        "srdc",
    srId:       "y2qn7r9y",
  },
  {
    playerId:   "N3rvus_-PL",
    clearTime:  "3:32.000",
    uploadTime: "2020-09-29",
    videoUrls:  ["https://youtu.be/6xZW8ldVyOc"],
    src:        "srdc",
    srId:       "zgvkppvz",
  },
  {
    playerId:   "Akiyato",
    clearTime:  "3:38.000",
    uploadTime: "2021-04-13",
    videoUrls:  ["https://www.youtube.com/watch?v=5M3Eg7wGWeo"],
    src:        "srdc",
    srId:       "y2x9l27m",
  },
  {
    playerId:   "Brazzi-4K",
    clearTime:  "3:50.000",
    uploadTime: "2020-08-24",
    videoUrls:  ["https://www.youtube.com/watch?v=Sn45pcBUX0k&feature=youtu.be"],
    src:        "srdc",
    srId:       "yw89009y",
  },
  {
    playerId:   "Zevfer",
    clearTime:  "3:54.449",
    uploadTime: "2020-10-24",
    videoUrls:  ["https://www.youtube.com/watch?v=kSARt7S3Qec&feature=youtu.be"],
    src:        "srdc",
    srId:       "yo36no0y",
  },
  {
    playerId:   "MigueZ_",
    clearTime:  "4:01.000",
    uploadTime: "2019-07-28",
    videoUrls:  ["https://www.youtube.com/watch?v=vro9_7nBUGM&t=50s"],
    src:        "srdc",
    srId:       "z1jovlgz",
  },
  {
    playerId:   "ROFLCOPTER1",
    clearTime:  "4:05.533",
    uploadTime: "2021-08-28",
    videoUrls:  ["https://www.youtube.com/watch?v=5Lwf_k0JqYA&t=198s"],
    src:        "srdc",
    srId:       "yderr2vm",
  },
  {
    playerId:   "dbrandt01",
    clearTime:  "4:15.000",
    uploadTime: "2019-01-09",
    videoUrls:  ["https://www.twitch.tv/videos/361824649"],
    src:        "srdc",
    srId:       "mr8owrdy",
  },
  {
    playerId:   "Spite",
    clearTime:  "4:21.000",
    uploadTime: "2018-07-15",
    videoUrls:  ["https://www.youtube.com/watch?v=3xxN6iD3u_0&t=3s"],
    src:        "srdc",
    srId:       "me80372m",
  },
  {
    playerId:   "slof",
    clearTime:  "5:00.000",
    uploadTime: "2018-08-25",
    videoUrls:  ["https://youtu.be/KuQXkNkCDkE"],
    src:        "srdc",
    srId:       "zg7xdrdz",
  },
  {
    playerId:   "Avate",
    clearTime:  "5:06.730",
    uploadTime: "2018-01-13",
    videoUrls:  ["https://youtu.be/5JxOLIrGZyk"],
    src:        "srdc",
    srId:       "yl9d0k2y",
  },
  {
    playerId:   "Icohedron",
    clearTime:  "5:27.000",
    uploadTime: "2018-09-21",
    videoUrls:  ["https://www.youtube.com/watch?v=7eJUTC5AJxc"],
    src:        "srdc",
    srId:       "zx4ognky",
  },
  {
    playerId:   "FbiKei",
    clearTime:  "7:50.070",
    uploadTime: "2017-12-20",
    videoUrls:  ["https://www.youtube.com/watch?v=qJ8Fy962ykA"],
    src:        "srdc",
    srId:       "yl96d6xy",
  },
  {
    playerId:   "iTrust",
    clearTime:  "8:06.800",
    uploadTime: "2017-11-01",
    videoUrls:  ["https://www.youtube.com/watch?v=60jpW3Pzwqw"],
    src:        "srdc",
    srId:       "z13pepgm",
  },
  {
    playerId:   "ashaceawe",
    clearTime:  "10:35.000",
    uploadTime: "2018-01-13",
    videoUrls:  ["https://www.youtube.com/watch?v=_o8qyZ2h6-c&feature=youtu.be"],
    src:        "srdc",
    srId:       "zq68rlry",
  },
  {
    playerId:   "thundawolf1887",
    clearTime:  "152:39.000",
    uploadTime: "2018-05-01",
    videoUrls:  ["https://youtu.be/ExH41Wv5Kl4"],
    src:        "srdc",
    srId:       "zq3gk99y",
  },
];