/* speedrun.com 原始抓取数据 — Legacy Categories / Teralyst / Co-op */
/* level_id=nwlomj0w | 共 19 条 */
var legacy_categories_teralyst_coopRecords = [
  {
    playerId:   "AnQianYu / _VOLT_PRIME_",
    clearTime:  "2:25.947",
    uploadTime: "2022-06-09",
    videoUrls:  ["https://youtu.be/1aRRhaWzUlg"],
    src:        "srdc",
    srId:       "yopld85m",
  },
  {
    playerId:   "Dur_ / Mige",
    clearTime:  "2:25.949",
    uploadTime: "2022-02-27",
    videoUrls:  ["https://www.youtube.com/watch?v=cz3jl-IOlhI"],
    src:        "srdc",
    srId:       "z0o03o8z",
  },
  {
    playerId:   "Bunni / chichi / greatshift",
    clearTime:  "2:25.967",
    uploadTime: "2021-08-04",
    videoUrls:  ["https://www.youtube.com/watch?v=mMqtVtjTJB4&ab_channel=greatshift"],
    src:        "srdc",
    srId:       "m37ologz",
  },
  {
    playerId:   "Mige / Dur_",
    clearTime:  "2:25.967",
    uploadTime: "2021-10-01",
    videoUrls:  ["https://www.youtube.com/watch?v=92_berMUqW8"],
    src:        "srdc",
    srId:       "yvopdv4z",
  },
  {
    playerId:   "Dur_ / DoubleXXF",
    clearTime:  "2:26.096",
    uploadTime: "2021-08-11",
    videoUrls:  ["https://www.youtube.com/watch?v=R0vpk64t76c"],
    src:        "srdc",
    srId:       "mrned24y",
  },
  {
    playerId:   "AnQianYu / lajixianyuplay",
    clearTime:  "2:26.199",
    uploadTime: "2022-05-23",
    videoUrls:  ["https://youtu.be/bqZS_jj8aXU"],
    src:        "srdc",
    srId:       "mr76oq4z",
  },
  {
    playerId:   "-Sky- / rh0n1n / saghzs / kouks",
    clearTime:  "2:26.217",
    uploadTime: "2021-06-11",
    videoUrls:  ["https://youtu.be/P_Z6ALX6UaM"],
    src:        "srdc",
    srId:       "m7d0vx0m",
  },
  {
    playerId:   "Bubs / elevate. / AziDHK",
    clearTime:  "2:26.233",
    uploadTime: "2020-11-30",
    videoUrls:  ["https://youtu.be/-ODOHEkt_9s"],
    src:        "srdc",
    srId:       "y2dk719z",
  },
  {
    playerId:   "-Antharas / Stalinlox / TTSupleninTT",
    clearTime:  "2:26.500",
    uploadTime: "2020-11-16",
    videoUrls:  ["https://www.youtube.com/watch?v=mJFLZI3IlPI&ab_channel=Stalinlox)", "https://www.youtube.com/watch?v=_KdINT1d4h0&ab_channel=Stalinlox)", "https://www.youtube.com/watch?v=kpy5RL_elwY&t=25s&ab_channel=DuoGays"],
    src:        "srdc",
    srId:       "zq49rxxm",
  },
  {
    playerId:   "Cronks / Bloody_001 / 123Ivy_Mike321 / _KoStOlOm_",
    clearTime:  "2:26.566",
    uploadTime: "2021-03-08",
    videoUrls:  ["https://www.youtube.com/watch?v=ArKmlir6lYY&t=1s"],
    src:        "srdc",
    srId:       "y2v2gj7z",
  },
  {
    playerId:   "Cronks / Bloody_001 / 123Ivy_Mike321",
    clearTime:  "2:26.633",
    uploadTime: "2021-03-05",
    videoUrls:  ["https://www.youtube.com/watch?v=UbDb3a9cctg&t=46s"],
    src:        "srdc",
    srId:       "m783vxez",
  },
  {
    playerId:   "Stalinlox / TTSupleninTT",
    clearTime:  "2:27.090",
    uploadTime: "2020-11-15",
    videoUrls:  ["https://www.youtube.com/watch?v=v9URYyRhO3M&feature=youtu.be&ab_channel=DuoGays"],
    src:        "srdc",
    srId:       "y91v4l2m",
  },
  {
    playerId:   "kouks / -Sky- / Aznvasions / MrOlolosh",
    clearTime:  "2:27.167",
    uploadTime: "2020-03-15",
    videoUrls:  ["https://youtu.be/MjJDqvmaRFc", "https://youtu.be/li5RRBEdes0", "https://youtu.be/Lp-8NU3JqCg", "https://www.youtube.com/watch?v=njOHYqNYbo0"],
    src:        "srdc",
    srId:       "y8158dnz",
  },
  {
    playerId:   "-Vergilius- / --taterD-- / Threezeeh_",
    clearTime:  "2:37.000",
    uploadTime: "2019-08-22",
    videoUrls:  ["https://youtu.be/i12jS3NA5rI"],
    src:        "srdc",
    srId:       "zp41xnnz",
  },
  {
    playerId:   "Pheonoxe / LavaSquid35",
    clearTime:  "2:55.199",
    uploadTime: "2020-09-27",
    videoUrls:  ["https://www.youtube.com/watch?v=mIB_dVdMYjw"],
    src:        "srdc",
    srId:       "zpl4l38m",
  },
  {
    playerId:   "Rickirado / GatinhoSafadinho",
    clearTime:  "3:34.000",
    uploadTime: "2023-05-21",
    videoUrls:  ["https://youtu.be/djutxfNMe5g"],
    src:        "srdc",
    srId:       "mrlk622m",
  },
  {
    playerId:   "V-_-iniciu-_-s / issaFoxy / turbodart",
    clearTime:  "4:16.000",
    uploadTime: "2019-05-11",
    videoUrls:  ["https://youtu.be/yyX6DIF4Ti0"],
    src:        "srdc",
    srId:       "m3oe28wm",
  },
  {
    playerId:   "AuhertBrahma / chutchens44",
    clearTime:  "7:24.000",
    uploadTime: "2019-05-11",
    videoUrls:  ["https://www.youtube.com/watch?v=bVUvbZ0qWH8"],
    src:        "srdc",
    srId:       "yd3kvn0z",
  },
  {
    playerId:   "howtoawesome3 / -Blorgus-",
    clearTime:  "12:32.000",
    uploadTime: "2018-10-10",
    videoUrls:  ["https://www.youtube.com/watch?v=35wQZXtLNB8"],
    src:        "srdc",
    srId:       "z03oxqoz",
  },
];