/* speedrun.com 原始抓取数据 — Legacy Categories / Test 20 / Solo */
/* level_id=owo6yo3w | 共 11 条 */
var legacy_categories_test_20_soloRecords = [
  {
    playerId:   "QuasarWF",
    clearTime:  "0:17.520",
    uploadTime: "2018-05-13",
    videoUrls:  ["https://youtu.be/Bd0cXuUaWoY"],
    src:        "srdc",
    srId:       "mk4jv23y",
  },
  {
    playerId:   "-Rekken-",
    clearTime:  "0:17.901",
    uploadTime: "2018-04-17",
    videoUrls:  ["https://youtu.be/iyb7FHepDkg"],
    src:        "srdc",
    srId:       "y8q47pwy",
  },
  {
    playerId:   "-AE-Lux",
    clearTime:  "0:18.018",
    uploadTime: "2018-09-12",
    videoUrls:  ["https://www.youtube.com/watch?v=5V-7QLVtfWg"],
    src:        "srdc",
    srId:       "z11rn5rz",
  },
  {
    playerId:   "OverusedMemes",
    clearTime:  "0:18.285",
    uploadTime: "2017-06-17",
    videoUrls:  ["https://www.youtube.com/watch?v=DCZLlv8M1HA"],
    src:        "srdc",
    srId:       "y8q14vwy",
  },
  {
    playerId:   "Chansey",
    clearTime:  "0:18.633",
    uploadTime: "2018-09-01",
    videoUrls:  ["https://www.youtube.com/watch?v=BRVD9X1boqs"],
    src:        "srdc",
    srId:       "yd39x8xz",
  },
  {
    playerId:   "Mortar",
    clearTime:  "0:21.433",
    uploadTime: "2022-12-02",
    videoUrls:  ["https://www.youtube.com/watch?v=L4aBacZg0tg"],
    src:        "srdc",
    srId:       "meekkq2m",
  },
  {
    playerId:   "Reaper261292",
    clearTime:  "0:21.490",
    uploadTime: "2020-06-25",
    videoUrls:  ["https://youtu.be/ACxcGe5_YsI"],
    src:        "srdc",
    srId:       "yjl8037z",
  },
  {
    playerId:   "Jason_0819",
    clearTime:  "0:21.683",
    uploadTime: "2021-11-24",
    videoUrls:  ["https://youtu.be/5kRTTdtk2xw"],
    src:        "srdc",
    srId:       "y27l9p9z",
  },
  {
    playerId:   "Nusmag",
    clearTime:  "0:22.027",
    uploadTime: "2017-06-16",
    videoUrls:  ["https://youtu.be/KpQopjSawEQ"],
    src:        "srdc",
    srId:       "z13j09gm",
  },
  {
    playerId:   "shaleve_hakime",
    clearTime:  "0:22.233",
    uploadTime: "2021-05-20",
    videoUrls:  ["https://www.youtube.com/watch?v=iTZN4GyYL7k"],
    src:        "srdc",
    srId:       "zp12rrgz",
  },
  {
    playerId:   "Reliquary",
    clearTime:  "0:23.000",
    uploadTime: "2020-03-07",
    videoUrls:  ["https://www.youtube.com/watch?v=kgsJHxxk7og&feature=youtu.be"],
    src:        "srdc",
    srId:       "yj30xrdz",
  },
];