/* speedrun.com 原始抓取数据 — Legacy Categories / Tridolons / Co-op */
/* level_id=5wkj3vvd | 共 24 条 */
var legacy_categories_tridolons_coopRecords = [
  {
    playerId:   "kouks / -Sky- / rh0n1n / saghzs",
    clearTime:  "7:50.150",
    uploadTime: "2022-01-18",
    videoUrls:  ["https://youtu.be/VAE4WSgiKuk"],
    src:        "srdc",
    srId:       "yorp490y",
  },
  {
    playerId:   "Bloody_001 / Fereeli / MonsieurApple",
    clearTime:  "7:52.250",
    uploadTime: "2022-01-09",
    videoUrls:  ["https://youtu.be/0AkEg6YhDDM"],
    src:        "srdc",
    srId:       "yjx54lgz",
  },
  {
    playerId:   "kouks / rh0n1n / -Sky- / saghzs",
    clearTime:  "7:52.466",
    uploadTime: "2021-06-09",
    videoUrls:  ["https://youtu.be/u1glsZ7mBZI"],
    src:        "srdc",
    srId:       "mkg0e71y",
  },
  {
    playerId:   "kouks / rh0n1n / saghzs",
    clearTime:  "7:56.533",
    uploadTime: "2021-04-14",
    videoUrls:  ["https://youtu.be/SkXr4IsDU0g"],
    src:        "srdc",
    srId:       "y2x3xn5m",
  },
  {
    playerId:   "julia_kukuruzka / violetcat",
    clearTime:  "7:57.014",
    uploadTime: "2022-08-06",
    videoUrls:  ["https://youtu.be/eNJO6RjIRH8"],
    src:        "srdc",
    srId:       "z0l3pvez",
  },
  {
    playerId:   "Eragoon / darkinmaui",
    clearTime:  "7:58.800",
    uploadTime: "2021-04-13",
    videoUrls:  ["https://youtu.be/KY4cl-TUO7I"],
    src:        "srdc",
    srId:       "yv14k66y",
  },
  {
    playerId:   "saghzs / -Sky- / Scouty",
    clearTime:  "7:58.900",
    uploadTime: "2021-03-17",
    videoUrls:  ["https://www.youtube.com/watch?v=MrttJ5YvJm4"],
    src:        "srdc",
    srId:       "mk7o65vy",
  },
  {
    playerId:   "Nalviscoming14 / AxeltrypHRM",
    clearTime:  "7:59.834",
    uploadTime: "2021-10-02",
    videoUrls:  ["https://youtu.be/FWNzs6LJ7Nw"],
    src:        "srdc",
    srId:       "zgr8klnm",
  },
  {
    playerId:   "rh0n1n / saghzs / -Sky-",
    clearTime:  "7:59.899",
    uploadTime: "2021-03-08",
    videoUrls:  ["https://youtu.be/vmjuPFaq47M"],
    src:        "srdc",
    srId:       "zp3666vm",
  },
  {
    playerId:   "Bunni / chichi",
    clearTime:  "8:00.133",
    uploadTime: "2021-03-23",
    videoUrls:  ["https://youtu.be/RA0e_yDxrCI"],
    src:        "srdc",
    srId:       "ylo551ny",
  },
  {
    playerId:   "Vaeli / Bvlbasaur",
    clearTime:  "8:01.866",
    uploadTime: "2022-07-07",
    videoUrls:  ["https://youtu.be/HYWiFKmOvw0"],
    src:        "srdc",
    srId:       "ydd4n30y",
  },
  {
    playerId:   "-Sky- / -AE-Lux / kouks / .Ayaya",
    clearTime:  "8:02.033",
    uploadTime: "2020-05-22",
    videoUrls:  ["https://youtu.be/cM4u3qrLpaI"],
    src:        "srdc",
    srId:       "y257ql9y",
  },
  {
    playerId:   "kouks / -Sky- / ImagineHunting / .Ayaya",
    clearTime:  "8:04.400",
    uploadTime: "2020-04-08",
    videoUrls:  ["https://www.youtube.com/watch?v=MCUEuU20WdQ&t="],
    src:        "srdc",
    srId:       "yjl4lr7z",
  },
  {
    playerId:   "saghzs / kouks / --Q--Luk / rh0n1n",
    clearTime:  "8:06.498",
    uploadTime: "2020-02-19",
    videoUrls:  ["https://www.twitch.tv/videos/554684773"],
    src:        "srdc",
    srId:       "m31e3j4z",
  },
  {
    playerId:   "_Divider_ / Xiazon / screemer2017 / Myasnik_Ashot",
    clearTime:  "8:16.196",
    uploadTime: "2019-04-10",
    videoUrls:  ["https://www.youtube.com/watch?v=UT0FttZ50oE"],
    src:        "srdc",
    srId:       "yo2g0q7z",
  },
  {
    playerId:   "Stenexes / Myasnik_Ashot / violetcat / DarkLigt864",
    clearTime:  "8:17.131",
    uploadTime: "2019-03-26",
    videoUrls:  ["https://www.youtube.com/watch?v=FN-xpM_pRY8"],
    src:        "srdc",
    srId:       "z51ngonm",
  },
  {
    playerId:   ".cat / Stenexes / screemer2017 / Octavia_Prime",
    clearTime:  "8:17.463",
    uploadTime: "2019-03-31",
    videoUrls:  ["https://www.youtube.com/watch?v=RmH3nSYvF6g"],
    src:        "srdc",
    srId:       "yo2g4j7z",
  },
  {
    playerId:   ".cat / screemer2017 / Stenexes / Dext3ry",
    clearTime:  "8:18.206",
    uploadTime: "2019-02-11",
    videoUrls:  ["https://www.youtube.com/watch?v=AiovzLUyRd4"],
    src:        "srdc",
    srId:       "m7pe0rem",
  },
  {
    playerId:   "Myasnik_Ashot / Murenas / DarkLigt864 / Po3itivchik123",
    clearTime:  "8:19.161",
    uploadTime: "2019-03-05",
    videoUrls:  ["https://www.youtube.com/watch?v=ja3Ab3t-YSo"],
    src:        "srdc",
    srId:       "ywp503pz",
  },
  {
    playerId:   "LarryyLotter / .Michael. / simpleID / Tomtommytom",
    clearTime:  "8:44.000",
    uploadTime: "2018-10-01",
    videoUrls:  ["https://www.youtube.com/watch?v=7iyEgI_lOVg&t="],
    src:        "srdc",
    srId:       "zp02negm",
  },
  {
    playerId:   "Cats. / slof / WorstPingEU / -APE-BigDaddyNoTail",
    clearTime:  "9:50.000",
    uploadTime: "2018-08-12",
    videoUrls:  ["https://youtu.be/iGpWgYs8BHc"],
    src:        "srdc",
    srId:       "mk95rdvz",
  },
  {
    playerId:   "slof / LayersR / ev0xpr0x / simpleID",
    clearTime:  "9:54.000",
    uploadTime: "2018-09-19",
    videoUrls:  ["https://youtu.be/3h_KNZJlsmQ"],
    src:        "srdc",
    srId:       "y92351rz",
  },
  {
    playerId:   "_Lumen_ / StatusLeaf",
    clearTime:  "10:33.000",
    uploadTime: "2023-02-04",
    videoUrls:  ["https://youtu.be/47IcT0m5hrU"],
    src:        "srdc",
    srId:       "zpgdl6vz",
  },
  {
    playerId:   "Monagarmr / Fileron",
    clearTime:  "11:57.000",
    uploadTime: "2023-06-04",
    videoUrls:  ["https://www.youtube.com/watch?v=-AtlrIWBvpQ&ab_channel=RaySharko"],
    src:        "srdc",
    srId:       "zqjg0orm",
  },
];