/* speedrun.com 原始抓取数据 — Legacy Categories / Tridolons / Solo */
/* level_id=5wkj3vvd | 共 42 条 */
var legacy_categories_tridolons_soloRecords = [
  {
    playerId:   "GrowFlowerAllTheWay",
    clearTime:  "7:51.733",
    uploadTime: "2023-08-30",
    videoUrls:  ["https://www.bilibili.com/video/BV1Fj41177LF/?spm_id_from=333.999.0.0&vd_source=19f806b56efc01d2ff619f2d1143e6ec"],
    src:        "srdc",
    srId:       "z0xwp59z",
  },
  {
    playerId:   "KILLYOURSELFPXII",
    clearTime:  "8:06.000",
    uploadTime: "2021-10-31",
    videoUrls:  ["https://www.bilibili.com/video/BV1Kg411K7cs/"],
    src:        "srdc",
    srId:       "ylqlrd2z",
  },
  {
    playerId:   "Bloody_001",
    clearTime:  "8:09.723",
    uploadTime: "2021-08-30",
    videoUrls:  ["https://www.youtube.com/watch?v=PiP-QBjG6rc"],
    src:        "srdc",
    srId:       "y8exn1xy",
  },
  {
    playerId:   "TeshinJr",
    clearTime:  "8:12.056",
    uploadTime: "2022-02-27",
    videoUrls:  ["https://youtu.be/vXItFsB6ORQ"],
    src:        "srdc",
    srId:       "z5vw5kgm",
  },
  {
    playerId:   "DeweySalt",
    clearTime:  "8:12.234",
    uploadTime: "2022-06-23",
    videoUrls:  ["https://www.youtube.com/watch?v=fCYUj_vRVVc"],
    src:        "srdc",
    srId:       "m330xowm",
  },
  {
    playerId:   "DanishThug29",
    clearTime:  "8:15.100",
    uploadTime: "2023-01-05",
    videoUrls:  ["https://youtu.be/C9fYPIjGMus"],
    src:        "srdc",
    srId:       "yol31e1y",
  },
  {
    playerId:   "Bunni",
    clearTime:  "8:17.633",
    uploadTime: "2021-08-08",
    videoUrls:  ["https://youtu.be/qFlza4vNZho"],
    src:        "srdc",
    srId:       "ywk4dv0y",
  },
  {
    playerId:   "DeweySalt",
    clearTime:  "8:27.000",
    uploadTime: "2022-06-14",
    videoUrls:  ["https://www.youtube.com/watch?v=HTMmAsxSYnY"],
    src:        "srdc",
    srId:       "yddjgnvy",
  },
  {
    playerId:   "zNecrum",
    clearTime:  "8:36.000",
    uploadTime: "2022-06-11",
    videoUrls:  ["https://youtu.be/A_LNefTmL1Q"],
    src:        "srdc",
    srId:       "yjp80g7y",
  },
  {
    playerId:   "touc",
    clearTime:  "8:38.667",
    uploadTime: "2022-04-05",
    videoUrls:  ["https://www.youtube.com/watch?v=Hkrk2hM375I"],
    src:        "srdc",
    srId:       "m3396p4m",
  },
  {
    playerId:   "saghzs",
    clearTime:  "8:53.000",
    uploadTime: "2021-01-19",
    videoUrls:  ["https://youtu.be/XOY-9NCW_bA"],
    src:        "srdc",
    srId:       "zqg6lp9m",
  },
  {
    playerId:   "saghzs",
    clearTime:  "8:54.000",
    uploadTime: "2020-03-16",
    videoUrls:  ["https://youtu.be/-IYUCxpNDms"],
    src:        "srdc",
    srId:       "zgk4xpvy",
  },
  {
    playerId:   "--Grey--",
    clearTime:  "9:03.000",
    uploadTime: "2020-10-07",
    videoUrls:  ["https://youtu.be/XLgyN8YzGqM"],
    src:        "srdc",
    srId:       "zq4w0n1m",
  },
  {
    playerId:   "BSKOTH",
    clearTime:  "9:09.848",
    uploadTime: "2023-06-17",
    videoUrls:  ["https://youtu.be/9DL6KJFb3HI"],
    src:        "srdc",
    srId:       "yl6rde2y",
  },
  {
    playerId:   "Tizio123",
    clearTime:  "9:12.200",
    uploadTime: "2022-05-25",
    videoUrls:  ["https://youtu.be/u5jg0ggJg5I"],
    src:        "srdc",
    srId:       "z0ponwjy",
  },
  {
    playerId:   "jianwz",
    clearTime:  "9:14.000",
    uploadTime: "2020-08-22",
    videoUrls:  ["https://youtu.be/E21q7AnVDks"],
    src:        "srdc",
    srId:       "mk36lx3z",
  },
  {
    playerId:   "UnOriginalGN",
    clearTime:  "9:19.833",
    uploadTime: "2021-05-27",
    videoUrls:  ["https://youtu.be/lCbebyA5h34"],
    src:        "srdc",
    srId:       "yo7p0g5m",
  },
  {
    playerId:   "seyhk",
    clearTime:  "9:22.000",
    uploadTime: "2020-10-04",
    videoUrls:  ["https://youtu.be/Z2vO630Spog"],
    src:        "srdc",
    srId:       "mk834p3m",
  },
  {
    playerId:   "kouks",
    clearTime:  "9:33.000",
    uploadTime: "2020-01-31",
    videoUrls:  ["https://youtu.be/l8ViaOHY9JI"],
    src:        "srdc",
    srId:       "yl050nry",
  },
  {
    playerId:   "CharmForLuck",
    clearTime:  "9:57.000",
    uploadTime: "2020-11-20",
    videoUrls:  ["https://www.youtube.com/watch?v=3DSGBTygkQI"],
    src:        "srdc",
    srId:       "ylo177ny",
  },
  {
    playerId:   "FearOmnicide",
    clearTime:  "9:57.000",
    uploadTime: "2022-06-21",
    videoUrls:  ["https://youtu.be/HoIDqtoZlF0"],
    src:        "srdc",
    srId:       "yl7l2jrm",
  },
  {
    playerId:   "UnOriginalGN",
    clearTime:  "10:02.100",
    uploadTime: "2021-05-14",
    videoUrls:  ["https://youtu.be/SJHZ5eHKNto"],
    src:        "srdc",
    srId:       "ylqq8jkz",
  },
  {
    playerId:   "Daisy_Fitzroy",
    clearTime:  "10:55.000",
    uploadTime: "2020-09-06",
    videoUrls:  ["https://youtu.be/P4-0sb8BSPQ"],
    src:        "srdc",
    srId:       "z5353rgy",
  },
  {
    playerId:   "Refraction",
    clearTime:  "11:01.000",
    uploadTime: "2022-09-16",
    videoUrls:  ["https://youtu.be/SzzDLgVXhls?feature=shared"],
    src:        "srdc",
    srId:       "y2k6plwy",
  },
  {
    playerId:   "Sparkle",
    clearTime:  "11:04.000",
    uploadTime: "2020-06-30",
    videoUrls:  ["https://youtu.be/KpETzk_KJGM"],
    src:        "srdc",
    srId:       "m358n56y",
  },
  {
    playerId:   "Yutiply",
    clearTime:  "11:09.000",
    uploadTime: "2022-05-16",
    videoUrls:  ["https://www.youtube.com/watch?v=W7qDFSp0UGI"],
    src:        "srdc",
    srId:       "yvr1l38z",
  },
  {
    playerId:   "MonsieurApple",
    clearTime:  "11:14.717",
    uploadTime: "2021-03-28",
    videoUrls:  ["https://youtu.be/BbaFaJT4jDQ"],
    src:        "srdc",
    srId:       "y66wwq0y",
  },
  {
    playerId:   "RandomMacBG",
    clearTime:  "11:16.000",
    uploadTime: "2020-07-21",
    videoUrls:  ["https://youtu.be/zk2oG5BU_fY"],
    src:        "srdc",
    srId:       "ylkxw82z",
  },
  {
    playerId:   "dart2g",
    clearTime:  "11:44.000",
    uploadTime: "2021-05-01",
    videoUrls:  ["https://youtu.be/S-GHxmn-fSk"],
    src:        "srdc",
    srId:       "z5r31kjy",
  },
  {
    playerId:   "ErrorFileSystem",
    clearTime:  "11:53.000",
    uploadTime: "2020-02-29",
    videoUrls:  ["https://www.youtube.com/watch?v=0Eb9cAeNqUk"],
    src:        "srdc",
    srId:       "z01vdljy",
  },
  {
    playerId:   "Akiyato",
    clearTime:  "12:10.246",
    uploadTime: "2023-03-08",
    videoUrls:  ["https://www.youtube.com/watch?v=K6e47hl_nxw"],
    src:        "srdc",
    srId:       "meegnvqm",
  },
  {
    playerId:   "Penguin103",
    clearTime:  "12:15.750",
    uploadTime: "2021-05-20",
    videoUrls:  ["https://youtu.be/BjQBUMeJAmc"],
    src:        "srdc",
    srId:       "zp12r8xz",
  },
  {
    playerId:   "Dawiddym",
    clearTime:  "12:16.000",
    uploadTime: "2021-04-09",
    videoUrls:  ["https://youtu.be/-aLmI6a4bFI"],
    src:        "srdc",
    srId:       "me7vvqqy",
  },
  {
    playerId:   "Yutiply",
    clearTime:  "13:13.525",
    uploadTime: "2022-04-23",
    videoUrls:  ["https://www.youtube.com/watch?v=lmE-gdyKfEk"],
    src:        "srdc",
    srId:       "m76q259y",
  },
  {
    playerId:   "--Q--EValueAction",
    clearTime:  "13:25.000",
    uploadTime: "2019-02-04",
    videoUrls:  ["https://www.youtube.com/watch?v=Kbe96hAbvyw"],
    src:        "srdc",
    srId:       "m7pep60m",
  },
  {
    playerId:   "martinettii",
    clearTime:  "14:55.000",
    uploadTime: "2021-01-05",
    videoUrls:  ["https://www.twitch.tv/videos/858822130"],
    src:        "srdc",
    srId:       "zn3nrx7y",
  },
  {
    playerId:   "-Rodrigo",
    clearTime:  "16:38.000",
    uploadTime: "2018-07-12",
    videoUrls:  ["https://www.youtube.com/watch?v=Snw0NYkJylY"],
    src:        "srdc",
    srId:       "y92531vz",
  },
  {
    playerId:   "-HabberDasher-",
    clearTime:  "17:34.000",
    uploadTime: "2018-08-06",
    videoUrls:  ["https://www.youtube.com/watch?v=y9_SAEKyifo"],
    src:        "srdc",
    srId:       "y6prrrpm",
  },
  {
    playerId:   "V-_-iniciu-_-s",
    clearTime:  "17:38.000",
    uploadTime: "2019-03-10",
    videoUrls:  ["https://youtu.be/4Mp_t1Rxu-g"],
    src:        "srdc",
    srId:       "yd3714jz",
  },
  {
    playerId:   "ROFLCOPTER1",
    clearTime:  "19:05.000",
    uploadTime: "2022-03-14",
    videoUrls:  ["https://www.twitch.tv/videos/1425857192"],
    src:        "srdc",
    srId:       "z12077wy",
  },
  {
    playerId:   "ptilulu83",
    clearTime:  "26:01.000",
    uploadTime: "2018-06-28",
    videoUrls:  ["https://www.youtube.com/watch?v=F8YOUcXBQA8"],
    src:        "srdc",
    srId:       "ywppvx3z",
  },
  {
    playerId:   "MrOlolosh",
    clearTime:  "29:04.000",
    uploadTime: "2020-05-28",
    videoUrls:  ["https://www.youtube.com/watch?v=hV-0_V4z9Fc"],
    src:        "srdc",
    srId:       "z5jd47jm",
  },
];