/* speedrun.com 原始抓取数据 — Rescue Missions / Brugia / Solo */
/* level_id=n93m60zd | 共 11 条 */
var rescue_missions_brugia_soloRecords = [
  {
    playerId:   "Salat",
    clearTime:  "0:22.100",
    uploadTime: "2026-06-07",
    videoUrls:  ["https://youtu.be/UAGi9kinVg0"],
    src:        "srdc",
    srId:       "zg115rjz",
  },
  {
    playerId:   "L1ndell",
    clearTime:  "0:22.917",
    uploadTime: "2026-05-05",
    videoUrls:  ["https://youtu.be/EAkWuaDiKIU"],
    src:        "srdc",
    srId:       "y8lkledm",
  },
  {
    playerId:   "PrimedDarkeN",
    clearTime:  "0:26.000",
    uploadTime: "2022-06-23",
    videoUrls:  ["https://www.youtube.com/watch?v=E5e5pUexKEg"],
    src:        "srdc",
    srId:       "yl7drenm",
  },
  {
    playerId:   "Wasamii",
    clearTime:  "0:32.000",
    uploadTime: "2025-05-17",
    videoUrls:  ["https://youtu.be/tjhvE56TbqM"],
    src:        "srdc",
    srId:       "mkw3g8lm",
  },
  {
    playerId:   "Febi",
    clearTime:  "0:33.000",
    uploadTime: "2021-04-16",
    videoUrls:  ["https://www.youtube.com/watch?v=WU9MWmv8HO0"],
    src:        "srdc",
    srId:       "zxgv0wgy",
  },
  {
    playerId:   "Boll",
    clearTime:  "0:35.000",
    uploadTime: "2021-02-10",
    videoUrls:  ["https://www.youtube.com/watch?v=W-_5nscmmkM&ab_channel=MuraTradebanned"],
    src:        "srdc",
    srId:       "zx6o7qez",
  },
  {
    playerId:   "TheLostJoshua",
    clearTime:  "0:36.000",
    uploadTime: "2022-11-15",
    videoUrls:  ["https://youtu.be/Xm_qzl3rDXI"],
    src:        "srdc",
    srId:       "zpdjllvz",
  },
  {
    playerId:   "zukerben",
    clearTime:  "0:39.000",
    uploadTime: "2020-11-26",
    videoUrls:  ["https://www.youtube.com/watch?v=mX5MSyJeFeg"],
    src:        "srdc",
    srId:       "yd0j10jz",
  },
  {
    playerId:   "Andy.",
    clearTime:  "0:44.000",
    uploadTime: "2020-11-25",
    videoUrls:  ["https://youtu.be/TVNFGQt0YKk"],
    src:        "srdc",
    srId:       "mk80ep3m",
  },
  {
    playerId:   "CreepingChamp",
    clearTime:  "0:49.000",
    uploadTime: "2020-11-13",
    videoUrls:  ["https://youtu.be/mQp7lY5eeFw"],
    src:        "srdc",
    srId:       "y8r8o5xm",
  },
  {
    playerId:   "LeChat930",
    clearTime:  "1:09.000",
    uploadTime: "2023-07-03",
    videoUrls:  ["https://www.youtube.com/watch?v=ozbPI0frSd4"],
    src:        "srdc",
    srId:       "zpwdk0vy",
  },
];