/* speedrun.com 原始抓取数据 — Rescue Missions / Caliban / Solo */
/* level_id=z98m1jlw | 共 9 条 */
var rescue_missions_caliban_soloRecords = [
  {
    playerId:   "Salat",
    clearTime:  "0:20.333",
    uploadTime: "2026-06-25",
    videoUrls:  ["https://www.youtube.com/watch?v=Oeynh5Y3rjc"],
    src:        "srdc",
    srId:       "m7410xem",
  },
  {
    playerId:   "L1ndell",
    clearTime:  "0:23.083",
    uploadTime: "2025-12-23",
    videoUrls:  ["https://youtu.be/DFgl5zcvVZ8"],
    src:        "srdc",
    srId:       "yj72v1dy",
  },
  {
    playerId:   "PrimedDarkeN",
    clearTime:  "0:26.000",
    uploadTime: "2022-06-23",
    videoUrls:  ["https://www.youtube.com/watch?v=QfHQtdHGUIs"],
    src:        "srdc",
    srId:       "z1p9r7rz",
  },
  {
    playerId:   "Febi",
    clearTime:  "0:30.000",
    uploadTime: "2021-07-06",
    videoUrls:  ["https://www.youtube.com/watch?v=H-xB35jJ9oA"],
    src:        "srdc",
    srId:       "yjgr6joy",
  },
  {
    playerId:   "zukerben",
    clearTime:  "0:37.000",
    uploadTime: "2020-11-25",
    videoUrls:  ["https://www.youtube.com/watch?v=89lj2KRtjsQ"],
    src:        "srdc",
    srId:       "z1ol15wm",
  },
  {
    playerId:   "Wasamii",
    clearTime:  "0:37.000",
    uploadTime: "2021-07-29",
    videoUrls:  ["https://youtu.be/r8NzFY_sj1k"],
    src:        "srdc",
    srId:       "zxov4gqz",
  },
  {
    playerId:   "CreepingChamp",
    clearTime:  "0:42.000",
    uploadTime: "2020-11-13",
    videoUrls:  ["https://youtu.be/niIkD5hRiwc"],
    src:        "srdc",
    srId:       "ywd3wlnz",
  },
  {
    playerId:   "Bombatack017",
    clearTime:  "0:52.000",
    uploadTime: "2024-03-14",
    videoUrls:  ["https://www.youtube.com/watch?v=mBY_Porw0mU"],
    src:        "srdc",
    srId:       "ywgddenz",
  },
  {
    playerId:   "LeChat930",
    clearTime:  "0:59.000",
    uploadTime: "2023-07-03",
    videoUrls:  ["https://www.youtube.com/watch?v=YBLEEqKvB64"],
    src:        "srdc",
    srId:       "znvq9kvm",
  },
];