/* speedrun.com 原始抓取数据 — Rescue Missions / Martialis / Solo */
/* level_id=yweq64rw | 共 11 条 */
var rescue_missions_martialis_soloRecords = [
  {
    playerId:   "Salat",
    clearTime:  "0:18.933",
    uploadTime: "2026-06-07",
    videoUrls:  ["https://youtu.be/dSkEJmqUvJs"],
    src:        "srdc",
    srId:       "yveeke4m",
  },
  {
    playerId:   "PrimedDarkeN",
    clearTime:  "0:25.200",
    uploadTime: "2022-06-26",
    videoUrls:  ["https://www.youtube.com/watch?v=IZdrpT-F2fY"],
    src:        "srdc",
    srId:       "znpx42lm",
  },
  {
    playerId:   "L1ndell",
    clearTime:  "0:25.267",
    uploadTime: "2022-11-11",
    videoUrls:  ["https://youtu.be/HMRo1zOrO3w"],
    src:        "srdc",
    srId:       "yv0kv5xz",
  },
  {
    playerId:   "RoniPrime",
    clearTime:  "0:25.900",
    uploadTime: "2025-12-21",
    videoUrls:  ["https://youtu.be/-D8EbquA9tY?si=JcwFHFmKHcJxlpKi"],
    src:        "srdc",
    srId:       "y40ogqkz",
  },
  {
    playerId:   "Febi",
    clearTime:  "0:30.000",
    uploadTime: "2022-01-08",
    videoUrls:  ["https://www.youtube.com/watch?v=wz56OH2c1a8"],
    src:        "srdc",
    srId:       "zxlg038z",
  },
  {
    playerId:   "Wasamii",
    clearTime:  "0:35.000",
    uploadTime: "2022-05-28",
    videoUrls:  ["https://youtu.be/5fxvRu9Va1E"],
    src:        "srdc",
    srId:       "zq77wk5m",
  },
  {
    playerId:   "zukerben",
    clearTime:  "0:37.000",
    uploadTime: "2020-11-26",
    videoUrls:  ["https://www.youtube.com/watch?v=-QnAFOwtsyk"],
    src:        "srdc",
    srId:       "m750x5ez",
  },
  {
    playerId:   "Andy.",
    clearTime:  "0:38.000",
    uploadTime: "2020-11-26",
    videoUrls:  ["https://youtu.be/AOerDBL6AaQ"],
    src:        "srdc",
    srId:       "mr9l6v4m",
  },
  {
    playerId:   "Frostyy19",
    clearTime:  "0:41.000",
    uploadTime: "2023-06-02",
    videoUrls:  ["https://www.youtube.com/watch?v=IfanVHHc0vs"],
    src:        "srdc",
    srId:       "mk0740xz",
  },
  {
    playerId:   "CreepingChamp",
    clearTime:  "0:46.000",
    uploadTime: "2020-11-13",
    videoUrls:  ["https://youtu.be/OcYPnZo11AU"],
    src:        "srdc",
    srId:       "z09p8voz",
  },
  {
    playerId:   "LeChat930",
    clearTime:  "0:55.000",
    uploadTime: "2023-07-03",
    videoUrls:  ["https://www.youtube.com/watch?v=a7m_rMbo8eU"],
    src:        "srdc",
    srId:       "y2gewl5z",
  },
];