/* speedrun.com 原始抓取数据 — Rescue Missions / Metis / Solo */
/* level_id=gdry5jzw | 共 9 条 */
var rescue_missions_metis_soloRecords = [
  {
    playerId:   "Salat",
    clearTime:  "0:32.317",
    uploadTime: "2026-06-27",
    videoUrls:  ["https://youtu.be/KVlpZpbt8To"],
    src:        "srdc",
    srId:       "y249n1jz",
  },
  {
    playerId:   "L1ndell",
    clearTime:  "0:36.000",
    uploadTime: "2022-03-26",
    videoUrls:  ["https://youtu.be/KuEDD7EeQXM"],
    src:        "srdc",
    srId:       "zxl1098z",
  },
  {
    playerId:   "Mortar",
    clearTime:  "0:37.000",
    uploadTime: "2021-02-10",
    videoUrls:  ["https://www.youtube.com/watch?v=z_4suc1WHPM"],
    src:        "srdc",
    srId:       "z18xgjry",
  },
  {
    playerId:   "_Dopa",
    clearTime:  "0:46.000",
    uploadTime: "2025-02-26",
    videoUrls:  ["https://youtu.be/PxIPWO8YvL0"],
    src:        "srdc",
    srId:       "z08d5kjm",
  },
  {
    playerId:   "Wasamii",
    clearTime:  "0:50.000",
    uploadTime: "2023-01-15",
    videoUrls:  ["https://youtu.be/0eRRHEe69qY"],
    src:        "srdc",
    srId:       "znj1e28m",
  },
  {
    playerId:   "zukerben",
    clearTime:  "0:52.000",
    uploadTime: "2020-11-25",
    videoUrls:  ["https://www.youtube.com/watch?v=PsrqxPVz4qs"],
    src:        "srdc",
    srId:       "m3gqoggz",
  },
  {
    playerId:   "CreepingChamp",
    clearTime:  "0:54.000",
    uploadTime: "2020-11-13",
    videoUrls:  ["https://youtu.be/sjT-ocA3QNM"],
    src:        "srdc",
    srId:       "ylv7pgxm",
  },
  {
    playerId:   "Bombatack017",
    clearTime:  "0:55.000",
    uploadTime: "2024-03-14",
    videoUrls:  ["https://www.youtube.com/watch?v=mkNBm1i2Djs"],
    src:        "srdc",
    srId:       "zglvv3jm",
  },
  {
    playerId:   "LeChat930",
    clearTime:  "1:01.000",
    uploadTime: "2023-07-12",
    videoUrls:  ["https://www.youtube.com/watch?v=jreIK3YHT28"],
    src:        "srdc",
    srId:       "zx3381kz",
  },
];