/* speedrun.com 原始抓取数据 — Rescue Missions / Naga / Solo */
/* level_id=rdnqe57d | 共 12 条 */
var rescue_missions_naga_soloRecords = [
  {
    playerId:   "Salat",
    clearTime:  "0:23.933",
    uploadTime: "2025-11-23",
    videoUrls:  ["https://youtu.be/k5OTeGtxQIs"],
    src:        "srdc",
    srId:       "zx5l89em",
  },
  {
    playerId:   "L1ndell",
    clearTime:  "0:24.400",
    uploadTime: "2025-11-21",
    videoUrls:  ["https://youtu.be/u9zAuFtyehY"],
    src:        "srdc",
    srId:       "y4081ldz",
  },
  {
    playerId:   "PrimedDarkeN",
    clearTime:  "0:29.000",
    uploadTime: "2022-06-28",
    videoUrls:  ["https://www.youtube.com/watch?v=oVYm0aSmB4o"],
    src:        "srdc",
    srId:       "y60e2kjy",
  },
  {
    playerId:   "Txdo",
    clearTime:  "0:34.000",
    uploadTime: "2023-07-20",
    videoUrls:  ["https://www.youtube.com/watch?v=KxnzhicxS1k"],
    src:        "srdc",
    srId:       "mrlvkp7m",
  },
  {
    playerId:   "Febi",
    clearTime:  "0:35.000",
    uploadTime: "2022-06-02",
    videoUrls:  ["https://www.youtube.com/watch?v=gF8r7A_41UU"],
    src:        "srdc",
    srId:       "z52x7jnz",
  },
  {
    playerId:   "zukerben",
    clearTime:  "0:39.000",
    uploadTime: "2020-11-25",
    videoUrls:  ["https://www.youtube.com/watch?v=vX6X2H8SDfY"],
    src:        "srdc",
    srId:       "y4eo3e2m",
  },
  {
    playerId:   "Wasamii",
    clearTime:  "0:39.000",
    uploadTime: "2022-05-28",
    videoUrls:  ["https://youtu.be/KECMns0PNzg"],
    src:        "srdc",
    srId:       "yvrr6g4z",
  },
  {
    playerId:   "Zulnaa",
    clearTime:  "0:40.000",
    uploadTime: "2021-10-03",
    videoUrls:  ["https://youtu.be/lrAed1N-vJo"],
    src:        "srdc",
    srId:       "y93k15ey",
  },
  {
    playerId:   "Theotim",
    clearTime:  "0:41.000",
    uploadTime: "2023-04-29",
    videoUrls:  ["https://youtu.be/q3sWeHMcUXg"],
    src:        "srdc",
    srId:       "y4o90n2z",
  },
  {
    playerId:   "Andy.",
    clearTime:  "0:49.000",
    uploadTime: "2020-11-22",
    videoUrls:  ["https://www.youtube.com/watch?v=0nT9t_yHMN0"],
    src:        "srdc",
    srId:       "mk8vk13m",
  },
  {
    playerId:   "CreepingChamp",
    clearTime:  "0:53.000",
    uploadTime: "2020-11-13",
    videoUrls:  ["https://youtu.be/ku-0kwSHrOg"],
    src:        "srdc",
    srId:       "y6r0gk0y",
  },
  {
    playerId:   "LeChat930",
    clearTime:  "1:05.000",
    uploadTime: "2023-07-04",
    videoUrls:  ["https://www.youtube.com/watch?v=SmY_sEmUSvs"],
    src:        "srdc",
    srId:       "y86xo71m",
  },
];