/* speedrun.com 原始抓取数据 — Rescue Missions / Numa / Solo */
/* level_id=rdnqe5vd | 共 9 条 */
var rescue_missions_numa_soloRecords = [
  {
    playerId:   "Salat",
    clearTime:  "0:24.683",
    uploadTime: "2026-06-15",
    videoUrls:  ["https://youtu.be/b0zBPXF7Lro"],
    src:        "srdc",
    srId:       "z02gppem",
  },
  {
    playerId:   "L1ndell",
    clearTime:  "0:30.000",
    uploadTime: "2022-08-02",
    videoUrls:  ["https://youtu.be/GotjjGk7iQw"],
    src:        "srdc",
    srId:       "y6x79xjy",
  },
  {
    playerId:   "PrimedDarkeN",
    clearTime:  "0:31.000",
    uploadTime: "2022-06-28",
    videoUrls:  ["https://www.youtube.com/watch?v=Uy4dFmJWQuw"],
    src:        "srdc",
    srId:       "m76o034y",
  },
  {
    playerId:   "Febi",
    clearTime:  "0:34.000",
    uploadTime: "2021-06-22",
    videoUrls:  ["https://www.youtube.com/watch?v=ImEs87eu3B8"],
    src:        "srdc",
    srId:       "y4rldqnz",
  },
  {
    playerId:   "Wasamii",
    clearTime:  "0:38.000",
    uploadTime: "2021-04-13",
    videoUrls:  ["https://youtu.be/Q7-KV9jZy5M"],
    src:        "srdc",
    srId:       "m3rd9gwm",
  },
  {
    playerId:   "zukerben",
    clearTime:  "0:42.000",
    uploadTime: "2020-11-26",
    videoUrls:  ["https://www.youtube.com/watch?v=qhvpA1Eo8Rw"],
    src:        "srdc",
    srId:       "ywdrklpz",
  },
  {
    playerId:   "Andy.",
    clearTime:  "0:43.000",
    uploadTime: "2020-11-22",
    videoUrls:  ["https://www.youtube.com/watch?v=PRzZuB_D0X0"],
    src:        "srdc",
    srId:       "mr9o7x4m",
  },
  {
    playerId:   "CreepingChamp",
    clearTime:  "0:48.000",
    uploadTime: "2020-11-13",
    videoUrls:  ["https://youtu.be/NhlecCAR08A"],
    src:        "srdc",
    srId:       "yj6penoz",
  },
  {
    playerId:   "LeChat930",
    clearTime:  "1:10.000",
    uploadTime: "2023-07-04",
    videoUrls:  ["https://www.youtube.com/watch?v=NYoi1kRX4-g"],
    src:        "srdc",
    srId:       "z0jl0q4y",
  },
];