/* speedrun.com 原始抓取数据 — Rescue Missions / Nuovo / Solo */
/* level_id=nwl2r6rd | 共 10 条 */
var rescue_missions_nuovo_soloRecords = [
  {
    playerId:   "Salat",
    clearTime:  "0:19.550",
    uploadTime: "2025-10-08",
    videoUrls:  ["https://youtu.be/ts7LwIkbWf8"],
    src:        "srdc",
    srId:       "zq53qk8z",
  },
  {
    playerId:   "L1ndell",
    clearTime:  "0:24.000",
    uploadTime: "2022-08-02",
    videoUrls:  ["https://youtu.be/1RXGFJlA7-k"],
    src:        "srdc",
    srId:       "znq8k0lz",
  },
  {
    playerId:   "PrimedDarkeN",
    clearTime:  "0:26.000",
    uploadTime: "2022-06-28",
    videoUrls:  ["https://www.youtube.com/watch?v=vms0P7IK3RE"],
    src:        "srdc",
    srId:       "zx7x3wey",
  },
  {
    playerId:   "Febi",
    clearTime:  "0:28.000",
    uploadTime: "2022-08-26",
    videoUrls:  ["https://www.youtube.com/watch?v=RWyKKt_-67w"],
    src:        "srdc",
    srId:       "yv01e2oz",
  },
  {
    playerId:   "Wasamii",
    clearTime:  "0:29.000",
    uploadTime: "2022-07-02",
    videoUrls:  ["https://youtu.be/yu1NdCLSElY"],
    src:        "srdc",
    srId:       "y2pnp19z",
  },
  {
    playerId:   "Mortar",
    clearTime:  "0:31.000",
    uploadTime: "2020-12-19",
    videoUrls:  ["https://www.youtube.com/watch?v=JdVI7tKwJLQ"],
    src:        "srdc",
    srId:       "zgvj1jjz",
  },
  {
    playerId:   "Boll",
    clearTime:  "0:34.000",
    uploadTime: "2021-01-13",
    videoUrls:  ["https://www.youtube.com/watch?v=OrjFIcNUa2o&feature=youtu.be"],
    src:        "srdc",
    srId:       "zp3n26gm",
  },
  {
    playerId:   "zukerben",
    clearTime:  "0:37.000",
    uploadTime: "2020-11-26",
    videoUrls:  ["https://www.youtube.com/watch?v=L0iLsCF18wQ"],
    src:        "srdc",
    srId:       "yo3nd3dy",
  },
  {
    playerId:   "CreepingChamp",
    clearTime:  "0:43.000",
    uploadTime: "2020-11-13",
    videoUrls:  ["https://youtu.be/mC-Mf7XzD30"],
    src:        "srdc",
    srId:       "me63nr2z",
  },
  {
    playerId:   "LeChat930",
    clearTime:  "1:02.000",
    uploadTime: "2023-07-03",
    videoUrls:  ["https://www.youtube.com/watch?v=pxZR3y-c7l8"],
    src:        "srdc",
    srId:       "ydj1vg0y",
  },
];