/* speedrun.com 原始抓取数据 — Rescue Missions / Orias / Solo */
/* level_id=ldy3mez9 | 共 10 条 */
var rescue_missions_orias_soloRecords = [
  {
    playerId:   "Salat",
    clearTime:  "0:11.700",
    uploadTime: "2026-06-24",
    videoUrls:  ["https://youtu.be/aFtNjyklIEI"],
    src:        "srdc",
    srId:       "y8l55dwm",
  },
  {
    playerId:   "L1ndell",
    clearTime:  "0:15.000",
    uploadTime: "2022-03-27",
    videoUrls:  ["https://youtu.be/XRuYPBroCsY"],
    src:        "srdc",
    srId:       "mejq5dqy",
  },
  {
    playerId:   "PrimedDarkeN",
    clearTime:  "0:16.000",
    uploadTime: "2021-06-16",
    videoUrls:  ["https://www.youtube.com/watch?v=2xtAbbAZikc"],
    src:        "srdc",
    srId:       "y6dqe40m",
  },
  {
    playerId:   "Febi",
    clearTime:  "0:17.000",
    uploadTime: "2021-06-07",
    videoUrls:  ["https://www.youtube.com/watch?v=jfks4JYPQPI"],
    src:        "srdc",
    srId:       "ywqreo0y",
  },
  {
    playerId:   "Mortar",
    clearTime:  "0:19.000",
    uploadTime: "2020-11-28",
    videoUrls:  ["https://www.youtube.com/watch?v=6Ri2QNbv5Hw"],
    src:        "srdc",
    srId:       "yo3nxjjy",
  },
  {
    playerId:   "CreepingChamp",
    clearTime:  "0:21.000",
    uploadTime: "2021-02-22",
    videoUrls:  ["https://youtu.be/WrEwIEkIBnk"],
    src:        "srdc",
    srId:       "z06l858z",
  },
  {
    playerId:   "Wasamii",
    clearTime:  "0:21.000",
    uploadTime: "2021-04-27",
    videoUrls:  ["https://youtu.be/LpVi0RpBpWU"],
    src:        "srdc",
    srId:       "z0r5594z",
  },
  {
    playerId:   "zukerben",
    clearTime:  "0:23.000",
    uploadTime: "2020-11-26",
    videoUrls:  ["https://www.youtube.com/watch?v=S2J6VXQstik"],
    src:        "srdc",
    srId:       "y91834vm",
  },
  {
    playerId:   "Andy.",
    clearTime:  "0:26.000",
    uploadTime: "2020-11-22",
    videoUrls:  ["https://www.youtube.com/watch?v=UnGT2ezJlS4"],
    src:        "srdc",
    srId:       "zxdn7xgy",
  },
  {
    playerId:   "LeChat930",
    clearTime:  "0:33.000",
    uploadTime: "2023-07-03",
    videoUrls:  ["https://www.youtube.com/watch?v=QbGKGlHo20o"],
    src:        "srdc",
    srId:       "yj2de6om",
  },
];