/* speedrun.com 原始抓取数据 — Rescue Missions / Regna / Solo */
/* level_id=rw6mjvg9 | 共 11 条 */
var rescue_missions_regna_soloRecords = [
  {
    playerId:   "Salat",
    clearTime:  "0:19.733",
    uploadTime: "2026-06-06",
    videoUrls:  ["https://youtu.be/EeOFKCebZss"],
    src:        "srdc",
    srId:       "ywoor42m",
  },
  {
    playerId:   "L1ndell",
    clearTime:  "0:25.000",
    uploadTime: "2022-08-01",
    videoUrls:  ["https://youtu.be/BICQQ99J8Bk"],
    src:        "srdc",
    srId:       "y2e9456y",
  },
  {
    playerId:   "PrimedDarkeN",
    clearTime:  "0:26.000",
    uploadTime: "2022-06-10",
    videoUrls:  ["https://www.youtube.com/watch?v=2-7ukPpY8Zw"],
    src:        "srdc",
    srId:       "y60oq3qy",
  },
  {
    playerId:   "Febi",
    clearTime:  "0:32.000",
    uploadTime: "2021-07-27",
    videoUrls:  ["https://www.youtube.com/watch?v=PhRpVmFZC2E"],
    src:        "srdc",
    srId:       "m771vgem",
  },
  {
    playerId:   "Zulnaa",
    clearTime:  "0:35.000",
    uploadTime: "2021-10-02",
    videoUrls:  ["https://www.youtube.com/watch?v=L-DPP1UQWsE"],
    src:        "srdc",
    srId:       "z5dkoo5m",
  },
  {
    playerId:   "Wasamii",
    clearTime:  "0:39.000",
    uploadTime: "2021-04-27",
    videoUrls:  ["https://youtu.be/5Pkvs92aoAU"],
    src:        "srdc",
    srId:       "ywq8830y",
  },
  {
    playerId:   "FXCloud",
    clearTime:  "0:41.000",
    uploadTime: "2020-12-12",
    videoUrls:  ["https://youtu.be/wuijGStoFHo"],
    src:        "srdc",
    srId:       "ywdx3knz",
  },
  {
    playerId:   "zukerben",
    clearTime:  "0:44.000",
    uploadTime: "2020-11-25",
    videoUrls:  ["https://www.youtube.com/watch?v=FeXC6Uj--6o"],
    src:        "srdc",
    srId:       "z09j39oz",
  },
  {
    playerId:   "CreepingChamp",
    clearTime:  "0:46.000",
    uploadTime: "2020-11-13",
    videoUrls:  ["https://youtu.be/omqnAH0Cjks"],
    src:        "srdc",
    srId:       "yv9rnw8z",
  },
  {
    playerId:   "Andy.",
    clearTime:  "0:46.000",
    uploadTime: "2020-11-22",
    videoUrls:  ["https://www.youtube.com/watch?v=eoKkBXHUHec"],
    src:        "srdc",
    srId:       "m3gl3j6z",
  },
  {
    playerId:   "LeChat930",
    clearTime:  "0:59.000",
    uploadTime: "2023-07-04",
    videoUrls:  ["https://www.youtube.com/watch?v=wYxnq1qCpnc"],
    src:        "srdc",
    srId:       "y86xg8wm",
  },
];