/* speedrun.com 原始抓取数据 — Rescue Missions / Triton / Solo */
/* level_id=ldy3mer9 | 共 18 条 */
var rescue_missions_triton_soloRecords = [
  {
    playerId:   "L1ndell",
    clearTime:  "0:16.383",
    uploadTime: "2026-05-29",
    videoUrls:  ["https://youtu.be/NFLXoqv1Wys"],
    src:        "srdc",
    srId:       "zxp5418y",
  },
  {
    playerId:   "Salat",
    clearTime:  "0:18.116",
    uploadTime: "2025-11-25",
    videoUrls:  ["https://youtu.be/1YoTcCrD-U4"],
    src:        "srdc",
    srId:       "zn57xjvz",
  },
  {
    playerId:   "PrimedDarkeN",
    clearTime:  "0:21.000",
    uploadTime: "2022-06-09",
    videoUrls:  ["https://www.youtube.com/watch?v=rq2YFAKlarA"],
    src:        "srdc",
    srId:       "y2pjj85z",
  },
  {
    playerId:   "OgvDams",
    clearTime:  "0:22.000",
    uploadTime: "2023-05-08",
    videoUrls:  ["https://www.youtube.com/watch?v=lsgiRhRt-t4&ab_channel=LeLording"],
    src:        "srdc",
    srId:       "y2gq77jz",
  },
  {
    playerId:   "Febi",
    clearTime:  "0:23.000",
    uploadTime: "2022-01-29",
    videoUrls:  ["https://www.youtube.com/watch?v=zPxLOYkfd38"],
    src:        "srdc",
    srId:       "mr6o787m",
  },
  {
    playerId:   "Txdo",
    clearTime:  "0:24.000",
    uploadTime: "2023-07-16",
    videoUrls:  ["https://www.youtube.com/watch?v=47mgO6aclmE"],
    src:        "srdc",
    srId:       "zge8vnvy",
  },
  {
    playerId:   "Wasamii",
    clearTime:  "0:25.000",
    uploadTime: "2022-06-28",
    videoUrls:  ["https://youtu.be/1GmcOLfdSMc"],
    src:        "srdc",
    srId:       "mkk1045m",
  },
  {
    playerId:   "TheLostJoshua",
    clearTime:  "0:25.000",
    uploadTime: "2023-01-10",
    videoUrls:  ["https://youtu.be/Ir-Nq5EGWKk"],
    src:        "srdc",
    srId:       "znjolglm",
  },
  {
    playerId:   "Yangoo",
    clearTime:  "0:25.000",
    uploadTime: "2023-04-22",
    videoUrls:  ["https://www.youtube.com/watch?v=2blga9KV5-4"],
    src:        "srdc",
    srId:       "zqex57xz",
  },
  {
    playerId:   "HL_Unknown",
    clearTime:  "0:25.000",
    uploadTime: "2024-07-13",
    videoUrls:  ["https://youtu.be/3V-_LoNEqeY?feature=shared"],
    src:        "srdc",
    srId:       "megkjd9y",
  },
  {
    playerId:   "Mortar",
    clearTime:  "0:27.000",
    uploadTime: "2020-12-24",
    videoUrls:  ["https://www.youtube.com/watch?v=nWG1CilP2lM"],
    src:        "srdc",
    srId:       "z53w9pny",
  },
  {
    playerId:   "ChungFu",
    clearTime:  "0:28.000",
    uploadTime: "2022-06-28",
    videoUrls:  ["https://www.youtube.com/watch?v=Ej3UBdhvsY4"],
    src:        "srdc",
    srId:       "zx7x3o5y",
  },
  {
    playerId:   "Theotim",
    clearTime:  "0:30.000",
    uploadTime: "2023-04-29",
    videoUrls:  ["https://www.youtube.com/watch?v=rro_jhnFb8w"],
    src:        "srdc",
    srId:       "zge3140y",
  },
  {
    playerId:   "zukerben",
    clearTime:  "0:32.000",
    uploadTime: "2020-11-26",
    videoUrls:  ["https://www.youtube.com/watch?v=Nfx5Nnb0pj0"],
    src:        "srdc",
    srId:       "m7507r0z",
  },
  {
    playerId:   "Boll",
    clearTime:  "0:32.000",
    uploadTime: "2021-01-13",
    videoUrls:  ["https://www.youtube.com/watch?v=REv2B2d08tg&feature=youtu.be"],
    src:        "srdc",
    srId:       "z18d299y",
  },
  {
    playerId:   "Andy.",
    clearTime:  "0:33.000",
    uploadTime: "2020-11-21",
    videoUrls:  ["https://www.youtube.com/watch?v=M5FYOqvceqU"],
    src:        "srdc",
    srId:       "mr9o704m",
  },
  {
    playerId:   "CreepingChamp",
    clearTime:  "0:35.000",
    uploadTime: "2020-12-02",
    videoUrls:  ["https://youtu.be/XjJVa8zKgrY"],
    src:        "srdc",
    srId:       "yv9vl4ez",
  },
  {
    playerId:   "LeChat930",
    clearTime:  "0:44.000",
    uploadTime: "2023-06-20",
    videoUrls:  ["https://www.youtube.com/watch?v=6WsZpFrv_QA"],
    src:        "srdc",
    srId:       "y4o83k3z",
  },
];