/* speedrun.com 原始抓取数据 — Rescue Missions / Zeipel / Solo */
/* level_id=n93m60ed | 共 9 条 */
var rescue_missions_zeipel_soloRecords = [
  {
    playerId:   "L1ndell",
    clearTime:  "0:26.000",
    uploadTime: "2026-05-12",
    videoUrls:  ["https://youtu.be/JvxJaNjzeqQ"],
    src:        "srdc",
    srId:       "z5n8qkjz",
  },
  {
    playerId:   "Salat",
    clearTime:  "0:29.000",
    uploadTime: "2026-05-07",
    videoUrls:  ["https://youtu.be/Zzn4BzFQBOU"],
    src:        "srdc",
    srId:       "z02dex9m",
  },
  {
    playerId:   "PrimedDarkeN",
    clearTime:  "0:35.000",
    uploadTime: "2021-07-19",
    videoUrls:  ["https://www.youtube.com/watch?v=m5v7lMtapuQ"],
    src:        "srdc",
    srId:       "yo7w1e5m",
  },
  {
    playerId:   "Febi",
    clearTime:  "0:37.000",
    uploadTime: "2021-07-18",
    videoUrls:  ["https://www.youtube.com/watch?v=KdDubY21s9Y"],
    src:        "srdc",
    srId:       "y4rdnvkz",
  },
  {
    playerId:   "zukerben",
    clearTime:  "0:47.000",
    uploadTime: "2020-11-26",
    videoUrls:  ["https://www.youtube.com/watch?v=Yp-njQk3FHA"],
    src:        "srdc",
    srId:       "me6l4r9z",
  },
  {
    playerId:   "Andy.",
    clearTime:  "0:49.000",
    uploadTime: "2020-11-21",
    videoUrls:  ["https://www.youtube.com/watch?v=avVdZe8qvwo"],
    src:        "srdc",
    srId:       "mk8vko3m",
  },
  {
    playerId:   "LeChat930",
    clearTime:  "0:49.000",
    uploadTime: "2023-09-18",
    videoUrls:  ["https://www.youtube.com/watch?v=55jYcXEAxRk"],
    src:        "srdc",
    srId:       "y4k31jdm",
  },
  {
    playerId:   "Bombatack017",
    clearTime:  "0:58.000",
    uploadTime: "2024-03-14",
    videoUrls:  ["https://www.youtube.com/watch?v=4Sop6Omlw-U"],
    src:        "srdc",
    srId:       "mew66v2m",
  },
  {
    playerId:   "CreepingChamp",
    clearTime:  "0:59.000",
    uploadTime: "2020-11-13",
    videoUrls:  ["https://youtu.be/tRchWLa5BCY"],
    src:        "srdc",
    srId:       "yo3pq15y",
  },
];