/* speedrun.com 原始抓取数据 — Orb Vallis / Heist 2 / Solo */
/* level_id=ldyj43zd | 共 21 条 */
var orb_vallis_heist_2_soloRecords = [
  {
    playerId:   "Endryx_Ow",
    clearTime:  "0:55.183",
    uploadTime: "2025-02-26",
    videoUrls:  ["https://youtu.be/4q22w72ryAY"],
    src:        "srdc",
    srId:       "zn92oxvy",
  },
  {
    playerId:   "SarcasticPengwuin",
    clearTime:  "0:59.500",
    uploadTime: "2024-06-02",
    videoUrls:  ["https://www.youtube.com/watch?v=oIWM3lj3QeM"],
    src:        "srdc",
    srId:       "z58w2ndz",
  },
  {
    playerId:   "Stalinlox",
    clearTime:  "1:05.783",
    uploadTime: "2020-11-23",
    videoUrls:  ["https://www.youtube.com/watch?v=cDzW9fEdbp0&feature=youtu.be&ab_channel=Stalinlox"],
    src:        "srdc",
    srId:       "z53elg5y",
  },
  {
    playerId:   "Mortar",
    clearTime:  "1:05.821",
    uploadTime: "2021-03-11",
    videoUrls:  ["https://www.youtube.com/watch?v=dwT5ooR7PcM"],
    src:        "srdc",
    srId:       "y8vpxq1z",
  },
  {
    playerId:   ".cat",
    clearTime:  "1:07.866",
    uploadTime: "2020-06-11",
    videoUrls:  ["https://www.youtube.com/watch?v=qVz1vLTpF8M"],
    src:        "srdc",
    srId:       "z1ooxp9m",
  },
  {
    playerId:   "Wambo",
    clearTime:  "1:09.233",
    uploadTime: "2020-03-30",
    videoUrls:  ["https://youtu.be/ZZ0tFwB-KdQ"],
    src:        "srdc",
    srId:       "z5j54ejm",
  },
  {
    playerId:   "Andy.",
    clearTime:  "1:09.333",
    uploadTime: "2020-10-11",
    videoUrls:  ["https://youtu.be/mHqnZ6kVtfA"],
    src:        "srdc",
    srId:       "zxd2rpqy",
  },
  {
    playerId:   "namenBARS",
    clearTime:  "1:10.099",
    uploadTime: "2019-05-04",
    videoUrls:  ["https://youtu.be/mpwYKZbk4lk"],
    src:        "srdc",
    srId:       "y895vqwm",
  },
  {
    playerId:   "DrJaska",
    clearTime:  "1:10.568",
    uploadTime: "2019-10-27",
    videoUrls:  ["https://youtu.be/OdbbjPC_zRU"],
    src:        "srdc",
    srId:       "y95x4ekz",
  },
  {
    playerId:   "xanzath",
    clearTime:  "1:11.333",
    uploadTime: "2019-04-27",
    videoUrls:  ["https://www.youtube.com/watch?v=B5mgRi6yb44"],
    src:        "srdc",
    srId:       "z03g0poz",
  },
  {
    playerId:   "-CheffDegu",
    clearTime:  "1:12.133",
    uploadTime: "2019-02-05",
    videoUrls:  ["https://youtu.be/MhHpWGwi6TE"],
    src:        "srdc",
    srId:       "z0385eoz",
  },
  {
    playerId:   "zukerben",
    clearTime:  "1:12.733",
    uploadTime: "2019-04-28",
    videoUrls:  ["https://www.youtube.com/watch?v=AeoRq9d_MRA"],
    src:        "srdc",
    srId:       "m3op8xgm",
  },
  {
    playerId:   "CoffeeFreak_",
    clearTime:  "1:14.766",
    uploadTime: "2019-07-09",
    videoUrls:  ["https://www.youtube.com/watch?v=9bHyPX4pRDM&feature=youtu.be"],
    src:        "srdc",
    srId:       "zgkwq40y",
  },
  {
    playerId:   "DivineSunder",
    clearTime:  "1:15.483",
    uploadTime: "2018-12-28",
    videoUrls:  ["https://www.youtube.com/watch?v=te8ZhjCMEHA"],
    src:        "srdc",
    srId:       "zg785jez",
  },
  {
    playerId:   "--Q--EValueAction",
    clearTime:  "1:20.897",
    uploadTime: "2019-02-05",
    videoUrls:  ["https://www.youtube.com/watch?v=y_VoQVCsG64"],
    src:        "srdc",
    srId:       "zq32re5y",
  },
  {
    playerId:   "acidfi",
    clearTime:  "1:21.266",
    uploadTime: "2020-07-27",
    videoUrls:  ["https://youtu.be/vBhjH5Y2IDw"],
    src:        "srdc",
    srId:       "yd5vx0wm",
  },
  {
    playerId:   "Honorfull",
    clearTime:  "1:26.633",
    uploadTime: "2019-02-04",
    videoUrls:  ["https://www.youtube.com/watch?v=vP9evQCZmSc&feature=youtu.be"],
    src:        "srdc",
    srId:       "z11v15rz",
  },
  {
    playerId:   "FrenzyLolz",
    clearTime:  "1:29.066",
    uploadTime: "2019-04-15",
    videoUrls:  ["https://youtu.be/RuOYNP3o9co"],
    src:        "srdc",
    srId:       "me85q63m",
  },
  {
    playerId:   "Ganta-Igarashi",
    clearTime:  "1:32.492",
    uploadTime: "2019-08-22",
    videoUrls:  ["https://youtu.be/PEkZuP4ZDhk"],
    src:        "srdc",
    srId:       "y21x2l7z",
  },
  {
    playerId:   "AceStar1",
    clearTime:  "1:44.800",
    uploadTime: "2021-08-21",
    videoUrls:  ["https://youtu.be/PlU4QwNfFQc"],
    src:        "srdc",
    srId:       "mrn9w78y",
  },
  {
    playerId:   "OcelotEpic",
    clearTime:  "1:54.267",
    uploadTime: "2021-05-23",
    videoUrls:  ["https://youtu.be/lntGgHIwglM"],
    src:        "srdc",
    srId:       "y8djlqxz",
  },
];