/* speedrun.com 原始抓取数据 — Sabotage Missions / Ares / Solo */
/* level_id=y9m2lp1d | 共 18 条 */
var sabotage_missions_ares_soloRecords = [
  {
    playerId:   "Salat",
    clearTime:  "0:22.417",
    uploadTime: "2026-05-04",
    videoUrls:  ["https://youtu.be/oL8wbh7t-BY"],
    src:        "srdc",
    srId:       "zpvpvrgz",
  },
  {
    playerId:   "Endryx_Ow",
    clearTime:  "0:22.500",
    uploadTime: "2025-01-05",
    videoUrls:  ["https://youtu.be/NHu_KPvEayI"],
    src:        "srdc",
    srId:       "yvn22qem",
  },
  {
    playerId:   "L1ndell",
    clearTime:  "0:26.000",
    uploadTime: "2022-04-01",
    videoUrls:  ["https://youtu.be/r4KU7XrTOoc"],
    src:        "srdc",
    srId:       "ydwkoqwm",
  },
  {
    playerId:   "PrimedDarkeN",
    clearTime:  "0:27.000",
    uploadTime: "2021-04-02",
    videoUrls:  ["https://www.youtube.com/watch?v=HGo1Hzme2Pk"],
    src:        "srdc",
    srId:       "z50qoeny",
  },
  {
    playerId:   "_Gabriel",
    clearTime:  "0:27.000",
    uploadTime: "2023-02-12",
    videoUrls:  ["https://www.youtube.com/watch?v=NBS7k7zTCio"],
    src:        "srdc",
    srId:       "y2jjgo7z",
  },
  {
    playerId:   "FXCloud",
    clearTime:  "0:28.000",
    uploadTime: "2026-01-14",
    videoUrls:  ["https://youtu.be/zzGx9kZfOX4"],
    src:        "srdc",
    srId:       "z56wp8ny",
  },
  {
    playerId:   "Wasamii",
    clearTime:  "0:35.000",
    uploadTime: "2021-01-13",
    videoUrls:  ["https://www.youtube.com/watch?v=cT761kFkAVg&ab_channel=Wasamii"],
    src:        "srdc",
    srId:       "zp3n2lnm",
  },
  {
    playerId:   "Febi",
    clearTime:  "0:35.000",
    uploadTime: "2021-03-15",
    videoUrls:  ["https://www.youtube.com/watch?v=V5CgZ9uZkFM"],
    src:        "srdc",
    srId:       "zp3k84xm",
  },
  {
    playerId:   "zukerben",
    clearTime:  "0:36.000",
    uploadTime: "2020-11-27",
    videoUrls:  ["https://www.youtube.com/watch?v=aN07l-TMMys"],
    src:        "srdc",
    srId:       "zgvel10z",
  },
  {
    playerId:   "Frostyy19",
    clearTime:  "0:40.000",
    uploadTime: "2023-06-03",
    videoUrls:  ["https://www.youtube.com/watch?v=9QaEVeJQGs4"],
    src:        "srdc",
    srId:       "znvorgvm",
  },
  {
    playerId:   "Bombatack017",
    clearTime:  "0:43.000",
    uploadTime: "2024-03-14",
    videoUrls:  ["https://www.youtube.com/watch?v=BuTInYQzKAk"],
    src:        "srdc",
    srId:       "zq844k1z",
  },
  {
    playerId:   "-Altieri-",
    clearTime:  "0:44.000",
    uploadTime: "2021-01-12",
    videoUrls:  ["https://youtu.be/-nW7f3l2VKs"],
    src:        "srdc",
    srId:       "mk7l3xly",
  },
  {
    playerId:   "Mano",
    clearTime:  "0:46.000",
    uploadTime: "2021-01-12",
    videoUrls:  ["https://www.youtube.com/watch?v=9POv27MRvPA&feature=youtu.be"],
    src:        "srdc",
    srId:       "mk7l3evy",
  },
  {
    playerId:   "Andy.",
    clearTime:  "0:47.000",
    uploadTime: "2021-01-12",
    videoUrls:  ["https://youtu.be/23FCfYPC3us"],
    src:        "srdc",
    srId:       "zgx3wpdm",
  },
  {
    playerId:   "OgvDams",
    clearTime:  "0:48.000",
    uploadTime: "2022-08-26",
    videoUrls:  ["https://www.youtube.com/watch?v=azvYtGN6kA8"],
    src:        "srdc",
    srId:       "z0lr0njz",
  },
  {
    playerId:   "LeChat930",
    clearTime:  "0:56.000",
    uploadTime: "2023-07-15",
    videoUrls:  ["https://www.youtube.com/watch?v=XVdCjUraCI0"],
    src:        "srdc",
    srId:       "zpwpnqgy",
  },
  {
    playerId:   "iamfumii",
    clearTime:  "1:01.000",
    uploadTime: "2020-12-12",
    videoUrls:  ["https://www.youtube.com/watch?v=LValWOfWpD8&feature=youtu.be"],
    src:        "srdc",
    srId:       "ywdx69pz",
  },
  {
    playerId:   "LucianPlaysAllDay",
    clearTime:  "1:55.000",
    uploadTime: "2020-11-27",
    videoUrls:  ["https://www.twitch.tv/videos/817238381"],
    src:        "srdc",
    srId:       "yd0jg4qz",
  },
];