/* speedrun.com 原始抓取数据 — Sabotage Missions / Cervantes / Solo */
/* level_id=xd4kq3pw | 共 16 条 */
var sabotage_missions_cervantes_soloRecords = [
  {
    playerId:   "Salat",
    clearTime:  "1:30.667",
    uploadTime: "2026-06-11",
    videoUrls:  ["https://youtu.be/u6l1wBAb9O8"],
    src:        "srdc",
    srId:       "yvekxjxm",
  },
  {
    playerId:   "Endryx_Ow",
    clearTime:  "1:32.417",
    uploadTime: "2024-11-17",
    videoUrls:  ["https://youtu.be/d1udXSzmMOk?si=3ERNvd4R7p6Lp_K7"],
    src:        "srdc",
    srId:       "ylx86kky",
  },
  {
    playerId:   "Mortar",
    clearTime:  "1:34.100",
    uploadTime: "2021-04-24",
    videoUrls:  ["https://www.youtube.com/watch?v=dVye1XEkt-U"],
    src:        "srdc",
    srId:       "zn1r2rvm",
  },
  {
    playerId:   "realfoxirl",
    clearTime:  "1:36.000",
    uploadTime: "2026-03-31",
    videoUrls:  ["https://youtu.be/Ww8aIfR71R0"],
    src:        "srdc",
    srId:       "y267gx5m",
  },
  {
    playerId:   "Titoxx",
    clearTime:  "1:37.000",
    uploadTime: "2024-02-29",
    videoUrls:  ["https://youtu.be/i6jS_aQELeU"],
    src:        "srdc",
    srId:       "y8w975wy",
  },
  {
    playerId:   "PrimedDarkeN",
    clearTime:  "1:38.000",
    uploadTime: "2020-12-24",
    videoUrls:  ["https://www.youtube.com/watch?v=3U30TZYUkqQ"],
    src:        "srdc",
    srId:       "yo35221y",
  },
  {
    playerId:   "Febi",
    clearTime:  "1:39.000",
    uploadTime: "2022-08-25",
    videoUrls:  ["https://www.youtube.com/watch?v=IdeVj8a-ZZQ"],
    src:        "srdc",
    srId:       "m3xrkwwm",
  },
  {
    playerId:   "Plyonate",
    clearTime:  "1:39.000",
    uploadTime: "2026-05-31",
    videoUrls:  ["https://www.youtube.com/watch?v=EcmTBg-7CN0"],
    src:        "srdc",
    srId:       "z107lv9m",
  },
  {
    playerId:   "TheLostJoshua",
    clearTime:  "1:40.000",
    uploadTime: "2022-11-15",
    videoUrls:  ["https://youtu.be/V1_YYBA4jgg"],
    src:        "srdc",
    srId:       "yv0d998z",
  },
  {
    playerId:   "Wasamii",
    clearTime:  "1:41.000",
    uploadTime: "2021-11-07",
    videoUrls:  ["https://youtu.be/AkLfC5js9_s"],
    src:        "srdc",
    srId:       "y27697wz",
  },
  {
    playerId:   "OgvDams",
    clearTime:  "1:43.000",
    uploadTime: "2022-08-25",
    videoUrls:  ["https://www.youtube.com/watch?v=2hoNgQxVSdk"],
    src:        "srdc",
    srId:       "yv010doz",
  },
  {
    playerId:   "Bombatack017",
    clearTime:  "1:44.000",
    uploadTime: "2024-03-14",
    videoUrls:  ["https://www.youtube.com/watch?v=gady2X12FBQ"],
    src:        "srdc",
    srId:       "y8wrr3xy",
  },
  {
    playerId:   "Frostyy19",
    clearTime:  "1:48.000",
    uploadTime: "2023-06-02",
    videoUrls:  ["https://www.youtube.com/watch?v=3WCGgSXuBj4"],
    src:        "srdc",
    srId:       "znvo827m",
  },
  {
    playerId:   "LeChat930",
    clearTime:  "1:55.000",
    uploadTime: "2023-07-15",
    videoUrls:  ["https://www.youtube.com/watch?v=rWl1qiLiEv4"],
    src:        "srdc",
    srId:       "m7031g4y",
  },
  {
    playerId:   "LucianPlaysAllDay",
    clearTime:  "2:24.000",
    uploadTime: "2020-11-27",
    videoUrls:  ["https://www.twitch.tv/videos/817240730"],
    src:        "srdc",
    srId:       "y6r2ojqy",
  },
  {
    playerId:   "Shredmachine",
    clearTime:  "3:41.000",
    uploadTime: "2025-04-03",
    videoUrls:  ["https://www.youtube.com/watch?v=pnSbTdkFbWc"],
    src:        "srdc",
    srId:       "m7e4wv5z",
  },
];