/* speedrun.com 原始抓取数据 — Sabotage Missions / Cypress / Solo */
/* level_id=rdqnx11d | 共 12 条 */
var sabotage_missions_cypress_soloRecords = [
  {
    playerId:   "Salat",
    clearTime:  "0:25.750",
    uploadTime: "2025-11-03",
    videoUrls:  ["https://youtu.be/LOHwB_dn7Vk"],
    src:        "srdc",
    srId:       "mkr7kelz",
  },
  {
    playerId:   "Endryx_Ow",
    clearTime:  "0:27.800",
    uploadTime: "2025-01-06",
    videoUrls:  ["https://youtu.be/ycw8v-o30Ek?si=hjcRG4R0VHj2OQIb"],
    src:        "srdc",
    srId:       "y2nvp2wy",
  },
  {
    playerId:   "L1ndell",
    clearTime:  "0:28.783",
    uploadTime: "2021-11-04",
    videoUrls:  ["https://youtu.be/M-lneFzH8fE"],
    src:        "srdc",
    srId:       "zp85dkry",
  },
  {
    playerId:   "PrimedDarkeN",
    clearTime:  "0:35.000",
    uploadTime: "2021-07-06",
    videoUrls:  ["https://www.youtube.com/watch?v=R_8BSIvpFGQ"],
    src:        "srdc",
    srId:       "z1r05kgm",
  },
  {
    playerId:   "Mortar",
    clearTime:  "0:38.000",
    uploadTime: "2020-12-24",
    videoUrls:  ["https://www.youtube.com/watch?v=DXhBKGgECjY"],
    src:        "srdc",
    srId:       "mr9d32gm",
  },
  {
    playerId:   "Febi",
    clearTime:  "0:38.000",
    uploadTime: "2021-06-07",
    videoUrls:  ["https://www.youtube.com/watch?v=ETK5lPoctBY"],
    src:        "srdc",
    srId:       "y2xg9kwm",
  },
  {
    playerId:   "TheLostJoshua",
    clearTime:  "0:44.000",
    uploadTime: "2022-11-15",
    videoUrls:  ["https://youtu.be/C5VyiALyH1w"],
    src:        "srdc",
    srId:       "zgq5vqny",
  },
  {
    playerId:   "Frostyy19",
    clearTime:  "0:45.000",
    uploadTime: "2023-06-01",
    videoUrls:  ["https://www.youtube.com/watch?v=pe7EltP-R2U"],
    src:        "srdc",
    srId:       "m705rk5y",
  },
  {
    playerId:   "Wasamii",
    clearTime:  "0:48.000",
    uploadTime: "2021-01-14",
    videoUrls:  ["https://www.youtube.com/watch?v=M3bS1Zs1hSo&ab_channel=Wasamii"],
    src:        "srdc",
    srId:       "y2v9eo5z",
  },
  {
    playerId:   "CreepingChamp",
    clearTime:  "0:55.000",
    uploadTime: "2020-12-01",
    videoUrls:  ["https://youtu.be/yx7xT_Xo-Os"],
    src:        "srdc",
    srId:       "zplp2xnm",
  },
  {
    playerId:   "LeChat930",
    clearTime:  "1:02.000",
    uploadTime: "2023-07-15",
    videoUrls:  ["https://www.youtube.com/watch?v=0bTK9RpUcS0"],
    src:        "srdc",
    srId:       "y62q3d6z",
  },
  {
    playerId:   "LucianPlaysAllDay",
    clearTime:  "1:40.000",
    uploadTime: "2020-11-27",
    videoUrls:  ["https://www.twitch.tv/videos/817243118"],
    src:        "srdc",
    srId:       "yd0jgoqz",
  },
];