/* speedrun.com 原始抓取数据 — Sabotage Missions / Enceladus / Solo */
/* level_id=5924xorw | 共 17 条 */
var sabotage_missions_enceladus_soloRecords = [
  {
    playerId:   "Salat",
    clearTime:  "0:09.266",
    uploadTime: "2025-05-22",
    videoUrls:  ["https://youtu.be/M8Rft4RNrYE"],
    src:        "srdc",
    srId:       "z16o1n9m",
  },
  {
    playerId:   "L1ndell",
    clearTime:  "0:13.000",
    uploadTime: "2022-03-31",
    videoUrls:  ["https://youtu.be/v7rGv6YQ3CQ"],
    src:        "srdc",
    srId:       "ywjlgjnz",
  },
  {
    playerId:   "Mortar",
    clearTime:  "0:15.000",
    uploadTime: "2020-12-06",
    videoUrls:  ["https://www.youtube.com/watch?v=9OhwtllFxBk"],
    src:        "srdc",
    srId:       "z09doljz",
  },
  {
    playerId:   "Boll",
    clearTime:  "0:18.000",
    uploadTime: "2021-01-13",
    videoUrls:  ["https://youtu.be/-IN4dgqpFNg"],
    src:        "srdc",
    srId:       "zp3n9g8m",
  },
  {
    playerId:   "Titoxx",
    clearTime:  "0:18.000",
    uploadTime: "2024-09-14",
    videoUrls:  ["https://www.youtube.com/watch?v=DbiPHgWFCYA"],
    src:        "srdc",
    srId:       "ywxr180m",
  },
  {
    playerId:   "Wakaaa",
    clearTime:  "0:19.000",
    uploadTime: "2024-03-13",
    videoUrls:  ["https://www.youtube.com/watch?v=7OyYF5_0I7Y&ab_channel=Stupid_waka"],
    src:        "srdc",
    srId:       "y6vrpvpm",
  },
  {
    playerId:   "DishonoredFNG",
    clearTime:  "0:19.333",
    uploadTime: "2025-01-04",
    videoUrls:  ["https://youtu.be/ptZGfrRHiG4"],
    src:        "srdc",
    srId:       "mko7q8xz",
  },
  {
    playerId:   "HL_Unknown",
    clearTime:  "0:21.000",
    uploadTime: "2025-01-18",
    videoUrls:  ["https://youtu.be/VIROU7DplC4?si=r3KjZaYu_BYetL6q"],
    src:        "srdc",
    srId:       "mko5g9lz",
  },
  {
    playerId:   "Yangoo",
    clearTime:  "0:23.000",
    uploadTime: "2023-04-18",
    videoUrls:  ["https://youtu.be/-odCY-hFDuE"],
    src:        "srdc",
    srId:       "y2jlvq5z",
  },
  {
    playerId:   "Wasamii",
    clearTime:  "0:24.000",
    uploadTime: "2021-01-21",
    videoUrls:  ["https://www.youtube.com/watch?v=hhyZUeZDWX4&ab_channel=Wasamii"],
    src:        "srdc",
    srId:       "zgx727jm",
  },
  {
    playerId:   "CreepingChamp",
    clearTime:  "0:30.000",
    uploadTime: "2021-02-22",
    videoUrls:  ["https://youtu.be/XTnRKJ0ercg"],
    src:        "srdc",
    srId:       "y8vxo2nz",
  },
  {
    playerId:   "Fr3zzco",
    clearTime:  "0:30.000",
    uploadTime: "2024-02-28",
    videoUrls:  ["https://youtu.be/wdWjC_Ohtik"],
    src:        "srdc",
    srId:       "z191729m",
  },
  {
    playerId:   "zukerben",
    clearTime:  "0:31.000",
    uploadTime: "2020-11-27",
    videoUrls:  ["https://www.youtube.com/watch?v=67SPqJ6bEWA"],
    src:        "srdc",
    srId:       "z53pg3gy",
  },
  {
    playerId:   "-Altieri-",
    clearTime:  "0:31.000",
    uploadTime: "2021-01-13",
    videoUrls:  ["https://www.youtube.com/watch?v=bydU2SB7kD8"],
    src:        "srdc",
    srId:       "mr4j6pgz",
  },
  {
    playerId:   "Frostyy19",
    clearTime:  "0:35.000",
    uploadTime: "2023-06-01",
    videoUrls:  ["https://www.youtube.com/watch?v=Q5uIHauYuYg"],
    src:        "srdc",
    srId:       "y2gdl6jz",
  },
  {
    playerId:   "LeChat930",
    clearTime:  "0:39.000",
    uploadTime: "2023-07-15",
    videoUrls:  ["https://www.youtube.com/watch?v=TqSdxBFiZq4"],
    src:        "srdc",
    srId:       "y866575m",
  },
  {
    playerId:   "LucianPlaysAllDay",
    clearTime:  "1:11.000",
    uploadTime: "2020-11-27",
    videoUrls:  ["https://www.twitch.tv/videos/817248682"],
    src:        "srdc",
    srId:       "ylv6n52m",
  },
];