/* speedrun.com 原始抓取数据 — Sabotage Missions / Ker / Solo */
/* level_id=ewp8gqz9 | 共 19 条 */
var sabotage_missions_ker_soloRecords = [
  {
    playerId:   "Salat",
    clearTime:  "0:11.150",
    uploadTime: "2026-04-29",
    videoUrls:  ["https://youtu.be/CarSzOg2loc"],
    src:        "srdc",
    srId:       "mkx0rw5z",
  },
  {
    playerId:   "Endryx_Ow",
    clearTime:  "0:11.550",
    uploadTime: "2026-04-27",
    videoUrls:  ["https://youtu.be/apNrO1XceW8"],
    src:        "srdc",
    srId:       "yvepprxm",
  },
  {
    playerId:   "Hvna",
    clearTime:  "0:13.900",
    uploadTime: "2026-03-05",
    videoUrls:  ["https://www.youtube.com/watch?v=J_sNZLDj7-g"],
    src:        "srdc",
    srId:       "m3817j6y",
  },
  {
    playerId:   "Mortar",
    clearTime:  "0:16.000",
    uploadTime: "2021-04-09",
    videoUrls:  ["https://www.youtube.com/watch?v=cs2uKYwrusc"],
    src:        "srdc",
    srId:       "z06vvn9z",
  },
  {
    playerId:   "L1ndell",
    clearTime:  "0:16.000",
    uploadTime: "2022-03-28",
    videoUrls:  ["https://youtu.be/Bg1FKeXfZmQ"],
    src:        "srdc",
    srId:       "z12wjqgy",
  },
  {
    playerId:   "PrimedDarkeN",
    clearTime:  "0:17.000",
    uploadTime: "2021-04-02",
    videoUrls:  ["https://www.youtube.com/watch?v=j8kNeF66kDs"],
    src:        "srdc",
    srId:       "znon8gvy",
  },
  {
    playerId:   "Wasamii",
    clearTime:  "0:19.000",
    uploadTime: "2022-07-02",
    videoUrls:  ["https://youtu.be/GzUgpp0jI1M"],
    src:        "srdc",
    srId:       "z52l2kjz",
  },
  {
    playerId:   "DishonoredFNG",
    clearTime:  "0:19.167",
    uploadTime: "2025-01-07",
    videoUrls:  ["https://youtu.be/JZixpoAm8MA"],
    src:        "srdc",
    srId:       "y4j2k23y",
  },
  {
    playerId:   "Kuremento",
    clearTime:  "0:20.000",
    uploadTime: "2021-04-08",
    videoUrls:  ["https://youtu.be/U-I0Cn3_-04"],
    src:        "srdc",
    srId:       "me9r2p8z",
  },
  {
    playerId:   "Yangoo",
    clearTime:  "0:20.000",
    uploadTime: "2022-06-26",
    videoUrls:  ["https://www.youtube.com/watch?v=Eio3O2edZ0c"],
    src:        "srdc",
    srId:       "zq7qwl5m",
  },
  {
    playerId:   "Txdo",
    clearTime:  "0:20.000",
    uploadTime: "2023-07-22",
    videoUrls:  ["https://www.youtube.com/watch?v=qE7wlv6fL48"],
    src:        "srdc",
    srId:       "znv2qn9m",
  },
  {
    playerId:   "HL_Unknown",
    clearTime:  "0:20.000",
    uploadTime: "2025-01-18",
    videoUrls:  ["https://youtu.be/5VyPMwmQbrE?si=RmJZH4XjJ3NjD4Al"],
    src:        "srdc",
    srId:       "y4j7r32y",
  },
  {
    playerId:   "Aepul",
    clearTime:  "0:20.000",
    uploadTime: "2025-02-12",
    videoUrls:  ["https://www.youtube.com/watch?v=Oz71eISBPas"],
    src:        "srdc",
    srId:       "m7e2vq4z",
  },
  {
    playerId:   "Febi",
    clearTime:  "0:22.000",
    uploadTime: "2021-03-28",
    videoUrls:  ["https://www.youtube.com/watch?v=rT9VPU08b0c"],
    src:        "srdc",
    srId:       "zno6nq3y",
  },
  {
    playerId:   "Fr3zzco",
    clearTime:  "0:25.000",
    uploadTime: "2024-06-30",
    videoUrls:  ["https://www.youtube.com/watch?v=xiHJoNj7nUk"],
    src:        "srdc",
    srId:       "ydnk0n0m",
  },
  {
    playerId:   "CreepingChamp",
    clearTime:  "0:26.000",
    uploadTime: "2020-12-03",
    videoUrls:  ["https://youtu.be/9c_KRgTENgU"],
    src:        "srdc",
    srId:       "z09x0gjz",
  },
  {
    playerId:   "zukerben",
    clearTime:  "0:29.000",
    uploadTime: "2020-11-27",
    videoUrls:  ["https://www.youtube.com/watch?v=0PlmifwCeKA"],
    src:        "srdc",
    srId:       "yj62owdz",
  },
  {
    playerId:   "LeChat930",
    clearTime:  "0:36.000",
    uploadTime: "2023-07-15",
    videoUrls:  ["https://www.youtube.com/watch?v=2FJ_X2Z07Zo"],
    src:        "srdc",
    srId:       "y2gkqgjz",
  },
  {
    playerId:   "LucianPlaysAllDay",
    clearTime:  "2:26.000",
    uploadTime: "2020-11-27",
    videoUrls:  ["https://www.twitch.tv/videos/817253690"],
    src:        "srdc",
    srId:       "zq4jen9m",
  },
];