/* speedrun.com 原始抓取数据 — Sabotage Missions / Kokabiel / Solo */
/* level_id=xd14g56d | 共 12 条 */
var sabotage_missions_kokabiel_soloRecords = [
  {
    playerId:   "Salat",
    clearTime:  "0:12.750",
    uploadTime: "2025-11-27",
    videoUrls:  ["https://youtu.be/ifIJRtk3Eb4"],
    src:        "srdc",
    srId:       "yj7pkody",
  },
  {
    playerId:   "L1ndell",
    clearTime:  "0:14.000",
    uploadTime: "2022-04-01",
    videoUrls:  ["https://youtu.be/oubEGIG7UaQ"],
    src:        "srdc",
    srId:       "mkejw31m",
  },
  {
    playerId:   "Mortar",
    clearTime:  "0:15.000",
    uploadTime: "2021-04-24",
    videoUrls:  ["https://www.youtube.com/watch?v=lYttIIE55U8"],
    src:        "srdc",
    srId:       "zq1r83rm",
  },
  {
    playerId:   "PrimedDarkeN",
    clearTime:  "0:18.000",
    uploadTime: "2021-04-19",
    videoUrls:  ["https://www.youtube.com/watch?v=brrWr3LyobY"],
    src:        "srdc",
    srId:       "yo72l31m",
  },
  {
    playerId:   "Kuremento",
    clearTime:  "0:21.000",
    uploadTime: "2021-04-12",
    videoUrls:  ["https://youtu.be/53G70uabzis"],
    src:        "srdc",
    srId:       "mkg47evy",
  },
  {
    playerId:   "Wasamii",
    clearTime:  "0:22.000",
    uploadTime: "2021-11-25",
    videoUrls:  ["https://youtu.be/vYT9ZOjiVyw"],
    src:        "srdc",
    srId:       "y27lv7wz",
  },
  {
    playerId:   "admiral_ackbar47",
    clearTime:  "0:25.000",
    uploadTime: "2021-02-22",
    videoUrls:  ["https://www.youtube.com/watch?v=h73KHFtUshg"],
    src:        "srdc",
    srId:       "yo9dx00y",
  },
  {
    playerId:   "Wakaaa",
    clearTime:  "0:28.000",
    uploadTime: "2024-03-13",
    videoUrls:  ["https://www.youtube.com/watch?v=f4JsOnQu5Zw&ab_channel=Stupid_waka"],
    src:        "srdc",
    srId:       "zq84r39z",
  },
  {
    playerId:   "zukerben",
    clearTime:  "0:29.000",
    uploadTime: "2020-11-27",
    videoUrls:  ["https://www.youtube.com/watch?v=MazcDrYHj7c"],
    src:        "srdc",
    srId:       "m3gq0oqz",
  },
  {
    playerId:   "Frostyy19",
    clearTime:  "0:29.000",
    uploadTime: "2023-06-01",
    videoUrls:  ["https://www.youtube.com/watch?v=EuJeeXwYsN4"],
    src:        "srdc",
    srId:       "znv3d69m",
  },
  {
    playerId:   "LeChat930",
    clearTime:  "0:33.000",
    uploadTime: "2023-07-15",
    videoUrls:  ["https://www.youtube.com/watch?v=uu1ioyVGEco"],
    src:        "srdc",
    srId:       "znve429m",
  },
  {
    playerId:   "LucianPlaysAllDay",
    clearTime:  "1:19.000",
    uploadTime: "2020-11-27",
    videoUrls:  ["https://www.twitch.tv/videos/817256118"],
    src:        "srdc",
    srId:       "z09jn28z",
  },
];