/* speedrun.com 原始抓取数据 — Sabotage Missions / Marduk / Solo */
/* level_id=r9g7v3k9 | 共 13 条 */
var sabotage_missions_marduk_soloRecords = [
  {
    playerId:   "Salat",
    clearTime:  "1:54.000",
    uploadTime: "2026-04-14",
    videoUrls:  ["https://youtu.be/ywZHQNr7_-I"],
    src:        "srdc",
    srId:       "y9gx1kkm",
  },
  {
    playerId:   "Endryx_Ow",
    clearTime:  "1:56.000",
    uploadTime: "2025-01-07",
    videoUrls:  ["https://youtu.be/w9J7b0Z77bg?si=T0Es8dtiQilQ9HTV"],
    src:        "srdc",
    srId:       "zq2gjp8z",
  },
  {
    playerId:   "PrimedDarkeN",
    clearTime:  "1:57.000",
    uploadTime: "2021-02-28",
    videoUrls:  ["https://www.youtube.com/watch?v=WEwRARTLo64"],
    src:        "srdc",
    srId:       "z50pdldy",
  },
  {
    playerId:   "_Gabriel",
    clearTime:  "2:00.000",
    uploadTime: "2023-09-07",
    videoUrls:  ["https://www.youtube.com/watch?v=z2NvgYrLqmI"],
    src:        "srdc",
    srId:       "znewo09z",
  },
  {
    playerId:   "Meln1K",
    clearTime:  "2:02.000",
    uploadTime: "2020-11-13",
    videoUrls:  ["https://www.youtube.com/watch?v=2o0l32qRXTY"],
    src:        "srdc",
    srId:       "z532kdgy",
  },
  {
    playerId:   "Feitan",
    clearTime:  "2:06.000",
    uploadTime: "2020-10-31",
    videoUrls:  ["https://www.youtube.com/watch?v=p7SKJL_BZuY"],
    src:        "srdc",
    srId:       "zp3rgw8m",
  },
  {
    playerId:   "Zulnaa",
    clearTime:  "2:10.000",
    uploadTime: "2021-09-30",
    videoUrls:  ["https://www.youtube.com/watch?v=Qup84Wwif88"],
    src:        "srdc",
    srId:       "zqvjp75m",
  },
  {
    playerId:   "LuxeWF",
    clearTime:  "2:11.000",
    uploadTime: "2021-01-27",
    videoUrls:  ["https://www.youtube.com/watch?v=YJHEnx7b6X8&ab_channel=hi"],
    src:        "srdc",
    srId:       "mr4ko72z",
  },
  {
    playerId:   "TheLostJoshua",
    clearTime:  "2:15.000",
    uploadTime: "2022-11-15",
    videoUrls:  ["https://youtu.be/jjpjkC-U7uQ"],
    src:        "srdc",
    srId:       "z0lg97jz",
  },
  {
    playerId:   "Andy.",
    clearTime:  "2:16.000",
    uploadTime: "2020-11-08",
    videoUrls:  ["https://www.youtube.com/watch?v=GyNeVM349Eg&feature=youtu.be"],
    src:        "srdc",
    srId:       "yo3plg1y",
  },
  {
    playerId:   "BlacknessFRAME",
    clearTime:  "2:33.000",
    uploadTime: "2021-03-01",
    videoUrls:  ["https://www.youtube.com/watch?v=Gvp3RW7xOQY"],
    src:        "srdc",
    srId:       "m780oxez",
  },
  {
    playerId:   "CreepingChamp",
    clearTime:  "2:47.000",
    uploadTime: "2020-10-31",
    videoUrls:  ["https://youtu.be/jtKMS-bKsPc"],
    src:        "srdc",
    srId:       "m3g3qgwz",
  },
  {
    playerId:   "LeChat930",
    clearTime:  "2:57.000",
    uploadTime: "2023-07-15",
    videoUrls:  ["https://www.youtube.com/watch?v=uDXqJkPSvmQ"],
    src:        "srdc",
    srId:       "yl6l4gky",
  },
];