/* speedrun.com 原始抓取数据 — Sabotage Missions / Naeglar / Solo */
/* level_id=kwjvnezw | 共 10 条 */
var sabotage_missions_naeglar_soloRecords = [
  {
    playerId:   "L1ndell",
    clearTime:  "0:28.000",
    uploadTime: "2026-05-05",
    videoUrls:  ["https://youtu.be/ghkN6301YX8"],
    src:        "srdc",
    srId:       "m7j3vk0m",
  },
  {
    playerId:   "EZQ8",
    clearTime:  "0:30.000",
    uploadTime: "2026-04-30",
    videoUrls:  ["https://www.youtube.com/watch?v=Urw52A1t4iA"],
    src:        "srdc",
    srId:       "m38qen4y",
  },
  {
    playerId:   "Endryx_Ow",
    clearTime:  "0:33.000",
    uploadTime: "2025-06-21",
    videoUrls:  ["https://youtu.be/vnpArDSxeUU"],
    src:        "srdc",
    srId:       "z5wvk5nz",
  },
  {
    playerId:   "Mortar",
    clearTime:  "0:36.000",
    uploadTime: "2024-02-13",
    videoUrls:  ["https://www.youtube.com/watch?v=ST0sKZ1KAtg"],
    src:        "srdc",
    srId:       "y6v3r76m",
  },
  {
    playerId:   "PrimedDarkeN",
    clearTime:  "0:41.000",
    uploadTime: "2022-06-09",
    videoUrls:  ["https://www.youtube.com/watch?v=xgHyiu8o76o"],
    src:        "srdc",
    srId:       "zq7ee7xm",
  },
  {
    playerId:   "chocochippu",
    clearTime:  "0:47.000",
    uploadTime: "2026-04-06",
    videoUrls:  ["https://www.youtube.com/watch?v=6xQlRVRaLjo"],
    src:        "srdc",
    srId:       "y2602wjm",
  },
  {
    playerId:   "Wasamii",
    clearTime:  "0:57.000",
    uploadTime: "2022-01-26",
    videoUrls:  ["https://www.youtube.com/watch?v=SYiYDPpsLGQ"],
    src:        "srdc",
    srId:       "y9lxdeey",
  },
  {
    playerId:   "Lirvexis",
    clearTime:  "1:29.000",
    uploadTime: "2026-02-14",
    videoUrls:  ["https://youtu.be/SrrDhR2C1PU"],
    src:        "srdc",
    srId:       "y40pgn2z",
  },
  {
    playerId:   "AuhertBrahma",
    clearTime:  "1:31.000",
    uploadTime: "2020-12-03",
    videoUrls:  ["https://youtu.be/ErdIOM6HMn8"],
    src:        "srdc",
    srId:       "y4ekn42m",
  },
  {
    playerId:   "LeChat930",
    clearTime:  "1:31.000",
    uploadTime: "2023-09-21",
    videoUrls:  ["https://www.youtube.com/watch?v=V9zkRrh79eo"],
    src:        "srdc",
    srId:       "zne4qovz",
  },
];