/* speedrun.com 原始抓取数据 — Sabotage Missions / Rusalka / Solo */
/* level_id=5d72o3vw | 共 18 条 */
var sabotage_missions_rusalka_soloRecords = [
  {
    playerId:   "Salat",
    clearTime:  "0:33.083",
    uploadTime: "2025-08-05",
    videoUrls:  ["https://youtu.be/mSinOowbbq8"],
    src:        "srdc",
    srId:       "y4njr4qm",
  },
  {
    playerId:   "L1ndell",
    clearTime:  "0:35.000",
    uploadTime: "2023-01-18",
    videoUrls:  ["https://youtu.be/tgC5Zchmz-o"],
    src:        "srdc",
    srId:       "z0n73g8m",
  },
  {
    playerId:   "Endryx_Ow",
    clearTime:  "0:35.000",
    uploadTime: "2025-06-08",
    videoUrls:  ["https://youtu.be/MO0AbKjh8MQ"],
    src:        "srdc",
    srId:       "m3vrx36z",
  },
  {
    playerId:   "PrimedDarkeN",
    clearTime:  "0:38.000",
    uploadTime: "2022-01-01",
    videoUrls:  ["https://www.youtube.com/watch?v=1N0uYt4DVPg"],
    src:        "srdc",
    srId:       "yvq9ww4m",
  },
  {
    playerId:   "Titoxx",
    clearTime:  "0:42.000",
    uploadTime: "2025-01-03",
    videoUrls:  ["https://www.youtube.com/watch?v=vzRfZNRtwSc"],
    src:        "srdc",
    srId:       "mr09xedm",
  },
  {
    playerId:   "OgvDams",
    clearTime:  "0:45.000",
    uploadTime: "2023-01-20",
    videoUrls:  ["https://www.youtube.com/watch?v=5EoiSMMkOm8&ab_channel=MrDams"],
    src:        "srdc",
    srId:       "zxno89km",
  },
  {
    playerId:   "Wasamii",
    clearTime:  "0:46.000",
    uploadTime: "2023-01-17",
    videoUrls:  ["https://youtu.be/Zn4wkaj3P6E"],
    src:        "srdc",
    srId:       "ydgrk2xy",
  },
  {
    playerId:   "Txdo",
    clearTime:  "0:46.000",
    uploadTime: "2023-07-19",
    videoUrls:  ["https://www.youtube.com/watch?v=z1n1xBoKRbo"],
    src:        "srdc",
    srId:       "yon0430z",
  },
  {
    playerId:   "solalune",
    clearTime:  "0:46.000",
    uploadTime: "2024-04-01",
    videoUrls:  ["https://youtu.be/ajAWDONX1zM"],
    src:        "srdc",
    srId:       "mkp57xxy",
  },
  {
    playerId:   "Febi",
    clearTime:  "0:47.000",
    uploadTime: "2021-11-25",
    videoUrls:  ["https://www.youtube.com/watch?v=tToSb7pQN1Y"],
    src:        "srdc",
    srId:       "y8e5rp1y",
  },
  {
    playerId:   "Yangoo",
    clearTime:  "0:47.000",
    uploadTime: "2023-04-18",
    videoUrls:  ["https://youtu.be/k1Bt3Yopf5k"],
    src:        "srdc",
    srId:       "yv8w2jom",
  },
  {
    playerId:   "Theotim",
    clearTime:  "0:47.000",
    uploadTime: "2024-05-07",
    videoUrls:  ["https://youtu.be/a__O4qxJcn0"],
    src:        "srdc",
    srId:       "zgl8kxdm",
  },
  {
    playerId:   "Mortar",
    clearTime:  "0:54.000",
    uploadTime: "2020-12-06",
    videoUrls:  ["https://www.youtube.com/watch?v=swaD5Hmtoc4"],
    src:        "srdc",
    srId:       "ywdgjv2z",
  },
  {
    playerId:   "ChungFu",
    clearTime:  "0:55.000",
    uploadTime: "2022-06-28",
    videoUrls:  ["https://www.youtube.com/watch?v=DjICsqWTXoQ"],
    src:        "srdc",
    srId:       "yvrxp78z",
  },
  {
    playerId:   "CreepingChamp",
    clearTime:  "1:09.000",
    uploadTime: "2020-12-01",
    videoUrls:  ["https://youtu.be/Vn6po1Ju1dA"],
    src:        "srdc",
    srId:       "me60jp8z",
  },
  {
    playerId:   "Fr3zzco",
    clearTime:  "1:09.000",
    uploadTime: "2024-02-28",
    videoUrls:  ["https://youtu.be/rAx4r44ADYc"],
    src:        "srdc",
    srId:       "y22qre5y",
  },
  {
    playerId:   "LeChat930",
    clearTime:  "1:18.000",
    uploadTime: "2023-07-16",
    videoUrls:  ["https://www.youtube.com/watch?v=rLOjVUZsxjE"],
    src:        "srdc",
    srId:       "z5pkjwdm",
  },
  {
    playerId:   "LucianPlaysAllDay",
    clearTime:  "2:40.000",
    uploadTime: "2020-11-27",
    videoUrls:  ["https://www.twitch.tv/videos/817258931"],
    src:        "srdc",
    srId:       "yd0jgx0z",
  },
];