/* speedrun.com 原始抓取数据 — Sabotage Missions / Sao / Solo */
/* level_id=owo3z2yw | 共 16 条 */
var sabotage_missions_sao_soloRecords = [
  {
    playerId:   "Salat",
    clearTime:  "0:13.566",
    uploadTime: "2025-11-29",
    videoUrls:  ["https://youtu.be/pdT85VUg_qI"],
    src:        "srdc",
    srId:       "m323rn6y",
  },
  {
    playerId:   "Endryx_Ow",
    clearTime:  "0:17.000",
    uploadTime: "2025-01-29",
    videoUrls:  ["https://youtu.be/pFis7dAkidk"],
    src:        "srdc",
    srId:       "zpk998ny",
  },
  {
    playerId:   "L1ndell",
    clearTime:  "0:19.000",
    uploadTime: "2021-12-11",
    videoUrls:  ["https://youtu.be/JHCdO6iJbTg"],
    src:        "srdc",
    srId:       "y203636m",
  },
  {
    playerId:   "PrimedDarkeN",
    clearTime:  "0:20.000",
    uploadTime: "2021-12-10",
    videoUrls:  ["https://www.youtube.com/watch?v=0VwMbkTC1Ls"],
    src:        "srdc",
    srId:       "zq0650ry",
  },
  {
    playerId:   "Febi",
    clearTime:  "0:21.000",
    uploadTime: "2021-12-07",
    videoUrls:  ["https://www.youtube.com/watch?v=bg12nw1-6Pc"],
    src:        "srdc",
    srId:       "y9l79wey",
  },
  {
    playerId:   "Kuremento",
    clearTime:  "0:27.000",
    uploadTime: "2021-04-02",
    videoUrls:  ["https://youtu.be/CPYyml74MEE"],
    src:        "srdc",
    srId:       "z06g32oz",
  },
  {
    playerId:   "Wakaaa",
    clearTime:  "0:28.000",
    uploadTime: "2024-03-14",
    videoUrls:  ["https://www.youtube.com/watch?v=ZubXk0mnCFQ&ab_channel=Stupid_waka"],
    src:        "srdc",
    srId:       "z5837gnz",
  },
  {
    playerId:   "Txdo",
    clearTime:  "0:29.000",
    uploadTime: "2023-07-22",
    videoUrls:  ["https://www.youtube.com/watch?v=WG_4WNonFZk"],
    src:        "srdc",
    srId:       "zpw6grry",
  },
  {
    playerId:   "Wasamii",
    clearTime:  "0:30.000",
    uploadTime: "2021-04-01",
    videoUrls:  ["https://youtu.be/iIfxLtyu4Wk"],
    src:        "srdc",
    srId:       "m784kg0z",
  },
  {
    playerId:   "Fr3zzco",
    clearTime:  "0:31.000",
    uploadTime: "2024-02-28",
    videoUrls:  ["https://youtu.be/DW6Sl-wRONU"],
    src:        "srdc",
    srId:       "yjo47pgz",
  },
  {
    playerId:   "zukerben",
    clearTime:  "0:32.000",
    uploadTime: "2020-11-27",
    videoUrls:  ["https://www.youtube.com/watch?v=SXbrgFVSCgI"],
    src:        "srdc",
    srId:       "ywdrx19z",
  },
  {
    playerId:   "Theotim",
    clearTime:  "0:36.000",
    uploadTime: "2023-04-29",
    videoUrls:  ["https://youtu.be/Tt8AxNvWgGU"],
    src:        "srdc",
    srId:       "zqjk5p1m",
  },
  {
    playerId:   "Frostyy19",
    clearTime:  "0:36.000",
    uploadTime: "2023-06-02",
    videoUrls:  ["https://www.youtube.com/watch?v=Z7vhs4dWSzM"],
    src:        "srdc",
    srId:       "m708p2ey",
  },
  {
    playerId:   "LeChat930",
    clearTime:  "0:45.000",
    uploadTime: "2023-07-15",
    videoUrls:  ["https://www.youtube.com/watch?v=3lqBhqkoehc"],
    src:        "srdc",
    srId:       "yvpv3eey",
  },
  {
    playerId:   "iamfumii",
    clearTime:  "0:57.000",
    uploadTime: "2020-12-13",
    videoUrls:  ["https://www.youtube.com/watch?v=Ya9tcHl-p8o&feature=youtu.be"],
    src:        "srdc",
    srId:       "y6revx6y",
  },
  {
    playerId:   "LucianPlaysAllDay",
    clearTime:  "1:17.000",
    uploadTime: "2020-11-27",
    videoUrls:  ["https://www.twitch.tv/videos/817260970"],
    src:        "srdc",
    srId:       "zxd3nr8y",
  },
];