/* speedrun.com 原始抓取数据 — Sabotage Missions / Stribog / Solo */
/* level_id=o9xxpl19 | 共 10 条 */
var sabotage_missions_stribog_soloRecords = [
  {
    playerId:   "Salat",
    clearTime:  "1:55.000",
    uploadTime: "2026-04-19",
    videoUrls:  ["https://youtu.be/Fh4Tk44Meas"],
    src:        "srdc",
    srId:       "mkxv343z",
  },
  {
    playerId:   "Endryx_Ow",
    clearTime:  "1:56.000",
    uploadTime: "2025-01-30",
    videoUrls:  ["https://youtu.be/t_-FQM2JqvY?si=Un-E4p9acZcMKWWh"],
    src:        "srdc",
    srId:       "ydvd25xy",
  },
  {
    playerId:   "PrimedDarkeN",
    clearTime:  "2:05.000",
    uploadTime: "2021-02-28",
    videoUrls:  ["https://www.youtube.com/watch?v=FiiI4R2LLg0"],
    src:        "srdc",
    srId:       "zqgjv29m",
  },
  {
    playerId:   "-Rekken-",
    clearTime:  "2:06.000",
    uploadTime: "2020-12-16",
    videoUrls:  ["https://www.youtube.com/watch?v=mzyyxUCmhRo&feature=youtu.be"],
    src:        "srdc",
    srId:       "zgvjx8nz",
  },
  {
    playerId:   "FXCloud",
    clearTime:  "2:09.000",
    uploadTime: "2020-12-13",
    videoUrls:  ["https://www.youtube.com/watch?v=Jm3yP1phWkc"],
    src:        "srdc",
    srId:       "zn3xe99y",
  },
  {
    playerId:   "Wasamii",
    clearTime:  "2:16.000",
    uploadTime: "2021-11-07",
    videoUrls:  ["https://youtu.be/rOai8DolA5A"],
    src:        "srdc",
    srId:       "mk5xl55m",
  },
  {
    playerId:   "Andy.",
    clearTime:  "2:18.000",
    uploadTime: "2020-11-20",
    videoUrls:  ["https://www.youtube.com/watch?v=o3kn6RiG3iM"],
    src:        "srdc",
    srId:       "yd0gdvqz",
  },
  {
    playerId:   "Bombatack017",
    clearTime:  "2:25.000",
    uploadTime: "2024-03-14",
    videoUrls:  ["https://www.youtube.com/watch?v=C_ZeknLybDk"],
    src:        "srdc",
    srId:       "m30gg9gm",
  },
  {
    playerId:   "LeChat930",
    clearTime:  "2:42.000",
    uploadTime: "2023-07-16",
    videoUrls:  ["https://www.youtube.com/watch?v=gFEb02jDTpw"],
    src:        "srdc",
    srId:       "mrl2kw7m",
  },
  {
    playerId:   "iamfumii",
    clearTime:  "2:47.000",
    uploadTime: "2020-12-13",
    videoUrls:  ["https://www.youtube.com/watch?v=9p3mb3mLgc4&feature=youtu.be"],
    src:        "srdc",
    srId:       "z09qdl9z",
  },
];