/* speedrun.com 原始抓取数据 — Sabotage Missions / Thebe / Solo */
/* level_id=29vzoknd | 共 12 条 */
var sabotage_missions_thebe_soloRecords = [
  {
    playerId:   "Salat",
    clearTime:  "1:51.000",
    uploadTime: "2026-04-21",
    videoUrls:  ["https://youtu.be/pQPw9S4DusI"],
    src:        "srdc",
    srId:       "yl2nee3z",
  },
  {
    playerId:   "Endryx_Ow",
    clearTime:  "1:53.000",
    uploadTime: "2024-11-17",
    videoUrls:  ["https://www.youtube.com/watch?v=7YWwtEMXOxM"],
    src:        "srdc",
    srId:       "mk16vr3y",
  },
  {
    playerId:   "Titoxx",
    clearTime:  "1:56.000",
    uploadTime: "2024-05-31",
    videoUrls:  ["https://www.youtube.com/watch?v=9C1Gjv7KXFc"],
    src:        "srdc",
    srId:       "z0d06e4y",
  },
  {
    playerId:   "PrimedDarkeN",
    clearTime:  "1:58.000",
    uploadTime: "2021-02-28",
    videoUrls:  ["https://www.youtube.com/watch?v=PUAtgaG3pK8"],
    src:        "srdc",
    srId:       "yw0rjq3m",
  },
  {
    playerId:   "CreepingChamp",
    clearTime:  "2:00.000",
    uploadTime: "2021-01-24",
    videoUrls:  ["https://youtu.be/aDt7RTsBBrg"],
    src:        "srdc",
    srId:       "zx6kn78z",
  },
  {
    playerId:   "Wasamii",
    clearTime:  "2:10.000",
    uploadTime: "2021-11-07",
    videoUrls:  ["https://youtu.be/ztbn3df8P5o"],
    src:        "srdc",
    srId:       "m37897qz",
  },
  {
    playerId:   "Frostyy19",
    clearTime:  "2:11.000",
    uploadTime: "2023-06-02",
    videoUrls:  ["https://www.youtube.com/watch?v=y-OKx79Mtmk"],
    src:        "srdc",
    srId:       "mrl4858m",
  },
  {
    playerId:   "TheLostJoshua",
    clearTime:  "2:23.000",
    uploadTime: "2022-11-15",
    videoUrls:  ["https://youtu.be/1iC98O0rsyk"],
    src:        "srdc",
    srId:       "zx81d7gm",
  },
  {
    playerId:   "LeChat930",
    clearTime:  "2:25.000",
    uploadTime: "2023-07-16",
    videoUrls:  ["https://www.youtube.com/watch?v=TSjgMk2NeOI"],
    src:        "srdc",
    srId:       "ydj2570y",
  },
  {
    playerId:   "Bombatack017",
    clearTime:  "2:25.000",
    uploadTime: "2024-03-14",
    videoUrls:  ["https://www.youtube.com/watch?v=1HFa7Q2VrK0"],
    src:        "srdc",
    srId:       "yvl9948z",
  },
  {
    playerId:   "darkinmaui",
    clearTime:  "2:36.000",
    uploadTime: "2021-01-26",
    videoUrls:  ["https://youtu.be/vKJ3QSkytbY"],
    src:        "srdc",
    srId:       "z065w79z",
  },
  {
    playerId:   "LucianPlaysAllDay",
    clearTime:  "3:49.000",
    uploadTime: "2020-11-27",
    videoUrls:  ["https://www.twitch.tv/videos/817263432"],
    src:        "srdc",
    srId:       "zn3vjlly",
  },
];